import type { Metadata } from "next";
import Link from "next/link";
import { LegalPage, Section, Bullets, Placeholder } from "../legal-page";
import { LEGAL } from "@/lib/legal";

export const metadata: Metadata = {
  title: "Privacy Policy — NumberSmith",
  description:
    "What information NumberSmith collects, how it is used, and how children's data is handled.",
};

const LAST_UPDATED = LEGAL.lastUpdated;

export default function PrivacyPage() {
  return (
    <LegalPage
      title="Privacy Policy"
      lastUpdated={LAST_UPDATED}
      intro="NumberSmith is used by school-age students, so we collect as little as possible and never sell it. This page explains exactly what we store, why, and what control you have."
    >
      <Section heading="1. Who we are">
        <p>
          NumberSmith is operated by <Placeholder>[LEGAL ENTITY NAME]</Placeholder>. For any
          privacy question or request, contact{" "}
          <a href={`mailto:${LEGAL.contactEmail}`} className="text-brand-600 underline">
            {LEGAL.contactEmail}
          </a>
          .
        </p>
      </Section>

      <Section heading="2. What we collect">
        <p>Everything below is either given to us by you or generated by your use of the service.</p>
        <p className="font-semibold text-slate-800">Account information</p>
        <Bullets
          items={[
            "Name and email address.",
            "A securely hashed password. We never store your password in readable form and cannot recover it.",
          ]}
        />
        <p className="font-semibold text-slate-800">Learning profile</p>
        <Bullets
          items={[
            "Grade level and age range.",
            "Previous competition experience and self-reported math level.",
            "Which competitions you are training for, and how many minutes a day you plan to practise.",
            "An optional target score or goal you type in yourself.",
          ]}
        />
        <p className="font-semibold text-slate-800">Activity</p>
        <Bullets
          items={[
            "Problems attempted, answers given, whether they were correct, time taken, and hints used.",
            "Placement test results, ratings, topic mastery, XP, streaks, and achievements.",
            "Competition simulation attempts and any scratch notes you write during them.",
          ]}
        />
        <p className="font-semibold text-slate-800">Payment</p>
        <Bullets
          items={[
            <>
              If you subscribe, payment is handled by <strong>Stripe</strong>. We store only your
              subscription status, plan, renewal date, and Stripe identifiers. We never receive or
              store full card numbers.
            </>,
          ]}
        />
        <p>
          We do <strong>not</strong> collect precise location, contacts, photos, or any special
          category data. We do not require a phone number or home address from students.
        </p>
      </Section>

      <Section heading="3. Why we use it">
        <Bullets
          items={[
            "To run your account and keep you signed in.",
            "To decide what you should practise next — this is the core function of the product, and it depends on your answer history.",
            "To show you your own progress, ratings, and statistics.",
            "To process subscription payments and provide support.",
            "To keep the service secure and prevent abuse.",
          ]}
        />
        <p>
          We do <strong>not</strong> sell your information, and we do <strong>not</strong> use it for
          behavioural advertising or share it with advertisers.
        </p>
      </Section>

      <Section heading="4. Children's privacy">
        <p>
          NumberSmith is designed for school-age students, including children under 13. In the United
          States, the Children&apos;s Online Privacy Protection Act (COPPA) applies to those users.
        </p>
        <Bullets
          items={[
            "A parent or legal guardian must create and consent to an account for a child under 13.",
            "We collect only what is reasonably necessary to run the learning platform, as listed above.",
            "We do not condition a child's participation on disclosing more information than is necessary.",
            "We do not show behavioural advertising to children and do not sell their information.",
            <>
              A parent or guardian may review their child&apos;s information, ask us to delete it, or
              refuse further collection by contacting{" "}
              <a href={`mailto:${LEGAL.contactEmail}`} className="text-brand-600 underline">
                {LEGAL.contactEmail}
              </a>
              . We will verify the request before acting on it.
            </>,
          ]}
        />
        <p>
          If we learn that we have collected information from a child under 13 without the required
          parental consent, we will delete it.
        </p>
      </Section>

      <Section heading="5. Who we share it with">
        <p>
          We share information only with service providers who help us run NumberSmith, and only as
          needed:
        </p>
        <Bullets
          items={[
            <>
              <strong>Stripe</strong> — payment processing and subscription management.
            </>,
            <>
              <strong>Vercel</strong> — application hosting.
            </>,
            <>
              <strong>Neon</strong> — database hosting.
            </>,
          ]}
        />
        <p>
          We may also disclose information if required by law, or as part of a business transfer, in
          which case we will notify you and this policy will continue to apply.
        </p>
      </Section>

      <Section heading="6. How long we keep it">
        <p>
          We keep your account and learning history for as long as your account is open, because your
          progress and ratings depend on it. If you delete your account we remove your personal
          information within{" "}
          {LEGAL.dataRetentionDays} days, except where we must retain records — such as
          payment records for tax purposes.
        </p>
      </Section>

      <Section heading="7. Security">
        <p>
          Passwords are hashed. Data is transmitted over encrypted connections and stored with
          reputable providers. No system is perfectly secure, but we take reasonable measures to
          protect your information and will notify affected users of a breach as required by law.
        </p>
      </Section>

      <Section heading="8. Your choices and rights">
        <Bullets
          items={[
            "You can view and edit your profile, competitions, and preferences in Settings at any time.",
            <>
              You can request a copy of your information, correction of it, or deletion of your
              account by contacting{" "}
              <a href={`mailto:${LEGAL.contactEmail}`} className="text-brand-600 underline">
                {LEGAL.contactEmail}
              </a>
              .
            </>,
            "Depending on where you live, you may have additional rights under laws such as the CCPA or GDPR. We honour those requests regardless of location.",
            "We do not sell personal information, so there is nothing to opt out of in that respect.",
          ]}
        />
      </Section>

      <Section heading="9. Cookies">
        <p>
          We use a single essential cookie to keep you signed in. We do not use advertising or
          third-party tracking cookies. Clearing it simply signs you out.
        </p>
      </Section>

      <Section heading="10. Changes to this policy">
        <p>
          If we make material changes we will notify account holders and update the date at the top
          of this page.
        </p>
      </Section>

      <Section heading="11. Contact">
        <p>
          Privacy questions or requests:{" "}
          <a href={`mailto:${LEGAL.contactEmail}`} className="text-brand-600 underline">
            {LEGAL.contactEmail}
          </a>
          . See also our{" "}
          <Link href="/legal/terms" className="text-brand-600 underline">
            Terms of Service
          </Link>
          .
        </p>
      </Section>
    </LegalPage>
  );
}
