import { redirect } from "next/navigation";
import { getCurrentUser } from "@/lib/auth";
import { isProUser } from "@/lib/subscription";
import { buildPaper } from "@/lib/engine/simulation";
import { levelsFor } from "@/lib/competition-levels";
import { ProblemFigure } from "@/components/practice/problem-figure";
import { MathText } from "@/components/math-text";
import { PrintButton } from "./print-button";

const LETTERS = ["A", "B", "C", "D", "E", "F"];

/**
 * A contest paper, laid out for paper.
 *
 * Competition maths is sat with a pencil. Practising only on screen trains a
 * different skill from the one the contest tests — no scratch space beside the
 * problem, no flipping back to question 7, no answer sheet. This renders the
 * same paper the simulator would build, formatted for a printer: problems,
 * then a bubble answer sheet, then solutions on their own pages.
 *
 * Deliberately outside the (app) route group so it does not inherit the
 * sidebar and header. A print stylesheet can hide chrome, but not inheriting
 * it is simpler and avoids a page-one margin full of nothing.
 */
export default async function PaperPage(props: PageProps<"/paper/[slug]">) {
  const user = await getCurrentUser();
  if (!user) redirect("/login");
  if (!(await isProUser(user.id))) redirect("/pricing?from=paper");

  const { slug } = await props.params;
  const { level: levelParam } = await props.searchParams;
  const levelId = typeof levelParam === "string" ? levelParam : null;

  let paper;
  try {
    paper = await buildPaper(user.id, slug, levelId);
  } catch {
    redirect("/simulations");
  }
  const { competition, level, problems, timeLimitMinutes } = paper;
  const hasLevels = levelsFor(slug).length > 0;

  return (
    <div className="paper mx-auto max-w-[8.5in] bg-white px-8 py-10 text-black">
      {/* Screen-only controls. `print:hidden` keeps them off the page itself. */}
      <div className="mb-8 flex flex-wrap items-center justify-between gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 print:hidden">
        <p className="text-sm text-slate-700">
          Print or save as PDF. Answers are on the sheet at the end, solutions after that.
        </p>
        <PrintButton />
      </div>

      <header className="mb-8 border-b-2 border-black pb-4">
        <h1 className="text-2xl font-bold">{competition.name}</h1>
        <p className="mt-1 text-sm">
          {hasLevels && level ? `${level.label} · ` : ""}
          {problems.length} questions · {timeLimitMinutes} minutes
        </p>
        <p className="mt-3 text-xs leading-relaxed">
          Practice paper generated by NumberSmith. Original problems — not an official{" "}
          {competition.shortName} paper, and not affiliated with its organisers. Do not use a
          calculator unless the real contest permits one.
        </p>
        <div className="mt-4 flex gap-8 text-sm">
          <span>Name: ______________________</span>
          <span>Date: ______________</span>
        </div>
      </header>

      <ol className="space-y-6">
        {problems.map((p, i) => {
          const choices = p.choices ? (JSON.parse(p.choices) as string[]) : [];
          return (
            // break-inside-avoid keeps a question and its choices on one page —
            // a problem split across a page break is unreadable on paper.
            <li key={p.id} className="break-inside-avoid">
              <div className="flex gap-3">
                <span className="font-bold tabular-nums">{i + 1}.</span>
                <div className="min-w-0 flex-1">
                  <div className="leading-relaxed">
                    <MathText>{p.question}</MathText>
                  </div>
                  {p.diagram && (
                    <div className="mt-3">
                      <ProblemFigure svg={p.diagram} />
                    </div>
                  )}
                  {choices.length > 0 && (
                    <div className="mt-2 flex flex-wrap gap-x-6 gap-y-1 text-sm">
                      {choices.map((c, j) => (
                        <span key={j}>
                          <span className="font-semibold">({LETTERS[j]})</span>{" "}
                          <MathText>{c}</MathText>
                        </span>
                      ))}
                    </div>
                  )}
                </div>
              </div>
            </li>
          );
        })}
      </ol>

      <section className="mt-10 break-before-page">
        <h2 className="border-b-2 border-black pb-2 text-xl font-bold">Answer Sheet</h2>
        <p className="mt-2 text-xs">Fill in one bubble per question.</p>
        <div className="mt-5 grid grid-cols-2 gap-x-10 gap-y-2 sm:grid-cols-3">
          {problems.map((p, i) => {
            const choices = p.choices ? (JSON.parse(p.choices) as string[]) : [];
            const n = choices.length || 5;
            return (
              <div key={p.id} className="flex items-center gap-2 break-inside-avoid">
                <span className="w-6 text-right text-sm font-semibold tabular-nums">{i + 1}.</span>
                {Array.from({ length: n }, (_, j) => (
                  <span
                    key={j}
                    className="flex h-5 w-5 items-center justify-center rounded-full border border-black text-[10px]"
                  >
                    {LETTERS[j]}
                  </span>
                ))}
              </div>
            );
          })}
        </div>
      </section>

      <section className="mt-10 break-before-page">
        <h2 className="border-b-2 border-black pb-2 text-xl font-bold">Answers &amp; Solutions</h2>
        <ol className="mt-5 space-y-5 text-sm">
          {problems.map((p, i) => (
            <li key={p.id} className="break-inside-avoid">
              <p className="font-semibold">
                {i + 1}. {p.answer}
              </p>
              <div className="mt-1 leading-relaxed">
                <MathText>{p.solution}</MathText>
              </div>
            </li>
          ))}
        </ol>
      </section>
    </div>
  );
}
