export type AchievementSeed = {
  slug: string;
  name: string;
  description: string;
  icon: string;
  category: "MILESTONE" | "ACCURACY" | "SPEED" | "MASTERY" | "STREAK" | "COMPETITION";
  criteria: { type: string; threshold?: number; topicSlug?: string };
  xpReward: number;
  order: number;
};

export const ACHIEVEMENTS: AchievementSeed[] = [
  {
    slug: "first-steps",
    name: "First Steps",
    description: "Solve your first problem on NumberSmith.",
    icon: "🎯",
    category: "MILESTONE",
    criteria: { type: "PROBLEMS_SOLVED", threshold: 1 },
    xpReward: 25,
    order: 1,
  },
  {
    slug: "hundred-problems",
    name: "100 Problems Solved",
    description: "Attempt 100 problems, whether or not you get them right.",
    icon: "🏆",
    category: "MILESTONE",
    criteria: { type: "PROBLEMS_SOLVED", threshold: 100 },
    xpReward: 200,
    order: 2,
  },
  {
    slug: "five-hundred-problems",
    name: "500 Problems Solved",
    description: "Attempt 500 problems across every topic.",
    icon: "📚",
    category: "MILESTONE",
    criteria: { type: "PROBLEMS_SOLVED", threshold: 500 },
    xpReward: 500,
    order: 3,
  },
  {
    slug: "streak-7",
    name: "7-Day Streak",
    description: "Practice seven days in a row.",
    icon: "🔥",
    category: "STREAK",
    criteria: { type: "STREAK", threshold: 7 },
    xpReward: 75,
    order: 4,
  },
  {
    slug: "streak-30",
    name: "30-Day Streak",
    description: "A full month of consistent daily practice.",
    icon: "🔥",
    category: "STREAK",
    criteria: { type: "STREAK", threshold: 30 },
    xpReward: 300,
    order: 5,
  },
  {
    slug: "accuracy-90",
    name: "90% Accuracy",
    description: "Hit 90% accuracy across your last 20 problems.",
    icon: "🎯",
    category: "ACCURACY",
    criteria: { type: "ROLLING_ACCURACY", threshold: 90 },
    xpReward: 150,
    order: 6,
  },
  {
    slug: "speed-demon",
    name: "10 Problems Under 2 Minutes",
    description: "Correctly solve 10 problems in under 2 minutes each.",
    icon: "⚡",
    category: "SPEED",
    criteria: { type: "FAST_CORRECT", threshold: 10 },
    xpReward: 100,
    order: 7,
  },
  {
    slug: "geometry-master",
    name: "Geometry Master",
    description: "Reach 90% mastery in Geometry.",
    icon: "🧠",
    category: "MASTERY",
    criteria: { type: "TOPIC_MASTERY", threshold: 90, topicSlug: "geometry" },
    xpReward: 150,
    order: 8,
  },
  {
    slug: "number-theory-master",
    name: "Number Theory Master",
    description: "Reach 90% mastery in Number Theory.",
    icon: "🔢",
    category: "MASTERY",
    criteria: { type: "TOPIC_MASTERY", threshold: 90, topicSlug: "number-theory" },
    xpReward: 150,
    order: 9,
  },
  {
    slug: "algebra-master",
    name: "Algebra Master",
    description: "Reach 90% mastery in Algebra.",
    icon: "🧮",
    category: "MASTERY",
    criteria: { type: "TOPIC_MASTERY", threshold: 90, topicSlug: "algebra" },
    xpReward: 150,
    order: 10,
  },
  {
    slug: "combinatorics-master",
    name: "Combinatorics Master",
    description: "Reach 90% mastery in Combinatorics.",
    icon: "🎲",
    category: "MASTERY",
    criteria: { type: "TOPIC_MASTERY", threshold: 90, topicSlug: "combinatorics" },
    xpReward: 150,
    order: 11,
  },
  {
    slug: "first-competition",
    name: "First Competition Completed",
    description: "Finish your first full competition simulation.",
    icon: "🏅",
    category: "COMPETITION",
    criteria: { type: "SIMULATIONS_COMPLETED", threshold: 1 },
    xpReward: 100,
    order: 12,
  },
  {
    slug: "perfect-simulation",
    name: "Perfect Simulation",
    description: "Score 100% on a full competition simulation.",
    icon: "💯",
    category: "COMPETITION",
    criteria: { type: "PERFECT_SIMULATION", threshold: 1 },
    xpReward: 300,
    order: 13,
  },
  {
    slug: "placement-complete",
    name: "Level Discovered",
    description: "Complete the NumberSmith Placement Test.",
    icon: "🧭",
    category: "MILESTONE",
    criteria: { type: "PLACEMENT_COMPLETED", threshold: 1 },
    xpReward: 50,
    order: 14,
  },
  {
    slug: "daily-challenge-streak-7",
    name: "Daily Challenger",
    description: "Complete 7 daily challenges.",
    icon: "🗓️",
    category: "STREAK",
    criteria: { type: "DAILY_CHALLENGES", threshold: 7 },
    xpReward: 100,
    order: 15,
  },
];
