import type { ProblemSeed } from "./problems";

/**
 * Hand-written problems styled after the two real Math League contest
 * tiers. Math League contests are short, clean, curriculum-based problems —
 * steady and approachable, testing solid mastery under modest time
 * pressure rather than olympiad-style tricks. None of these are
 * transcribed from real Math League contests; they are original
 * NumberSmith problems written to match that format, phrasing, and
 * difficulty band.
 *
 * Math League (Elementary & Middle School) (math-league-elementary-middle)
 * targets grades 4-8: fractions, ratios, basic geometry, and simple word
 * problems, all short-answer with clean numeric or fraction results.
 *
 * Math League (High School) (math-league-high-school) targets core
 * high-school curriculum — algebra II, geometry, precalc-lite, basic
 * trig — with light competition technique, all multiple choice with five
 * answer options.
 */

export const MATH_LEAGUE_EM_PROBLEMS: ProblemSeed[] = [
  {
    slug: "math-league-em-01",
    question: "What is 2/3 + 1/5?",
    format: "SHORT_ANSWER",
    answer: "13/15",
    solution: "Common denominator is 15: 2/3 = 10/15 and 1/5 = 3/15. Adding gives 13/15.",
    hints: ["Rewrite both fractions with denominator 15.", "10/15 + 3/15"],
    difficulty: 2,
    topicSlug: "fractions",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-02",
    question: "The ratio of red marbles to blue marbles in a bag is 4:7. If there are 21 blue marbles, how many red marbles are there?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "21 blue marbles is 3 groups of 7 (since 21 ÷ 7 = 3). Each group has 4 red marbles, so red = 3 × 4 = 12.",
    hints: ["Find how many groups of 7 make 21.", "Multiply that number of groups by 4."],
    difficulty: 2,
    topicSlug: "ratios-proportions",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-03",
    question: "A triangle has angles measuring 38° and 71°. What is the measure of the third angle, in degrees?",
    format: "SHORT_ANSWER",
    answer: "71",
    solution: "The three angles of a triangle sum to 180°. 180 - 38 - 71 = 71.",
    hints: ["The angles of a triangle always add to 180°.", "Subtract the two given angles from 180."],
    difficulty: 2,
    topicSlug: "triangles",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-04",
    question: "Twelve is 30% of what number?",
    format: "SHORT_ANSWER",
    answer: "40",
    solution: "12 = 0.30 × n, so n = 12 / 0.30 = 40.",
    hints: ["Write 30% as the decimal 0.30.", "Divide 12 by 0.30."],
    difficulty: 2,
    topicSlug: "percentages",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-05",
    question: "A rectangular garden is 9 meters long and 6 meters wide. A gardener wants to put a fence post every 3 meters along the perimeter, including at each corner. How many posts are needed?",
    format: "SHORT_ANSWER",
    answer: "10",
    solution: "The perimeter is 2(9 + 6) = 30 meters. Posts every 3 meters around a closed loop gives 30 / 3 = 10 posts.",
    hints: ["Find the perimeter of the rectangle first.", "For a closed loop, the number of evenly spaced posts equals perimeter divided by spacing."],
    difficulty: 3,
    topicSlug: "area-volume",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-06",
    question: "Find the average of 14, 19, 23, and 32.",
    format: "SHORT_ANSWER",
    answer: "22",
    solution: "Sum = 14 + 19 + 23 + 32 = 88. Average = 88 / 4 = 22.",
    hints: ["Add all four numbers together.", "Divide the sum by 4."],
    difficulty: 2,
    topicSlug: "averages",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-07",
    question: "A car travels 180 miles in 3 hours at a constant speed. At that same speed, how many miles will it travel in 5 hours?",
    format: "SHORT_ANSWER",
    answer: "300",
    solution: "Speed = 180 / 3 = 60 miles per hour. In 5 hours it travels 60 × 5 = 300 miles.",
    hints: ["First find the speed in miles per hour.", "Multiply the speed by 5 hours."],
    difficulty: 2,
    topicSlug: "rates",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-08",
    question: "What is the greatest common factor of 48 and 60?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "48 = 2^4 × 3 and 60 = 2^2 × 3 × 5. The shared factors are 2^2 × 3 = 12.",
    hints: ["Write the prime factorization of each number.", "Multiply together the lowest power of each shared prime."],
    difficulty: 3,
    topicSlug: "number-properties",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-09",
    question: "Solve for x: 5x - 7 = 3x + 15.",
    format: "SHORT_ANSWER",
    answer: "11",
    solution: "Subtract 3x from both sides: 2x - 7 = 15. Add 7: 2x = 22. Divide by 2: x = 11.",
    hints: ["Get all the x terms on one side of the equation.", "Then isolate x by undoing addition/subtraction, then multiplication/division."],
    difficulty: 3,
    topicSlug: "linear-equations",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-10",
    question: "A regular hexagon has a perimeter of 42 cm. What is the length of one side, in centimeters?",
    format: "SHORT_ANSWER",
    answer: "7",
    solution: "A regular hexagon has 6 equal sides, so each side is 42 / 6 = 7 cm.",
    hints: ["A regular hexagon has 6 equal sides.", "Divide the perimeter by 6."],
    difficulty: 2,
    topicSlug: "polygons",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-11",
    question: "Sam has $45. He spends 2/5 of it on a book and then 1/3 of what remains on a snack. How much money does he have left, in dollars?",
    format: "SHORT_ANSWER",
    answer: "18",
    solution: "The book costs 2/5 × 45 = 18 dollars, leaving 45 - 18 = 27 dollars. The snack costs 1/3 × 27 = 9 dollars, leaving 27 - 9 = 18 dollars.",
    hints: ["Find the cost of the book first, then subtract it from $45.", "Take 1/3 of what remains for the snack, then subtract that too."],
    difficulty: 4,
    topicSlug: "fractions",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-12",
    question: "The sum of three consecutive even integers is 84. What is the largest of the three integers?",
    format: "SHORT_ANSWER",
    answer: "30",
    solution: "Let the integers be n, n+2, n+4. Their sum is 3n + 6 = 84, so n = 26. The largest is n + 4 = 30.",
    hints: ["Represent the three consecutive even integers as n, n+2, and n+4.", "Set 3n + 6 equal to 84 and solve for n."],
    difficulty: 4,
    topicSlug: "number-patterns",
    competitionSlug: "math-league-elementary-middle",
  },
];

export const MATH_LEAGUE_HS_PROBLEMS: ProblemSeed[] = [
  {
    slug: "math-league-hs-01",
    question: "Solve for x: 2x^2 - 5x - 3 = 0. Which of the following is a solution?",
    format: "MULTIPLE_CHOICE",
    choices: ["x = -1/2", "x = 3", "x = -3", "x = 1", "x = 5/2"],
    answer: "B",
    solution: "Factoring: 2x^2 - 5x - 3 = (2x + 1)(x - 3) = 0, so x = -1/2 or x = 3. Only x = 3 appears among the choices.",
    hints: ["Try factoring the quadratic as (2x + 1)(x - 3).", "Set each factor equal to zero and solve."],
    difficulty: 4,
    topicSlug: "quadratics",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-02",
    question: "What is the sum of the first 20 terms of the arithmetic sequence 3, 7, 11, 15, ...?",
    format: "MULTIPLE_CHOICE",
    choices: ["800", "820", "780", "760", "840"],
    answer: "B",
    solution: "The 20th term is 3 + 19(4) = 79. Sum = 20(3 + 79)/2 = 20(82)/2 = 820.",
    hints: ["Find the 20th term using a_n = a_1 + (n-1)d.", "Use the sum formula S_n = n(a_1 + a_n)/2."],
    difficulty: 5,
    topicSlug: "sequences",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-03",
    question: "In right triangle ABC, angle C = 90°, side a = 9, and side b = 12. What is the length of the hypotenuse c?",
    format: "MULTIPLE_CHOICE",
    choices: ["21", "√63", "15", "13", "18"],
    answer: "C",
    solution: "By the Pythagorean theorem, c = √(9^2 + 12^2) = √(81 + 144) = √225 = 15.",
    hints: ["Apply the Pythagorean theorem c^2 = a^2 + b^2.", "9^2 + 12^2 = 225, and 225 is a perfect square."],
    difficulty: 4,
    topicSlug: "triangles",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-04",
    question: "Simplify: (3x^2y^3)^2 / (9x^3y^4).",
    format: "MULTIPLE_CHOICE",
    choices: ["x^2 y^2", "3x y^2", "x y^2 / 3", "x y^2", "x^2 y^2 / 3"],
    answer: "D",
    solution: "(3x^2y^3)^2 = 9x^4y^6. Dividing by 9x^3y^4 gives (9/9)x^(4-3)y^(6-4) = x y^2.",
    hints: ["First square the numerator: (3x^2y^3)^2 = 9x^4y^6.", "Then divide, subtracting exponents of like bases."],
    difficulty: 4,
    topicSlug: "exponents-radicals",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-05",
    question: "Two circles have radii 5 and 8, and their centers are 13 units apart. What is true about these two circles?",
    format: "MULTIPLE_CHOICE",
    choices: [
      "They are externally tangent",
      "They are internally tangent",
      "They do not intersect",
      "They intersect at two points",
      "One circle is entirely inside the other",
    ],
    answer: "A",
    solution: "Two circles are externally tangent when the distance between centers equals the sum of the radii. Here 5 + 8 = 13, which matches the given distance, so they are externally tangent.",
    hints: ["Compare the distance between centers to the sum and difference of the radii.", "Sum of radii = 5 + 8 = 13."],
    difficulty: 5,
    topicSlug: "circles",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-06",
    question: "If f(x) = 2x - 3 and g(x) = x^2 + 1, what is f(g(2))?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "5", "9", "11", "7"],
    answer: "E",
    solution: "g(2) = 2^2 + 1 = 5. Then f(5) = 2(5) - 3 = 7.",
    hints: ["Evaluate the inner function g(2) first.", "Plug that result into f(x) = 2x - 3."],
    difficulty: 4,
    topicSlug: "functions",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-07",
    question: "Solve the system: 3x + 2y = 16 and x - y = 2. What is the value of x?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "5", "2", "6"],
    answer: "B",
    solution: "From x - y = 2, x = y + 2. Substituting: 3(y+2) + 2y = 16, so 3y + 6 + 2y = 16, 5y = 10, y = 2, and x = y + 2 = 4.",
    hints: ["Solve the second equation for x in terms of y.", "Substitute into the first equation and solve for y, then back-substitute."],
    difficulty: 5,
    topicSlug: "systems-of-equations",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-08",
    question: "In a right triangle, one acute angle measures 30°. If the side opposite that angle has length 7, what is the length of the hypotenuse?",
    format: "MULTIPLE_CHOICE",
    choices: ["7√2", "7√3", "14", "10.5", "21"],
    answer: "C",
    solution: "sin(30°) = opposite/hypotenuse = 1/2, so hypotenuse = opposite / sin(30°) = 7 / (1/2) = 14.",
    hints: ["Use sin(30°) = 1/2 and the relation sin(angle) = opposite/hypotenuse.", "Solve for the hypotenuse by dividing."],
    difficulty: 5,
    topicSlug: "triangles",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-09",
    question: "Factor completely: x^3 - 9x.",
    format: "MULTIPLE_CHOICE",
    choices: ["x(x-9)(x+1)", "(x-3)^2(x+3)", "x^2(x-9)", "x(x-3)(x+3)", "x(x^2-9x)"],
    answer: "D",
    solution: "x^3 - 9x = x(x^2 - 9) = x(x-3)(x+3), using the difference of squares on x^2 - 9.",
    hints: ["Factor out the common factor of x first.", "Then recognize x^2 - 9 as a difference of squares."],
    difficulty: 4,
    topicSlug: "factoring",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-10",
    question: "Solve the inequality: -3x + 7 < 1. Which describes the solution set?",
    format: "MULTIPLE_CHOICE",
    choices: ["x > 2", "x < 2", "x > -2", "x < -2", "x > 8/3"],
    answer: "A",
    solution: "-3x + 7 < 1 gives -3x < -6. Dividing by -3 flips the inequality: x > 2.",
    hints: ["Subtract 7 from both sides first.", "Remember to flip the inequality sign when dividing by a negative number."],
    difficulty: 4,
    topicSlug: "inequalities",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-11",
    question: "A circle has equation x^2 + y^2 - 6x + 4y - 3 = 0. What is the radius of the circle?",
    format: "MULTIPLE_CHOICE",
    choices: ["√13", "16", "13", "5", "4"],
    answer: "E",
    solution: "Completing the square: (x^2 - 6x + 9) + (y^2 + 4y + 4) = 3 + 9 + 4, giving (x-3)^2 + (y+2)^2 = 16. So the radius is √16 = 4.",
    hints: ["Complete the square separately for the x-terms and y-terms.", "The right-hand side after completing the square equals the radius squared."],
    difficulty: 6,
    topicSlug: "coordinate-geometry",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-12",
    question: "How many distinct real solutions does the equation x^4 - 5x^2 + 4 = 0 have?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "0", "4", "3", "1"],
    answer: "C",
    solution: "Let u = x^2. Then u^2 - 5u + 4 = 0 factors as (u-1)(u-4) = 0, so u = 1 or u = 4, meaning x^2 = 1 or x^2 = 4. This gives x = ±1, ±2 — four distinct real solutions.",
    hints: ["Substitute u = x^2 to turn this into a quadratic in u.", "Solve for u, then remember each positive u value gives two real x values."],
    difficulty: 6,
    topicSlug: "polynomials",
    competitionSlug: "math-league-high-school",
  },
];
