import type { ProblemSeed } from "./problems";

/**
 * Problems written for the Countdown round: one answer, under 45 seconds, typed.
 *
 * The rest of the bank is written for untimed practice and for contest papers,
 * and none of it fits here. Its quickest problems are estimated at 60 seconds —
 * already over the clock — and a countdown round assembled from it served
 * things like "a garden bed is shaped like a trapezoid…", a 150-second problem
 * with 45 seconds to answer it. That is not a speed round, it is a stopwatch on
 * failure.
 *
 * So these are a different kind of question, not merely easier ones:
 *
 *   - One idea, then arithmetic you can hold in your head. No configuration to
 *     set up, no case analysis, nothing to write down more than once.
 *   - Short to *read*. Reading is part of the 45 seconds, and a three-sentence
 *     setup spends a third of the clock before any thinking starts. Nearly all
 *     of these are one sentence.
 *   - Rewarding a technique, not raw calculation. `43² − 42²` is a mental
 *     problem via difference of squares and a slog without it; the units digit
 *     of a large power is instant once you see the cycle. The point of a speed
 *     round is that recognition beats grinding, so speed measures fluency
 *     rather than how fast a student can multiply.
 *   - Exact, terse answers — an integer, a simple fraction, a multiple of π.
 *     Nothing a student would have to decide how to format under time.
 *
 * Difficulty still spans 1-7 and still means difficulty: cd-033 (trailing zeros
 * of 25!) is harder than cd-001 (15% of 60) while being no slower. Countdown
 * centres its selection on the student's rating, so the range matters.
 *
 * Deliberately not tagged to a competition. These belong to a *format*, not a
 * contest, and tagging them MATHCOUNTS would leak 20-second questions into
 * MATHCOUNTS simulation papers where they would wreck the ramp. Countdown finds
 * them by `estimatedTimeSeconds` instead, which is the property that actually
 * defines them.
 *
 * All original NumberSmith content. Answers are verified independently in
 * `scripts/check-countdown-bank.ts`.
 */
export const COUNTDOWN_PROBLEMS: ProblemSeed[] = [
  // ---------------------------- arithmetic ----------------------------
  {
    slug: "cd-001",
    question: "What is 15% of 60?",
    format: "SHORT_ANSWER",
    answer: "9",
    solution: "10% of 60 is 6 and 5% is half of that, 3. So 15% is 6 + 3 = 9.",
    hints: ["Split 15% into 10% + 5%."],
    difficulty: 1,
    topicSlug: "percentages",
    estimatedTimeSeconds: 15,
  },
  {
    slug: "cd-002",
    question: "What is one quarter of one third of 96?",
    format: "SHORT_ANSWER",
    answer: "8",
    solution: "A quarter of a third is a twelfth, and 96 / 12 = 8.",
    hints: ["Multiply the fractions first, then divide once."],
    difficulty: 2,
    topicSlug: "fractions",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-003",
    question: "25% of what number is 13?",
    format: "SHORT_ANSWER",
    answer: "52",
    solution: "25% is a quarter, so the number is 4 x 13 = 52.",
    hints: ["Going backwards through 25% means multiplying by 4."],
    difficulty: 2,
    topicSlug: "percentages",
    estimatedTimeSeconds: 15,
  },
  {
    slug: "cd-004",
    question: "What is 80 increased by 35%?",
    format: "SHORT_ANSWER",
    answer: "108",
    solution: "35% of 80 is 28, and 80 + 28 = 108.",
    hints: ["10% of 80 is 8, so 35% is 8 + 8 + 8 + 4."],
    difficulty: 2,
    topicSlug: "percentages",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-005",
    question: "What is 7/8 of 64?",
    format: "SHORT_ANSWER",
    answer: "56",
    solution: "64 / 8 = 8, and 7 x 8 = 56.",
    hints: ["Divide by the denominator before multiplying."],
    difficulty: 1,
    topicSlug: "fractions",
    estimatedTimeSeconds: 15,
  },
  {
    slug: "cd-006",
    question: "What is 1/2 + 1/3 + 1/6?",
    format: "SHORT_ANSWER",
    answer: "1",
    solution: "Over a denominator of 6 these are 3/6 + 2/6 + 1/6 = 6/6 = 1.",
    hints: ["Every denominator divides 6."],
    difficulty: 2,
    topicSlug: "fractions",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-007",
    question: "What is 1 - 1/2 - 1/4 - 1/8?",
    format: "SHORT_ANSWER",
    answer: "1/8",
    solution:
      "Each subtraction removes half of what is left: 1 becomes 1/2, then 1/4, then 1/8.",
    hints: ["Track what remains rather than adding up what you took away."],
    difficulty: 2,
    topicSlug: "fractions",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-008",
    question: "What is 120% of 45?",
    format: "SHORT_ANSWER",
    answer: "54",
    solution: "45 + 20% of 45 = 45 + 9 = 54.",
    hints: ["120% is the whole plus a fifth."],
    difficulty: 2,
    topicSlug: "percentages",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-009",
    question: "What is 35% of 35% of 400?",
    format: "SHORT_ANSWER",
    answer: "49",
    solution: "35% of 400 is 140, and 35% of 140 is 49.",
    hints: ["Or note that 0.35 x 0.35 x 400 = 0.1225 x 400."],
    difficulty: 4,
    topicSlug: "percentages",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-010",
    question: "Express 2/5 as a percentage.",
    format: "SHORT_ANSWER",
    answer: "40",
    solution: "2/5 = 4/10 = 40/100, which is 40%.",
    hints: ["Scale the denominator to 100."],
    difficulty: 1,
    topicSlug: "percentages",
    estimatedTimeSeconds: 15,
  },
  {
    slug: "cd-011",
    question: "What is the average of 12, 19, 23, and 26?",
    format: "SHORT_ANSWER",
    answer: "20",
    solution: "The sum is 80, and 80 / 4 = 20.",
    hints: ["Pair 12 with 26 and 19 with 23."],
    difficulty: 2,
    topicSlug: "averages",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-012",
    question: "The average of five numbers is 14. Four of them add to 51. What is the fifth?",
    format: "SHORT_ANSWER",
    answer: "19",
    solution: "All five total 5 x 14 = 70, so the fifth is 70 - 51 = 19.",
    hints: ["Turn the average into a total first."],
    difficulty: 3,
    topicSlug: "averages",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-013",
    question: "Two numbers are in the ratio 3:5 and add to 64. What is the larger number?",
    format: "SHORT_ANSWER",
    answer: "40",
    solution: "There are 8 parts, so each part is 8, and the larger is 5 x 8 = 40.",
    hints: ["Count the parts in the ratio."],
    difficulty: 2,
    topicSlug: "ratios-proportions",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-014",
    question: "If 4 pencils cost $1.20, how many dollars do 10 pencils cost?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution: "One pencil costs $0.30, so ten cost $3.00.",
    hints: ["Find the price of one pencil."],
    difficulty: 2,
    topicSlug: "rates",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-015",
    question:
      "A car travels 180 miles in 3 hours. At that rate, how many miles does it travel in 50 minutes?",
    format: "SHORT_ANSWER",
    answer: "50",
    solution: "The rate is 60 miles per hour, which is exactly 1 mile per minute, so 50 miles.",
    hints: ["60 miles per hour is a mile a minute."],
    difficulty: 3,
    topicSlug: "rates",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-016",
    question: "What is 99 x 101?",
    format: "SHORT_ANSWER",
    answer: "9999",
    solution: "This is (100 - 1)(100 + 1) = 100^2 - 1 = 9999.",
    hints: ["The two factors sit either side of 100."],
    difficulty: 3,
    topicSlug: "factoring",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-017",
    question: "What is 43^2 - 42^2?",
    format: "SHORT_ANSWER",
    answer: "85",
    solution: "By difference of squares this is (43 - 42)(43 + 42) = 1 x 85 = 85.",
    hints: ["Factor rather than squaring either number."],
    difficulty: 3,
    topicSlug: "factoring",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-018",
    question: "What is 1 + 2 + 3 + ... + 20?",
    format: "SHORT_ANSWER",
    answer: "210",
    solution: "The sum is 20 x 21 / 2 = 210.",
    hints: ["Pair the first with the last: ten pairs each summing to 21."],
    difficulty: 2,
    topicSlug: "sequences",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-019",
    question: "What is the sum of the first 15 positive odd numbers?",
    format: "SHORT_ANSWER",
    answer: "225",
    solution: "The first n odd numbers sum to n^2, so the answer is 15^2 = 225.",
    hints: ["1, 1+3, 1+3+5 are 1, 4, 9 — all perfect squares."],
    difficulty: 3,
    topicSlug: "number-patterns",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-020",
    question: "What is 1! + 2! + 3! + 4! + 5!?",
    format: "SHORT_ANSWER",
    answer: "153",
    solution: "1 + 2 + 6 + 24 + 120 = 153.",
    hints: ["Each factorial is the previous one times the next integer."],
    difficulty: 3,
    topicSlug: "number-patterns",
    estimatedTimeSeconds: 30,
  },

  // --------------------------- number theory ---------------------------
  {
    slug: "cd-021",
    question: "What is the units digit of 3^2026?",
    format: "SHORT_ANSWER",
    answer: "9",
    solution:
      "Units digits of powers of 3 cycle 3, 9, 7, 1 with period 4. Since 2026 leaves remainder 2 on division by 4, the units digit is 9.",
    hints: ["List the units digits of 3, 9, 27, 81 and look for the cycle."],
    difficulty: 4,
    topicSlug: "modular-arithmetic",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-022",
    question: "What is the units digit of 7^100?",
    format: "SHORT_ANSWER",
    answer: "1",
    solution:
      "Powers of 7 end in 7, 9, 3, 1, repeating every 4. As 100 is a multiple of 4, the units digit is 1.",
    hints: ["A multiple of 4 lands on the last entry of the cycle."],
    difficulty: 4,
    topicSlug: "modular-arithmetic",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-023",
    question: "What is the remainder when 2^10 is divided by 7?",
    format: "SHORT_ANSWER",
    answer: "2",
    solution: "2^10 = 1024, and 1024 = 7 x 146 + 2, so the remainder is 2.",
    hints: ["2^3 = 8 leaves remainder 1, so 2^9 does too."],
    difficulty: 4,
    topicSlug: "modular-arithmetic",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-024",
    question: "What is the remainder when 1 + 2 + 3 + ... + 100 is divided by 7?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution: "The sum is 5050, and 5050 = 7 x 721 + 3.",
    hints: ["Add the whole thing up first using the pairing trick."],
    difficulty: 5,
    topicSlug: "modular-arithmetic",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-025",
    question: "How many positive divisors does 72 have?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "72 = 2^3 x 3^2, so it has (3 + 1)(2 + 1) = 12 divisors.",
    hints: ["Add one to each exponent in the prime factorisation, then multiply."],
    difficulty: 3,
    topicSlug: "factorization",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-026",
    question: "What is the sum of all positive divisors of 28?",
    format: "SHORT_ANSWER",
    answer: "56",
    solution: "The divisors are 1, 2, 4, 7, 14, 28, which add to 56.",
    hints: ["List divisors in pairs that multiply to 28."],
    difficulty: 4,
    topicSlug: "factorization",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-027",
    question: "What is the sum of the distinct prime factors of 210?",
    format: "SHORT_ANSWER",
    answer: "17",
    solution: "210 = 2 x 3 x 5 x 7, and 2 + 3 + 5 + 7 = 17.",
    hints: ["210 is the product of the first four primes."],
    difficulty: 3,
    topicSlug: "primes",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-028",
    question: "What is the greatest common divisor of 84 and 126?",
    format: "SHORT_ANSWER",
    answer: "42",
    solution: "84 = 2^2 x 3 x 7 and 126 = 2 x 3^2 x 7, so the gcd is 2 x 3 x 7 = 42.",
    hints: ["126 - 84 = 42, and 42 divides both."],
    difficulty: 3,
    topicSlug: "divisibility",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-029",
    question: "What is the least common multiple of 12 and 18?",
    format: "SHORT_ANSWER",
    answer: "36",
    solution: "12 x 18 = 216 and their gcd is 6, so the lcm is 216 / 6 = 36.",
    hints: ["Check the multiples of 18: 18, 36."],
    difficulty: 2,
    topicSlug: "divisibility",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-030",
    question: "What is the smallest prime number greater than 90?",
    format: "SHORT_ANSWER",
    answer: "97",
    solution:
      "91 = 7 x 13, 93 = 3 x 31, and 95 = 5 x 19, while 97 has no prime factor up to 9. So 97.",
    hints: ["91 looks prime but is not."],
    difficulty: 3,
    topicSlug: "primes",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-031",
    question: "How many prime numbers are there strictly between 20 and 40?",
    format: "SHORT_ANSWER",
    answer: "4",
    solution: "They are 23, 29, 31, and 37 — four primes.",
    hints: ["Check only the odd numbers not divisible by 3."],
    difficulty: 3,
    topicSlug: "primes",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-032",
    question: "What is the largest three-digit multiple of 7?",
    format: "SHORT_ANSWER",
    answer: "994",
    solution: "1000 = 7 x 142 + 6, so subtract the remainder: 1000 - 6 = 994.",
    hints: ["Divide 1000 by 7 and take off the remainder."],
    difficulty: 3,
    topicSlug: "divisibility",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-033",
    question: "How many zeros does 25! end in?",
    format: "SHORT_ANSWER",
    answer: "6",
    solution:
      "Trailing zeros count factors of 5: there are 5 multiples of 5 up to 25, and 25 contributes a second factor, giving 6.",
    hints: ["Count factors of 5, not of 10 — and do not forget 25 has two."],
    difficulty: 5,
    topicSlug: "factorization",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-034",
    question: "What is the smallest positive integer with exactly six positive divisors?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution:
      "Six divisors means the form p^5 or p^2 q. The smallest of each are 32 and 12, so 12.",
    hints: ["Six factors as 6 or as 3 x 2, giving two possible shapes."],
    difficulty: 5,
    topicSlug: "factorization",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-035",
    question: "What is the sum of the digits of 2^10?",
    format: "SHORT_ANSWER",
    answer: "7",
    solution: "2^10 = 1024, and 1 + 0 + 2 + 4 = 7.",
    hints: ["2^10 is a number worth knowing by heart."],
    difficulty: 3,
    topicSlug: "integer-properties",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-036",
    question: "What is 111111 divided by 3?",
    format: "SHORT_ANSWER",
    answer: "37037",
    solution: "Dividing digit by digit gives 37037, since 3 x 37037 = 111111.",
    hints: ["111 / 3 = 37, and the pattern repeats."],
    difficulty: 3,
    topicSlug: "divisibility",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-037",
    question: "What positive integer squared equals 1369?",
    format: "SHORT_ANSWER",
    answer: "37",
    solution:
      "It ends in 9, so the root ends in 3 or 7, and it lies between 30^2 = 900 and 40^2 = 1600. Checking, 37^2 = 1369.",
    hints: ["The final digit of the square limits the final digit of the root."],
    difficulty: 4,
    topicSlug: "integer-properties",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-038",
    question: "How many integers from 1 to 100 are divisible by 3 or by 5?",
    format: "SHORT_ANSWER",
    answer: "47",
    solution: "There are 33 multiples of 3 and 20 of 5, sharing 6 multiples of 15: 33 + 20 - 6 = 47.",
    hints: ["Do not count the multiples of 15 twice."],
    difficulty: 4,
    topicSlug: "inclusion-exclusion",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-039",
    question: "What is the remainder when 5^2027 is divided by 4?",
    format: "SHORT_ANSWER",
    answer: "1",
    solution: "5 leaves remainder 1 on division by 4, so every power of 5 does too.",
    hints: ["Reduce the base before worrying about the exponent."],
    difficulty: 4,
    topicSlug: "modular-arithmetic",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-040",
    question: "Today is Tuesday. What day of the week will it be 100 days from now?",
    format: "SHORT_ANSWER",
    answer: "Thursday",
    solution: "100 = 7 x 14 + 2, so it is two days past Tuesday: Thursday.",
    hints: ["Only the remainder on division by 7 matters."],
    difficulty: 4,
    topicSlug: "modular-arithmetic",
    estimatedTimeSeconds: 30,
  },

  // ------------------------------ algebra ------------------------------
  {
    slug: "cd-041",
    question: "If 3x + 7 = 31, what is x?",
    format: "SHORT_ANSWER",
    answer: "8",
    solution: "3x = 24, so x = 8.",
    hints: ["Undo the addition, then the multiplication."],
    difficulty: 2,
    topicSlug: "linear-equations",
    estimatedTimeSeconds: 15,
  },
  {
    slug: "cd-042",
    question: "Solve 5(x - 3) = 2x + 9 for x.",
    format: "SHORT_ANSWER",
    answer: "8",
    solution: "5x - 15 = 2x + 9, so 3x = 24 and x = 8.",
    hints: ["Expand, then gather the x terms on one side."],
    difficulty: 3,
    topicSlug: "linear-equations",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-043",
    question: "If x + y = 10 and xy = 21, what is x^2 + y^2?",
    format: "SHORT_ANSWER",
    answer: "58",
    solution: "x^2 + y^2 = (x + y)^2 - 2xy = 100 - 42 = 58.",
    hints: ["Square the sum and see what extra term appears."],
    difficulty: 4,
    topicSlug: "factoring",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-044",
    question: "If x + 1/x = 3, what is x^2 + 1/x^2?",
    format: "SHORT_ANSWER",
    answer: "7",
    solution: "Squaring gives x^2 + 2 + 1/x^2 = 9, so x^2 + 1/x^2 = 7.",
    hints: ["Square both sides; the cross term is a constant."],
    difficulty: 5,
    topicSlug: "factoring",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-045",
    question: "What is x^2 - y^2 when x = 17 and y = 13?",
    format: "SHORT_ANSWER",
    answer: "120",
    solution: "(17 - 13)(17 + 13) = 4 x 30 = 120.",
    hints: ["Factor first — no squaring needed."],
    difficulty: 3,
    topicSlug: "factoring",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-046",
    question: "What is the larger root of x^2 - 9x + 20 = 0?",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "It factors as (x - 4)(x - 5) = 0, so the roots are 4 and 5.",
    hints: ["Find two numbers multiplying to 20 and adding to 9."],
    difficulty: 3,
    topicSlug: "quadratics",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-047",
    question: "What is the sum of the roots of 2x^2 - 10x + 3 = 0?",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "The sum of the roots is -b/a = 10/2 = 5.",
    hints: ["You do not need the roots themselves."],
    difficulty: 4,
    topicSlug: "quadratics",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-048",
    question: "What is the product of the roots of 3x^2 + 7x - 12 = 0?",
    format: "SHORT_ANSWER",
    answer: "-4",
    solution: "The product of the roots is c/a = -12/3 = -4.",
    hints: ["Vieta again — mind the sign."],
    difficulty: 4,
    topicSlug: "quadratics",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-049",
    question: "If f(x) = 2x^2 - 3x + 1, what is f(4)?",
    format: "SHORT_ANSWER",
    answer: "21",
    solution: "2(16) - 12 + 1 = 32 - 12 + 1 = 21.",
    hints: ["Substitute and work left to right."],
    difficulty: 3,
    topicSlug: "functions",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-050",
    question: "If f(x) = x^2 + 1, what is f(f(2))?",
    format: "SHORT_ANSWER",
    answer: "26",
    solution: "f(2) = 5, and f(5) = 26.",
    hints: ["Work from the inside out."],
    difficulty: 4,
    topicSlug: "functions",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-051",
    question: "What is the 8th term of the arithmetic sequence 5, 9, 13, ...?",
    format: "SHORT_ANSWER",
    answer: "33",
    solution: "The common difference is 4, so the 8th term is 5 + 7 x 4 = 33.",
    hints: ["Seven steps, not eight, separate the 1st and 8th terms."],
    difficulty: 2,
    topicSlug: "sequences",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-052",
    question: "What is the 20th term of the arithmetic sequence 3, 7, 11, ...?",
    format: "SHORT_ANSWER",
    answer: "79",
    solution: "3 + 19 x 4 = 3 + 76 = 79.",
    hints: ["Nineteen gaps of 4."],
    difficulty: 2,
    topicSlug: "sequences",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-053",
    question: "What is the 100th term of the sequence 2, 5, 8, 11, ...?",
    format: "SHORT_ANSWER",
    answer: "299",
    solution: "2 + 99 x 3 = 2 + 297 = 299.",
    hints: ["The nth term is 3n - 1."],
    difficulty: 3,
    topicSlug: "patterns",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-054",
    question: "What is the sum of the first six terms of the geometric sequence 2, 6, 18, ...?",
    format: "SHORT_ANSWER",
    answer: "728",
    solution: "The terms are 2, 6, 18, 54, 162, 486, adding to 728.",
    hints: ["Or use 2(3^6 - 1)/(3 - 1)."],
    difficulty: 5,
    topicSlug: "sequences",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-055",
    question: "If 2^x = 32, what is x?",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "32 = 2^5, so x = 5.",
    hints: ["Write 32 as a power of 2."],
    difficulty: 2,
    topicSlug: "exponents-radicals",
    estimatedTimeSeconds: 15,
  },
  {
    slug: "cd-056",
    question: "If 3^(x+1) = 81, what is x?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution: "81 = 3^4, so x + 1 = 4 and x = 3.",
    hints: ["Match the exponents once both sides share a base."],
    difficulty: 3,
    topicSlug: "exponents-radicals",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-057",
    question: "What is 2^10 - 2^9?",
    format: "SHORT_ANSWER",
    answer: "512",
    solution: "2^10 - 2^9 = 2^9(2 - 1) = 2^9 = 512.",
    hints: ["Factor out the smaller power."],
    difficulty: 4,
    topicSlug: "exponents-radicals",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-058",
    question: "What is the square root of 144 plus the square root of 81?",
    format: "SHORT_ANSWER",
    answer: "21",
    solution: "12 + 9 = 21.",
    hints: ["Both are perfect squares."],
    difficulty: 2,
    topicSlug: "exponents-radicals",
    estimatedTimeSeconds: 15,
  },
  {
    slug: "cd-059",
    question: "If a + b = 12 and a - b = 4, what is ab?",
    format: "SHORT_ANSWER",
    answer: "32",
    solution: "Adding gives 2a = 16 so a = 8, then b = 4, and ab = 32.",
    hints: ["Add the two equations."],
    difficulty: 3,
    topicSlug: "systems-of-equations",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-060",
    question: "In the expansion of (x - 2)(x + 5), what is the coefficient of x?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution: "The x terms are 5x - 2x = 3x, so the coefficient is 3.",
    hints: ["Only the two cross terms matter."],
    difficulty: 3,
    topicSlug: "polynomials",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-061",
    question: "What is the smallest integer x for which 4x > 55?",
    format: "SHORT_ANSWER",
    answer: "14",
    solution: "x > 13.75, so the smallest integer is 14.",
    hints: ["Divide, then round up."],
    difficulty: 3,
    topicSlug: "inequalities",
    estimatedTimeSeconds: 20,
  },

  // ------------------------------ geometry ------------------------------
  {
    slug: "cd-062",
    question: "What is the area of a triangle with base 14 and height 9?",
    format: "SHORT_ANSWER",
    answer: "63",
    solution: "Half of 14 x 9 = 126 is 63.",
    hints: ["Halve the base first."],
    difficulty: 2,
    topicSlug: "triangles",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-063",
    question: "A square has area 49. What is its perimeter?",
    format: "SHORT_ANSWER",
    answer: "28",
    solution: "The side is 7, so the perimeter is 4 x 7 = 28.",
    hints: ["Take the square root before multiplying."],
    difficulty: 2,
    topicSlug: "quadrilaterals",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-064",
    question: "What is the sum of the interior angles of an octagon, in degrees?",
    format: "SHORT_ANSWER",
    answer: "1080",
    solution: "(8 - 2) x 180 = 1080 degrees.",
    hints: ["An n-gon splits into n - 2 triangles."],
    difficulty: 3,
    topicSlug: "polygons",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-065",
    question: "What is the measure, in degrees, of one interior angle of a regular hexagon?",
    format: "SHORT_ANSWER",
    answer: "120",
    solution: "The interior angles total 720 degrees, and 720 / 6 = 120.",
    hints: ["Find the total, then divide by 6."],
    difficulty: 3,
    topicSlug: "polygons",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-066",
    question: "What is the measure, in degrees, of an exterior angle of a regular pentagon?",
    format: "SHORT_ANSWER",
    answer: "72",
    solution: "Exterior angles always total 360 degrees, so each is 360 / 5 = 72.",
    hints: ["The exterior angles of any polygon sum to 360."],
    difficulty: 3,
    topicSlug: "polygons",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-067",
    question: "How many diagonals does a decagon have?",
    format: "SHORT_ANSWER",
    answer: "35",
    solution: "10 x 7 / 2 = 35, since each of the 10 vertices joins 7 non-neighbours.",
    hints: ["Count from each vertex, then halve to avoid double counting."],
    difficulty: 4,
    topicSlug: "polygons",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-068",
    question: "Two angles of a triangle measure 47 and 68 degrees. What is the third, in degrees?",
    format: "SHORT_ANSWER",
    answer: "65",
    solution: "180 - 47 - 68 = 65 degrees.",
    hints: ["The two given angles sum to 115."],
    difficulty: 2,
    topicSlug: "angles",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-069",
    question: "A right triangle has legs 9 and 12. What is the length of its hypotenuse?",
    format: "SHORT_ANSWER",
    answer: "15",
    solution: "This is a 3-4-5 triangle scaled by 3, so the hypotenuse is 15.",
    hints: ["Divide all sides by 3 and look for a familiar triple."],
    difficulty: 2,
    topicSlug: "triangles",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-070",
    question: "A right triangle has hypotenuse 25 and one leg 7. What is the other leg?",
    format: "SHORT_ANSWER",
    answer: "24",
    solution: "625 - 49 = 576, whose square root is 24.",
    hints: ["7-24-25 is a triple worth remembering."],
    difficulty: 3,
    topicSlug: "triangles",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-071",
    question: "What is the circumference of a circle of radius 7? Give your answer in terms of pi.",
    format: "SHORT_ANSWER",
    answer: "14pi",
    solution: "The circumference is 2 x pi x 7 = 14pi.",
    hints: ["Circumference is 2 pi r."],
    difficulty: 2,
    topicSlug: "circles",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-072",
    question: "What is the area of a circle of diameter 10? Give your answer in terms of pi.",
    format: "SHORT_ANSWER",
    answer: "25pi",
    solution: "The radius is 5, so the area is 25pi.",
    hints: ["Halve the diameter before squaring."],
    difficulty: 3,
    topicSlug: "circles",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-073",
    question: "A circle has area 36pi. What is its radius?",
    format: "SHORT_ANSWER",
    answer: "6",
    solution: "r^2 = 36, so r = 6.",
    hints: ["Divide out the pi first."],
    difficulty: 3,
    topicSlug: "circles",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-074",
    question: "What is the volume of a cube with edge length 6?",
    format: "SHORT_ANSWER",
    answer: "216",
    solution: "6^3 = 216.",
    hints: ["Cube the edge."],
    difficulty: 2,
    topicSlug: "area-volume",
    estimatedTimeSeconds: 15,
  },
  {
    slug: "cd-075",
    question: "What is the surface area of a cube with edge length 5?",
    format: "SHORT_ANSWER",
    answer: "150",
    solution: "Six faces of area 25 each give 150.",
    hints: ["Six faces, not four."],
    difficulty: 2,
    topicSlug: "area-volume",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-076",
    question:
      "What is the volume of a cylinder of radius 3 and height 7? Give your answer in terms of pi.",
    format: "SHORT_ANSWER",
    answer: "63pi",
    solution: "The base area is 9pi, and 9pi x 7 = 63pi.",
    hints: ["Base area times height."],
    difficulty: 3,
    topicSlug: "area-volume",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-077",
    question: "What is the area of a trapezoid with parallel sides 6 and 14 and height 5?",
    format: "SHORT_ANSWER",
    answer: "50",
    solution: "The average of the parallel sides is 10, and 10 x 5 = 50.",
    hints: ["Average the two parallel sides, then multiply by the height."],
    difficulty: 3,
    topicSlug: "quadrilaterals",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-078",
    question: "What is the area of a rhombus whose diagonals measure 8 and 10?",
    format: "SHORT_ANSWER",
    answer: "40",
    solution: "Half the product of the diagonals: 8 x 10 / 2 = 40.",
    hints: ["Half the product of the diagonals."],
    difficulty: 3,
    topicSlug: "quadrilaterals",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-079",
    question: "A rectangle has perimeter 34 and length 11. What is its area?",
    format: "SHORT_ANSWER",
    answer: "66",
    solution: "The length and width sum to 17, so the width is 6 and the area is 66.",
    hints: ["Half the perimeter is one length plus one width."],
    difficulty: 3,
    topicSlug: "quadrilaterals",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-080",
    question: "What is the distance between the points (1, 2) and (7, 10)?",
    format: "SHORT_ANSWER",
    answer: "10",
    solution: "The legs are 6 and 8, so the distance is 10.",
    hints: ["A 6-8-10 right triangle."],
    difficulty: 3,
    topicSlug: "coordinate-geometry",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-081",
    question: "What is the slope of the line through (-3, 5) and (9, 1)?",
    format: "SHORT_ANSWER",
    answer: "-1/3",
    solution: "The slope is (1 - 5)/(9 - (-3)) = -4/12 = -1/3.",
    hints: ["Mind the sign on the run as well as the rise."],
    difficulty: 3,
    topicSlug: "coordinate-geometry",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-082",
    question: "What is the angle, in degrees, between the hands of a clock at 3:30?",
    format: "SHORT_ANSWER",
    answer: "75",
    solution:
      "The minute hand is at 180 degrees and the hour hand is halfway between 3 and 4, at 105 degrees. The difference is 75 degrees.",
    hints: ["The hour hand has moved half an hour past the 3."],
    difficulty: 5,
    topicSlug: "angles",
    estimatedTimeSeconds: 40,
  },

  // -------------------- counting and probability --------------------
  {
    slug: "cd-083",
    question: "In how many orders can the letters of MATH be arranged?",
    format: "SHORT_ANSWER",
    answer: "24",
    solution: "Four distinct letters give 4! = 24 arrangements.",
    hints: ["All four letters are different."],
    difficulty: 2,
    topicSlug: "permutations",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-084",
    question: "In how many orders can the letters of LEVEL be arranged?",
    format: "SHORT_ANSWER",
    answer: "30",
    solution: "5! / (2! x 2!) = 120 / 4 = 30, dividing out the repeated L and E.",
    hints: ["Two letters each appear twice."],
    difficulty: 4,
    topicSlug: "permutations",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-085",
    question: "How many ways are there to choose 2 objects from 8?",
    format: "SHORT_ANSWER",
    answer: "28",
    solution: "8 x 7 / 2 = 28.",
    hints: ["Order does not matter, so divide by 2."],
    difficulty: 3,
    topicSlug: "combinations",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-086",
    question: "How many ways are there to choose 3 objects from 10?",
    format: "SHORT_ANSWER",
    answer: "120",
    solution: "10 x 9 x 8 / 6 = 720 / 6 = 120.",
    hints: ["Divide the falling product by 3!."],
    difficulty: 3,
    topicSlug: "combinations",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-087",
    question: "How many subsets does a set of 5 elements have?",
    format: "SHORT_ANSWER",
    answer: "32",
    solution: "Each element is in or out, giving 2^5 = 32 subsets.",
    hints: ["Two independent choices per element."],
    difficulty: 3,
    topicSlug: "counting-principles",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-088",
    question: "How many three-digit numbers have three distinct nonzero digits?",
    format: "SHORT_ANSWER",
    answer: "504",
    solution: "9 choices, then 8, then 7: 9 x 8 x 7 = 504.",
    hints: ["Nine digits are available, and none may repeat."],
    difficulty: 4,
    topicSlug: "counting-principles",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-089",
    question:
      "In how many ways can 5 people stand in a row if two particular people must be next to each other?",
    format: "SHORT_ANSWER",
    answer: "48",
    solution: "Glue the pair into one block: 4! orderings, times 2 for the pair's internal order, is 48.",
    hints: ["Treat the pair as a single unit, then order it internally."],
    difficulty: 5,
    topicSlug: "permutations",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-090",
    question: "Two fair six-sided dice are rolled. What is the probability the sum is 7?",
    format: "SHORT_ANSWER",
    answer: "1/6",
    solution: "Six of the 36 equally likely outcomes total 7, so the probability is 1/6.",
    hints: ["One of the six faces on the second die works for each face on the first."],
    difficulty: 3,
    topicSlug: "basic-probability",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-091",
    question: "Two fair six-sided dice are rolled. What is the probability both show even numbers?",
    format: "SHORT_ANSWER",
    answer: "1/4",
    solution: "Each die is even with probability 1/2, and the rolls are independent, so 1/4.",
    hints: ["Multiply the two independent probabilities."],
    difficulty: 3,
    topicSlug: "basic-probability",
    estimatedTimeSeconds: 20,
  },
  {
    slug: "cd-092",
    question: "A fair coin is flipped 4 times. What is the probability of exactly 2 heads?",
    format: "SHORT_ANSWER",
    answer: "3/8",
    solution: "There are 6 of the 16 outcomes with two heads, and 6/16 = 3/8.",
    hints: ["Count the ways to choose which two flips are heads."],
    difficulty: 4,
    topicSlug: "counting-probability",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-093",
    question: "One card is drawn from a standard 52-card deck. What is the probability it is a heart?",
    format: "SHORT_ANSWER",
    answer: "1/4",
    solution: "13 of the 52 cards are hearts, so the probability is 1/4.",
    hints: ["Four suits, equally sized."],
    difficulty: 2,
    topicSlug: "basic-probability",
    estimatedTimeSeconds: 15,
  },
  {
    slug: "cd-094",
    question: "What is the expected value of one roll of a fair six-sided die?",
    format: "SHORT_ANSWER",
    answer: "7/2",
    solution: "The average of 1 through 6 is 21/6 = 7/2.",
    hints: ["Pair 1 with 6, 2 with 5, 3 with 4."],
    difficulty: 3,
    topicSlug: "expected-value",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-095",
    question:
      "A jar holds 5 red and 3 blue marbles. Two are drawn without replacement. What is the probability both are red?",
    format: "SHORT_ANSWER",
    answer: "5/14",
    solution: "(5/8) x (4/7) = 20/56 = 5/14.",
    hints: ["The second draw comes from a jar with one fewer marble."],
    difficulty: 4,
    topicSlug: "conditional-probability",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-096",
    question:
      "A fair coin is flipped 3 times. What is the probability of getting at least one head?",
    format: "SHORT_ANSWER",
    answer: "7/8",
    solution: "The only failing outcome is all three tails, with probability 1/8, so 1 - 1/8 = 7/8.",
    hints: ["Count the complement instead."],
    difficulty: 3,
    topicSlug: "basic-probability",
    estimatedTimeSeconds: 25,
  },

  // ------------------------------ hard tail ------------------------------
  // Difficulty 6-10, still inside the clock.
  //
  // Countdown centres selection on the student's rating, and with the bank
  // topping out at difficulty 5 anyone above about 1700 got no at-level
  // question at all — the selector fell through to slower problems, which is
  // precisely the failure this bank exists to fix. The strongest students are
  // also the ones a speed round suits best.
  //
  // These are hard in the way a speed round can be: the idea is the whole
  // problem and the execution is one line. "If x^2 - 5x + 6 = 0, what is
  // x^3 - 5x^2 + 6x + 7?" is instant once you see the substitution and
  // hopeless without it. None of them reward faster arithmetic.
  {
    slug: "cd-097",
    question: "What is the remainder when 3^100 is divided by 5?",
    format: "SHORT_ANSWER",
    answer: "1",
    solution: "3^4 = 81 leaves remainder 1, and 100 is a multiple of 4, so the remainder is 1.",
    hints: ["Find the smallest power of 3 that leaves remainder 1."],
    difficulty: 6,
    topicSlug: "modular-arithmetic",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-098",
    question: "What is 1 - 2 + 3 - 4 + ... + 99 - 100?",
    format: "SHORT_ANSWER",
    answer: "-50",
    solution: "Group into 50 pairs, each equal to -1, giving -50.",
    hints: ["Pair each odd term with the even term after it."],
    difficulty: 6,
    topicSlug: "sequences",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-099",
    question: "How many zeros does 100! end in?",
    format: "SHORT_ANSWER",
    answer: "24",
    solution: "Factors of 5: 20 multiples of 5, plus 4 more from the multiples of 25, giving 24.",
    hints: ["Count multiples of 5, then of 25."],
    difficulty: 6,
    topicSlug: "factorization",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-100",
    question: "What is the sum of the roots of x^3 - 6x^2 + 11x - 6 = 0?",
    format: "SHORT_ANSWER",
    answer: "6",
    solution: "For a monic cubic the roots sum to minus the x^2 coefficient, so 6.",
    hints: ["Vieta works for cubics too."],
    difficulty: 6,
    topicSlug: "polynomials",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-101",
    question: "What is the coefficient of x^2 in the expansion of (1 + x)^6?",
    format: "SHORT_ANSWER",
    answer: "15",
    solution: "The coefficient is 6 choose 2 = 15.",
    hints: ["Binomial coefficients."],
    difficulty: 6,
    topicSlug: "polynomials",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-102",
    question: "How many ordered pairs of positive integers (x, y) satisfy xy = 36?",
    format: "SHORT_ANSWER",
    answer: "9",
    solution: "One pair per divisor of 36, and 36 = 2^2 x 3^2 has 9 divisors.",
    hints: ["Each choice of x forces y."],
    difficulty: 6,
    topicSlug: "divisibility",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-103",
    question: "How many digits does 2^20 have?",
    format: "SHORT_ANSWER",
    answer: "7",
    solution: "2^20 = 1048576, which has 7 digits.",
    hints: ["2^20 is 1024 squared."],
    difficulty: 6,
    topicSlug: "integer-properties",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-104",
    question: "What is the sum of the distinct prime factors of 1001?",
    format: "SHORT_ANSWER",
    answer: "31",
    solution: "1001 = 7 x 11 x 13, and 7 + 11 + 13 = 31.",
    hints: ["1001 is the product of three consecutive primes."],
    difficulty: 6,
    topicSlug: "primes",
    estimatedTimeSeconds: 30,
  },
  {
    slug: "cd-105",
    question: "If i^2 = -1, what is i^2026?",
    format: "SHORT_ANSWER",
    answer: "-1",
    solution: "Powers of i cycle with period 4, and 2026 leaves remainder 2, so i^2026 = i^2 = -1.",
    hints: ["Reduce the exponent modulo 4."],
    difficulty: 6,
    topicSlug: "exponents-radicals",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-106",
    question: "What is the sum of the coefficients of (2x - 1)^5?",
    format: "SHORT_ANSWER",
    answer: "1",
    solution: "Substituting x = 1 gives the sum of the coefficients: (2 - 1)^5 = 1.",
    hints: ["Set x = 1."],
    difficulty: 6,
    topicSlug: "polynomials",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-107",
    question: "What is 1/(1x2) + 1/(2x3) + 1/(3x4) + ... + 1/(9x10)?",
    format: "SHORT_ANSWER",
    answer: "9/10",
    solution: "Each term is 1/k - 1/(k+1), so the sum telescopes to 1 - 1/10 = 9/10.",
    hints: ["Split each term into a difference of two reciprocals."],
    difficulty: 7,
    topicSlug: "sequences",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-108",
    question: "How many integers from 1 to 100 are relatively prime to 100?",
    format: "SHORT_ANSWER",
    answer: "40",
    solution: "100 = 2^2 x 5^2, so the count is 100 x (1/2) x (4/5) = 40.",
    hints: ["Exclude the multiples of 2 and of 5."],
    difficulty: 7,
    topicSlug: "advanced-number-theory",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-109",
    question: "How many subsets of a 10-element set have an even number of elements?",
    format: "SHORT_ANSWER",
    answer: "512",
    solution: "Exactly half of the 2^10 subsets have even size, giving 2^9 = 512.",
    hints: ["Toggling one fixed element pairs even subsets with odd ones."],
    difficulty: 7,
    topicSlug: "counting-principles",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-110",
    question: "What is the largest power of 2 dividing 20!?",
    format: "SHORT_ANSWER",
    answer: "18",
    solution: "10 + 5 + 2 + 1 = 18, counting multiples of 2, 4, 8, and 16.",
    hints: ["Add up the multiples of each power of 2."],
    difficulty: 7,
    topicSlug: "factorization",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-111",
    question:
      "How many solutions in positive integers does x + y + z = 10 have, counting order?",
    format: "SHORT_ANSWER",
    answer: "36",
    solution: "Place 2 dividers in the 9 gaps between 10 units: 9 choose 2 = 36.",
    hints: ["Stars and bars."],
    difficulty: 7,
    topicSlug: "counting-principles",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-112",
    question: "What is the units digit of 1! + 2! + 3! + ... + 10!?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution:
      "From 5! on, every factorial ends in 0, so only 1 + 2 + 6 + 24 matters: it ends in 3.",
    hints: ["Most of these terms contribute nothing to the units digit."],
    difficulty: 7,
    topicSlug: "number-patterns",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-113",
    question: "What is the sum of the reciprocals of the roots of 2x^2 - 7x + 3 = 0?",
    format: "SHORT_ANSWER",
    answer: "7/3",
    solution: "The sum of reciprocals is (sum of roots)/(product) = (7/2)/(3/2) = 7/3.",
    hints: ["Both Vieta quantities, divided."],
    difficulty: 7,
    topicSlug: "quadratics",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-114",
    question:
      "Two distinct numbers are chosen from 1 to 10. What is the probability their sum is even?",
    format: "SHORT_ANSWER",
    answer: "4/9",
    solution: "Both must be odd or both even: 10 + 10 = 20 of the 45 pairs, which is 4/9.",
    hints: ["An even sum needs matching parity."],
    difficulty: 7,
    topicSlug: "counting-probability",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-115",
    question: "How many integers from 1 to 1000 are divisible by neither 2 nor 3?",
    format: "SHORT_ANSWER",
    answer: "333",
    solution: "1000 - 500 - 333 + 166 = 333.",
    hints: ["Inclusion-exclusion, then subtract from 1000."],
    difficulty: 7,
    topicSlug: "inclusion-exclusion",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-116",
    question: "How many positive integers below 100 are perfect squares or perfect cubes?",
    format: "SHORT_ANSWER",
    answer: "11",
    solution: "9 squares and 4 cubes, with 1 and 64 counted twice: 9 + 4 - 2 = 11.",
    hints: ["The overlap is the perfect sixth powers."],
    difficulty: 7,
    topicSlug: "inclusion-exclusion",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-117",
    question: "What is floor(sqrt(1)) + floor(sqrt(2)) + ... + floor(sqrt(10))?",
    format: "SHORT_ANSWER",
    answer: "19",
    solution: "The values are 1,1,1,2,2,2,2,2,3,3, which sum to 19.",
    hints: ["The value jumps only at perfect squares."],
    difficulty: 7,
    topicSlug: "number-patterns",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-118",
    question: "What is the remainder when 2^10 is divided by 1000?",
    format: "SHORT_ANSWER",
    answer: "24",
    solution: "2^10 = 1024, so the remainder is 24.",
    hints: ["The last three digits are all that matter."],
    difficulty: 6,
    topicSlug: "modular-arithmetic",
    estimatedTimeSeconds: 25,
  },
  {
    slug: "cd-119",
    question: "If x^2 - 5x + 6 = 0, what is x^3 - 5x^2 + 6x + 7?",
    format: "SHORT_ANSWER",
    answer: "7",
    solution: "x^3 - 5x^2 + 6x = x(x^2 - 5x + 6) = 0, so the expression is 7.",
    hints: ["Factor an x out of the first three terms."],
    difficulty: 8,
    topicSlug: "polynomials",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-120",
    question: "In how many ways can a 1-by-10 strip be tiled by 1-by-1 and 1-by-2 pieces?",
    format: "SHORT_ANSWER",
    answer: "89",
    solution:
      "The counts satisfy the Fibonacci recurrence from 1 and 2, giving 1, 2, 3, 5, 8, 13, 21, 34, 55, 89.",
    hints: ["Consider the last piece placed."],
    difficulty: 8,
    topicSlug: "recursion-in-counting",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-121",
    question: "What is the remainder when 7^(7^7) is divided by 4?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution: "7 leaves remainder 3, and 3^odd leaves remainder 3. The exponent is odd, so 3.",
    hints: ["Only the parity of the exponent matters modulo 4."],
    difficulty: 8,
    topicSlug: "modular-arithmetic",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-122",
    question: "How many positive divisors of 1000 are perfect squares?",
    format: "SHORT_ANSWER",
    answer: "4",
    solution: "1000 = 2^3 x 5^3, so a square divisor needs even exponents: 2 choices each, giving 4.",
    hints: ["Both exponents must be even and at most 3."],
    difficulty: 8,
    topicSlug: "factorization",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-123",
    question: "What is the 2026th digit after the decimal point of 1/7?",
    format: "SHORT_ANSWER",
    answer: "8",
    solution:
      "1/7 = 0.142857 repeating with period 6. Since 2026 leaves remainder 4, the digit is the 4th: 8.",
    hints: ["Find the period, then reduce 2026 modulo it."],
    difficulty: 8,
    topicSlug: "number-patterns",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-124",
    question: "How many distinct prime factors does 2^12 - 1 have?",
    format: "SHORT_ANSWER",
    answer: "4",
    solution: "2^12 - 1 = 4095 = 3^2 x 5 x 7 x 13, which is 4 distinct primes.",
    hints: ["Factor 4095 by repeated small primes."],
    difficulty: 8,
    topicSlug: "advanced-number-theory",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-125",
    question:
      "What is the probability a random permutation of 1, 2, 3, 4 leaves no number in its own position?",
    format: "SHORT_ANSWER",
    answer: "3/8",
    solution: "There are 9 such permutations out of 24, and 9/24 = 3/8.",
    hints: ["Count derangements of four objects."],
    difficulty: 8,
    topicSlug: "advanced-combinatorics",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-126",
    question: "What is the remainder when 2^2026 is divided by 9?",
    format: "SHORT_ANSWER",
    answer: "7",
    solution: "2 has order 6 modulo 9, and 2026 leaves remainder 4, so 2^4 = 16 leaves 7.",
    hints: ["Find the order of 2 modulo 9 first."],
    difficulty: 9,
    topicSlug: "advanced-number-theory",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-127",
    question: "What is the greatest common divisor of 2^12 - 1 and 2^18 - 1?",
    format: "SHORT_ANSWER",
    answer: "63",
    solution: "gcd(2^a - 1, 2^b - 1) = 2^gcd(a,b) - 1, and gcd(12, 18) = 6, so 2^6 - 1 = 63.",
    hints: ["The exponents' gcd controls the answer."],
    difficulty: 9,
    topicSlug: "advanced-number-theory",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-128",
    question: "What is the multiplicative order of 2 modulo 11?",
    format: "SHORT_ANSWER",
    answer: "10",
    solution:
      "The powers of 2 modulo 11 run 2, 4, 8, 5, 10, 9, 7, 3, 6, 1 — ten of them before returning to 1.",
    hints: ["The order divides 10, so test 1, 2, 5, then 10."],
    difficulty: 9,
    topicSlug: "advanced-number-theory",
    estimatedTimeSeconds: 45,
  },
  {
    slug: "cd-129",
    question:
      "What is the sum of the first ten terms of 1/2, 1/4, 1/8, ...? Give your answer as a fraction.",
    format: "SHORT_ANSWER",
    answer: "1023/1024",
    solution: "The sum is 1 - 1/2^10 = 1023/1024.",
    hints: ["Each partial sum falls short of 1 by the last term."],
    difficulty: 7,
    topicSlug: "sequences",
    estimatedTimeSeconds: 35,
  },
  {
    slug: "cd-130",
    question:
      "If w is a nonreal cube root of 1, what is (1 + w)(1 + w^2)?",
    format: "SHORT_ANSWER",
    answer: "1",
    solution:
      "Expanding gives 1 + w + w^2 + w^3 = 1 + (-1) + 1 = 1, using 1 + w + w^2 = 0 and w^3 = 1.",
    hints: ["The three cube roots of 1 sum to zero."],
    difficulty: 10,
    topicSlug: "advanced-number-theory",
    estimatedTimeSeconds: 40,
  },
  {
    slug: "cd-131",
    question:
      "For how many integers n from 1 to 100 is the number of integers below n and coprime to n odd?",
    format: "SHORT_ANSWER",
    answer: "2",
    solution:
      "Euler's totient is even for every n greater than 2, so only n = 1 and n = 2 qualify.",
    hints: ["Coprime residues pair up as r and n - r for large n."],
    difficulty: 10,
    topicSlug: "advanced-number-theory",
    estimatedTimeSeconds: 45,
  },
  {
    slug: "cd-132",
    question:
      "How many lattice points lie strictly inside the circle of radius 2 centred at the origin?",
    format: "SHORT_ANSWER",
    answer: "9",
    solution:
      "Points with x^2 + y^2 < 4 have both coordinates in {-1, 0, 1}, and all 9 of those qualify.",
    hints: ["Both coordinates must have absolute value at most 1."],
    difficulty: 7,
    topicSlug: "coordinate-geometry",
    estimatedTimeSeconds: 40,
  },
];
