export type ProblemSeed = {
  slug: string;
  question: string;
  format: "MULTIPLE_CHOICE" | "SHORT_ANSWER" | "INTEGER";
  choices?: string[];
  answer: string;
  solution: string;
  hints: string[];
  difficulty: number; // 1-10
  topicSlug: string;
  competitionSlug?: string;
};

// All problems are original NumberSmith content, written and verified for this
// platform. None are transcribed from official competition archives.

export const PROBLEMS: ProblemSeed[] = [
  // ============================= ARITHMETIC =============================
  {
    slug: "arith-fractions-01",
    question: "What is 3/4 + 1/8?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "7/8", "5/8", "4/12", "1/2"],
    answer: "B",
    solution: "Rewrite 3/4 as 6/8. Then 6/8 + 1/8 = 7/8.",
    hints: ["Find a common denominator of 8.", "3/4 = 6/8, so add the numerators over 8."],
    difficulty: 1,
    topicSlug: "fractions",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "arith-fractions-02",
    question: "Simplify 18/24 to lowest terms.",
    format: "MULTIPLE_CHOICE",
    choices: ["2/3", "4/5", "5/6", "3/4", "7/8"],
    answer: "D",
    solution: "The GCD of 18 and 24 is 6. Dividing both by 6 gives 3/4.",
    hints: ["Find the greatest common divisor of 18 and 24.", "6 divides both evenly."],
    difficulty: 2,
    topicSlug: "fractions",
  },
  {
    slug: "arith-ratios-01",
    question:
      "The ratio of boys to girls in a class is 3:5. If there are 24 students total, how many girls are there?",
    format: "SHORT_ANSWER",
    answer: "15",
    solution: "3 + 5 = 8 total parts. Each part is 24 / 8 = 3 students. Girls = 5 parts = 15.",
    hints: ["Add the ratio parts to find how many students each part represents.", "5 parts × 3 students per part."],
    difficulty: 2,
    topicSlug: "ratios-proportions",
  },
  {
    slug: "arith-ratios-02",
    question:
      "A recipe calls for flour and sugar in a ratio of 5:2. If you use 350g of flour, how much sugar (in grams) should you use?",
    format: "MULTIPLE_CHOICE",
    choices: ["140", "175", "120", "150", "100"],
    answer: "A",
    solution: "350 / 5 = 70 grams per part. Sugar = 2 parts × 70 = 140 grams.",
    hints: ["Divide the flour amount by its ratio part (5) to find one 'part'.", "Multiply that by the sugar's ratio part (2)."],
    difficulty: 3,
    topicSlug: "ratios-proportions",
  },
  {
    slug: "arith-percent-01",
    question: "What is 15% of 240?",
    format: "SHORT_ANSWER",
    answer: "36",
    solution: "15% of 240 = 0.15 × 240 = 36.",
    hints: ["Convert 15% to the decimal 0.15.", "Multiply 0.15 by 240."],
    difficulty: 2,
    topicSlug: "percentages",
  },
  {
    slug: "arith-percent-02",
    question:
      "A shirt originally priced at $40 is discounted 25%. The sale price is then increased by 10%. What is the final price?",
    format: "MULTIPLE_CHOICE",
    choices: ["30", "33", "36", "32", "35"],
    answer: "B",
    solution: "After the discount: 40 × 0.75 = $30. After the increase: 30 × 1.10 = $33.",
    hints: ["Apply the 25% discount first — multiply by 0.75.", "Then increase the new price by 10% — multiply by 1.10."],
    difficulty: 3,
    topicSlug: "percentages",
    competitionSlug: "amc8",
  },
  {
    slug: "arith-percent-03",
    question: "A number increased by 20% equals 90. What is the original number?",
    format: "SHORT_ANSWER",
    answer: "75",
    solution: "Let the number be x. 1.2x = 90, so x = 90 / 1.2 = 75.",
    hints: ["Set up the equation 1.2x = 90.", "Divide both sides by 1.2."],
    difficulty: 4,
    topicSlug: "percentages",
    competitionSlug: "amc8",
  },
  {
    slug: "arith-rates-01",
    question: "A car travels 150 miles in 3 hours. At the same rate, how many miles does it travel in 5 hours?",
    format: "SHORT_ANSWER",
    answer: "250",
    solution: "Rate = 150 / 3 = 50 mph. Distance in 5 hours = 50 × 5 = 250 miles.",
    hints: ["Find the rate in miles per hour first.", "Multiply the rate by 5 hours."],
    difficulty: 2,
    topicSlug: "rates",
  },
  {
    slug: "arith-rates-02",
    question:
      "Pipe A fills a tank in 6 hours. Pipe B fills the same tank in 3 hours. Working together, how many hours does it take to fill the tank?",
    format: "MULTIPLE_CHOICE",
    choices: ["2.5", "3", "2", "1.5", "4"],
    answer: "C",
    solution: "Combined rate = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2 tank per hour, so it takes 2 hours.",
    hints: ["Add the two pipes' rates (tanks per hour), not their times.", "1/6 + 1/3 = 1/2 tank per hour."],
    difficulty: 3,
    topicSlug: "rates",
    competitionSlug: "mathcounts",
  },
  {
    slug: "arith-averages-01",
    question:
      "The average of 4 numbers is 18. If one number is removed, the average of the remaining 3 is 20. What number was removed?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "Sum of 4 numbers = 72. Sum of remaining 3 = 60. Removed number = 72 - 60 = 12.",
    hints: ["Multiply each average by its count to get the total sum.", "Subtract the new total from the original total."],
    difficulty: 2,
    topicSlug: "averages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "arith-averages-02",
    question: "Test scores of 82, 91, 76, 88, and x average to 85. Find x.",
    format: "MULTIPLE_CHOICE",
    choices: ["85", "90", "82", "84", "88"],
    answer: "E",
    solution: "Total needed = 85 × 5 = 425. Sum of the four known scores = 337. x = 425 - 337 = 88.",
    hints: ["Multiply the target average by 5 to find the required total.", "Subtract the sum of the known scores."],
    difficulty: 3,
    topicSlug: "averages",
  },
  {
    slug: "arith-numprop-01",
    question: "How many positive divisors does 60 have?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "60 = 2² × 3¹ × 5¹. Number of divisors = (2+1)(1+1)(1+1) = 12.",
    hints: ["Write 60 as a product of prime powers.", "Add 1 to each exponent and multiply the results."],
    difficulty: 3,
    topicSlug: "number-properties",
  },
  {
    slug: "arith-numprop-02",
    question: "What is the units digit of 7^123?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "7", "9", "1", "5"],
    answer: "A",
    solution: "Units digits of powers of 7 cycle 7, 9, 3, 1 with period 4. 123 mod 4 = 3, so the answer matches the 3rd term: 3.",
    hints: ["Look at the pattern of units digits: 7, 9, 3, 1, 7, 9, 3, 1, ...", "Find 123 mod 4 to see where in the cycle it lands."],
    difficulty: 4,
    topicSlug: "number-properties",
  },
  {
    slug: "arith-fractions-03",
    question: "If 2/3 of a number is 15 more than 1/4 of the number, what is the number?",
    format: "SHORT_ANSWER",
    answer: "36",
    solution: "5x/12 = 15, so x = 15 × 12 / 5 = 36.",
    hints: ["Write the equation (2/3)x - (1/4)x = 15.", "Combine the fractions using a common denominator of 12."],
    difficulty: 5,
    topicSlug: "fractions",
    competitionSlug: "amc10",
  },
  {
    slug: "arith-ratios-03",
    question: "Three numbers are in the ratio 2:3:5 and sum to 150. What is the largest of the three numbers?",
    format: "MULTIPLE_CHOICE",
    choices: ["50", "75", "60", "90", "70"],
    answer: "B",
    solution: "Total parts = 10, so each part = 15. The largest number is 5 × 15 = 75.",
    hints: ["Add the ratio parts to get the value of one part.", "Multiply the largest ratio number by that value."],
    difficulty: 5,
    topicSlug: "ratios-proportions",
  },

  // ============================== ALGEBRA ==============================
  {
    slug: "alg-linear-01",
    question: "Solve for x: 3x + 7 = 22.",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "3x = 15, so x = 5.",
    hints: ["Subtract 7 from both sides first.", "Then divide both sides by 3."],
    difficulty: 2,
    topicSlug: "linear-equations",
  },
  {
    slug: "alg-linear-02",
    question: "If 5(x - 2) = 3x + 4, what is x?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "8", "7", "5", "9"],
    answer: "C",
    solution: "5x - 10 = 3x + 4. Then 2x = 14, so x = 7.",
    hints: ["Distribute the 5 on the left side first.", "Collect x terms on one side and constants on the other."],
    difficulty: 3,
    topicSlug: "linear-equations",
  },
  {
    slug: "alg-systems-01",
    question: "If x + y = 10 and x - y = 4, what is x?",
    format: "SHORT_ANSWER",
    answer: "7",
    solution: "Adding the two equations: 2x = 14, so x = 7.",
    hints: ["Add the two equations together to eliminate y.", "Solve the resulting equation for x."],
    difficulty: 3,
    topicSlug: "systems-of-equations",
  },
  {
    slug: "alg-systems-02",
    question: "If 3x + 2y = 16 and x - y = 2, what is x + y?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "7", "5", "8", "4"],
    answer: "A",
    solution: "From x - y = 2, x = y + 2. Substituting: 3(y+2) + 2y = 16, so 5y = 10, y = 2, x = 4. Then x + y = 6.",
    hints: ["Solve the second equation for x in terms of y.", "Substitute into the first equation and solve for y."],
    difficulty: 4,
    topicSlug: "systems-of-equations",
    competitionSlug: "amc10",
  },
  {
    slug: "alg-ineq-01",
    question: "How many positive integers x satisfy 3x - 5 < 16?",
    format: "SHORT_ANSWER",
    answer: "6",
    solution: "3x < 21, so x < 7. The positive integers less than 7 are 1 through 6 — that's 6 values.",
    hints: ["Isolate x to get x < 7.", "Count the positive integers strictly less than 7."],
    difficulty: 3,
    topicSlug: "inequalities",
  },
  {
    slug: "alg-ineq-02",
    question: "What is the largest integer x satisfying 4x + 9 ≤ 37?",
    format: "MULTIPLE_CHOICE",
    choices: ["8", "6", "9", "7", "5"],
    answer: "D",
    solution: "4x ≤ 28, so x ≤ 7. The largest integer satisfying this is 7.",
    hints: ["Subtract 9 from both sides.", "Divide by 4 to isolate x."],
    difficulty: 4,
    topicSlug: "inequalities",
  },
  {
    slug: "alg-factoring-01",
    question: "If x² - 5x + 6 = 0, what is the sum of the two solutions?",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "By Vieta's formulas, the sum of the roots of x² - 5x + 6 = 0 is -(-5)/1 = 5. (The roots are 2 and 3.)",
    hints: ["Try factoring: (x - 2)(x - 3) = 0.", "Or recall that for x² + bx + c = 0, the sum of roots is -b."],
    difficulty: 3,
    topicSlug: "factoring",
  },
  {
    slug: "alg-factoring-02",
    question: "What is the product of the two roots of x² - 7x + 12 = 0?",
    format: "MULTIPLE_CHOICE",
    choices: ["7", "-12", "-7", "5", "12"],
    answer: "E",
    solution: "By Vieta's formulas, the product of the roots equals c/a = 12/1 = 12. (The roots are 3 and 4.)",
    hints: ["Try factoring the quadratic into two binomials.", "For x² + bx + c, the product of roots is c."],
    difficulty: 4,
    topicSlug: "factoring",
  },
  {
    slug: "alg-poly-01",
    question: "If f(x) = x² - 3x + 2, what is f(5)?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "f(5) = 25 - 15 + 2 = 12.",
    hints: ["Substitute x = 5 directly into the expression.", "Compute 5² first, then subtract 3(5), then add 2."],
    difficulty: 5,
    topicSlug: "polynomials",
  },
  {
    slug: "alg-exp-01",
    question: "Simplify 2⁵ × 2³.",
    format: "MULTIPLE_CHOICE",
    choices: ["64", "256", "128", "32", "512"],
    answer: "B",
    solution: "When multiplying powers with the same base, add exponents: 2⁵ × 2³ = 2⁸ = 256.",
    hints: ["Same base — add the exponents.", "2⁸ = 256."],
    difficulty: 3,
    topicSlug: "exponents-radicals",
  },
  {
    slug: "alg-exp-02",
    question: "What is √144 + √81?",
    format: "SHORT_ANSWER",
    answer: "21",
    solution: "√144 = 12 and √81 = 9. 12 + 9 = 21.",
    hints: ["Find each square root separately.", "12 is the square root of 144."],
    difficulty: 4,
    topicSlug: "exponents-radicals",
  },
  {
    slug: "alg-exp-03",
    question: "If 3^(x+1) = 81, what is x?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "2", "3", "5", "27"],
    answer: "C",
    solution: "81 = 3⁴, so x + 1 = 4, giving x = 3.",
    hints: ["Write 81 as a power of 3.", "Set the exponents equal to each other."],
    difficulty: 6,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc10",
  },
  {
    slug: "alg-seq-01",
    question: "Find the 10th term of the arithmetic sequence 4, 7, 10, 13, ...",
    format: "SHORT_ANSWER",
    answer: "31",
    solution: "aₙ = 4 + (n-1)(3). a₁₀ = 4 + 9(3) = 4 + 27 = 31.",
    hints: ["Identify the common difference (it's 3).", "Use aₙ = a₁ + (n-1)d."],
    difficulty: 3,
    topicSlug: "sequences",
  },
  {
    slug: "alg-seq-02",
    question: "What is the sum of the first 20 positive integers?",
    format: "MULTIPLE_CHOICE",
    choices: ["210", "200", "190", "220", "205"],
    answer: "A",
    solution: "Sum = n(n+1)/2 = 20(21)/2 = 210.",
    hints: ["Use the formula for the sum of the first n positive integers.", "n(n+1)/2 with n = 20."],
    difficulty: 5,
    topicSlug: "sequences",
  },
  {
    slug: "alg-seq-03",
    question: "In a geometric sequence, a₁ = 3 and the common ratio is 2. What is a₆?",
    format: "SHORT_ANSWER",
    answer: "96",
    solution: "aₙ = a₁ × r^(n-1). a₆ = 3 × 2⁵ = 3 × 32 = 96.",
    hints: ["Use aₙ = a₁ × r^(n-1).", "You need 2 raised to the 5th power, not the 6th."],
    difficulty: 6,
    topicSlug: "sequences",
  },
  {
    slug: "alg-func-01",
    question: "If f(x) = 2x - 3, what is f(f(4))?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "7", "9", "11", "3"],
    answer: "B",
    solution: "f(4) = 2(4) - 3 = 5. Then f(5) = 2(5) - 3 = 7.",
    hints: ["Work from the inside out — find f(4) first.", "Then plug that result back into f."],
    difficulty: 4,
    topicSlug: "functions",
  },
  {
    slug: "alg-quad-01",
    question: "What is the sum of the roots of 2x² - 8x + 6 = 0?",
    format: "SHORT_ANSWER",
    answer: "4",
    solution: "Sum of roots = -b/a = 8/2 = 4.",
    hints: ["Use Vieta's formula: sum of roots = -b/a.", "Here a = 2 and b = -8."],
    difficulty: 6,
    topicSlug: "quadratics",
  },
  {
    slug: "alg-quad-02",
    question:
      "For what positive value of k does x² + kx + 9 = 0 have exactly one real solution?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "3", "12", "6", "18"],
    answer: "D",
    solution: "One real solution means the discriminant is 0: k² - 36 = 0, so k = ±6. Taking the positive value, k = 6.",
    hints: ["Set the discriminant b² - 4ac equal to 0.", "Solve k² - 36 = 0 for the positive root."],
    difficulty: 7,
    topicSlug: "quadratics",
    competitionSlug: "amc12",
  },

  // ============================== GEOMETRY ==============================
  {
    slug: "geo-angles-01",
    question: "Two angles are supplementary. One measures 65°. What is the other?",
    format: "SHORT_ANSWER",
    answer: "115",
    solution: "Supplementary angles sum to 180°. 180 - 65 = 115.",
    hints: ["Supplementary angles add up to 180°.", "Subtract 65 from 180."],
    difficulty: 1,
    topicSlug: "angles",
  },
  {
    slug: "geo-angles-02",
    question: "In a triangle, two angles measure 50° and 60°. What is the third angle?",
    format: "MULTIPLE_CHOICE",
    choices: ["60", "80", "70", "65", "75"],
    answer: "C",
    solution: "Triangle angles sum to 180°. 180 - 50 - 60 = 70.",
    hints: ["The angles of a triangle always sum to 180°.", "Subtract both given angles from 180."],
    difficulty: 2,
    topicSlug: "angles",
    competitionSlug: "amc8",
  },
  {
    slug: "geo-triangles-01",
    question: "A right triangle has legs of length 6 and 8. What is the length of the hypotenuse?",
    format: "SHORT_ANSWER",
    answer: "10",
    solution: "By the Pythagorean theorem: √(6² + 8²) = √(36 + 64) = √100 = 10.",
    hints: ["Use the Pythagorean theorem a² + b² = c².", "6² + 8² = 100."],
    difficulty: 3,
    topicSlug: "triangles",
  },
  {
    slug: "geo-triangles-02",
    question: "An isosceles triangle has a base angle of 70°. What is the vertex angle?",
    format: "MULTIPLE_CHOICE",
    choices: ["40", "70", "50", "60", "45"],
    answer: "A",
    solution: "Both base angles are 70° each, totaling 140°. The vertex angle is 180 - 140 = 40°.",
    hints: ["In an isosceles triangle, the two base angles are equal.", "All three angles must sum to 180°."],
    difficulty: 4,
    topicSlug: "triangles",
  },
  {
    slug: "geo-quad-01",
    question: "A rectangle has length 12 and width 5. What is its perimeter?",
    format: "SHORT_ANSWER",
    answer: "34",
    solution: "Perimeter = 2(length + width) = 2(12 + 5) = 34.",
    hints: ["Perimeter of a rectangle = 2(l + w).", "Add length and width, then double it."],
    difficulty: 2,
    topicSlug: "quadrilaterals",
  },
  {
    slug: "geo-quad-02",
    question: "A parallelogram has base 9 and height 4. What is its area?",
    format: "MULTIPLE_CHOICE",
    choices: ["26", "18", "40", "13", "36"],
    answer: "E",
    solution: "Area of a parallelogram = base × height = 9 × 4 = 36.",
    hints: ["Area of a parallelogram uses the same formula as a rectangle.", "Multiply base by height."],
    difficulty: 3,
    topicSlug: "quadrilaterals",
    competitionSlug: "mathcounts",
  },
  {
    slug: "geo-polygons-01",
    question: "What is the sum of the interior angles of a hexagon?",
    format: "SHORT_ANSWER",
    answer: "720",
    solution: "Sum of interior angles = (n - 2) × 180. For n = 6: 4 × 180 = 720.",
    hints: ["Use the formula (n - 2) × 180° for an n-sided polygon.", "A hexagon has 6 sides."],
    difficulty: 4,
    topicSlug: "polygons",
  },
  {
    slug: "geo-polygons-02",
    question: "Each interior angle of a regular polygon measures 150°. How many sides does it have?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "12", "9", "15", "8"],
    answer: "B",
    solution: "Each exterior angle is 180 - 150 = 30°. Number of sides = 360 / 30 = 12.",
    hints: ["Find the exterior angle first (180° minus the interior angle).", "Exterior angles of a regular polygon sum to 360°."],
    difficulty: 5,
    topicSlug: "polygons",
  },
  {
    slug: "geo-circles-01",
    question: "A circle has radius 7. Using π ≈ 22/7, what is its circumference?",
    format: "SHORT_ANSWER",
    answer: "44",
    solution: "C = 2πr = 2 × (22/7) × 7 = 44.",
    hints: ["Use C = 2πr.", "The 7s will cancel nicely with 22/7."],
    difficulty: 3,
    topicSlug: "circles",
  },
  {
    slug: "geo-circles-02",
    question: "A circle has diameter 10. What is its area in terms of π?",
    format: "MULTIPLE_CHOICE",
    choices: ["10π", "50π", "25π", "100π", "20π"],
    answer: "C",
    solution: "Radius = 5. Area = πr² = π(5²) = 25π.",
    hints: ["Find the radius from the diameter first.", "Area = πr²."],
    difficulty: 4,
    topicSlug: "circles",
    competitionSlug: "amc8",
  },
  {
    slug: "geo-similarity-01",
    question: "Triangle ABC is similar to triangle DEF with a ratio of 2:3. If AB = 8, what is DE?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "8 × (3/2) = 12.",
    hints: ["Set up a proportion using the similarity ratio.", "DE / AB = 3 / 2."],
    difficulty: 5,
    topicSlug: "similarity-congruence",
  },
  {
    slug: "geo-similarity-02",
    question:
      "Two similar triangles have areas in ratio 4:9. What is the ratio of their corresponding side lengths?",
    format: "MULTIPLE_CHOICE",
    choices: ["4:9", "2:9", "16:81", "2:3", "4:3"],
    answer: "D",
    solution: "The ratio of areas equals the square of the ratio of sides. √(4/9) = 2/3.",
    hints: ["Area ratio = (side ratio)².", "Take the square root of 4/9."],
    difficulty: 6,
    topicSlug: "similarity-congruence",
  },
  {
    slug: "geo-coord-01",
    question: "What is the distance between the points (1, 2) and (4, 6)?",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "Distance = √((4-1)² + (6-2)²) = √(9 + 16) = √25 = 5.",
    hints: ["Use the distance formula √((x₂-x₁)² + (y₂-y₁)²).", "The differences are 3 and 4 — a familiar Pythagorean pair."],
    difficulty: 3,
    topicSlug: "coordinate-geometry",
  },
  {
    slug: "geo-coord-02",
    question: "What is the slope of the line through (2, 3) and (6, 11)?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "1/2", "4", "8", "1"],
    answer: "A",
    solution: "Slope = (11 - 3) / (6 - 2) = 8 / 4 = 2.",
    hints: ["Slope = (change in y) / (change in x).", "Compute 11-3 and 6-2 first."],
    difficulty: 4,
    topicSlug: "coordinate-geometry",
  },
  {
    slug: "geo-area-01",
    question: "A rectangular box has dimensions 4 × 5 × 6. What is its volume?",
    format: "SHORT_ANSWER",
    answer: "120",
    solution: "Volume = 4 × 5 × 6 = 120.",
    hints: ["Volume of a rectangular box = length × width × height.", "Multiply all three dimensions together."],
    difficulty: 3,
    topicSlug: "area-volume",
  },
  {
    slug: "geo-area-02",
    question: "A cylinder has radius 3 and height 10. What is its volume in terms of π?",
    format: "MULTIPLE_CHOICE",
    choices: ["30π", "60π", "90π", "270π", "45π"],
    answer: "C",
    solution: "Volume = πr²h = π(3²)(10) = 90π.",
    hints: ["Volume of a cylinder = πr²h.", "Square the radius before multiplying by height."],
    difficulty: 5,
    topicSlug: "area-volume",
  },
  {
    slug: "geo-transform-01",
    question: "Point (3, -2) is reflected over the x-axis. What are its new coordinates?",
    format: "SHORT_ANSWER",
    answer: "(3, 2)",
    solution: "Reflecting over the x-axis negates the y-coordinate: (3, -2) → (3, 2).",
    hints: ["Reflecting over the x-axis keeps x the same.", "The y-coordinate flips sign."],
    difficulty: 4,
    topicSlug: "transformations",
  },
  {
    slug: "geo-3d-01",
    question: "A cube has surface area 96. What is its volume?",
    format: "MULTIPLE_CHOICE",
    choices: ["48", "64", "96", "32", "128"],
    answer: "B",
    solution: "Surface area = 6s² = 96, so s² = 16, s = 4. Volume = s³ = 64.",
    hints: ["A cube's surface area is 6 times the side length squared.", "Find the side length first, then cube it."],
    difficulty: 6,
    topicSlug: "three-d-geometry",
  },

  // =========================== NUMBER THEORY ===========================
  {
    slug: "nt-divisibility-01",
    question: "What is the smallest positive integer divisible by both 4 and 6?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "The least common multiple of 4 and 6 is 12.",
    hints: ["List multiples of each number until you find a common one.", "4, 8, 12, ... and 6, 12, ..."],
    difficulty: 2,
    topicSlug: "divisibility",
  },
  {
    slug: "nt-divisibility-02",
    question: "How many two-digit numbers are divisible by 7?",
    format: "MULTIPLE_CHOICE",
    choices: ["13", "12", "14", "11", "15"],
    answer: "A",
    solution: "The two-digit multiples of 7 range from 14 to 98: (98-14)/7 + 1 = 13.",
    hints: ["Find the smallest and largest two-digit multiples of 7.", "Count how many terms are in that list."],
    difficulty: 3,
    topicSlug: "divisibility",
    competitionSlug: "amc8",
  },
  {
    slug: "nt-primes-01",
    question: "What is the sum of the first five prime numbers?",
    format: "SHORT_ANSWER",
    answer: "28",
    solution: "2 + 3 + 5 + 7 + 11 = 28.",
    hints: ["List the first five primes: 2, 3, 5, 7, 11.", "Add them up."],
    difficulty: 2,
    topicSlug: "primes",
  },
  {
    slug: "nt-primes-02",
    question: "How many prime numbers are there between 30 and 50?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "6", "3", "7", "5"],
    answer: "E",
    solution: "The primes between 30 and 50 are 31, 37, 41, 43, and 47 — that's 5.",
    hints: ["Check each number between 30 and 50 for divisibility by small primes.", "Don't forget to check 31 and 47."],
    difficulty: 4,
    topicSlug: "primes",
  },
  {
    slug: "nt-modular-01",
    question: "What is 47 mod 6?",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "47 = 6 × 7 + 5, so the remainder is 5.",
    hints: ["Divide 47 by 6 and find the remainder.", "6 × 7 = 42, and 47 - 42 = 5."],
    difficulty: 4,
    topicSlug: "modular-arithmetic",
  },
  {
    slug: "nt-modular-02",
    question: "What is the remainder when 2¹⁰ is divided by 7?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "2", "4", "3", "5"],
    answer: "B",
    solution: "2¹⁰ = 1024. 1024 = 7 × 146 + 2, so the remainder is 2.",
    hints: ["Compute 2¹⁰ = 1024 first.", "Divide 1024 by 7 and find the remainder."],
    difficulty: 5,
    topicSlug: "modular-arithmetic",
  },
  {
    slug: "nt-diophantine-01",
    question:
      "Find a positive integer solution (x, y) to 3x + 5y = 34 with the smallest possible positive y. Report x.",
    format: "SHORT_ANSWER",
    answer: "8",
    solution: "Try y = 1: 3x = 29, not an integer. Try y = 2: 3x = 24, so x = 8. This is the smallest working y.",
    hints: ["Try small positive values of y and check whether x comes out as a positive integer.", "y = 1 doesn't work — try y = 2."],
    difficulty: 6,
    topicSlug: "diophantine-equations",
  },
  {
    slug: "nt-factorization-01",
    question: "What is the greatest common divisor of 48 and 60?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "48 = 2⁴ × 3, and 60 = 2² × 3 × 5. The GCD is 2² × 3 = 12.",
    hints: ["Write both numbers as products of prime factors.", "Take the lowest power of each shared prime."],
    difficulty: 3,
    topicSlug: "factorization",
  },
  {
    slug: "nt-factorization-02",
    question: "What is the least common multiple of 8 and 12?",
    format: "MULTIPLE_CHOICE",
    choices: ["48", "12", "36", "24", "96"],
    answer: "D",
    solution: "8 = 2³, 12 = 2² × 3. LCM = 2³ × 3 = 24.",
    hints: ["Write both numbers in prime-factored form.", "Take the highest power of each prime that appears."],
    difficulty: 4,
    topicSlug: "factorization",
  },
  {
    slug: "nt-patterns-01",
    question: "What is the next number in the pattern: 2, 6, 12, 20, 30, ...?",
    format: "SHORT_ANSWER",
    answer: "42",
    solution: "The differences are 4, 6, 8, 10, so the next difference is 12: 30 + 12 = 42. (These are n(n+1).)",
    hints: ["Look at the differences between consecutive terms.", "Each term is n(n+1) for n = 1, 2, 3, ..."],
    difficulty: 3,
    topicSlug: "number-patterns",
  },
  {
    slug: "nt-patterns-02",
    question: "What is the 8th triangular number?",
    format: "MULTIPLE_CHOICE",
    choices: ["36", "28", "45", "32", "40"],
    answer: "A",
    solution: "The nth triangular number is n(n+1)/2. For n = 8: 8(9)/2 = 36.",
    hints: ["Triangular numbers follow n(n+1)/2.", "Substitute n = 8."],
    difficulty: 5,
    topicSlug: "number-patterns",
  },
  {
    slug: "nt-integer-01",
    question: "How many positive integers less than 100 are perfect squares?",
    format: "SHORT_ANSWER",
    answer: "9",
    solution: "1², 2², ..., 9² = 81 are all less than 100 (10² = 100 is not less than 100). That's 9 values.",
    hints: ["List perfect squares: 1, 4, 9, 16, ...", "Stop once you reach 100 itself — it doesn't count."],
    difficulty: 4,
    topicSlug: "integer-properties",
  },
  {
    slug: "nt-integer-02",
    question: "What is the units digit of 13¹⁷?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "7", "3", "1", "5"],
    answer: "C",
    solution: "The units digit follows the cycle of 3: 3, 9, 7, 1 (period 4). 17 mod 4 = 1, matching the 1st term: 3.",
    hints: ["Only the units digit of the base (3) matters.", "Find the cycle of units digits for powers of 3."],
    difficulty: 6,
    topicSlug: "integer-properties",
  },
  {
    slug: "nt-divisibility-03",
    question: "How many positive divisors does 360 have?",
    format: "INTEGER",
    answer: "24",
    solution: "360 = 2³ × 3² × 5. Number of divisors = (3+1)(2+1)(1+1) = 24.",
    hints: ["Prime factorize 360 completely.", "Add 1 to each exponent and multiply."],
    difficulty: 7,
    topicSlug: "divisibility",
    competitionSlug: "aime",
  },
  {
    slug: "nt-modular-03",
    question: "Find the remainder when 7¹⁰⁰ is divided by 13.",
    format: "INTEGER",
    answer: "9",
    solution:
      "By Fermat's Little Theorem, 7¹² ≡ 1 (mod 13). Since 100 = 12(8) + 4, 7¹⁰⁰ ≡ 7⁴ (mod 13). 7² = 49 ≡ 10, and 7⁴ = 10² = 100 ≡ 9 (mod 13).",
    hints: ["Fermat's Little Theorem tells you 7¹² ≡ 1 (mod 13).", "Reduce the exponent 100 modulo 12, then compute the smaller power."],
    difficulty: 8,
    topicSlug: "modular-arithmetic",
    competitionSlug: "aime",
  },

  // =========================== COMBINATORICS ===========================
  {
    slug: "combo-counting-01",
    question:
      "A restaurant offers 3 appetizers and 4 main courses. How many different appetizer-and-main combinations are possible?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "By the multiplication principle, 3 × 4 = 12.",
    hints: ["Use the multiplication (counting) principle.", "Multiply the number of choices at each stage."],
    difficulty: 2,
    topicSlug: "counting-principles",
  },
  {
    slug: "combo-counting-02",
    question: "How many 3-digit numbers can be formed using the digits 1-5 without repetition?",
    format: "MULTIPLE_CHOICE",
    choices: ["125", "20", "60", "15", "100"],
    answer: "C",
    solution: "5 choices for the first digit, 4 for the second, 3 for the third: 5 × 4 × 3 = 60.",
    hints: ["Since digits can't repeat, each choice reduces the pool by one.", "5 × 4 × 3."],
    difficulty: 3,
    topicSlug: "counting-principles",
    competitionSlug: "amc8",
  },
  {
    slug: "combo-perm-01",
    question: "In how many ways can 5 people be arranged in a row?",
    format: "SHORT_ANSWER",
    answer: "120",
    solution: "5! = 5 × 4 × 3 × 2 × 1 = 120.",
    hints: ["This is a permutation of all 5 people.", "Compute 5 factorial."],
    difficulty: 4,
    topicSlug: "permutations",
  },
  {
    slug: "combo-perm-02",
    question: "In how many ways can the letters of the word MATH be arranged?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "16", "20", "8", "24"],
    answer: "E",
    solution: "All 4 letters are distinct, so there are 4! = 24 arrangements.",
    hints: ["Check whether any letters repeat (they don't here).", "Compute 4!."],
    difficulty: 5,
    topicSlug: "permutations",
  },
  {
    slug: "combo-comb-01",
    question: "How many ways can you choose 3 books from a shelf of 8 different books?",
    format: "SHORT_ANSWER",
    answer: "56",
    solution: "C(8,3) = 8! / (3!5!) = 56.",
    hints: ["Order doesn't matter here, so use combinations, not permutations.", "C(8,3) = (8×7×6)/(3×2×1)."],
    difficulty: 4,
    topicSlug: "combinations",
  },
  {
    slug: "combo-comb-02",
    question: "A committee of 4 is chosen from 10 people. How many different committees are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["5040", "40", "720", "120", "210"],
    answer: "E",
    solution: "C(10,4) = 10! / (4!6!) = 210.",
    hints: ["Committees have no internal order, so use combinations.", "C(10,4) = (10×9×8×7)/(4×3×2×1)."],
    difficulty: 5,
    topicSlug: "combinations",
    competitionSlug: "amc10",
  },
  {
    slug: "combo-casework-01",
    question: "How many positive integers less than 50 are divisible by 3 or 5?",
    format: "SHORT_ANSWER",
    answer: "22",
    solution:
      "Divisible by 3: 16. Divisible by 5: 9. Divisible by both (15): 3. By inclusion-exclusion: 16 + 9 - 3 = 22.",
    hints: ["Count multiples of 3, then multiples of 5, separately.", "Subtract the overlap (multiples of 15) to avoid double-counting."],
    difficulty: 5,
    topicSlug: "casework",
  },
  {
    slug: "combo-casework-02",
    question: "How many ways can you make exactly 30 cents using only dimes and nickels?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "5", "6", "2"],
    answer: "B",
    solution:
      "10d + 5n = 30. Solutions: (d,n) = (0,6), (1,4), (2,2), (3,0) — that's 4 ways.",
    hints: ["Set up 10d + 5n = 30 and try each value of d from 0 up.", "d can be 0, 1, 2, or 3."],
    difficulty: 6,
    topicSlug: "casework",
  },
  {
    slug: "combo-pigeonhole-01",
    question:
      "What is the minimum number of people needed to guarantee that at least 2 of them share the same birth month?",
    format: "SHORT_ANSWER",
    answer: "13",
    solution: "There are 12 months. By the pigeonhole principle, 12 + 1 = 13 people guarantee a shared month.",
    hints: ["Think of the 12 months as 'boxes'.", "The pigeonhole principle says you need one more than the number of boxes."],
    difficulty: 5,
    topicSlug: "pigeonhole",
  },
  {
    slug: "combo-pigeonhole-02",
    question:
      "A drawer has 10 red socks and 10 blue socks, mixed together with the light off. What is the minimum number of socks you must pull out to guarantee a matching pair?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "11", "4", "10", "3"],
    answer: "E",
    solution:
      "In the worst case, the first two socks are different colors (one red, one blue). The third sock must match one of them, so 3 guarantees a pair.",
    hints: ["Consider the worst possible order you could pull socks in.", "With only 2 colors, how many socks force a repeat?"],
    difficulty: 6,
    topicSlug: "pigeonhole",
  },
  {
    slug: "combo-inclexcl-01",
    question:
      "In a class of 30 students, 18 study Spanish, 15 study French, and 8 study both. How many study neither language?",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "Studying at least one: 18 + 15 - 8 = 25. Studying neither: 30 - 25 = 5.",
    hints: ["Use inclusion-exclusion to find how many study at least one language.", "Subtract that from the total class size."],
    difficulty: 6,
    topicSlug: "inclusion-exclusion",
  },
  {
    slug: "combo-recursion-01",
    question:
      "How many ways can you climb a staircase of 6 steps if you can take 1 or 2 steps at a time?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "21", "8", "13", "15"],
    answer: "D",
    solution:
      "This follows the Fibonacci-like recursion f(n) = f(n-1) + f(n-2), with f(1)=1, f(2)=2. f(3)=3, f(4)=5, f(5)=8, f(6)=13.",
    hints: ["The number of ways to reach step n depends on step n-1 and step n-2.", "Build up the sequence: f(1)=1, f(2)=2, f(3)=3, ..."],
    difficulty: 7,
    topicSlug: "recursion-in-counting",
    competitionSlug: "hmmt",
  },
  {
    slug: "combo-graph-01",
    question: "A graph has 6 vertices, and every vertex has degree 3. How many edges does it have?",
    format: "INTEGER",
    answer: "9",
    solution: "The sum of all degrees is 6 × 3 = 18. Since each edge contributes 2 to the degree sum, edges = 18/2 = 9.",
    hints: ["The handshake lemma: sum of degrees = 2 × (number of edges).", "Sum the degrees first, then divide by 2."],
    difficulty: 7,
    topicSlug: "graph-theory",
    competitionSlug: "aime",
  },
  {
    slug: "combo-comb-03",
    question: "How many distinct ways can the letters of the word BANANA be arranged?",
    format: "SHORT_ANSWER",
    answer: "60",
    solution: "BANANA has 6 letters: B(1), A(3), N(2). Arrangements = 6! / (3! × 2!) = 720 / 12 = 60.",
    hints: ["This word has repeated letters — divide out the repeats.", "6! / (3! for the A's × 2! for the N's)."],
    difficulty: 6,
    topicSlug: "permutations",
  },
  {
    slug: "combo-polygon-01",
    question: "How many diagonals does a convex decagon (10-gon) have?",
    format: "MULTIPLE_CHOICE",
    choices: ["45", "40", "35", "30", "25"],
    answer: "C",
    solution: "Diagonals = n(n-3)/2 = 10(7)/2 = 35.",
    hints: ["Use the formula n(n-3)/2 for diagonals of a convex n-gon.", "Substitute n = 10."],
    difficulty: 6,
    topicSlug: "combinations",
    competitionSlug: "pumac",
  },

  // ============================= PROBABILITY =============================
  {
    slug: "prob-basic-01",
    question:
      "A standard six-sided die is rolled. What is the probability of rolling a number greater than 4? Express your answer as a fraction.",
    format: "SHORT_ANSWER",
    answer: "1/3",
    solution: "Favorable outcomes {5, 6} out of 6 total: 2/6 = 1/3.",
    hints: ["List the outcomes greater than 4.", "Reduce the fraction to lowest terms."],
    difficulty: 2,
    topicSlug: "basic-probability",
  },
  {
    slug: "prob-basic-02",
    question: "A bag has 4 red and 6 blue marbles. What is the probability of drawing a red marble?",
    format: "MULTIPLE_CHOICE",
    choices: ["3/5", "2/5", "1/5", "4/5", "1/2"],
    answer: "B",
    solution: "P(red) = 4/10 = 2/5.",
    hints: ["Divide the number of red marbles by the total.", "Reduce 4/10 to lowest terms."],
    difficulty: 3,
    topicSlug: "basic-probability",
    competitionSlug: "mathcounts",
  },
  {
    slug: "prob-counting-01",
    question:
      "Two fair coins are flipped. What is the probability that both show heads? Express your answer as a fraction.",
    format: "SHORT_ANSWER",
    answer: "1/4",
    solution: "P(HH) = 1/2 × 1/2 = 1/4.",
    hints: ["The two flips are independent — multiply their probabilities.", "Each coin has a 1/2 chance of heads."],
    difficulty: 4,
    topicSlug: "counting-probability",
  },
  {
    slug: "prob-counting-02",
    question: "A fair die is rolled twice. What is the probability the sum is 7?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/12", "1/9", "1/6", "5/36", "1/3"],
    answer: "C",
    solution:
      "Favorable pairs: (1,6),(2,5),(3,4),(4,3),(5,2),(6,1) — 6 out of 36 total outcomes: 6/36 = 1/6.",
    hints: ["List all pairs of rolls that sum to 7.", "There are 36 total equally likely outcomes for two dice."],
    difficulty: 5,
    topicSlug: "counting-probability",
  },
  {
    slug: "prob-conditional-01",
    question:
      "A box has 3 red and 2 blue balls. Two balls are drawn without replacement. What is the probability both are red? Express your answer as a fraction.",
    format: "SHORT_ANSWER",
    answer: "3/10",
    solution: "P = (3/5) × (2/4) = 6/20 = 3/10.",
    hints: ["Multiply the probability of the first draw by the probability of the second, given the first happened.", "After removing one red ball, only 4 balls remain, 2 of them red."],
    difficulty: 6,
    topicSlug: "conditional-probability",
  },
  {
    slug: "prob-conditional-02",
    question:
      "In a group, 60% of people like math, and 40% like both math and science. Of those who like math, what percent also like science?",
    format: "MULTIPLE_CHOICE",
    choices: ["66.7%", "40%", "60%", "24%", "50%"],
    answer: "A",
    solution: "P(science | math) = P(both) / P(math) = 0.40 / 0.60 ≈ 66.7%.",
    hints: ["Use the conditional probability formula P(A|B) = P(A and B) / P(B).", "Divide 0.40 by 0.60."],
    difficulty: 7,
    topicSlug: "conditional-probability",
  },
  {
    slug: "prob-expected-01",
    question:
      "A game pays $10 for rolling a 6 on a fair die and costs $1 to play regardless of outcome. What is the expected net profit per play, rounded to the nearest cent?",
    format: "SHORT_ANSWER",
    answer: "0.67",
    solution: "Expected payout = 10 × (1/6) ≈ 1.667. Net = 1.667 - 1 ≈ 0.67.",
    hints: ["Find the expected payout first: 10 × P(rolling a 6).", "Subtract the $1 cost to play."],
    difficulty: 6,
    topicSlug: "expected-value",
  },
  {
    slug: "prob-expected-02",
    question: "A fair coin is flipped 4 times. What is the expected number of heads?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "2", "3", "2.5", "1.5"],
    answer: "B",
    solution: "Expected value = n × p = 4 × 0.5 = 2.",
    hints: ["For repeated independent trials, expected value = n × p.", "Here n = 4 and p = 0.5."],
    difficulty: 7,
    topicSlug: "expected-value",
  },
  {
    slug: "prob-strategy-01",
    question:
      "A bag has 5 red and 3 green candies. One is drawn at random. What is the probability it is NOT green? Express your answer as a fraction.",
    format: "SHORT_ANSWER",
    answer: "5/8",
    solution: "P(not green) = P(red) = 5/8.",
    hints: ["'Not green' means the candy is red.", "Divide red candies by total candies."],
    difficulty: 5,
    topicSlug: "games-and-strategies",
  },
  {
    slug: "prob-counting-03",
    question:
      "A fair 6-sided die is rolled 3 times. What is the probability that at least one roll is a 6? Express your answer as a fraction in lowest terms.",
    format: "SHORT_ANSWER",
    answer: "91/216",
    solution:
      "P(no 6 in 3 rolls) = (5/6)³ = 125/216. P(at least one 6) = 1 - 125/216 = 91/216.",
    hints: ["It's easier to find the probability of the complement: no 6 at all.", "Subtract that probability from 1."],
    difficulty: 8,
    topicSlug: "counting-probability",
    competitionSlug: "amc12",
  },

  // ================================ LOGIC ================================
  {
    slug: "logic-deduction-01",
    question: "All squares are rectangles. A certain shape is not a rectangle. Can it be a square?",
    format: "SHORT_ANSWER",
    answer: "No",
    solution: "Since every square is a rectangle, anything that is not a rectangle cannot be a square.",
    hints: ["Think about what 'all squares are rectangles' implies in reverse.", "If it's not a rectangle, it can't belong to the smaller category either."],
    difficulty: 1,
    topicSlug: "deduction",
  },
  {
    slug: "logic-puzzle-01",
    question: "Amy is taller than Ben. Ben is taller than Cara. Who is the shortest?",
    format: "MULTIPLE_CHOICE",
    choices: ["Ben", "Cara", "Amy", "Cannot be determined"],
    answer: "B",
    solution: "Amy > Ben > Cara in height, so Cara is the shortest.",
    hints: ["Order all three people from tallest to shortest.", "Amy is tallest, so who's left at the bottom?"],
    difficulty: 2,
    topicSlug: "logical-puzzles",
  },
  {
    slug: "logic-patterns-01",
    question: "What is the next letter in the pattern: A, C, E, G, ...?",
    format: "SHORT_ANSWER",
    answer: "I",
    solution: "The pattern skips one letter each time: A, (B), C, (D), E, (F), G, (H), I.",
    hints: ["Look at the letters being skipped between each term.", "Every other letter of the alphabet is used."],
    difficulty: 3,
    topicSlug: "patterns",
  },
  {
    slug: "logic-puzzle-02",
    question:
      "Alex, Blake, and Casey each play a different sport: soccer, tennis, or basketball. Alex doesn't play soccer or basketball. Blake doesn't play tennis or basketball. What does Casey play?",
    format: "MULTIPLE_CHOICE",
    choices: ["Soccer", "Tennis", "Basketball", "Cannot be determined"],
    answer: "C",
    solution:
      "Alex must play tennis (the only sport not excluded). Blake can't play tennis (taken) or basketball, so Blake plays soccer. That leaves basketball for Casey.",
    hints: ["Start with the person who has the most restrictions — Alex.", "Once Alex and Blake's sports are fixed, Casey gets what's left."],
    difficulty: 4,
    topicSlug: "logical-puzzles",
  },
  {
    slug: "logic-invariants-01",
    question:
      "A number is repeatedly replaced by the sum of its digits until a single digit remains. Starting from 999,999,999 (nine 9's), what single digit does it reach?",
    format: "SHORT_ANSWER",
    answer: "9",
    solution:
      "The digit sum of nine 9's is 81, and 8+1=9. Since the original number is divisible by 9 (and nonzero), its digital root is always 9.",
    hints: ["A number's digital root relates to its remainder mod 9.", "A nonzero multiple of 9 always has digital root 9."],
    difficulty: 6,
    topicSlug: "invariants",
  },
  {
    slug: "logic-patterns-02",
    question: "How many squares of any size are in a 4×4 grid of unit squares?",
    format: "SHORT_ANSWER",
    answer: "30",
    solution: "Sum of squares of side lengths: 4² + 3² + 2² + 1² = 16 + 9 + 4 + 1 = 30.",
    hints: ["Count 1×1 squares, then 2×2, then 3×3, then 4×4 separately.", "There are k² squares of size k in a 4×4 grid, for k = 1, 2, 3, 4."],
    difficulty: 4,
    topicSlug: "patterns",
  },
  {
    slug: "logic-strategy-01",
    question:
      "Two players alternately remove 1, 2, or 3 stones from a pile of 17. Whoever removes the last stone wins. If both play optimally, who wins?",
    format: "MULTIPLE_CHOICE",
    choices: ["First player", "Second player", "Depends on second player's moves", "Neither can guarantee a win"],
    answer: "A",
    solution:
      "Losing positions are multiples of 4 (0, 4, 8, 12, 16). Since 17 is not a multiple of 4, the first player can remove 1 stone to leave 16 — a losing position for the opponent.",
    hints: ["Think about which pile sizes are 'safe' to hand to your opponent.", "Multiples of 4 are losing positions for whoever faces them."],
    difficulty: 7,
    topicSlug: "strategy",
  },
  {
    slug: "logic-deduction-02",
    question:
      "Five houses in a row are numbered 1 to 5, left to right. The red house is immediately to the left of the blue house. The blue house is number 4. The green house is number 1. What number is the red house?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "4", "5", "3", "1"],
    answer: "D",
    solution: "The blue house is 4, and red is immediately to its left, so red is house 3.",
    hints: ["'Immediately to the left' means one number lower.", "The blue house's number is given directly."],
    difficulty: 3,
    topicSlug: "deduction",
  },

  // ======================== ADVANCED / OLYMPIAD ========================
  {
    slug: "adv-functional-01",
    question:
      "A function satisfies f(x + y) = f(x) + f(y) for all real x, y, and f(1) = 5. What is f(7)?",
    format: "SHORT_ANSWER",
    answer: "35",
    solution: "This is Cauchy's functional equation; for integers, f(n) = n·f(1) = 5n. So f(7) = 35.",
    hints: ["Try building up f(2), f(3), ... from f(1) using the given rule.", "f(n) = n × f(1) for positive integers n."],
    difficulty: 8,
    topicSlug: "functional-equations",
    competitionSlug: "usamts",
  },
  {
    slug: "adv-numtheory-01",
    question: "Find the smallest positive integer n such that n! is divisible by 1000.",
    format: "SHORT_ANSWER",
    answer: "15",
    solution:
      "1000 = 2³ × 5³, and factorials always have far more factors of 2 than 5, so we need the number of factors of 5 in n! to reach 3. The count of 5s in n! is ⌊n/5⌋ + ⌊n/25⌋ + ... For n=15: ⌊15/5⌋=3. For n=14: ⌊14/5⌋=2 (not enough). So the smallest n is 15.",
    hints: ["Focus on counting factors of 5 in n! — factors of 2 are never the bottleneck.", "Use Legendre's formula: ⌊n/5⌋ + ⌊n/25⌋ + ..."],
    difficulty: 9,
    topicSlug: "advanced-number-theory",
  },
  {
    slug: "adv-combo-01",
    question:
      "How many ways can 8 people be seated around a circular table, where rotations are considered the same arrangement but reflections are different?",
    format: "INTEGER",
    answer: "5040",
    solution: "Circular permutations of n distinct objects = (n-1)!. For n = 8: 7! = 5040.",
    hints: ["Fix one person's seat to remove the rotational symmetry.", "Arrange the remaining 7 people in the remaining seats."],
    difficulty: 9,
    topicSlug: "advanced-combinatorics",
    competitionSlug: "aime",
  },
  {
    slug: "adv-geometry-01",
    question:
      "In right triangle ABC with the right angle at A, AB = 9 and AC = 12. What is the radius of the inscribed circle?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution:
      "BC = √(9² + 12²) = √225 = 15. For a right triangle, the inradius r = (leg₁ + leg₂ - hypotenuse) / 2 = (9 + 12 - 15) / 2 = 3.",
    hints: ["Find the hypotenuse first using the Pythagorean theorem.", "A right triangle's inradius has the shortcut formula r = (a + b - c) / 2."],
    difficulty: 8,
    topicSlug: "advanced-geometry",
    competitionSlug: "usamts",
  },
  {
    slug: "adv-inequality-01",
    question: "For positive reals a and b with a + b = 10, what is the maximum possible value of ab?",
    format: "SHORT_ANSWER",
    answer: "25",
    solution: "By AM-GM, ab is maximized when a = b = 5, giving ab = 25.",
    hints: ["Try the AM-GM inequality, or just test what happens as a and b get close together.", "The product of two numbers with fixed sum is maximized when they're equal."],
    difficulty: 8,
    topicSlug: "inequalities-olympiad",
    competitionSlug: "usamts",
  },
  {
    slug: "adv-proof-01",
    question: "Which proof technique is most naturally used to show that there are infinitely many primes?",
    format: "MULTIPLE_CHOICE",
    choices: ["Direct substitution", "Exhaustive case check", "Proof by contradiction", "Proof by induction only"],
    answer: "C",
    solution:
      "Euclid's classic argument assumes finitely many primes exist, constructs a number not divisible by any of them, and derives a contradiction.",
    hints: ["Think of Euclid's classic argument.", "It starts by assuming the opposite of what we want to prove."],
    difficulty: 7,
    topicSlug: "proof-techniques",
  },
  {
    slug: "adv-numtheory-02",
    question:
      "Find the number of ordered pairs of positive integers (x, y) satisfying 1/x + 1/y = 1/12.",
    format: "INTEGER",
    answer: "15",
    solution:
      "Rearranging gives (x-12)(y-12) = 144. Since 144 = 2⁴ × 3² has (4+1)(2+1) = 15 positive divisors, there are 15 valid ordered pairs.",
    hints: ["Multiply both sides by 12xy and rearrange to factor the equation.", "You should arrive at (x - 12)(y - 12) = 144 — count its positive divisor pairs."],
    difficulty: 10,
    topicSlug: "advanced-number-theory",
    competitionSlug: "aime",
  },
  {
    slug: "adv-combo-02",
    question: "How many distinct ways can the letters of the word OLYMPIAD be arranged?",
    format: "SHORT_ANSWER",
    answer: "40320",
    solution: "All 8 letters (O, L, Y, M, P, I, A, D) are distinct, so there are 8! = 40320 arrangements.",
    hints: ["Check whether any letters repeat (they don't).", "Compute 8!."],
    difficulty: 9,
    topicSlug: "advanced-combinatorics",
  },
  {
    slug: "adv-geometry-02",
    question: "A regular hexagon has side length 6. What is its area?",
    format: "SHORT_ANSWER",
    answer: "54√3",
    solution: "A regular hexagon's area is (3√3/2)s². For s = 6: (3√3/2)(36) = 54√3.",
    hints: ["A regular hexagon can be split into 6 equilateral triangles.", "The area formula is (3√3/2)s²."],
    difficulty: 9,
    topicSlug: "advanced-geometry",
  },
  {
    slug: "adv-inequality-02",
    question: "By AM-GM, what is the minimum value of x + 4/x for x > 0?",
    format: "SHORT_ANSWER",
    answer: "4",
    solution: "By AM-GM, x + 4/x ≥ 2√(x · 4/x) = 2√4 = 4, with equality at x = 2.",
    hints: ["Apply AM-GM to the two terms x and 4/x.", "The minimum occurs when the two terms are equal."],
    difficulty: 9,
    topicSlug: "inequalities-olympiad",
  },
];
