import type { ProblemSeed } from "./problems";

/**
 * Hand-written problems styled after MATHCOUNTS (a US middle-school math
 * competition run by the MATHCOUNTS Foundation).
 *
 * Real MATHCOUNTS rounds: Sprint (30 questions, 40 minutes, no calculator,
 * short-answer, difficulty rising through the round), Target (8 questions
 * in 4 pairs, 6 minutes per pair, calculator allowed, harder/multi-step),
 * and Team (10 questions, 20 minutes, calculator allowed, collaborative,
 * meatier setups). All rounds use short/fill-in numeric answers, never
 * multiple choice, and answers are given in simplest form (integers,
 * reduced fractions, or terminating decimals).
 *
 * Problems 1-20 below are written at Sprint-easy-to-mid difficulty,
 * problems 21-30 at Sprint-hard/Target difficulty, and problems 31-36 at
 * Team-round difficulty with meatier multi-step setups. Every problem is
 * original NumberSmith content, written and verified for this platform;
 * none are transcribed from any real MATHCOUNTS contest.
 *
 * Seeded as practice (isPlacement: false), same as the other
 * competition-tagged problem sets.
 */
export const MATHCOUNTS_PROBLEMS: ProblemSeed[] = [
  {
    slug: "mathcounts-01",
    question:
      "A recipe calls for 2/3 cup of sugar. If Maria wants to make 3/4 of the recipe, how many cups of sugar does she need?",
    format: "SHORT_ANSWER",
    answer: "1/2",
    solution: "Multiply the amounts: (2/3) × (3/4) = 6/12 = 1/2 cup.",
    hints: [
      "Making a fraction of a recipe means multiplying each ingredient amount by that fraction.",
      "Multiply 2/3 by 3/4 and simplify.",
    ],
    difficulty: 2,
    topicSlug: "fractions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-02",
    question: "The ratio of red marbles to blue marbles in a jar is 4:7. If there are 28 blue marbles, how many red marbles are there?",
    format: "SHORT_ANSWER",
    answer: "16",
    solution: "Since 28 blue marbles correspond to 7 parts, each part is 28 / 7 = 4 marbles. Red marbles = 4 parts = 4 × 4 = 16.",
    hints: [
      "Find how many marbles one ratio 'part' represents using the blue count.",
      "Multiply that per-part value by the red side of the ratio.",
    ],
    difficulty: 2,
    topicSlug: "ratios-proportions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-03",
    question: "What is 15% of 60?",
    format: "SHORT_ANSWER",
    answer: "9",
    solution: "15% of 60 = 0.15 × 60 = 9.",
    hints: ["Convert 15% to the decimal 0.15.", "Multiply 0.15 by 60."],
    difficulty: 2,
    topicSlug: "percentages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-04",
    question: "A car travels 150 miles in 3 hours at a constant speed. At this same rate, how many miles will it travel in 5 hours?",
    format: "SHORT_ANSWER",
    answer: "250",
    solution: "The rate is 150 / 3 = 50 miles per hour. In 5 hours it travels 50 × 5 = 250 miles.",
    hints: ["Find the speed in miles per hour first.", "Multiply the speed by the new number of hours."],
    difficulty: 2,
    topicSlug: "rates",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-05",
    question: "The average of four numbers is 12. If three of the numbers are 8, 10, and 14, what is the fourth number?",
    format: "SHORT_ANSWER",
    answer: "16",
    solution: "The total sum is 4 × 12 = 48. The three known numbers sum to 8 + 10 + 14 = 32. The fourth number is 48 - 32 = 16.",
    hints: ["Use the average to find the total sum of all four numbers.", "Subtract the sum of the three known numbers from that total."],
    difficulty: 2,
    topicSlug: "averages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-06",
    question: "What is the smallest positive integer that is divisible by both 6 and 8?",
    format: "SHORT_ANSWER",
    answer: "24",
    solution: "6 = 2 × 3 and 8 = 2^3. The least common multiple is 2^3 × 3 = 24.",
    hints: ["Find the least common multiple of 6 and 8.", "Write each number's prime factorization first."],
    difficulty: 2,
    topicSlug: "number-properties",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-07",
    question: "Solve for x: 3x + 7 = 22.",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "Subtract 7 from both sides: 3x = 15. Divide by 3: x = 5.",
    hints: ["Isolate the term with x by subtracting 7 from both sides.", "Then divide both sides by 3."],
    difficulty: 3,
    topicSlug: "linear-equations",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-08",
    question:
      "Two angles are supplementary. One angle measures 50 degrees more than the other. What is the measure, in degrees, of the smaller angle?",
    format: "SHORT_ANSWER",
    answer: "65",
    solution: "Let the smaller angle be x, so the larger is x + 50. Since they are supplementary, x + (x + 50) = 180, giving 2x = 130, so x = 65.",
    hints: [
      "Supplementary angles sum to 180 degrees.",
      "Let the smaller angle be x and write the larger one in terms of x, then solve.",
    ],
    difficulty: 3,
    topicSlug: "angles",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-09",
    question: "In a triangle, the three angles measure 2x, 3x, and 4x degrees. What is the value of x?",
    format: "SHORT_ANSWER",
    answer: "20",
    solution: "The angles of a triangle sum to 180 degrees: 2x + 3x + 4x = 180, so 9x = 180, giving x = 20.",
    hints: ["The three angles of any triangle sum to 180 degrees.", "Add the three expressions and set the sum equal to 180."],
    difficulty: 3,
    topicSlug: "triangles",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-10",
    question:
      "A rectangle has a perimeter of 60 cm, and its length is 6 cm more than its width. What is the area of the rectangle, in square centimeters?",
    format: "SHORT_ANSWER",
    answer: "216",
    solution:
      "Let the width be w, so the length is w + 6. The perimeter is 2(w + (w + 6)) = 60, so 2w + 6 = 30, giving w = 12 and length = 18. The area is 12 × 18 = 216.",
    hints: [
      "Let the width be w and write the length in terms of w.",
      "Use the perimeter formula to solve for w, then compute the area.",
    ],
    difficulty: 3,
    topicSlug: "quadrilaterals",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-11",
    question: "A circle has a radius of 7. What is its circumference, in terms of π?",
    format: "SHORT_ANSWER",
    answer: "14π",
    solution: "Circumference = 2πr = 2π(7) = 14π.",
    hints: ["Use the circumference formula C = 2πr.", "Substitute r = 7."],
    difficulty: 3,
    topicSlug: "circles",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-12",
    question: "What is the sum of the interior angles of a hexagon, in degrees?",
    format: "SHORT_ANSWER",
    answer: "720",
    solution: "For an n-sided polygon, the interior angle sum is (n - 2) × 180. For a hexagon, n = 6, so the sum is (6 - 2) × 180 = 720.",
    hints: ["Use the interior angle sum formula (n - 2) × 180.", "A hexagon has 6 sides."],
    difficulty: 3,
    topicSlug: "polygons",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-13",
    question: "Simplify: 2^5 × 2^3 ÷ 2^4.",
    format: "SHORT_ANSWER",
    answer: "16",
    solution: "Combine exponents: 2^5 × 2^3 ÷ 2^4 = 2^(5+3-4) = 2^4 = 16.",
    hints: ["When multiplying or dividing powers of the same base, add or subtract the exponents.", "Simplify the exponent first, then evaluate."],
    difficulty: 3,
    topicSlug: "exponents-radicals",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-14",
    question: "What is the 10th term of the arithmetic sequence 5, 9, 13, 17, …?",
    format: "SHORT_ANSWER",
    answer: "41",
    solution: "The common difference is 4. The 10th term is 5 + 9 × 4 = 5 + 36 = 41.",
    hints: ["Find the common difference between consecutive terms.", "The nth term is the first term plus (n - 1) times the common difference."],
    difficulty: 3,
    topicSlug: "sequences",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-15",
    question: "What is the smallest positive integer greater than 100 that is divisible by 9?",
    format: "SHORT_ANSWER",
    answer: "108",
    solution: "Dividing 100 by 9 gives approximately 11.1, so the next multiple of 9 is 9 × 12 = 108.",
    hints: ["Divide 100 by 9 to see which multiple of 9 comes just after it.", "Round up to the next whole multiple."],
    difficulty: 3,
    topicSlug: "divisibility",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-16",
    question: "How many prime numbers are there between 20 and 40?",
    format: "SHORT_ANSWER",
    answer: "4",
    solution: "The primes between 20 and 40 are 23, 29, 31, and 37, for a total of 4.",
    hints: ["List every integer from 21 to 39 and cross out the composite ones.", "Check each remaining candidate for divisors."],
    difficulty: 3,
    topicSlug: "primes",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-17",
    question:
      "A pizza shop offers 3 crust types, 4 cheese types, and 2 sauce types. How many different pizzas can be made by choosing one of each?",
    format: "SHORT_ANSWER",
    answer: "24",
    solution: "By the counting principle, multiply the number of choices: 3 × 4 × 2 = 24.",
    hints: ["Use the multiplication counting principle.", "Multiply the number of options for each independent choice together."],
    difficulty: 3,
    topicSlug: "counting-principles",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-18",
    question: "In how many ways can 5 different books be arranged in a row on a shelf?",
    format: "SHORT_ANSWER",
    answer: "120",
    solution: "The number of arrangements of 5 distinct items is 5! = 5 × 4 × 3 × 2 × 1 = 120.",
    hints: ["This is a permutation of all 5 books.", "Compute 5 factorial."],
    difficulty: 3,
    topicSlug: "permutations",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-19",
    question: "A committee of 3 people is to be chosen from a group of 8 people. How many different committees are possible?",
    format: "SHORT_ANSWER",
    answer: "56",
    solution: "Since order doesn't matter, use combinations: C(8,3) = 8! / (3! × 5!) = 56.",
    hints: ["The order the committee members are chosen doesn't matter, so use combinations, not permutations.", "Compute C(8,3)."],
    difficulty: 4,
    topicSlug: "combinations",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-20",
    question:
      "A bag contains 4 red and 6 blue marbles. If one marble is drawn at random, what is the probability that it is red? Express your answer as a fraction in lowest terms.",
    format: "SHORT_ANSWER",
    answer: "2/5",
    solution: "There are 10 marbles total, 4 of which are red, so the probability is 4/10 = 2/5.",
    hints: ["Probability is favorable outcomes over total outcomes.", "Reduce the resulting fraction to lowest terms."],
    difficulty: 3,
    topicSlug: "basic-probability",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-21",
    question: "If x + y = 15 and x - y = 3, what is the value of xy?",
    format: "SHORT_ANSWER",
    answer: "54",
    solution: "Adding the equations: 2x = 18, so x = 9. Then y = 15 - 9 = 6. Thus xy = 9 × 6 = 54.",
    hints: ["Add the two equations to eliminate y.", "Once you have x, substitute back to find y."],
    difficulty: 4,
    topicSlug: "systems-of-equations",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-22",
    question: "How many positive integers x satisfy 3x - 5 < 16?",
    format: "SHORT_ANSWER",
    answer: "6",
    solution: "Solving: 3x < 21, so x < 7. The positive integers satisfying this are 1, 2, 3, 4, 5, and 6, a total of 6 values.",
    hints: ["Solve the inequality for x first.", "Count only the positive integers strictly less than that bound."],
    difficulty: 4,
    topicSlug: "inequalities",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-23",
    question:
      "The expression x^2 - 5x - 24 factors as (x - a)(x + b), where a and b are positive integers with a > b. What is the value of a - b?",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "We need two numbers with product -24 and sum -5: those are -8 and 3. So x^2 - 5x - 24 = (x - 8)(x + 3), giving a = 8 and b = 3. Thus a - b = 5.",
    hints: ["Find two numbers that multiply to -24 and add to -5.", "Match those numbers to a and b in (x - a)(x + b)."],
    difficulty: 4,
    topicSlug: "factoring",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-24",
    question: "If f(x) = 2x^2 - 3x + 1, what is the value of f(4)?",
    format: "SHORT_ANSWER",
    answer: "21",
    solution: "f(4) = 2(4)^2 - 3(4) + 1 = 2(16) - 12 + 1 = 32 - 12 + 1 = 21.",
    hints: ["Substitute x = 4 into the expression for f(x).", "Follow order of operations: square before multiplying."],
    difficulty: 4,
    topicSlug: "functions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-25",
    question: "The equation x^2 - 9x + 20 = 0 has two roots. What is the sum of the squares of the roots?",
    format: "SHORT_ANSWER",
    answer: "41",
    solution:
      "By Vieta's formulas, the roots sum to 9 and multiply to 20. The sum of squares equals (sum)^2 - 2(product) = 9^2 - 2(20) = 81 - 40 = 41.",
    hints: ["Use Vieta's formulas to find the sum and product of the roots without solving for them individually.", "Sum of squares equals (sum)^2 minus twice the product."],
    difficulty: 5,
    topicSlug: "quadratics",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-26",
    question:
      "Triangle ABC is similar to triangle DEF, with vertices corresponding in order. If AB = 6, DE = 9, and the area of triangle ABC is 24, what is the area of triangle DEF?",
    format: "SHORT_ANSWER",
    answer: "54",
    solution:
      "The similarity ratio is DE/AB = 9/6 = 3/2. The area ratio is the square of the similarity ratio: (3/2)^2 = 9/4. The area of DEF is 24 × 9/4 = 54.",
    hints: [
      "Find the ratio of corresponding side lengths first.",
      "The ratio of areas of similar figures is the square of the ratio of corresponding sides.",
    ],
    difficulty: 5,
    topicSlug: "similarity-congruence",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-27",
    question: "What is the distance between the points (3, -2) and (7, 1)?",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "Using the distance formula: √((7-3)^2 + (1-(-2))^2) = √(4^2 + 3^2) = √(16 + 9) = √25 = 5.",
    hints: ["Use the distance formula, which comes from the Pythagorean theorem.", "Find the horizontal and vertical differences between the points first."],
    difficulty: 5,
    topicSlug: "coordinate-geometry",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-28",
    question: "A cylinder has radius 3 and height 10. What is its volume, in terms of π?",
    format: "SHORT_ANSWER",
    answer: "90π",
    solution: "Volume = π r^2 h = π(3^2)(10) = π(9)(10) = 90π.",
    hints: ["Use the cylinder volume formula V = π r^2 h.", "Substitute the given radius and height."],
    difficulty: 5,
    topicSlug: "area-volume",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-29",
    question: "What is the remainder when 2^10 is divided by 7?",
    format: "SHORT_ANSWER",
    answer: "2",
    solution: "2^10 = 1024. Since 7 × 146 = 1022, the remainder is 1024 - 1022 = 2.",
    hints: ["Compute 2^10 directly, or track powers of 2 modulo 7 to find a repeating pattern.", "Divide the result by 7 and find what's left over."],
    difficulty: 5,
    topicSlug: "modular-arithmetic",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-30",
    question:
      "A fair six-sided die is rolled once. If you win x dollars for rolling a number x, what is the expected value of your winnings, in dollars? Express your answer as a fraction.",
    format: "SHORT_ANSWER",
    answer: "7/2",
    solution: "The expected value is the average of the outcomes: (1+2+3+4+5+6)/6 = 21/6 = 7/2.",
    hints: ["Expected value is the sum of each outcome times its probability.", "Since each face is equally likely, this is just the average of 1 through 6."],
    difficulty: 5,
    topicSlug: "expected-value",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-31",
    question: "How many three-digit numbers have digits that are strictly increasing from left to right (each digit greater than the one before it)?",
    format: "SHORT_ANSWER",
    answer: "84",
    solution:
      "A strictly increasing three-digit number can't use the digit 0 (it could never be the largest digit needed to place it last, and it can't lead). So choose any 3 distinct digits from 1-9; there is exactly one way to arrange them in increasing order. This gives C(9,3) = 84.",
    hints: [
      "Since the digits must strictly increase, once you pick any 3 distinct digits there's only one valid order for them.",
      "The digit 0 can never appear in such a number — think about why, then count using combinations of 1-9.",
    ],
    difficulty: 6,
    topicSlug: "casework",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-32",
    question: "What is the minimum number of people needed in a room to guarantee that at least 3 of them were born in the same month?",
    format: "SHORT_ANSWER",
    answer: "25",
    solution:
      "There are 12 months. In the worst case, 2 people could be born in each month before a third match is forced: 2 × 12 = 24 people. The 25th person must share a month with at least 2 others, guaranteeing 3.",
    hints: [
      "Think about the worst possible spread of birth months before a third match is forced (pigeonhole principle).",
      "Find the maximum number of people who could all avoid having 3 in the same month, then add one.",
    ],
    difficulty: 6,
    topicSlug: "pigeonhole",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-33",
    question:
      "A jar contains 5 red and 3 blue marbles. Two marbles are drawn at random without replacement. Given that the first marble drawn is red, what is the probability that the second marble is also red? Express your answer as a fraction in lowest terms.",
    format: "SHORT_ANSWER",
    answer: "4/7",
    solution:
      "After removing one red marble, 4 red and 3 blue marbles remain, for 7 total. The probability the second marble is red is 4/7.",
    hints: ["Update the counts of marbles remaining after the first red marble is removed.", "Compute the probability using the new totals."],
    difficulty: 6,
    topicSlug: "conditional-probability",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-34",
    question:
      "A rectangular box has dimensions 3, 4, and 12. What is the length of the space diagonal connecting two opposite corners of the box?",
    format: "SHORT_ANSWER",
    answer: "13",
    solution:
      "The space diagonal of a box with dimensions a, b, c has length √(a² + b² + c²) = √(9 + 16 + 144) = √169 = 13.",
    hints: ["The space diagonal formula extends the Pythagorean theorem to three dimensions.", "Square each dimension, add them, then take the square root."],
    difficulty: 6,
    topicSlug: "three-d-geometry",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-35",
    question:
      "Working alone, Pipe A can fill a tank in 6 hours, and Pipe B can fill the same tank in 4 hours. Both pipes are opened together, but after 1 hour Pipe A is shut off. How many additional hours does Pipe B alone need to finish filling the tank? Express your answer as a fraction.",
    format: "SHORT_ANSWER",
    answer: "7/3",
    solution:
      "Pipe A fills 1/6 of the tank per hour and Pipe B fills 1/4 per hour. Together for 1 hour, they fill 1/6 + 1/4 = 5/12 of the tank. The remaining 7/12 must be filled by Pipe B alone, which takes (7/12) ÷ (1/4) = 7/3 hours.",
    hints: [
      "Find the fraction of the tank filled during the first hour when both pipes work together.",
      "Divide the remaining fraction of the tank by Pipe B's rate to find the additional time needed.",
    ],
    difficulty: 7,
    topicSlug: "rates",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-36",
    question: "How many ordered pairs of positive integers (x, y) satisfy x^2 - y^2 = 45?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution:
      "Factor: (x - y)(x + y) = 45. Since 45 is odd, both factors x - y and x + y must be odd, so any factor pair works. The factor pairs (d, e) with d ≤ e and d × e = 45 are (1,45), (3,15), and (5,9), giving (x,y) = (23,22), (9,6), and (7,2) respectively — all positive integers. This gives 3 ordered pairs.",
    hints: [
      "Factor the left side as a difference of squares: (x - y)(x + y) = 45.",
      "Each factor pair (d, e) of 45 with d ≤ e gives x = (d+e)/2 and y = (e-d)/2 — check which pairs give integer, positive solutions.",
    ],
    difficulty: 7,
    topicSlug: "integer-properties",
    competitionSlug: "mathcounts",
  },

{
    slug: "mathcounts-37",
    question:
      "A school store sells pencils in packs of 12. If the store sold 17 packs on Monday and 23 packs on Tuesday, how many individual pencils did it sell over the two days?",
    format: "SHORT_ANSWER",
    answer: "480",
    solution: "The store sold 17 + 23 = 40 packs total. Each pack has 12 pencils, so it sold 40 × 12 = 480 pencils.",
    hints: ["First find the total number of packs sold over both days.", "Multiply the total number of packs by 12 pencils per pack."],
    difficulty: 3,
    topicSlug: "arithmetic",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-38",
    question: "A shirt originally priced at $40 is on sale for 25% off. What is the sale price, in dollars?",
    format: "SHORT_ANSWER",
    answer: "30",
    solution: "A 25% discount means the shirt costs 75% of the original price: 0.75 × 40 = 30.",
    hints: ["A 25% discount leaves 75% of the original price.", "Multiply $40 by 0.75."],
    difficulty: 3,
    topicSlug: "percentages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-39",
    question: "In a class, the ratio of boys to girls is 5:6. If there are 30 boys, how many girls are there?",
    format: "SHORT_ANSWER",
    answer: "36",
    solution: "Since 30 boys correspond to 5 parts, each part is 30 / 5 = 6 students. Girls = 6 parts = 6 × 6 = 36.",
    hints: ["Find how many students one ratio 'part' represents using the number of boys.", "Multiply that per-part value by the girls' side of the ratio."],
    difficulty: 3,
    topicSlug: "ratios-proportions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-40",
    question: "Two angles are complementary. One angle is twice the other. What is the measure, in degrees, of the larger angle?",
    format: "SHORT_ANSWER",
    answer: "60",
    solution: "Let the smaller angle be x, so the larger is 2x. Since they are complementary, x + 2x = 90, so 3x = 90 and x = 30. The larger angle is 2(30) = 60.",
    hints: ["Complementary angles sum to 90 degrees.", "Let the smaller angle be x and write the larger as 2x, then solve."],
    difficulty: 3,
    topicSlug: "angles",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-41",
    question: "What is the sum of the first five prime numbers?",
    format: "SHORT_ANSWER",
    answer: "28",
    solution: "The first five primes are 2, 3, 5, 7, and 11. Their sum is 2 + 3 + 5 + 7 + 11 = 28.",
    hints: ["List the first five prime numbers, remembering that 1 is not prime.", "Add the five values together."],
    difficulty: 3,
    topicSlug: "primes",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-42",
    question: "Solve for y: 5y - 3 = 2y + 12.",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "Subtract 2y from both sides: 3y - 3 = 12. Add 3: 3y = 15. Divide by 3: y = 5.",
    hints: ["Collect all the y-terms on one side of the equation.", "Then isolate y by undoing addition/subtraction and division."],
    difficulty: 3,
    topicSlug: "linear-equations",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-43",
    question: "A restaurant offers 4 appetizers, 5 main courses, and 3 desserts. How many different three-course meals (one of each) can be ordered?",
    format: "SHORT_ANSWER",
    answer: "60",
    solution: "By the counting principle, multiply the number of choices at each course: 4 × 5 × 3 = 60.",
    hints: ["Use the multiplication counting principle.", "Multiply the number of options for each independent course together."],
    difficulty: 3,
    topicSlug: "counting-principles",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-44",
    question:
      "A standard six-sided die is rolled once. What is the probability that the result is a number greater than 4? Express your answer as a fraction in lowest terms.",
    format: "SHORT_ANSWER",
    answer: "1/3",
    solution: "The numbers greater than 4 are 5 and 6, so there are 2 favorable outcomes out of 6. The probability is 2/6 = 1/3.",
    hints: ["List the outcomes on the die that are greater than 4.", "Divide the count of favorable outcomes by 6 and simplify."],
    difficulty: 3,
    topicSlug: "basic-probability",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-45",
    question: "Three siblings have ages that are consecutive even integers. If the sum of their ages is 42, what is the age of the youngest sibling?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "Let the ages be x, x + 2, and x + 4. Then x + (x + 2) + (x + 4) = 42, so 3x + 6 = 42, giving 3x = 36 and x = 12.",
    hints: ["Represent the three consecutive even ages as x, x + 2, and x + 4.", "Add the three expressions and set the sum equal to 42."],
    difficulty: 3,
    topicSlug: "algebra",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-46",
    question: "A gardener plants trees in rows of 15. If she plants 8 full rows and then 9 more trees, how many trees did she plant in total?",
    format: "SHORT_ANSWER",
    answer: "129",
    solution: "The 8 full rows contain 8 × 15 = 120 trees. Adding the 9 extra trees gives 120 + 9 = 129.",
    hints: ["Find the number of trees in the full rows first.", "Add the extra trees planted beyond the full rows."],
    difficulty: 3,
    topicSlug: "arithmetic",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-47",
    question: "A number increased by 20% equals 96. What is the original number?",
    format: "SHORT_ANSWER",
    answer: "80",
    solution: "If x is the original number, then 1.2x = 96, so x = 96 / 1.2 = 80.",
    hints: ["A 20% increase means multiplying the original number by 1.2.", "Divide 96 by 1.2 to undo the increase."],
    difficulty: 3,
    topicSlug: "percentages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-48",
    question: "A recipe uses flour and sugar in the ratio 5:2. If a baker uses 20 cups of flour, how many cups of sugar does he need?",
    format: "SHORT_ANSWER",
    answer: "8",
    solution: "Since 20 cups of flour correspond to 5 parts, each part is 20 / 5 = 4 cups. Sugar = 2 parts = 2 × 4 = 8 cups.",
    hints: ["Find how many cups one ratio 'part' represents using the flour amount.", "Multiply that per-part value by the sugar side of the ratio."],
    difficulty: 3,
    topicSlug: "ratios-proportions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-49",
    question: "A triangle has side lengths 9, 12, and 15. What is its area?",
    format: "SHORT_ANSWER",
    answer: "54",
    solution: "Since 9² + 12² = 81 + 144 = 225 = 15², this is a right triangle with legs 9 and 12. Its area is (1/2)(9)(12) = 54.",
    hints: ["Check whether the Pythagorean theorem holds for these three side lengths.", "If it's a right triangle, the two shorter sides are the legs — use them as base and height."],
    difficulty: 3,
    topicSlug: "triangles",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-50",
    question: "What is the largest three-digit number divisible by 13?",
    format: "SHORT_ANSWER",
    answer: "988",
    solution: "Dividing 999 by 13 gives about 76.8, so the largest multiple of 13 at most 999 is 13 × 76 = 988.",
    hints: ["Divide 999 by 13 to see how many full multiples of 13 fit.", "Round down to the nearest whole multiple."],
    difficulty: 3,
    topicSlug: "divisibility",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-51",
    question: "If x² = 49 and x is negative, what is the value of x?",
    format: "SHORT_ANSWER",
    answer: "-7",
    solution: "The two square roots of 49 are 7 and -7. Since x is negative, x = -7.",
    hints: ["A positive number has two square roots, one positive and one negative.", "Pick the negative one."],
    difficulty: 3,
    topicSlug: "quadratics",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-52",
    question: "In how many ways can 4 distinct trophies be awarded to 4 different students, one trophy per student?",
    format: "SHORT_ANSWER",
    answer: "24",
    solution: "This is a permutation of 4 distinct items: 4! = 4 × 3 × 2 × 1 = 24.",
    hints: ["Each trophy goes to a different student, so this is a permutation.", "Compute 4 factorial."],
    difficulty: 3,
    topicSlug: "permutations",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-53",
    question:
      "A bag contains 3 green, 5 yellow, and 2 orange balls. If one ball is drawn at random, what is the probability it is not yellow? Express your answer as a fraction in lowest terms.",
    format: "SHORT_ANSWER",
    answer: "1/2",
    solution: "There are 10 balls total, 5 of which are yellow, so 5 are not yellow. The probability is 5/10 = 1/2.",
    hints: ["Find the total number of balls and how many are yellow.", "The balls that are 'not yellow' are green plus orange."],
    difficulty: 3,
    topicSlug: "counting-probability",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-54",
    question: "A printer prints 45 pages in 5 minutes at a constant rate. How many pages can it print in 12 minutes?",
    format: "SHORT_ANSWER",
    answer: "108",
    solution: "The rate is 45 / 5 = 9 pages per minute. In 12 minutes it prints 9 × 12 = 108 pages.",
    hints: ["Find the printing rate in pages per minute first.", "Multiply that rate by the new number of minutes."],
    difficulty: 3,
    topicSlug: "rates",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-55",
    question: "What is the value of 7 + 6 × (9 - 4)?",
    format: "SHORT_ANSWER",
    answer: "37",
    solution: "Following order of operations: 9 - 4 = 5, then 6 × 5 = 30, then 7 + 30 = 37.",
    hints: ["Evaluate the parentheses first.", "Then handle multiplication before addition."],
    difficulty: 3,
    topicSlug: "arithmetic",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-56",
    question: "60 is what percent of 150?",
    format: "SHORT_ANSWER",
    answer: "40",
    solution: "60 / 150 = 0.4 = 40%.",
    hints: ["Divide the part by the whole.", "Convert the resulting decimal to a percent."],
    difficulty: 3,
    topicSlug: "percentages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-57",
    question:
      "A map has a scale of 1 inch to 8 miles. If two cities are 3.5 inches apart on the map, how many miles apart are they actually?",
    format: "SHORT_ANSWER",
    answer: "28",
    solution: "Each inch represents 8 miles, so 3.5 inches represents 3.5 × 8 = 28 miles.",
    hints: ["Each inch on the map corresponds to 8 real miles.", "Multiply the map distance by the scale factor."],
    difficulty: 3,
    topicSlug: "ratios-proportions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-58",
    question: "A parallelogram has a base of 14 and a height of 5. What is its area?",
    format: "SHORT_ANSWER",
    answer: "70",
    solution: "The area of a parallelogram is base × height = 14 × 5 = 70.",
    hints: ["Use the parallelogram area formula, base times height.", "Substitute the given values."],
    difficulty: 3,
    topicSlug: "quadrilaterals",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-59",
    question: "What is the sum of all positive divisors of 24?",
    format: "SHORT_ANSWER",
    answer: "60",
    solution: "The divisors of 24 are 1, 2, 3, 4, 6, 8, 12, and 24. Their sum is 1+2+3+4+6+8+12+24 = 60.",
    hints: ["List all the positive divisors of 24 systematically in pairs.", "Add all of them together."],
    difficulty: 4,
    topicSlug: "number-properties",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-60",
    question: "If 2x + y = 11 and x - y = 1, what is the value of x?",
    format: "SHORT_ANSWER",
    answer: "4",
    solution: "Adding the two equations eliminates y: (2x + y) + (x - y) = 11 + 1, so 3x = 12, giving x = 4.",
    hints: ["Add the two equations together to eliminate y.", "Solve the resulting equation for x."],
    difficulty: 4,
    topicSlug: "systems-of-equations",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-61",
    question: "A pizza place offers 6 toppings. How many different 2-topping pizzas can be made, assuming no topping is repeated?",
    format: "SHORT_ANSWER",
    answer: "15",
    solution: "The order of toppings doesn't matter, so use combinations: C(6,2) = (6 × 5) / (2 × 1) = 15.",
    hints: ["Since the order of toppings doesn't matter, use combinations rather than permutations.", "Compute C(6,2)."],
    difficulty: 4,
    topicSlug: "combinations",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-62",
    question:
      "A drawer has 4 black socks and 6 white socks. Two socks are drawn without replacement. Given that the first sock drawn is white, what is the probability that the second sock is also white? Express your answer as a fraction in lowest terms.",
    format: "SHORT_ANSWER",
    answer: "5/9",
    solution: "After removing one white sock, 5 white and 4 black socks remain, for 9 total. The probability the second sock is white is 5/9.",
    hints: ["Update the counts of socks remaining after the first white sock is removed.", "Compute the probability using the new totals."],
    difficulty: 4,
    topicSlug: "conditional-probability",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-63",
    question:
      "The average of six numbers is 15. If one of the numbers is removed, the average of the remaining five numbers is 14. What was the number removed?",
    format: "SHORT_ANSWER",
    answer: "20",
    solution: "The sum of all six numbers is 6 × 15 = 90. The sum of the remaining five is 5 × 14 = 70. The removed number is 90 - 70 = 20.",
    hints: ["Use the averages to find the total sum before and after removal.", "Subtract the new sum from the original sum."],
    difficulty: 4,
    topicSlug: "averages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-64",
    question: "A theater has 24 rows with 18 seats each. If 3/4 of the seats are filled, how many seats are empty?",
    format: "SHORT_ANSWER",
    answer: "108",
    solution: "The theater has 24 × 18 = 432 seats. Filled seats are (3/4)(432) = 324, so empty seats are 432 - 324 = 108.",
    hints: ["Find the total number of seats in the theater first.", "Find how many are filled, then subtract from the total."],
    difficulty: 4,
    topicSlug: "arithmetic",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-65",
    question: "A price is increased by 10% and then decreased by 10%. What percent of the original price is the final price?",
    format: "SHORT_ANSWER",
    answer: "99",
    solution: "The final price is (1.10)(0.90) = 0.99 times the original, which is 99% of the original price.",
    hints: ["Apply the increase and decrease as successive multipliers, not by simply adding percents.", "Multiply 1.10 by 0.90."],
    difficulty: 4,
    topicSlug: "percentages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-66",
    question: "The ratio of cats to dogs to birds in a shelter is 3:4:5. If there are 60 animals total, how many dogs are there?",
    format: "SHORT_ANSWER",
    answer: "20",
    solution: "The ratio parts sum to 3 + 4 + 5 = 12. Each part represents 60 / 12 = 5 animals. Dogs = 4 parts = 4 × 5 = 20.",
    hints: ["Add the ratio parts together to find the total number of parts.", "Find the value of one part, then multiply by the dogs' share."],
    difficulty: 4,
    topicSlug: "ratios-proportions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-67",
    question: "A circle has a diameter of 18. What is its area, in terms of π?",
    format: "SHORT_ANSWER",
    answer: "81π",
    solution: "The radius is 18 / 2 = 9. The area is πr² = π(9²) = 81π.",
    hints: ["Find the radius from the diameter first.", "Use the area formula A = πr²."],
    difficulty: 4,
    topicSlug: "circles",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-68",
    question: "What is the smallest positive integer with exactly 6 positive divisors?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution:
      "Checking integers in order: 12 = 2² × 3 has (2+1)(1+1) = 6 divisors (1, 2, 3, 4, 6, 12), and every smaller positive integer has fewer than 6 divisors.",
    hints: ["If n = p^a × q^b, the number of divisors is (a+1)(b+1).", "Test small numbers in increasing order and count their divisors directly."],
    difficulty: 4,
    topicSlug: "integer-properties",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-69",
    question: "Simplify: √50 + √8. Express your answer in simplest radical form.",
    format: "SHORT_ANSWER",
    answer: "7√2",
    solution: "√50 = √(25 × 2) = 5√2, and √8 = √(4 × 2) = 2√2. Adding: 5√2 + 2√2 = 7√2.",
    hints: ["Rewrite each radical using the largest perfect-square factor.", "Combine the like radical terms."],
    difficulty: 4,
    topicSlug: "exponents-radicals",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-70",
    question: "How many two-digit numbers have digits that sum to 9?",
    format: "SHORT_ANSWER",
    answer: "9",
    solution: "The two-digit numbers with digit sum 9 are 18, 27, 36, 45, 54, 63, 72, 81, and 90 — a total of 9 numbers.",
    hints: ["Let the tens digit be t (1-9) and the units digit be 9 - t.", "Check which values of t from 1 to 9 give a valid units digit (0-9)."],
    difficulty: 4,
    topicSlug: "casework",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-71",
    question: "A spinner is divided into 4 equal sections labeled 2, 4, 6, and 8. What is the expected value of one spin?",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "Since each section is equally likely, the expected value is the average of the labels: (2+4+6+8)/4 = 20/4 = 5.",
    hints: ["Expected value is the sum of outcomes times their probabilities.", "Since each outcome is equally likely, this is just the average of the four values."],
    difficulty: 4,
    topicSlug: "expected-value",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-72",
    question: "Evaluate: 3/4 - 5/12 + 1/6. Express your answer as a fraction in lowest terms.",
    format: "SHORT_ANSWER",
    answer: "1/2",
    solution: "Using a common denominator of 12: 9/12 - 5/12 + 2/12 = 6/12 = 1/2.",
    hints: ["Rewrite each fraction with a common denominator of 12.", "Combine the numerators, then simplify."],
    difficulty: 4,
    topicSlug: "fractions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-73",
    question: "A factory produces 480 widgets in an 8-hour shift at a constant rate. How many widgets does it produce in 3.5 hours?",
    format: "SHORT_ANSWER",
    answer: "210",
    solution: "The rate is 480 / 8 = 60 widgets per hour. In 3.5 hours it produces 60 × 3.5 = 210 widgets.",
    hints: ["Find the production rate per hour first.", "Multiply that rate by 3.5 hours."],
    difficulty: 4,
    topicSlug: "arithmetic",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-74",
    question: "In a survey of 250 students, 40% prefer math and the rest prefer other subjects. How many students prefer subjects other than math?",
    format: "SHORT_ANSWER",
    answer: "150",
    solution: "Students who prefer math: 0.40 × 250 = 100. The rest, 250 - 100 = 150, prefer other subjects.",
    hints: ["Find how many students prefer math first.", "Subtract from the total number of students surveyed."],
    difficulty: 4,
    topicSlug: "percentages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-75",
    question: "Two numbers are in the ratio 3:5. If their sum is 96, what is the larger number?",
    format: "SHORT_ANSWER",
    answer: "60",
    solution: "The ratio parts sum to 3 + 5 = 8. Each part is 96 / 8 = 12. The larger number is 5 × 12 = 60.",
    hints: ["Add the ratio parts to find the total number of parts.", "Find the value of one part, then scale up to the larger number's share."],
    difficulty: 4,
    topicSlug: "ratios-proportions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-76",
    question: "Each interior angle of a regular polygon measures 150 degrees. How many sides does the polygon have?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "Each exterior angle is 180 - 150 = 30 degrees. Since exterior angles of a regular polygon sum to 360, the number of sides is 360 / 30 = 12.",
    hints: ["Find the exterior angle, which is supplementary to the interior angle.", "The exterior angles of any convex polygon sum to 360 degrees."],
    difficulty: 4,
    topicSlug: "polygons",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-77",
    question: "What is the remainder when 3^7 is divided by 5?",
    format: "SHORT_ANSWER",
    answer: "2",
    solution: "Powers of 3 mod 5 cycle as 3, 4, 2, 1 (period 4). Since 7 mod 4 = 3, the remainder matches the 3rd term in the cycle, which is 2.",
    hints: ["Compute successive powers of 3 modulo 5 and look for a repeating pattern.", "Use the cycle length to find where the exponent 7 falls."],
    difficulty: 4,
    topicSlug: "modular-arithmetic",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-78",
    question: "If g(x) = 3x - 7, what is the value of x such that g(x) = 20?",
    format: "SHORT_ANSWER",
    answer: "9",
    solution: "Set 3x - 7 = 20. Adding 7 gives 3x = 27, so x = 9.",
    hints: ["Set the expression for g(x) equal to 20.", "Solve the resulting linear equation for x."],
    difficulty: 4,
    topicSlug: "functions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-79",
    question:
      "In a class of 30 students, 18 take Spanish, 15 take French, and 8 take both. How many students take neither language?",
    format: "SHORT_ANSWER",
    answer: "5",
    solution: "The number taking at least one language is 18 + 15 - 8 = 25. Those taking neither are 30 - 25 = 5.",
    hints: ["Use inclusion-exclusion to find how many students take at least one language.", "Subtract that result from the total class size."],
    difficulty: 4,
    topicSlug: "inclusion-exclusion",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-80",
    question:
      "A jar contains 6 red, 4 blue, and 5 green marbles. If one marble is drawn at random, what is the probability it is red or green? Express your answer as a fraction in lowest terms.",
    format: "SHORT_ANSWER",
    answer: "11/15",
    solution: "There are 15 marbles total, of which 6 + 5 = 11 are red or green. The probability is 11/15, which is already in lowest terms.",
    hints: ["Find the total number of marbles and how many are red or green.", "Write that as a fraction and check whether it can be reduced."],
    difficulty: 4,
    topicSlug: "basic-probability",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-81",
    question: "What is the minimum number of students needed in a class to guarantee that at least 4 of them have birthdays in the same month?",
    format: "SHORT_ANSWER",
    answer: "37",
    solution: "There are 12 months. In the worst case, 3 students could have birthdays in each month before a 4th match is forced: 3 × 12 = 36 students. The 37th student must share a month with 3 others.",
    hints: ["Think about the worst possible spread of birthdays across the 12 months before a 4th match is forced.", "Find the maximum number of students who could all avoid having 4 in the same month, then add one."],
    difficulty: 4,
    topicSlug: "pigeonhole",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-82",
    question: "A store buys a jacket for $60 and sells it for $84. What is the percent markup based on the cost price?",
    format: "SHORT_ANSWER",
    answer: "40",
    solution: "The markup amount is 84 - 60 = 24. As a percent of the cost, 24/60 = 0.40 = 40%.",
    hints: ["Find the dollar amount of the markup first.", "Divide the markup by the original cost, then convert to a percent."],
    difficulty: 5,
    topicSlug: "arithmetic",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-83",
    question: "After a 20% discount, a jacket costs $56. What was the original price, in dollars?",
    format: "SHORT_ANSWER",
    answer: "70",
    solution: "If x is the original price, then 0.80x = 56, so x = 56 / 0.80 = 70.",
    hints: ["The discounted price is 80% of the original price.", "Divide the sale price by 0.80 to recover the original price."],
    difficulty: 5,
    topicSlug: "percentages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-84",
    question: "The ratio of a rectangle's length to width is 7:4. If the perimeter is 66, what is the area of the rectangle?",
    format: "SHORT_ANSWER",
    answer: "252",
    solution:
      "Let the length be 7k and the width 4k. The perimeter is 2(7k + 4k) = 22k = 66, so k = 3. The length is 21 and the width is 12, giving an area of 21 × 12 = 252.",
    hints: ["Represent the length and width as 7k and 4k using the ratio.", "Use the perimeter to solve for k, then compute the area."],
    difficulty: 5,
    topicSlug: "ratios-proportions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-85",
    question: "A right circular cone has a radius of 6 and a height of 8. What is its volume, in terms of π?",
    format: "SHORT_ANSWER",
    answer: "96π",
    solution: "The volume of a cone is (1/3)πr²h = (1/3)π(6²)(8) = (1/3)π(36)(8) = 96π.",
    hints: ["Use the cone volume formula V = (1/3)πr²h.", "Substitute the given radius and height."],
    difficulty: 5,
    topicSlug: "area-volume",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-86",
    question:
      "The expression x² + bx + 36 factors as (x + m)(x + n), where m and n are positive integers. If b is as small as possible, what is the value of b?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution:
      "Here b = m + n where mn = 36. The factor pairs of 36 are (1,36), (2,18), (3,12), (4,9), and (6,6), with sums 37, 20, 15, 13, and 12. The smallest sum is 12, from m = n = 6.",
    hints: ["List the positive factor pairs of 36 and their sums.", "b equals m + n, so find the factor pair with the smallest sum."],
    difficulty: 5,
    topicSlug: "factoring",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-87",
    question: "In an arithmetic sequence, the 3rd term is 11 and the 7th term is 27. What is the first term?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution:
      "The common difference is (27 - 11) / (7 - 3) = 16/4 = 4. The first term is two steps before the 3rd term: 11 - 2(4) = 3.",
    hints: ["Use the two given terms to find the common difference.", "Step backward from the 3rd term to the 1st term using that difference."],
    difficulty: 5,
    topicSlug: "sequences",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-88",
    question: "License plates consist of 3 letters followed by 2 digits. How many different license plates are possible if letters and digits can repeat?",
    format: "SHORT_ANSWER",
    answer: "1757600",
    solution: "There are 26 choices for each of the 3 letters and 10 choices for each of the 2 digits: 26³ × 10² = 17576 × 100 = 1,757,600.",
    hints: ["Count the choices for the letter positions and digit positions separately.", "Multiply all five choice-counts together using the counting principle."],
    difficulty: 5,
    topicSlug: "counting-principles",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-89",
    question: "Two fair six-sided dice are rolled. What is the probability that the sum is 7? Express your answer as a fraction in lowest terms.",
    format: "SHORT_ANSWER",
    answer: "1/6",
    solution: "There are 36 equally likely outcomes. The pairs summing to 7 are (1,6),(2,5),(3,4),(4,3),(5,2),(6,1), a total of 6. The probability is 6/36 = 1/6.",
    hints: ["List all the ordered pairs of dice rolls that sum to 7.", "Divide the count of favorable outcomes by 36 total outcomes and simplify."],
    difficulty: 5,
    topicSlug: "counting-probability",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-90",
    question:
      "Amy, Ben, and Cody each play a different sport: soccer, tennis, or golf. Amy does not play soccer or golf. Ben does not play tennis or golf. What sport does Cody play?",
    format: "SHORT_ANSWER",
    answer: "golf",
    solution:
      "Since Amy doesn't play soccer or golf, Amy plays tennis. Since Ben doesn't play tennis (already taken by Amy) or golf, Ben plays soccer. That leaves golf for Cody.",
    hints: ["Start with the person who has the most restrictions to pin down their sport first.", "Once two of the three sports are assigned, the third person gets what's left."],
    difficulty: 5,
    topicSlug: "deduction",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-91",
    question: "The sum of three consecutive odd integers is 141. What is the largest of the three integers?",
    format: "SHORT_ANSWER",
    answer: "49",
    solution: "Let the integers be x, x+2, x+4. Then 3x + 6 = 141, so 3x = 135 and x = 45. The largest integer is 45 + 4 = 49.",
    hints: ["Represent the three consecutive odd integers as x, x+2, and x+4.", "Add them, set equal to 141, and solve for x."],
    difficulty: 5,
    topicSlug: "arithmetic",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-92",
    question: "A population of bacteria grows by 50% every hour. If there are 800 bacteria now, how many will there be in 2 hours?",
    format: "SHORT_ANSWER",
    answer: "1800",
    solution: "Growing by 50% each hour multiplies the population by 1.5 each time: 800 × 1.5 × 1.5 = 800 × 2.25 = 1800.",
    hints: ["Growth of 50% per hour means multiplying by 1.5 each hour, not adding a fixed amount.", "Apply the multiplier twice, for the two hours."],
    difficulty: 5,
    topicSlug: "percentages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-93",
    question:
      "At a company, the ratio of managers to employees is 2:15. If there are 12 managers, what is the total number of people (managers plus employees) at the company?",
    format: "SHORT_ANSWER",
    answer: "102",
    solution: "Since 12 managers correspond to 2 parts, each part is 6. Employees = 15 parts = 15 × 6 = 90. Total people = 12 + 90 = 102.",
    hints: ["Find the value of one ratio 'part' using the number of managers.", "Find the number of employees, then add the managers back in."],
    difficulty: 5,
    topicSlug: "ratios-proportions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-94",
    question: "A triangle has vertices at (0,0), (6,0), and (0,8). What is the length of its longest side?",
    format: "SHORT_ANSWER",
    answer: "10",
    solution: "The two legs have lengths 6 and 8. The third side, the hypotenuse, is √(6² + 8²) = √(36 + 64) = √100 = 10, which is the longest side.",
    hints: ["Find the lengths of all three sides using the distance formula or the coordinates directly.", "The side opposite the right angle is the hypotenuse and the longest side."],
    difficulty: 5,
    topicSlug: "coordinate-geometry",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-95",
    question: "What is the greatest common divisor of 84 and 126?",
    format: "SHORT_ANSWER",
    answer: "42",
    solution: "84 = 2² × 3 × 7 and 126 = 2 × 3² × 7. The GCD takes the lowest power of each shared prime: 2 × 3 × 7 = 42.",
    hints: ["Write the prime factorization of each number.", "Multiply the lowest power of each prime that appears in both factorizations."],
    difficulty: 5,
    topicSlug: "number-theory",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-96",
    question: "If P(x) = x³ - 2x² + x - 5, what is the remainder when P(x) is divided by (x - 2)?",
    format: "SHORT_ANSWER",
    answer: "-3",
    solution: "By the remainder theorem, the remainder equals P(2) = 2³ - 2(2²) + 2 - 5 = 8 - 8 + 2 - 5 = -3.",
    hints: ["Use the remainder theorem: dividing by (x - a) leaves a remainder of P(a).", "Substitute x = 2 into P(x)."],
    difficulty: 5,
    topicSlug: "polynomials",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-97",
    question: "How many distinct ways can the letters of the word 'LEVEL' be arranged?",
    format: "SHORT_ANSWER",
    answer: "30",
    solution: "LEVEL has 5 letters with L repeated twice and E repeated twice. The number of distinct arrangements is 5! / (2! × 2!) = 120/4 = 30.",
    hints: ["Count the total letters and note which letters repeat.", "Divide the total permutations by the factorial of each repeated letter's count."],
    difficulty: 5,
    topicSlug: "permutations",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-98",
    question:
      "A box contains 20 tickets numbered 1 through 20. If one ticket is drawn at random, what is the probability that the number is a multiple of 3 or a multiple of 4? Express your answer as a fraction in lowest terms.",
    format: "SHORT_ANSWER",
    answer: "1/2",
    solution:
      "Multiples of 3: 3,6,9,12,15,18 (6 numbers). Multiples of 4: 4,8,12,16,20 (5 numbers). Multiples of 12 (both): 12 (1 number). By inclusion-exclusion, the count is 6 + 5 - 1 = 10, so the probability is 10/20 = 1/2.",
    hints: ["Count the multiples of 3 and multiples of 4 separately, then find the overlap (multiples of 12).", "Use inclusion-exclusion to avoid double-counting before dividing by 20."],
    difficulty: 5,
    topicSlug: "basic-probability",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-99",
    question:
      "Two players alternately remove either 1 or 2 stones from a pile of 17 stones; the player who removes the last stone wins. If both players play optimally and Player 1 moves first, how many stones should Player 1 remove on the first turn to guarantee a win?",
    format: "SHORT_ANSWER",
    answer: "2",
    solution:
      "A pile size that is a multiple of 3 is a losing position for the player about to move (whatever they take, 1 or 2, the opponent restores it to a multiple of 3). Since 17 = 15 + 2, Player 1 should remove 2 stones, leaving 15 (a multiple of 3) for Player 2.",
    hints: ["Figure out which pile sizes are 'losing positions' for the player whose turn it is.", "Multiples of 3 turn out to be losing positions — get the pile down to one."],
    difficulty: 5,
    topicSlug: "games-and-strategies",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-100",
    question: "A number is divided into two parts such that one part is 3 times the other. If the two parts differ by 48, what is the larger part?",
    format: "SHORT_ANSWER",
    answer: "72",
    solution: "Let the smaller part be x, so the larger is 3x. Their difference is 3x - x = 2x = 48, so x = 24. The larger part is 3(24) = 72.",
    hints: ["Represent the two parts as x and 3x.", "Set their difference equal to 48 and solve for x."],
    difficulty: 5,
    topicSlug: "arithmetic",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-101",
    question:
      "A jacket's price was reduced by 30% to $63. A week later, this reduced price is increased by 30%. What is the price after the increase, in dollars?",
    format: "SHORT_ANSWER",
    answer: "81.9",
    solution: "Increasing $63 by 30% gives 63 × 1.30 = 81.9.",
    hints: ["The 30% increase is applied to the already-reduced price of $63, not the original price.", "Multiply $63 by 1.30."],
    difficulty: 5,
    topicSlug: "percentages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-102",
    question:
      "A blend of nuts contains almonds, cashews, and peanuts in the ratio 2:3:5. If the blend contains 45 more peanuts than almonds, how many cashews are in the blend?",
    format: "SHORT_ANSWER",
    answer: "45",
    solution: "Let one part be k. Peanuts minus almonds is 5k - 2k = 3k = 45, so k = 15. Cashews are 3 parts = 3 × 15 = 45.",
    hints: ["Let one ratio 'part' be k, and write peanuts minus almonds in terms of k.", "Solve for k, then find the number of cashews."],
    difficulty: 5,
    topicSlug: "ratios-proportions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-103",
    question: "Two similar triangles have corresponding sides in ratio 2:5. If the perimeter of the smaller triangle is 18, what is the perimeter of the larger triangle?",
    format: "SHORT_ANSWER",
    answer: "45",
    solution: "Perimeters of similar figures scale the same way as their sides: 18 × (5/2) = 45.",
    hints: ["The ratio of perimeters of similar figures equals the ratio of corresponding sides.", "Scale the smaller perimeter by 5/2."],
    difficulty: 5,
    topicSlug: "similarity-congruence",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-104",
    question: "How many positive integers less than 100 are divisible by both 4 and 6?",
    format: "SHORT_ANSWER",
    answer: "8",
    solution: "A number divisible by both 4 and 6 must be divisible by lcm(4,6) = 12. The multiples of 12 less than 100 are 12, 24, ..., 96, which is 8 numbers.",
    hints: ["Find the least common multiple of 4 and 6.", "Count the multiples of that LCM that are less than 100."],
    difficulty: 5,
    topicSlug: "divisibility",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-105",
    question: "The product of two consecutive positive even integers is 168. What is the sum of the two integers?",
    format: "SHORT_ANSWER",
    answer: "26",
    solution: "Let the integers be x and x+2, so x(x+2) = 168, giving x² + 2x - 168 = 0. This factors as (x-12)(x+14) = 0, so x = 12. The integers are 12 and 14, which sum to 26.",
    hints: ["Set up the equation x(x+2) = 168 and rearrange into standard quadratic form.", "Factor the quadratic, keeping only the positive solution."],
    difficulty: 6,
    topicSlug: "quadratics",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-106",
    question: "A committee of 4 is to be chosen from 6 men and 5 women. How many committees include at least 2 women?",
    format: "SHORT_ANSWER",
    answer: "215",
    solution:
      "Sum the cases by number of women: 2 women, 2 men: C(5,2)C(6,2) = 10×15 = 150. 3 women, 1 man: C(5,3)C(6,1) = 10×6 = 60. 4 women, 0 men: C(5,4)C(6,0) = 5×1 = 5. Total: 150 + 60 + 5 = 215.",
    hints: ["Break the problem into cases based on exactly how many women are on the committee (2, 3, or 4).", "Compute each case with combinations and add the results together."],
    difficulty: 6,
    topicSlug: "combinations",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-107",
    question:
      "A box contains 3 red, 4 blue, and 5 green pens. Two pens are drawn without replacement. What is the probability that both are blue? Express your answer as a fraction in lowest terms.",
    format: "SHORT_ANSWER",
    answer: "1/11",
    solution: "There are C(12,2) = 66 ways to draw 2 pens from 12, and C(4,2) = 6 ways to draw 2 blue pens. The probability is 6/66 = 1/11.",
    hints: ["Find the total number of ways to draw 2 pens from all 12.", "Find the number of ways to draw 2 blue pens specifically, then form the ratio."],
    difficulty: 6,
    topicSlug: "conditional-probability",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-108",
    question:
      "The sequence 2, 6, 12, 20, 30, ... follows the pattern n(n+1) for n = 1, 2, 3, .... What is the 12th term?",
    format: "SHORT_ANSWER",
    answer: "156",
    solution: "The 12th term is 12 × 13 = 156.",
    hints: ["Substitute n = 12 into the formula n(n+1).", "Multiply the two consecutive integers together."],
    difficulty: 6,
    topicSlug: "number-patterns",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-109",
    question: "A tank is 1/5 full of water. After adding 24 liters, it becomes 3/5 full. What is the total capacity of the tank, in liters?",
    format: "SHORT_ANSWER",
    answer: "60",
    solution: "The 24 liters added fills 3/5 - 1/5 = 2/5 of the tank's capacity. So the full capacity C satisfies (2/5)C = 24, giving C = 60.",
    hints: ["Find what fraction of the tank the 24 liters represents.", "Set up an equation relating that fraction of capacity to 24 liters."],
    difficulty: 6,
    topicSlug: "arithmetic",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-110",
    question: "A store's revenue increased from $12,000 to $15,600 over one year. By what percent did the revenue increase?",
    format: "SHORT_ANSWER",
    answer: "30",
    solution: "The increase is 15600 - 12000 = 3600. As a percent of the original: 3600/12000 = 0.30 = 30%.",
    hints: ["Find the dollar increase in revenue first.", "Divide the increase by the original revenue and convert to a percent."],
    difficulty: 6,
    topicSlug: "percentages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-111",
    question:
      "An alloy is made of copper and zinc in the ratio 7:3. How many kilograms of zinc must be added to 50 kg of this alloy to change the ratio of copper to zinc to 7:5?",
    format: "SHORT_ANSWER",
    answer: "10",
    solution:
      "In 50 kg of alloy, copper is (7/10)(50) = 35 kg and zinc is (3/10)(50) = 15 kg. To reach a 7:5 ratio with 35 kg of copper unchanged, zinc must equal (5/7)(35) = 25 kg. So 25 - 15 = 10 kg of zinc must be added.",
    hints: ["Find the current amounts of copper and zinc in the 50 kg alloy.", "The copper amount stays fixed — find the zinc amount needed for the new ratio, then find the difference."],
    difficulty: 6,
    topicSlug: "ratios-proportions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-112",
    question: "A cube has a surface area of 150 square units. What is its volume?",
    format: "SHORT_ANSWER",
    answer: "125",
    solution: "The surface area is 6s², so 6s² = 150 gives s² = 25 and s = 5. The volume is s³ = 5³ = 125.",
    hints: ["Use the surface area formula for a cube, 6s², to find the side length.", "Cube the side length to find the volume."],
    difficulty: 6,
    topicSlug: "three-d-geometry",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-113",
    question: "What is the units digit of 7^123?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution: "The units digits of powers of 7 cycle as 7, 9, 3, 1 (period 4). Since 123 mod 4 = 3, the units digit matches the 3rd term in the cycle, which is 3.",
    hints: ["Find the repeating pattern of units digits for powers of 7.", "Use the exponent modulo the cycle length to find the matching position."],
    difficulty: 6,
    topicSlug: "modular-arithmetic",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-114",
    question: "If 2^(x+3) = 64, what is the value of x?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution: "Since 64 = 2^6, we need x + 3 = 6, so x = 3.",
    hints: ["Rewrite 64 as a power of 2.", "Set the exponents equal to each other."],
    difficulty: 6,
    topicSlug: "exponents-radicals",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-115",
    question: "How many 4-digit numbers (using digits 0-9, first digit nonzero) are even and have all distinct digits?",
    format: "SHORT_ANSWER",
    answer: "2296",
    solution:
      "Case 1, last digit 0: first digit has 9 choices (1-9), second has 8, third has 7: 9×8×7 = 504. Case 2, last digit in {2,4,6,8} (4 choices): first digit can't be 0 or the last digit (8 choices), second digit has 8 remaining choices, third has 7: 4 × 8 × 8 × 7 = 1792. Total: 504 + 1792 = 2296.",
    hints: ["Split into cases based on whether the last (even) digit is 0 or one of {2,4,6,8}, since 0 can't be the first digit.", "Count the choices for the remaining digits in each case and add the cases together."],
    difficulty: 6,
    topicSlug: "casework",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-116",
    question:
      "A game costs $5 to play. You roll a fair six-sided die and win an amount in dollars equal to twice the number rolled. What is the expected net profit (winnings minus cost) of playing this game, in dollars?",
    format: "SHORT_ANSWER",
    answer: "2",
    solution: "The average roll is (1+2+3+4+5+6)/6 = 3.5, so expected winnings are 2 × 3.5 = 7. The expected net profit is 7 - 5 = 2.",
    hints: ["Find the expected winnings before subtracting the cost.", "Subtract the $5 cost from the expected winnings."],
    difficulty: 6,
    topicSlug: "expected-value",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-117",
    question:
      "Machine A can complete a job in 6 hours, and Machine B can complete the same job in 10 hours. Both machines work on the job, but Machine B starts 2 hours after Machine A. How long total, from when Machine A starts, does it take to complete the job? Express your answer as a fraction in lowest terms.",
    format: "SHORT_ANSWER",
    answer: "9/2",
    solution:
      "In the first 2 hours, Machine A alone completes 2/6 = 1/3 of the job, leaving 2/3. Once both work together, their combined rate is 1/6 + 1/10 = 5/30 + 3/30 = 8/30 = 4/15 per hour. The remaining 2/3 takes (2/3) ÷ (4/15) = (2/3)(15/4) = 5/2 hours. Total time from the start is 2 + 5/2 = 9/2 hours.",
    hints: ["Find how much of the job Machine A finishes alone during the first 2 hours.", "Find the combined rate once Machine B joins, then divide the remaining work by that rate."],
    difficulty: 6,
    topicSlug: "rates",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-118",
    question:
      "The sum of the digits of a two-digit number is 11. If the digits are reversed, the new number is 45 more than the original number. What is the original number?",
    format: "SHORT_ANSWER",
    answer: "38",
    solution:
      "Let the tens digit be a and units digit be b, with a + b = 11. Reversing gives (10b + a) - (10a + b) = 9(b - a) = 45, so b - a = 5. Solving a + b = 11 and b - a = 5 gives b = 8, a = 3, so the original number is 38. (Check: reversed is 83, and 83 - 38 = 45.)",
    hints: ["Set up two equations: one for the digit sum, one for the difference after reversing.", "Solve the system for the tens and units digits."],
    difficulty: 6,
    topicSlug: "arithmetic",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-119",
    question:
      "A solution contains 40% salt. How many liters of pure water must be added to 15 liters of this solution to reduce the salt concentration to 24%?",
    format: "SHORT_ANSWER",
    answer: "10",
    solution:
      "The salt amount is 0.40 × 15 = 6 liters, which doesn't change. If x liters of water are added, the new concentration is 6/(15+x) = 0.24, so 15 + x = 25, giving x = 10.",
    hints: ["The amount of salt stays constant — only the total volume changes.", "Set up an equation for the new concentration in terms of the added water, x."],
    difficulty: 6,
    topicSlug: "percentages",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-120",
    question: "The ratio of the areas of two similar hexagons is 9:16. What is the ratio of their perimeters, expressed as a fraction in lowest terms?",
    format: "SHORT_ANSWER",
    answer: "3/4",
    solution: "For similar figures, the ratio of perimeters is the square root of the ratio of areas: √(9/16) = 3/4.",
    hints: ["The ratio of areas of similar figures is the square of the ratio of corresponding lengths.", "Take the square root of the given area ratio."],
    difficulty: 6,
    topicSlug: "ratios-proportions",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-121",
    question: "A circle is inscribed in a square with side length 10. What is the area of the region inside the square but outside the circle, in terms of π?",
    format: "SHORT_ANSWER",
    answer: "100-25π",
    solution: "The square's area is 10² = 100. The inscribed circle has radius 5, so its area is π(5²) = 25π. The region outside the circle but inside the square is 100 - 25π.",
    hints: ["The circle inscribed in the square has a diameter equal to the square's side length.", "Subtract the circle's area from the square's area."],
    difficulty: 6,
    topicSlug: "area-volume",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-122",
    question: "What is the smallest prime number that is greater than 100?",
    format: "SHORT_ANSWER",
    answer: "101",
    solution: "Checking 101: it is not divisible by 2, 3, 5, or 7 (the primes up to its square root, about 10.05), so 101 is prime.",
    hints: ["101 is odd and doesn't end in 0 or 5, so check divisibility by small primes.", "You only need to test primes up to the square root of 101."],
    difficulty: 6,
    topicSlug: "primes",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-123",
    question: "The sum of a number and its reciprocal is 5/2. What is the number, if it is greater than 1?",
    format: "SHORT_ANSWER",
    answer: "2",
    solution:
      "Let the number be x. Then x + 1/x = 5/2. Multiplying by 2x: 2x² - 5x + 2 = 0, which factors as (2x - 1)(x - 2) = 0, giving x = 1/2 or x = 2. Since x > 1, the number is 2.",
    hints: ["Multiply both sides by 2x to clear the fraction and get a quadratic equation.", "Factor the quadratic and choose the root greater than 1."],
    difficulty: 6,
    topicSlug: "quadratics",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-124",
    question: "How many integers from 1 to 200 are divisible by neither 3 nor 5?",
    format: "SHORT_ANSWER",
    answer: "107",
    solution:
      "Multiples of 3: floor(200/3) = 66. Multiples of 5: floor(200/5) = 40. Multiples of 15 (both): floor(200/15) = 13. By inclusion-exclusion, divisible by 3 or 5: 66 + 40 - 13 = 93. Divisible by neither: 200 - 93 = 107.",
    hints: ["Count multiples of 3, multiples of 5, and multiples of 15 (the overlap) up to 200.", "Use inclusion-exclusion to find the count divisible by 3 or 5, then subtract from 200."],
    difficulty: 6,
    topicSlug: "inclusion-exclusion",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-125",
    question:
      "A committee of 3 people is chosen at random from a group of 5 men and 4 women. What is the probability that the committee has at least one woman? Express your answer as a fraction in lowest terms.",
    format: "SHORT_ANSWER",
    answer: "37/42",
    solution:
      "Total committees: C(9,3) = 84. Committees with no women (all men): C(5,3) = 10. Committees with at least one woman: 84 - 10 = 74. The probability is 74/84 = 37/42.",
    hints: ["It's easier to find the complement: the probability of choosing all men.", "Subtract that count from the total, then simplify the resulting fraction."],
    difficulty: 6,
    topicSlug: "counting-probability",
    competitionSlug: "mathcounts",
  },
  {
    slug: "mathcounts-126",
    question: "The average of 5 consecutive integers is 34. What is the largest of the five integers?",
    format: "SHORT_ANSWER",
    answer: "36",
    solution: "For 5 consecutive integers, the average equals the middle (3rd) integer, so the middle integer is 34. The largest integer is two more than the middle: 34 + 2 = 36.",
    hints: ["For an odd count of consecutive integers, the average equals the middle term.", "Add 2 to the middle term to reach the largest of the five."],
    difficulty: 6,
    topicSlug: "averages",
    competitionSlug: "mathcounts",
  },
];
