import type { ProblemSeed } from "./problems";

/**
 * Hand-written problems styled after the AMC 8 (American Mathematics
 * Competition 8, for students in grades 8 and below).
 *
 * AMC 8 problems are 5-choice multiple choice, phrased as accessible but
 * cleverly-constructed word problems drawn from arithmetic, basic algebra,
 * geometry, number theory, combinatorics, and logic. Every problem below
 * is an original NumberSmith problem, written to match that phrasing,
 * tone, and increasing difficulty ramp; none are transcribed, closely
 * paraphrased, or numerically reskinned from any real AMC 8 contest.
 * Difficulty rises roughly from 2 (problem 1) to 7 (problem 30), mirroring
 * how the real 25-question, 40-minute contest escalates from one-step
 * arithmetic to problems that combine two or three ideas.
 *
 * Seeded as practice (isPlacement: false), same as the other
 * competition-tagged problem sets.
 */
export const AMC8_PROBLEMS: ProblemSeed[] = [
  {
    slug: "amc8-01",
    question:
      "A pizza is cut into 8 equal slices. Sam eats 3 slices and Mia eats 2 slices. What fraction of the pizza is left?",
    format: "MULTIPLE_CHOICE",
    choices: ["3/8", "5/8", "1/2", "2/8", "3/5"],
    answer: "A",
    solution:
      "Together Sam and Mia eat 3 + 2 = 5 slices out of 8, leaving 8 - 5 = 3 slices. That is 3/8 of the pizza.",
    hints: [
      "Find the total number of slices eaten first.",
      "Subtract the eaten slices from 8, then write the result as a fraction of 8.",
    ],
    difficulty: 2,
    topicSlug: "fractions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-02",
    question: "A shirt originally costs $40. It is on sale for 25% off. What is the sale price?",
    format: "MULTIPLE_CHOICE",
    choices: ["$30", "$25", "$35", "$10", "$32"],
    answer: "A",
    solution: "25% of $40 is $10, so the sale price is $40 - $10 = $30.",
    hints: [
      "First find 25% of the original price.",
      "Subtract that discount amount from $40.",
    ],
    difficulty: 2,
    topicSlug: "percentages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-03",
    question:
      "In a fruit basket, the ratio of apples to oranges is 4:3. If there are 12 apples, how many oranges are there?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "8", "16", "12", "7"],
    answer: "A",
    solution: "Since 12 apples correspond to 4 parts, each part is 12/4 = 3. Oranges are 3 parts, so 3 × 3 = 9.",
    hints: [
      "Figure out how many fruits one \"part\" of the ratio represents.",
      "Multiply that part size by the number of parts for oranges.",
    ],
    difficulty: 2,
    topicSlug: "ratios-proportions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-04",
    question:
      "Maria scored 82, 88, and 90 on three tests. What score must she earn on a fourth test so that her average over all four tests is exactly 88?",
    format: "MULTIPLE_CHOICE",
    choices: ["92", "90", "88", "94", "96"],
    answer: "A",
    solution: "Four tests averaging 88 requires a total of 88 × 4 = 352. Her first three tests total 82 + 88 + 90 = 260, so she needs 352 - 260 = 92.",
    hints: [
      "Multiply the target average by 4 to get the required total of all four scores.",
      "Subtract her current total from that required total.",
    ],
    difficulty: 2,
    topicSlug: "averages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-05",
    question: "What is the sum of the first 10 positive even integers?",
    format: "MULTIPLE_CHOICE",
    choices: ["110", "100", "90", "120", "55"],
    answer: "A",
    solution: "The first 10 positive even integers are 2, 4, ..., 20, which equal 2(1 + 2 + ... + 10) = 2 × 55 = 110.",
    hints: [
      "Factor a 2 out of every term in the sum.",
      "The sum of the first 10 positive integers is 55.",
    ],
    difficulty: 2,
    topicSlug: "number-properties",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-06",
    question:
      "A train travels 180 miles in 3 hours at a constant speed. At this same speed, how many miles does it travel in 5 hours?",
    format: "MULTIPLE_CHOICE",
    choices: ["300", "280", "240", "360", "250"],
    answer: "A",
    solution: "The speed is 180 / 3 = 60 miles per hour. In 5 hours it travels 60 × 5 = 300 miles.",
    hints: [
      "Find the train's speed in miles per hour first.",
      "Multiply that speed by the new number of hours.",
    ],
    difficulty: 3,
    topicSlug: "rates",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-07",
    question: "Three times a number, decreased by 7, equals 20. What is the number?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "9", "13", "4", "11"],
    answer: "B",
    solution: "Let the number be x. Then 3x - 7 = 20, so 3x = 27 and x = 9.",
    hints: [
      "Translate the sentence into the equation 3x - 7 = 20.",
      "Add 7 to both sides before dividing by 3.",
    ],
    difficulty: 3,
    topicSlug: "linear-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-08",
    question:
      "Two angles are supplementary. One angle is 30 degrees more than twice the other. What is the measure, in degrees, of the smaller angle?",
    format: "MULTIPLE_CHOICE",
    choices: ["50", "40", "60", "70", "45"],
    answer: "A",
    solution: "Let the smaller angle be x. Then x + (2x + 30) = 180, so 3x = 150 and x = 50. (The other angle is 130.)",
    hints: [
      "Supplementary angles sum to 180 degrees.",
      "Write the larger angle in terms of x and set the two angles' sum equal to 180.",
    ],
    difficulty: 3,
    topicSlug: "angles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-09",
    question:
      "A sandwich shop offers 3 types of bread, 4 types of filling, and 2 types of cheese. How many different sandwiches can be made using exactly one bread, one filling, and one cheese?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "9", "20", "12", "30"],
    answer: "A",
    solution: "By the multiplication principle, the number of sandwiches is 3 × 4 × 2 = 24.",
    hints: [
      "Each choice (bread, filling, cheese) is made independently.",
      "Multiply the number of options for each category together.",
    ],
    difficulty: 3,
    topicSlug: "counting-principles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-10",
    question: "How many positive divisors does 36 have?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "6", "8", "12", "10"],
    answer: "A",
    solution: "36 = 2^2 × 3^2, so the number of divisors is (2+1)(2+1) = 9.",
    hints: [
      "Write the prime factorization of 36.",
      "Add 1 to each exponent in the factorization, then multiply the results.",
    ],
    difficulty: 3,
    topicSlug: "divisibility",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-11",
    question:
      "A rectangular garden measures 12 feet by 8 feet. A path of uniform width 2 feet surrounds the garden on the outside. What is the area of the path, in square feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["96", "88", "80", "100", "112"],
    answer: "A",
    solution:
      "Including the path, the outer rectangle measures (12+4) by (8+4), i.e. 16 by 12, for an area of 192. The garden itself has area 12 × 8 = 96. The path's area is 192 - 96 = 96.",
    hints: [
      "The path adds 2 feet to every side, so it adds 4 feet total to each dimension.",
      "Find the area of the larger outer rectangle and subtract the garden's area.",
    ],
    difficulty: 4,
    topicSlug: "area-volume",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-12",
    question: "The first term of an arithmetic sequence is 5 and the common difference is 4. What is the 15th term?",
    format: "MULTIPLE_CHOICE",
    choices: ["61", "65", "56", "60", "64"],
    answer: "A",
    solution: "The 15th term is 14 steps from the first term: 5 + 14 × 4 = 5 + 56 = 61.",
    hints: [
      "The nth term of an arithmetic sequence is the first term plus (n-1) times the common difference.",
      "Be careful: the 15th term is 14 steps away from the first term, not 15.",
    ],
    difficulty: 4,
    topicSlug: "sequences",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-13",
    question:
      "The lengths of two sides of a triangle are 7 and 15. Which of the following cannot be the length of the third side?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "14", "20", "22", "16"],
    answer: "D",
    solution:
      "By the triangle inequality, the third side c must satisfy 15 - 7 < c < 15 + 7, i.e. 8 < c < 22. Since 22 is not strictly less than 22, it cannot be the third side.",
    hints: [
      "The triangle inequality says the third side must be less than the sum and more than the difference of the other two sides.",
      "Check each choice against the strict inequality 8 < c < 22.",
    ],
    difficulty: 4,
    topicSlug: "triangles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-14",
    question: "What is the sum of all prime numbers between 10 and 30?",
    format: "MULTIPLE_CHOICE",
    choices: ["112", "100", "120", "108", "116"],
    answer: "A",
    solution:
      "The primes between 10 and 30 are 11, 13, 17, 19, 23, and 29. Their sum is 11+13+17+19+23+29 = 112.",
    hints: [
      "List every prime number strictly between 10 and 30.",
      "Add the six primes together carefully.",
    ],
    difficulty: 4,
    topicSlug: "primes",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-15",
    question: "A committee of 3 people is to be chosen from a group of 8 people. How many different committees are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["56", "24", "336", "48", "64"],
    answer: "A",
    solution: "Since order does not matter, the number of committees is C(8,3) = (8×7×6)/(3×2×1) = 56.",
    hints: [
      "Since the committee is unordered, this is a combination, not a permutation.",
      "Compute C(8,3) using the combination formula.",
    ],
    difficulty: 4,
    topicSlug: "combinations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-16",
    question:
      "A rectangle has a perimeter of 46 and a length that is 5 more than its width. What is the area of the rectangle?",
    format: "MULTIPLE_CHOICE",
    choices: ["126", "130", "120", "132", "117"],
    answer: "A",
    solution:
      "Let the width be w, so the length is w + 5. The perimeter gives 2(w + (w+5)) = 46, so 2w + 5 = 23 and w = 9. The length is 14, and the area is 9 × 14 = 126.",
    hints: [
      "Let the width be w and write the length in terms of w.",
      "Use the perimeter formula 2(length + width) = 46 to solve for w first.",
    ],
    difficulty: 5,
    topicSlug: "quadrilaterals",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-17",
    question: "What is the remainder when 2^20 is divided by 7?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "1", "2", "6", "3"],
    answer: "A",
    solution:
      "Since 2^3 = 8 ≡ 1 (mod 7), write 20 = 3×6 + 2, so 2^20 = (2^3)^6 × 2^2 ≡ 1^6 × 4 ≡ 4 (mod 7).",
    hints: [
      "Look for a small power of 2 that is congruent to 1 modulo 7.",
      "Write the exponent 20 in terms of that small power plus a remainder.",
    ],
    difficulty: 5,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-18",
    question: "A circle has a circumference of 18π. What is the area of the circle?",
    format: "MULTIPLE_CHOICE",
    choices: ["81π", "90π", "162π", "36π", "324π"],
    answer: "A",
    solution: "From C = 2πr = 18π, the radius is r = 9. The area is πr^2 = π(9^2) = 81π.",
    hints: [
      "Use the circumference formula to find the radius first.",
      "Substitute that radius into the area formula πr^2.",
    ],
    difficulty: 5,
    topicSlug: "circles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-19",
    question:
      "A bag contains 4 red marbles, 5 blue marbles, and 3 green marbles. One marble is drawn at random. What is the probability that it is not blue?",
    format: "MULTIPLE_CHOICE",
    choices: ["7/12", "5/12", "1/3", "3/4", "2/3"],
    answer: "A",
    solution: "There are 12 marbles total, of which 12 - 5 = 7 are not blue. The probability is 7/12.",
    hints: [
      "Find the total number of marbles and the number that are not blue.",
      "Write the probability as (not blue) / (total).",
    ],
    difficulty: 5,
    topicSlug: "basic-probability",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-20",
    question:
      "Alice, Ben, and Cara each play a different sport: soccer, tennis, or swimming. Alice does not play soccer. Ben does not play tennis or swimming. Cara does not play swimming. What sport does Alice play?",
    format: "MULTIPLE_CHOICE",
    choices: ["Swimming", "Soccer", "Tennis", "Cannot be determined", "Soccer and tennis"],
    answer: "A",
    solution:
      "Since Ben plays neither tennis nor swimming, Ben must play soccer. Since Alice does not play soccer and Cara does not play swimming, Cara must play tennis, leaving swimming for Alice.",
    hints: [
      "Start with the person who has the most restrictions — figure out Ben's sport first.",
      "Once Ben's sport is fixed, use Cara's restriction to place the remaining two sports.",
    ],
    difficulty: 5,
    topicSlug: "logical-puzzles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-21",
    question: "If 3^(x+2) = 81, what is the value of x?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "4", "3", "6", "1"],
    answer: "A",
    solution: "Since 81 = 3^4, we need x + 2 = 4, so x = 2.",
    hints: [
      "Rewrite 81 as a power of 3.",
      "Once both sides share a base, set the exponents equal.",
    ],
    difficulty: 5,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-22",
    question: "The sum of two numbers is 34 and their difference is 8. What is the product of the two numbers?",
    format: "MULTIPLE_CHOICE",
    choices: ["273", "264", "280", "252", "289"],
    answer: "A",
    solution:
      "Let the numbers be x and y with x + y = 34 and x - y = 8. Adding gives 2x = 42, so x = 21 and y = 13. Their product is 21 × 13 = 273.",
    hints: [
      "Add the two given equations to solve for one variable directly.",
      "Once you have both numbers, multiply them.",
    ],
    difficulty: 6,
    topicSlug: "systems-of-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-23",
    question:
      "Triangle PQR is similar to triangle STU, with side PQ corresponding to side ST. If PQ = 6, ST = 9, and the area of triangle PQR is 24, what is the area of triangle STU?",
    format: "MULTIPLE_CHOICE",
    choices: ["54", "36", "48", "60", "45"],
    answer: "A",
    solution:
      "The similarity ratio of sides is 9/6 = 1.5, so the ratio of areas is 1.5^2 = 2.25. The area of triangle STU is 24 × 2.25 = 54.",
    hints: [
      "Find the ratio of corresponding sides first.",
      "The ratio of areas of similar figures is the square of the ratio of corresponding sides.",
    ],
    difficulty: 6,
    topicSlug: "similarity-congruence",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-24",
    question:
      "What is the minimum number of people needed in a room to guarantee that at least 3 of them were born in the same month?",
    format: "MULTIPLE_CHOICE",
    choices: ["25", "24", "13", "36", "26"],
    answer: "A",
    solution:
      "By the pigeonhole principle, with 12 months, 2 × 12 = 24 people could have at most 2 per month with none tripled up. One more person, 25 total, forces some month to have 3.",
    hints: [
      "Think about the worst case: how many people can you place with at most 2 per month?",
      "Add one more person to that worst-case total to force a third match.",
    ],
    difficulty: 6,
    topicSlug: "pigeonhole",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-25",
    question: "A line passes through the points (2, 3) and (6, 11). What is the y-intercept of this line?",
    format: "MULTIPLE_CHOICE",
    choices: ["-1", "1", "-2", "0", "2"],
    answer: "A",
    solution:
      "The slope is (11-3)/(6-2) = 8/4 = 2. Using point-slope form with (2,3): y - 3 = 2(x - 2), so y = 2x - 1. The y-intercept is -1.",
    hints: [
      "Find the slope between the two given points first.",
      "Use the slope and one point to write the line's equation, then set x = 0.",
    ],
    difficulty: 6,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-26",
    question:
      "A sequence is defined by a1 = 2, a2 = 5, and for n ≥ 3, a_n = a_(n-1) + a_(n-2). What is a7?",
    format: "MULTIPLE_CHOICE",
    choices: ["50", "49", "45", "55", "48"],
    answer: "A",
    solution:
      "Computing term by term: a3 = 7, a4 = 12, a5 = 19, a6 = 31, a7 = a6 + a5 = 31 + 19 = 50.",
    hints: [
      "Compute the sequence one term at a time using the recursive rule.",
      "Each new term is the sum of the two terms immediately before it.",
    ],
    difficulty: 6,
    topicSlug: "recursion-in-counting",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-27",
    question:
      "In a class of 30 students, 18 take Spanish, 15 take French, and 8 take both languages. How many students take neither language?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "7", "8", "10", "3"],
    answer: "A",
    solution:
      "By inclusion-exclusion, the number taking at least one language is 18 + 15 - 8 = 25. The number taking neither is 30 - 25 = 5.",
    hints: [
      "Use inclusion-exclusion to find how many students take at least one of the two languages.",
      "Subtract that count from the total class size.",
    ],
    difficulty: 6,
    topicSlug: "inclusion-exclusion",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-28",
    question:
      "The equation x^2 - 9x + k = 0 has two (not necessarily distinct) positive integer roots. What is the largest possible value of k?",
    format: "MULTIPLE_CHOICE",
    choices: ["20", "18", "14", "8", "16"],
    answer: "A",
    solution:
      "By Vieta's formulas, the two roots sum to 9 and their product is k. To maximize the product of two positive integers with a fixed sum of 9, choose them as close together as possible: 4 and 5, giving k = 20.",
    hints: [
      "Use Vieta's formulas to relate the roots' sum and product to the coefficients.",
      "For a fixed sum, the product of two positive integers is maximized when they are as close together as possible.",
    ],
    difficulty: 7,
    topicSlug: "quadratics",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-29",
    question: "How many ordered pairs of positive integers (x, y) satisfy 4x + 3y = 60?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "5", "3", "6", "15"],
    answer: "A",
    solution:
      "Solving for y: y = (60 - 4x)/3, which requires 60 - 4x to be a positive multiple of 3. Since 60 is already divisible by 3, x must be a multiple of 3. Positive multiples of 3 with 4x < 60 are x = 3, 6, 9, 12, each giving a positive integer y (16, 12, 8, 4). That is 4 ordered pairs.",
    hints: [
      "Solve for y in terms of x, then determine which values of x make y a positive integer.",
      "x must be a multiple of 3 for 60 - 4x to be divisible by 3 — count how many such x keep y positive.",
    ],
    difficulty: 7,
    topicSlug: "diophantine-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-30",
    question:
      "Two players, Alex and Blake, take turns removing 1, 2, or 3 stones from a pile of 17 stones, with Alex moving first. The player who removes the last stone wins. If both players play optimally, who wins, and how many stones does the winner remove on their very first move?",
    format: "MULTIPLE_CHOICE",
    choices: [
      "Alex, by removing 1 stone",
      "Alex, by removing 3 stones",
      "Blake, by removing 2 stones",
      "Alex, by removing 2 stones",
      "Blake, no matter what Alex does",
    ],
    answer: "A",
    solution:
      "Since each move removes 1 to 3 stones, a pile size that is a multiple of 4 is always a losing position for the player about to move, because whatever they remove (1, 2, or 3), the opponent can restore the pile to the next lower multiple of 4. Since 17 is 1 more than the multiple of 4 equal to 16, Alex should remove 1 stone, leaving 16 for Blake — a losing position. Alex wins by removing 1 stone first.",
    hints: [
      "Think about which pile sizes are 'safe' to hand to your opponent — sizes where any move they make can be countered back to another safe size.",
      "Multiples of 4 are losing positions for the player about to move, since 1, 2, or 3 removed can always be answered to return to the next lower multiple of 4.",
    ],
    difficulty: 7,
    topicSlug: "games-and-strategies",
    competitionSlug: "amc8",
  },

{
    slug: "amc8-31",
    question:
      "A baker makes 150 cookies and packs them into boxes of 8 cookies each, filling as many full boxes as possible. How many cookies are left over?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "4", "8", "2", "0"],
    answer: "A",
    solution:
      "150 ÷ 8 = 18 remainder 6, since 8 × 18 = 144 and 150 − 144 = 6.",
    hints: [
      "Find the largest multiple of 8 that is at most 150.",
      "Subtract that multiple from 150.",
    ],
    difficulty: 2,
    topicSlug: "arithmetic",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-32",
    question: "What is 2/3 + 1/6?",
    format: "MULTIPLE_CHOICE",
    choices: ["5/9", "1", "5/6", "1/2", "3/9"],
    answer: "C",
    solution:
      "Convert 2/3 to sixths: 2/3 = 4/6. Then 4/6 + 1/6 = 5/6.",
    hints: [
      "Find a common denominator of 6.",
      "Add the numerators once the denominators match.",
    ],
    difficulty: 2,
    topicSlug: "fractions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-33",
    question: "A store marks up a $50 item by 20% to set its price. What is the new price?",
    format: "MULTIPLE_CHOICE",
    choices: ["$60", "$70", "$55", "$40", "$65"],
    answer: "A",
    solution: "20% of $50 is $10, so the new price is $50 + $10 = $60.",
    hints: [
      "Find 20% of $50 first.",
      "Add that amount to the original price.",
    ],
    difficulty: 2,
    topicSlug: "percentages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-34",
    question:
      "A recipe uses flour and sugar in the ratio 5:2. If a baker uses 20 cups of flour, how many cups of sugar does she use?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "8", "10", "4", "12"],
    answer: "B",
    solution: "Since 20 cups of flour is 4 times 5, sugar is 4 times 2 = 8 cups.",
    hints: [
      "Find how many times larger 20 is than 5.",
      "Multiply that factor by 2 to get the sugar amount.",
    ],
    difficulty: 2,
    topicSlug: "ratios-proportions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-35",
    question:
      "The average of four numbers is 15. Three of the numbers are 10, 12, and 18. What is the fourth number?",
    format: "MULTIPLE_CHOICE",
    choices: ["20", "15", "24", "18", "22"],
    answer: "A",
    solution:
      "Four numbers averaging 15 sum to 60. The first three sum to 10 + 12 + 18 = 40, so the fourth is 60 − 40 = 20.",
    hints: [
      "Multiply the average by 4 to find the total sum.",
      "Subtract the sum of the known numbers.",
    ],
    difficulty: 2,
    topicSlug: "averages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-36",
    question: "What is the units digit of 7 × 8 × 9?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "2", "6", "8", "0"],
    answer: "A",
    solution: "7 × 8 = 56, and 56 × 9 = 504. The units digit is 4.",
    hints: [
      "Multiply the numbers step by step.",
      "Only the final units digit matters for the answer.",
    ],
    difficulty: 2,
    topicSlug: "number-properties",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-37",
    question: "A square has a perimeter of 24 inches. What is the area of the square, in square inches?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "64", "30", "36", "48"],
    answer: "D",
    solution: "The perimeter 24 gives a side length of 24/4 = 6. The area is 6 × 6 = 36.",
    hints: [
      "Divide the perimeter by 4 to find the side length.",
      "Square the side length to get the area.",
    ],
    difficulty: 2,
    topicSlug: "geometry",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-38",
    question: "Two angles of a triangle measure 50 degrees and 65 degrees. What is the measure of the third angle?",
    format: "MULTIPLE_CHOICE",
    choices: ["55", "60", "75", "65", "70"],
    answer: "D",
    solution: "The angles of a triangle sum to 180 degrees, so the third angle is 180 − 50 − 65 = 65.",
    hints: [
      "Recall that a triangle's angles sum to 180 degrees.",
      "Subtract the two given angles from 180.",
    ],
    difficulty: 2,
    topicSlug: "angles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-39",
    question: "Which of the following numbers is prime?",
    format: "MULTIPLE_CHOICE",
    choices: ["87", "51", "57", "97", "91"],
    answer: "D",
    solution:
      "51 = 3 × 17, 57 = 3 × 19, 87 = 3 × 29, and 91 = 7 × 13 are all composite. 97 has no divisors other than 1 and itself, so it is prime.",
    hints: [
      "Check each option for small prime factors like 3, 7, and 13.",
      "97 is not divisible by any prime up to its square root (about 9.8).",
    ],
    difficulty: 2,
    topicSlug: "primes",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-40",
    question: "What is the smallest positive integer that is divisible by both 6 and 8?",
    format: "MULTIPLE_CHOICE",
    choices: ["48", "36", "16", "12", "24"],
    answer: "E",
    solution:
      "The least common multiple of 6 and 8 is 24, since 24 = 6 × 4 = 8 × 3 and no smaller positive integer works.",
    hints: [
      "List multiples of 8 and check which is also a multiple of 6.",
      "The answer is the least common multiple of 6 and 8.",
    ],
    difficulty: 2,
    topicSlug: "divisibility",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-41",
    question: "Compute 8 + 6 × 5 − 4.",
    format: "MULTIPLE_CHOICE",
    choices: ["66", "34", "30", "38", "54"],
    answer: "B",
    solution: "Following order of operations, first compute 6 × 5 = 30. Then 8 + 30 − 4 = 34.",
    hints: [
      "Multiplication happens before addition and subtraction.",
      "Compute 6 × 5 first, then add 8 and subtract 4.",
    ],
    difficulty: 2,
    topicSlug: "arithmetic",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-42",
    question: "Which of the following fractions is closest to 1/2?",
    format: "MULTIPLE_CHOICE",
    choices: ["3/8", "7/15", "5/9", "2/5", "4/7"],
    answer: "B",
    solution:
      "Converting to decimals: 3/8 = 0.375, 5/9 ≈ 0.556, 4/7 ≈ 0.571, 2/5 = 0.4, 7/15 ≈ 0.467. The value closest to 0.5 is 7/15, which differs from 1/2 by only 1/30.",
    hints: [
      "Convert each fraction to a decimal to compare.",
      "Find which decimal is nearest to 0.5.",
    ],
    difficulty: 2,
    topicSlug: "fractions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-43",
    question: "A printer prints 45 pages in 3 minutes. At this rate, how many pages does it print in 8 minutes?",
    format: "MULTIPLE_CHOICE",
    choices: ["90", "110", "120", "135", "100"],
    answer: "C",
    solution: "The printer's rate is 45/3 = 15 pages per minute. In 8 minutes it prints 15 × 8 = 120 pages.",
    hints: [
      "Find the printer's rate in pages per minute.",
      "Multiply that rate by 8.",
    ],
    difficulty: 2,
    topicSlug: "rates",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-44",
    question:
      "A license plate consists of 2 letters followed by 3 digits. How many license plates are possible if letters and digits can repeat?",
    format: "MULTIPLE_CHOICE",
    choices: ["260,000", "1,000,000", "676,000", "67,600", "520,000"],
    answer: "C",
    solution:
      "There are 26 choices for each letter and 10 choices for each digit, so the total is 26 × 26 × 10 × 10 × 10 = 676,000.",
    hints: [
      "Multiply the number of choices for each position together.",
      "There are 26 options for each letter slot and 10 for each digit slot.",
    ],
    difficulty: 2,
    topicSlug: "counting-principles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-45",
    question: "A rectangle has length 9 and width 4. What is its perimeter?",
    format: "MULTIPLE_CHOICE",
    choices: ["36", "52", "26", "18", "13"],
    answer: "C",
    solution: "Perimeter = 2(length + width) = 2(9 + 4) = 26.",
    hints: [
      "Add the length and width first.",
      "Double that sum to get the perimeter.",
    ],
    difficulty: 2,
    topicSlug: "quadrilaterals",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-46",
    question: "What is the next number in the pattern 2, 6, 18, 54, ...?",
    format: "MULTIPLE_CHOICE",
    choices: ["144", "216", "108", "81", "162"],
    answer: "E",
    solution:
      "Each term is 3 times the previous term (2×3=6, 6×3=18, 18×3=54), so the next term is 54 × 3 = 162.",
    hints: [
      "Find the ratio between consecutive terms.",
      "Multiply the last term by that ratio.",
    ],
    difficulty: 2,
    topicSlug: "number-patterns",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-47",
    question: "In a class of 25 students, 40% are boys. How many girls are in the class?",
    format: "MULTIPLE_CHOICE",
    choices: ["13", "14", "10", "15", "12"],
    answer: "D",
    solution: "40% of 25 is 10 boys, so the remaining 25 − 10 = 15 students are girls.",
    hints: [
      "Find 40% of 25 to get the number of boys.",
      "Subtract that from the total to find the girls.",
    ],
    difficulty: 2,
    topicSlug: "percentages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-48",
    question: "An isosceles triangle has a base angle of 70 degrees. What is the measure of the vertex angle?",
    format: "MULTIPLE_CHOICE",
    choices: ["70", "55", "40", "110", "35"],
    answer: "C",
    solution: "Both base angles are 70 degrees, summing to 140. The vertex angle is 180 − 140 = 40 degrees.",
    hints: [
      "In an isosceles triangle, the two base angles are equal.",
      "Subtract twice the base angle from 180.",
    ],
    difficulty: 2,
    topicSlug: "triangles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-49",
    question: "How many even integers are there between 11 and 40, inclusive?",
    format: "MULTIPLE_CHOICE",
    choices: ["13", "20", "14", "15", "16"],
    answer: "D",
    solution: "The even integers from 12 to 40 are 12, 14, ..., 40. There are (40 − 12)/2 + 1 = 15 of them.",
    hints: [
      "List the smallest and largest even integers in the range.",
      "Use (last − first)/2 + 1 to count evenly spaced terms.",
    ],
    difficulty: 2,
    topicSlug: "integer-properties",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-50",
    question: "A standard six-sided die is rolled once. What is the probability that the result is a multiple of 3?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/6", "1/2", "1/3", "2/3", "1/4"],
    answer: "C",
    solution: "There are two multiples of 3 among 1–6, namely 3 and 6, so the probability is 2/6 = 1/3.",
    hints: [
      "List the outcomes from 1 to 6 that are multiples of 3.",
      "Divide the count of favorable outcomes by 6.",
    ],
    difficulty: 2,
    topicSlug: "basic-probability",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-51",
    question: "Five more than twice a number is 27. What is the number?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "11", "12", "16", "10"],
    answer: "B",
    solution: "2x + 5 = 27 gives 2x = 22, so x = 11.",
    hints: [
      "Translate to the equation 2x + 5 = 27.",
      "Subtract 5, then divide by 2.",
    ],
    difficulty: 3,
    topicSlug: "linear-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-52",
    question:
      "In a bag of marbles, red to blue marbles are in ratio 3:5, and there are 48 marbles total. How many blue marbles are there?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "30", "18", "36", "15"],
    answer: "B",
    solution:
      "There are 3 + 5 = 8 parts total, so each part is 48/8 = 6 marbles. Blue marbles are 5 × 6 = 30.",
    hints: [
      "Add the ratio parts to find the total number of parts.",
      "Multiply the size of one part by the blue ratio number.",
    ],
    difficulty: 3,
    topicSlug: "ratios-proportions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-53",
    question: "A rectangular box has dimensions 4 by 5 by 6. What is its volume?",
    format: "MULTIPLE_CHOICE",
    choices: ["120", "60", "90", "150", "100"],
    answer: "A",
    solution: "Volume = length × width × height = 4 × 5 × 6 = 120.",
    hints: [
      "Multiply all three dimensions together.",
      "Order does not matter: 4 × 5 × 6 is the same as any rearrangement.",
    ],
    difficulty: 3,
    topicSlug: "area-volume",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-54",
    question: "An arithmetic sequence begins 4, 9, 14, 19, .... What is the 10th term?",
    format: "MULTIPLE_CHOICE",
    choices: ["49", "54", "44", "45", "50"],
    answer: "A",
    solution:
      "The 10th term is 4 + 9 × 5 = 4 + 45 = 49, since the 10th term is 9 steps past the first.",
    hints: [
      "The nth term equals the first term plus (n − 1) times the common difference.",
      "Here the common difference is 5.",
    ],
    difficulty: 3,
    topicSlug: "sequences",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-55",
    question: "What is the sum of all positive divisors of 28?",
    format: "MULTIPLE_CHOICE",
    choices: ["42", "58", "56", "55", "50"],
    answer: "C",
    solution: "The divisors of 28 are 1, 2, 4, 7, 14, and 28, which sum to 56.",
    hints: [
      "List every divisor of 28 from 1 up to 28 itself.",
      "Add all the divisors together.",
    ],
    difficulty: 3,
    topicSlug: "divisibility",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-56",
    question: "In a parallelogram, one angle measures 62 degrees. What is the measure of an angle adjacent to it?",
    format: "MULTIPLE_CHOICE",
    choices: ["128", "90", "118", "62", "112"],
    answer: "C",
    solution: "Consecutive angles in a parallelogram are supplementary, so the adjacent angle is 180 − 62 = 118 degrees.",
    hints: [
      "Adjacent angles in a parallelogram add up to 180 degrees.",
      "Subtract the given angle from 180.",
    ],
    difficulty: 3,
    topicSlug: "angles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-57",
    question: "The average of five consecutive integers is 21. What is the largest of the five integers?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "23", "21", "25", "22"],
    answer: "B",
    solution:
      "For five consecutive integers, the average equals the middle (third) term, so the integers are 19, 20, 21, 22, 23. The largest is 23.",
    hints: [
      "The average of consecutive integers equals the middle term.",
      "List the five consecutive integers centered on 21.",
    ],
    difficulty: 3,
    topicSlug: "averages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-58",
    question:
      "A pizza shop offers 6 toppings. How many different 2-topping pizzas can be made, where order doesn't matter and toppings aren't repeated?",
    format: "MULTIPLE_CHOICE",
    choices: ["15", "20", "12", "30", "10"],
    answer: "A",
    solution: "C(6,2) = (6 × 5)/2 = 15.",
    hints: [
      "Since order doesn't matter, use combinations, not permutations.",
      "Compute C(6,2) = (6 × 5)/(2 × 1).",
    ],
    difficulty: 3,
    topicSlug: "combinations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-59",
    question: "What is the sum of the digits of 4,987?",
    format: "MULTIPLE_CHOICE",
    choices: ["26", "29", "28", "30", "27"],
    answer: "C",
    solution: "4 + 9 + 8 + 7 = 28.",
    hints: [
      "Add each digit of the number individually.",
      "Double-check the addition: 4+9=13, 13+8=21, 21+7=28.",
    ],
    difficulty: 3,
    topicSlug: "number-properties",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-60",
    question: "A circle has a radius of 7. What is its circumference, in terms of π?",
    format: "MULTIPLE_CHOICE",
    choices: ["28π", "7π", "49π", "14π", "21π"],
    answer: "D",
    solution: "Circumference = 2πr = 2π(7) = 14π.",
    hints: [
      "Use the formula C = 2πr.",
      "Substitute r = 7 directly.",
    ],
    difficulty: 3,
    topicSlug: "circles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-61",
    question:
      "A tank is 3/4 full of water. After removing 15 gallons, it is 1/2 full. What is the tank's total capacity, in gallons?",
    format: "MULTIPLE_CHOICE",
    choices: ["30", "90", "60", "45", "75"],
    answer: "C",
    solution:
      "Let the capacity be T. Then (3/4)T − 15 = (1/2)T, so (1/4)T = 15, giving T = 60.",
    hints: [
      "Set up an equation relating the two fractional amounts and the 15 gallons removed.",
      "The difference between 3/4 and 1/2 of the tank is exactly 15 gallons.",
    ],
    difficulty: 3,
    topicSlug: "fractions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-62",
    question:
      "Two hoses fill a pool. Hose A alone fills it in 6 hours; Hose B alone fills it in 3 hours. How many hours does it take both hoses working together to fill the pool?",
    format: "MULTIPLE_CHOICE",
    choices: ["1.5", "3", "2.5", "2", "4.5"],
    answer: "D",
    solution:
      "Hose A fills 1/6 of the pool per hour and Hose B fills 1/3 = 2/6 per hour. Together they fill 3/6 = 1/2 per hour, so it takes 2 hours to fill the whole pool.",
    hints: [
      "Add the two hoses' rates (pool per hour) together.",
      "The time to finish is 1 divided by the combined rate.",
    ],
    difficulty: 3,
    topicSlug: "rates",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-63",
    question: "A right triangle has legs of length 9 and 12. What is the length of the hypotenuse?",
    format: "MULTIPLE_CHOICE",
    choices: ["16", "13", "21", "14", "15"],
    answer: "E",
    solution: "By the Pythagorean theorem, the hypotenuse is √(9² + 12²) = √(81 + 144) = √225 = 15.",
    hints: [
      "Apply the Pythagorean theorem a² + b² = c².",
      "9-12-15 is a scaled-up 3-4-5 triangle.",
    ],
    difficulty: 3,
    topicSlug: "triangles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-64",
    question: "What is the remainder when 100 is divided by 7?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "1", "3", "4", "5"],
    answer: "A",
    solution: "7 × 14 = 98, and 100 − 98 = 2, so the remainder is 2.",
    hints: [
      "Find the largest multiple of 7 that is at most 100.",
      "Subtract that multiple from 100.",
    ],
    difficulty: 3,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-65",
    question:
      "A population of 400 increases by 15% one year and then decreases by 10% the next year. What is the population after these two changes?",
    format: "MULTIPLE_CHOICE",
    choices: ["414", "400", "420", "410", "405"],
    answer: "A",
    solution:
      "After a 15% increase, the population is 400 × 1.15 = 460. After a 10% decrease, it becomes 460 × 0.9 = 414.",
    hints: [
      "Apply each percent change one at a time, in order.",
      "Multiply by 1.15 for the increase and by 0.9 for the decrease.",
    ],
    difficulty: 3,
    topicSlug: "percentages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-66",
    question: "What is the sum of the interior angles of a hexagon?",
    format: "MULTIPLE_CHOICE",
    choices: ["720°", "540°", "600°", "1080°", "900°"],
    answer: "A",
    solution:
      "The sum of interior angles of an n-gon is (n − 2) × 180. For a hexagon, n = 6, giving (6 − 2) × 180 = 720°.",
    hints: [
      "Use the formula (n − 2) × 180 for a polygon's interior angle sum.",
      "A hexagon has 6 sides.",
    ],
    difficulty: 3,
    topicSlug: "polygons",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-67",
    question: "How many 3-digit numbers (100 to 999) have all three digits odd?",
    format: "MULTIPLE_CHOICE",
    choices: ["243", "100", "120", "150", "125"],
    answer: "E",
    solution:
      "Each of the three digits must be chosen from {1,3,5,7,9}, giving 5 options per digit. The total is 5 × 5 × 5 = 125.",
    hints: [
      "There are 5 odd digits to choose from: 1, 3, 5, 7, 9.",
      "Multiply the number of choices for each of the three digit positions.",
    ],
    difficulty: 3,
    topicSlug: "counting-principles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-68",
    question: "What is the greatest common factor of 84 and 126?",
    format: "MULTIPLE_CHOICE",
    choices: ["63", "14", "42", "28", "21"],
    answer: "C",
    solution:
      "84 = 2² × 3 × 7 and 126 = 2 × 3² × 7. The GCF takes the lowest power of each shared prime: 2 × 3 × 7 = 42.",
    hints: [
      "Write the prime factorization of each number.",
      "The GCF uses the smallest power of each common prime factor.",
    ],
    difficulty: 3,
    topicSlug: "factorization",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-69",
    question: "What is the distance between the points (1, 2) and (4, 6)?",
    format: "MULTIPLE_CHOICE",
    choices: ["7", "25", "6", "4", "5"],
    answer: "E",
    solution: "The distance is √((4−1)² + (6−2)²) = √(9+16) = √25 = 5.",
    hints: [
      "Use the distance formula √((x2−x1)² + (y2−y1)²).",
      "This is a 3-4-5 right triangle in disguise.",
    ],
    difficulty: 3,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-70",
    question:
      "Four friends — Dan, Ella, Finn, and Grace — each finished in a different place (1st through 4th) in a race. Dan finished before Ella. Finn finished 2nd. Grace did not finish 1st or 4th. Who finished 1st?",
    format: "MULTIPLE_CHOICE",
    choices: ["Dan", "Finn", "Ella", "Cannot be determined", "Grace"],
    answer: "A",
    solution:
      "Finn is 2nd. Since Grace is neither 1st nor 4th, and 2nd is taken, Grace must be 3rd. That leaves 1st and 4th for Dan and Ella, and since Dan finishes before Ella, Dan is 1st and Ella is 4th.",
    hints: [
      "Place Finn first since his position is given directly.",
      "Use Grace's restriction to find her position, then order Dan and Ella in what's left.",
    ],
    difficulty: 3,
    topicSlug: "logical-puzzles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-71",
    question: "The equation x² − 7x + 12 = 0 has two roots. What is the sum of the squares of the roots?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "37", "25", "13", "49"],
    answer: "C",
    solution:
      "By Vieta's formulas the roots sum to 7 and multiply to 12. The sum of squares is (sum)² − 2(product) = 49 − 24 = 25.",
    hints: [
      "Use Vieta's formulas to find the sum and product of the roots without solving for them individually.",
      "Recall that r² + s² = (r+s)² − 2rs.",
    ],
    difficulty: 4,
    topicSlug: "quadratics",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-72",
    question:
      "Twice a number plus three times another number is 26. The first number minus the second number is 3. What is the first number?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "9", "4", "7", "6"],
    answer: "D",
    solution:
      "From x − y = 3, x = y + 3. Substituting into 2x + 3y = 26 gives 2(y+3) + 3y = 26, so 5y + 6 = 26, y = 4, and x = 7.",
    hints: [
      "Solve the simpler equation for one variable in terms of the other.",
      "Substitute into the first equation and solve.",
    ],
    difficulty: 4,
    topicSlug: "systems-of-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-73",
    question: "A cylinder has radius 3 and height 10. What is its volume, in terms of π?",
    format: "MULTIPLE_CHOICE",
    choices: ["270π", "94π", "60π", "90π", "30π"],
    answer: "D",
    solution: "Volume = πr²h = π(3²)(10) = 90π.",
    hints: [
      "Use the formula V = πr²h.",
      "Square the radius before multiplying by height.",
    ],
    difficulty: 4,
    topicSlug: "area-volume",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-74",
    question:
      "Two similar rectangles have a ratio of corresponding sides of 2:5. If the smaller rectangle has area 12, what is the area of the larger rectangle?",
    format: "MULTIPLE_CHOICE",
    choices: ["75", "30", "60", "96", "48"],
    answer: "A",
    solution:
      "The ratio of areas is the square of the side ratio: (5/2)² = 25/4. The larger area is 12 × 25/4 = 75.",
    hints: [
      "Square the ratio of sides to get the ratio of areas.",
      "Multiply the smaller area by that squared ratio.",
    ],
    difficulty: 4,
    topicSlug: "similarity-congruence",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-75",
    question: "What is the smallest positive integer with exactly 6 positive divisors?",
    format: "MULTIPLE_CHOICE",
    choices: ["16", "18", "20", "24", "12"],
    answer: "E",
    solution:
      "Checking numbers in order, 12 = 2² × 3 has divisors 1, 2, 3, 4, 6, 12 — exactly 6 divisors — and no smaller number does (checking 1 through 11 gives divisor counts of at most 4).",
    hints: [
      "The number of divisors of p^a × q^b is (a+1)(b+1).",
      "Try small combinations like 2² × 3 and check the divisor count directly.",
    ],
    difficulty: 4,
    topicSlug: "number-theory",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-76",
    question: "What is the value of √50 + √18, in simplest radical form?",
    format: "MULTIPLE_CHOICE",
    choices: ["5√5", "8√6", "√68", "8√2", "68"],
    answer: "D",
    solution: "√50 = 5√2 and √18 = 3√2, so their sum is 5√2 + 3√2 = 8√2.",
    hints: [
      "Simplify each radical by factoring out the largest perfect square.",
      "Both simplify to a multiple of √2, so they can be combined.",
    ],
    difficulty: 4,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-77",
    question: "In how many ways can 5 different books be arranged in a row on a shelf?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "120", "60", "100", "20"],
    answer: "B",
    solution: "There are 5! = 120 ways to arrange 5 distinct books.",
    hints: [
      "This is a permutation of all 5 books.",
      "Compute 5 × 4 × 3 × 2 × 1.",
    ],
    difficulty: 4,
    topicSlug: "permutations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-78",
    question:
      "A circular pizza with diameter 16 inches is cut into 8 equal slices. What is the area of one slice, in terms of π?",
    format: "MULTIPLE_CHOICE",
    choices: ["64π", "8π", "16π", "4π", "32π"],
    answer: "B",
    solution:
      "The radius is 8, so the total area is π(8²) = 64π. One of 8 equal slices has area 64π/8 = 8π.",
    hints: [
      "Find the radius from the diameter, then the total area.",
      "Divide the total area by the number of slices.",
    ],
    difficulty: 4,
    topicSlug: "circles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-79",
    question: "How many positive integers less than 100 are divisible by both 4 and 6?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "12", "16", "7", "8"],
    answer: "E",
    solution:
      "Divisible by both 4 and 6 means divisible by lcm(4,6) = 12. The multiples of 12 below 100 are 12, 24, ..., 96, which is 8 numbers.",
    hints: [
      "Find the least common multiple of 4 and 6 first.",
      "Count the multiples of that LCM that are less than 100.",
    ],
    difficulty: 4,
    topicSlug: "divisibility",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-80",
    question: "The first term of a geometric sequence is 3 and the fourth term is 81. What is the common ratio?",
    format: "MULTIPLE_CHOICE",
    choices: ["27", "9", "3", "6", "4"],
    answer: "C",
    solution: "Since a4 = a1 × r³, we have 81 = 3r³, so r³ = 27 and r = 3.",
    hints: [
      "Use the formula for the nth term of a geometric sequence.",
      "Divide 81 by 3 to isolate r³, then take the cube root.",
    ],
    difficulty: 4,
    topicSlug: "sequences",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-81",
    question:
      "A bag contains 4 white and 6 black socks. Two socks are drawn at random without replacement. What is the probability both are white?",
    format: "MULTIPLE_CHOICE",
    choices: ["2/15", "1/3", "2/9", "4/25", "1/5"],
    answer: "A",
    solution:
      "P(first white) = 4/10. Given that, P(second white) = 3/9. Multiplying, the probability both are white is (4/10)(3/9) = 12/90 = 2/15.",
    hints: [
      "Multiply the probability of the first sock being white by the probability of the second also being white given the first was white.",
      "Remember the total number of socks decreases by one after the first draw.",
    ],
    difficulty: 4,
    topicSlug: "counting-probability",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-82",
    question:
      "In triangle ABC, angle A is twice angle B, and angle C is 20 degrees more than angle B. What is the measure of angle B?",
    format: "MULTIPLE_CHOICE",
    choices: ["30", "35", "50", "40", "45"],
    answer: "D",
    solution:
      "Let angle B = x. Then angle A = 2x and angle C = x + 20. Summing: x + 2x + (x+20) = 180, so 4x + 20 = 180, 4x = 160, x = 40.",
    hints: [
      "Express all three angles in terms of angle B.",
      "Set their sum equal to 180 and solve.",
    ],
    difficulty: 4,
    topicSlug: "triangles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-83",
    question: "A number increased by 40% equals 84. What is the original number?",
    format: "MULTIPLE_CHOICE",
    choices: ["50", "56", "67.2", "70", "60"],
    answer: "E",
    solution: "1.4x = 84 gives x = 84/1.4 = 60.",
    hints: [
      "Write the equation x + 0.4x = 84, i.e., 1.4x = 84.",
      "Divide 84 by 1.4.",
    ],
    difficulty: 4,
    topicSlug: "linear-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-84",
    question: "Today is a Tuesday. What day of the week will it be 100 days from today?",
    format: "MULTIPLE_CHOICE",
    choices: ["Friday", "Wednesday", "Thursday", "Saturday", "Monday"],
    answer: "C",
    solution:
      "Since 100 = 14×7 + 2, 100 days from now is the same as 2 days from now. Two days after Tuesday is Thursday.",
    hints: [
      "Find the remainder when 100 is divided by 7.",
      "Count that many days forward from Tuesday.",
    ],
    difficulty: 4,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-85",
    question:
      "Among 50 students, 28 play basketball and 22 play volleyball, and 10 play both. How many play neither sport?",
    format: "MULTIPLE_CHOICE",
    choices: ["8", "10", "18", "12", "6"],
    answer: "B",
    solution:
      "By inclusion-exclusion, students playing at least one sport number 28 + 22 − 10 = 40. Those playing neither are 50 − 40 = 10.",
    hints: [
      "Use inclusion-exclusion to find the number playing at least one sport.",
      "Subtract that from the total number of students.",
    ],
    difficulty: 4,
    topicSlug: "inclusion-exclusion",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-86",
    question: "A cube has a surface area of 96 square units. What is the volume of the cube?",
    format: "MULTIPLE_CHOICE",
    choices: ["96", "16", "48", "64", "32"],
    answer: "D",
    solution: "Surface area 6s² = 96 gives s² = 16, so s = 4. The volume is s³ = 64.",
    hints: [
      "Use the formula for a cube's surface area, 6s², to find the side length.",
      "Cube the side length to get the volume.",
    ],
    difficulty: 4,
    topicSlug: "three-d-geometry",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-87",
    question:
      "A tile pattern uses 3 tiles for stage 1, 7 tiles for stage 2, and 11 tiles for stage 3, increasing by the same amount each stage. How many tiles are needed for stage 8?",
    format: "MULTIPLE_CHOICE",
    choices: ["28", "27", "35", "31", "32"],
    answer: "D",
    solution:
      "The pattern increases by 4 tiles each stage, so stage n uses 3 + 4(n−1) tiles. Stage 8 uses 3 + 4(7) = 3 + 28 = 31.",
    hints: [
      "Find the common difference between consecutive stages.",
      "Use stage n = first term + (n−1) × common difference.",
    ],
    difficulty: 4,
    topicSlug: "patterns",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-88",
    question: "If 4(x − 3) = 2(x + 5), what is the value of x?",
    format: "MULTIPLE_CHOICE",
    choices: ["13", "9", "7", "8", "11"],
    answer: "E",
    solution:
      "Expanding gives 4x − 12 = 2x + 10. Subtracting 2x and adding 12 to both sides gives 2x = 22, so x = 11.",
    hints: [
      "Distribute both sides of the equation first.",
      "Collect the x terms on one side and constants on the other.",
    ],
    difficulty: 4,
    topicSlug: "algebra",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-89",
    question: "A trapezoid has parallel sides of length 8 and 14, and a height of 6. What is its area?",
    format: "MULTIPLE_CHOICE",
    choices: ["44", "72", "132", "66", "60"],
    answer: "D",
    solution: "Area = (1/2)(b1+b2)(h) = (1/2)(8+14)(6) = 11 × 6 = 66.",
    hints: [
      "Use the trapezoid area formula (1/2)(sum of parallel sides)(height).",
      "Add the two parallel sides before multiplying by half the height.",
    ],
    difficulty: 4,
    topicSlug: "quadrilaterals",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-90",
    question:
      "A drawer contains socks of 5 different colors. What is the minimum number of socks you must pull out (without looking) to guarantee at least 2 socks of the same color?",
    format: "MULTIPLE_CHOICE",
    choices: ["11", "5", "6", "10", "4"],
    answer: "C",
    solution:
      "In the worst case you could pull one sock of each of the 5 colors before getting a repeat, so 5 + 1 = 6 socks guarantees a matching pair.",
    hints: [
      "Think about the worst-case order in which socks could be pulled.",
      "Once all 5 colors have appeared once, the next sock must repeat a color.",
    ],
    difficulty: 4,
    topicSlug: "pigeonhole",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-91",
    question: "The roots of x² − 6x + c = 0 are both positive integers. What is the largest possible value of c?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "12", "8", "6", "5"],
    answer: "A",
    solution:
      "By Vieta's formulas, the roots sum to 6. For two positive integers with a fixed sum, the product is maximized when they're equal: 3 and 3, giving c = 3×3 = 9.",
    hints: [
      "Use Vieta's formulas to relate root sum and product to the coefficients.",
      "For a fixed sum, the product is largest when the two integers are as close together as possible.",
    ],
    difficulty: 5,
    topicSlug: "quadratics",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-92",
    question: "How many ordered pairs of positive integers (x, y) satisfy 5x + 2y = 40?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "8", "5", "2"],
    answer: "A",
    solution:
      "Solve for y: y = (40 − 5x)/2, which requires 40 − 5x to be even, so x must be even. Positive even x with 5x < 40 gives x = 2, 4, 6, yielding y = 15, 10, 5 respectively — all positive integers. That's 3 ordered pairs.",
    hints: [
      "Solve for y in terms of x and determine which values of x keep y a positive integer.",
      "x must be even for 40 − 5x to be divisible by 2; check which even x also keep y positive.",
    ],
    difficulty: 5,
    topicSlug: "diophantine-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-93",
    question:
      "In triangle ABC, D and E are midpoints of AB and AC respectively. If DE = 7, what is the length of BC?",
    format: "MULTIPLE_CHOICE",
    choices: ["28", "7", "14", "21", "10.5"],
    answer: "C",
    solution:
      "By the midsegment theorem, DE is parallel to BC and half its length, so BC = 2 × DE = 14.",
    hints: [
      "Recall the midsegment theorem: the segment joining two midpoints of a triangle is parallel to and half the length of the third side.",
      "Double DE to find BC.",
    ],
    difficulty: 5,
    topicSlug: "similarity-congruence",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-94",
    question:
      "Two players take turns removing 1 or 2 stones from a pile of 21 stones; Ana moves first. The player who removes the last stone wins. If both play optimally, who wins?",
    format: "MULTIPLE_CHOICE",
    choices: ["It depends on later moves", "Ana, by removing 1 stone", "Ben, only if Ana errs", "Ben, no matter what Ana does", "Ana, by removing 2 stones"],
    answer: "D",
    solution:
      "With moves of 1 or 2 stones, multiples of 3 are losing positions for the player about to move, since any move (1 or 2) lets the opponent return the pile to the next lower multiple of 3. Since 21 is a multiple of 3, Ana (moving first) is already in a losing position, so Ben wins with correct play.",
    hints: [
      "Identify which pile sizes are 'safe' — sizes where any move can be answered to return to another safe size.",
      "Multiples of 3 are losing positions here, since removing 1 or 2 always lets the opponent restore a multiple of 3.",
    ],
    difficulty: 5,
    topicSlug: "games-and-strategies",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-95",
    question: "A committee of 4 is chosen from 6 men and 5 women. How many committees have exactly 2 men and 2 women?",
    format: "MULTIPLE_CHOICE",
    choices: ["100", "55", "120", "210", "150"],
    answer: "E",
    solution:
      "Choose 2 of the 6 men: C(6,2) = 15. Choose 2 of the 5 women: C(5,2) = 10. Multiply: 15 × 10 = 150.",
    hints: [
      "Handle the men and women selections separately, then multiply the counts.",
      "Compute C(6,2) and C(5,2) individually.",
    ],
    difficulty: 5,
    topicSlug: "combinations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-96",
    question: "What is the units digit of 3^47?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "9", "3", "1", "7"],
    answer: "E",
    solution:
      "The units digits of powers of 3 cycle every 4: 3, 9, 7, 1, 3, 9, 7, 1, .... Since 47 = 4×11 + 3, the units digit matches the 3rd term of the cycle, which is 7.",
    hints: [
      "Find the repeating cycle of units digits for powers of 3.",
      "Use the remainder when 47 is divided by 4 to locate the position in the cycle.",
    ],
    difficulty: 5,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-97",
    question:
      "A line has equation y = 2x − 5. Another line is perpendicular to it and passes through (4, 1). What is the y-intercept of the second line?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "1", "3", "5", "-1"],
    answer: "C",
    solution:
      "The perpendicular slope is the negative reciprocal of 2, which is −1/2. Using point-slope form through (4,1): y − 1 = −(1/2)(x − 4), so y = −(1/2)x + 3. The y-intercept is 3.",
    hints: [
      "The slopes of perpendicular lines multiply to −1.",
      "Use point-slope form with the new slope and the given point, then set x = 0.",
    ],
    difficulty: 5,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-98",
    question: "How many three-digit numbers have digits that are all the same (like 222 or 777)?",
    format: "MULTIPLE_CHOICE",
    choices: ["99", "10", "8", "90", "9"],
    answer: "E",
    solution:
      "A number like ddd (d repeated three times) is a valid 3-digit number for d = 1 through 9 (d = 0 would give 000, not a 3-digit number). That's 9 numbers.",
    hints: [
      "The repeated digit can't be 0, or the number wouldn't have 3 digits.",
      "Count the possible digits 1 through 9.",
    ],
    difficulty: 5,
    topicSlug: "casework",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-99",
    question:
      "A game costs $2 to play. You roll a fair six-sided die and win $5 if it lands on a 6, and win nothing otherwise. What is the expected net profit (winnings minus cost) of playing once, in dollars?",
    format: "MULTIPLE_CHOICE",
    choices: ["-1", "1/6", "5/6", "-7/6", "-1/6"],
    answer: "D",
    solution:
      "Expected winnings are 5 × (1/6) = 5/6 dollars. Subtracting the $2 cost gives an expected net profit of 5/6 − 2 = −7/6 dollars.",
    hints: [
      "Compute the expected winnings first: probability of winning times the prize.",
      "Subtract the cost to play from the expected winnings.",
    ],
    difficulty: 5,
    topicSlug: "expected-value",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-100",
    question:
      "A rectangular box has dimensions 3 by 4 by 12. What is the length of the diagonal from one corner to the opposite corner?",
    format: "MULTIPLE_CHOICE",
    choices: ["12.5", "19", "17", "15", "13"],
    answer: "E",
    solution: "The space diagonal is √(3² + 4² + 12²) = √(9 + 16 + 144) = √169 = 13.",
    hints: [
      "Use the 3D distance formula √(a² + b² + c²) for the box's dimensions.",
      "3, 4, and 12 combine into a recognizable sum: 9+16+144=169, a perfect square.",
    ],
    difficulty: 5,
    topicSlug: "three-d-geometry",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-101",
    question: "A function satisfies f(x) = 2x + 3 for all x. What is f(f(4))?",
    format: "MULTIPLE_CHOICE",
    choices: ["25", "14", "11", "22", "28"],
    answer: "A",
    solution: "f(4) = 2(4) + 3 = 11. Then f(11) = 2(11) + 3 = 25.",
    hints: [
      "Compute the inner function value first: f(4).",
      "Plug that result back into f to get f(f(4)).",
    ],
    difficulty: 5,
    topicSlug: "functions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-102",
    question: "What is the smallest positive integer n such that n! is divisible by 1000?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "15", "20", "25", "10"],
    answer: "B",
    solution:
      "1000 = 2³×5³, and factors of 2 are always more abundant than factors of 5 in n!, so we need three factors of 5. Counting multiples of 5 up to n: n=10 gives only two factors of 5 (from 5 and 10), but n=15 gives three (from 5, 10, and 15). So the smallest such n is 15.",
    hints: [
      "Since 1000 = 2³×5³, focus on counting factors of 5 in n!, as they are the limiting factor.",
      "Count multiples of 5 (and 25) up to n until you accumulate three factors of 5.",
    ],
    difficulty: 5,
    topicSlug: "number-theory",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-103",
    question: "If P(x) = x³ − 4x² + x + 6 and P(2) is computed, what is the result?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "4", "-2", "0", "6"],
    answer: "D",
    solution: "P(2) = 2³ − 4(2²) + 2 + 6 = 8 − 16 + 2 + 6 = 0.",
    hints: [
      "Substitute x = 2 into every term of the polynomial.",
      "Compute each term separately before summing.",
    ],
    difficulty: 5,
    topicSlug: "polynomials",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-104",
    question:
      "A box has 3 red and 5 blue balls. Two balls are drawn without replacement. Given that the first ball drawn is red, what is the probability that the second ball is also red?",
    format: "MULTIPLE_CHOICE",
    choices: ["2/8", "2/7", "1/4", "3/7", "3/8"],
    answer: "B",
    solution:
      "After removing one red ball, 2 red and 5 blue balls remain, for 7 total. The probability the second ball is red is 2/7.",
    hints: [
      "Update the counts after the first red ball is removed.",
      "Divide the new number of red balls by the new total.",
    ],
    difficulty: 5,
    topicSlug: "conditional-probability",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-105",
    question: "A square is inscribed in a circle of radius 6. What is the area of the square?",
    format: "MULTIPLE_CHOICE",
    choices: ["72", "144", "108", "96", "36"],
    answer: "A",
    solution:
      "The square's diagonal equals the circle's diameter, 12. For a square with diagonal d, the area is d²/2, so the area is 144/2 = 72.",
    hints: [
      "The diagonal of the inscribed square equals the circle's diameter.",
      "Use area = (diagonal²)/2 for a square.",
    ],
    difficulty: 5,
    topicSlug: "circles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-106",
    question:
      "Among four friends — Priya, Quinn, Rosa, and Sam — each owns a different pet: cat, dog, fish, or bird. Priya's pet is not the cat or the fish. Quinn's pet is the dog. Rosa's pet is not the bird. Sam owns the fish. What pet does Priya own?",
    format: "MULTIPLE_CHOICE",
    choices: ["Dog", "Cat", "Cannot be determined", "Fish", "Bird"],
    answer: "E",
    solution:
      "Quinn owns the dog and Sam owns the fish, leaving cat and bird for Priya and Rosa. Since Priya's pet is not the cat, Priya must own the bird (and Rosa owns the cat, consistent with Rosa not owning the bird).",
    hints: [
      "Place Quinn's and Sam's pets first since they're given directly.",
      "Use Priya's restriction to choose between the two remaining pets.",
    ],
    difficulty: 5,
    topicSlug: "deduction",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-107",
    question: "If a + b = 12 and a² − b² = 48, what is the value of a − b?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "8", "4", "3", "5"],
    answer: "C",
    solution:
      "Factor: a² − b² = (a−b)(a+b) = 48. Since a+b = 12, we get (a−b)(12) = 48, so a − b = 4.",
    hints: [
      "Factor a² − b² as (a−b)(a+b).",
      "Divide 48 by the known value of a+b.",
    ],
    difficulty: 5,
    topicSlug: "algebra",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-108",
    question:
      "A regular hexagon has side length 4. If it is divided into 6 equilateral triangles from the center, what is the area of the hexagon, in terms of √3?",
    format: "MULTIPLE_CHOICE",
    choices: ["24√3", "16√3", "36√3", "48√3", "12√3"],
    answer: "A",
    solution:
      "Each equilateral triangle with side 4 has area (√3/4)(4²) = 4√3. Six such triangles give a total hexagon area of 6 × 4√3 = 24√3.",
    hints: [
      "Find the area of one equilateral triangle using (√3/4)s².",
      "Multiply by 6 since the hexagon is made of 6 such triangles.",
    ],
    difficulty: 5,
    topicSlug: "area-volume",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-109",
    question: "A fair coin is flipped 4 times. What is the probability of getting exactly 3 heads?",
    format: "MULTIPLE_CHOICE",
    choices: ["3/8", "1/8", "1/2", "1/4", "1/16"],
    answer: "D",
    solution:
      "There are C(4,3) = 4 ways to choose which flips are heads, out of 2⁴ = 16 total outcomes. The probability is 4/16 = 1/4.",
    hints: [
      "Count the number of ways to choose which 3 of the 4 flips are heads.",
      "Divide by the total number of possible outcomes, 2⁴ = 16.",
    ],
    difficulty: 5,
    topicSlug: "counting-probability",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-110",
    question: "If 2^a = 32 and 3^b = 81, what is the value of a + b?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "9", "13", "20", "4"],
    answer: "B",
    solution: "Since 32 = 2⁵, a = 5. Since 81 = 3⁴, b = 4. Thus a + b = 5 + 4 = 9.",
    hints: [
      "Rewrite each equation with matching bases to solve for the exponent.",
      "Add the two exponent values together.",
    ],
    difficulty: 5,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc8",
  },
];
