import type { ProblemSeed } from "./problems";

/**
 * Hand-written problems styled after Math Kangaroo, an international
 * puzzle-style competition for grades 1-12.
 *
 * Math Kangaroo is a single 75-minute round of all multiple-choice
 * questions (5 choices, A-E), with no penalty for wrong answers. The
 * 30-question format used by older grades groups questions into three
 * point tiers of 10 questions each: 3-point (basic, one-step), 4-point
 * (one clever twist or two steps), and 5-point (genuinely tricky, often
 * visual/spatial, pattern-based, or requiring a reframing insight rather
 * than heavy computation). The style favors puzzles, shapes, patterns,
 * logic, and playful scenarios over dense algebra, with small, friendly
 * numbers. Difficulty here is kept low relative to other competitions in
 * this app, per that spirit — even the hardest problems stay accessible.
 *
 * Every problem below is an original NumberSmith problem written to
 * match that format, phrasing, and difficulty ramp; none are transcribed
 * from any real Math Kangaroo contest.
 *
 * Seeded as practice (isPlacement: false), same as the other
 * competition-tagged problem sets.
 */
export const MATH_KANGAROO_PROBLEMS: ProblemSeed[] = [
  // ============================= 3-POINT TIER (difficulty 1-2) =============================
  {
    slug: "kangaroo-01",
    question: "A frog is sitting on step 3 of a staircase. It hops up 5 steps, then down 2 steps. Which step is it on now?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "6", "5", "7", "8"],
    answer: "B",
    solution: "Starting at step 3, hopping up 5 steps gives 3 + 5 = 8. Hopping down 2 steps gives 8 - 2 = 6.",
    hints: ["Add the up-hops and subtract the down-hops from the starting step.", "3 + 5 = 8, then 8 - 2 = ?"],
    difficulty: 1,
    topicSlug: "number-patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-02",
    question: "Maya has 4 red apples and 7 green apples in a basket. She eats 2 red apples and buys 3 more green apples. How many apples are in the basket now?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "12", "11", "13", "14"],
    answer: "B",
    solution: "Red apples: 4 - 2 = 2. Green apples: 7 + 3 = 10. Total = 2 + 10 = 12.",
    hints: ["Track red and green apples separately, then add.", "Red: 4 - 2 = 2. Green: 7 + 3 = 10."],
    difficulty: 1,
    topicSlug: "number-patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-03",
    question: "In a row of five houses numbered 1 through 5 from left to right, the blue house is immediately to the left of the red house, and the red house is house number 4. What number is the blue house?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "3", "2", "5", "It cannot be determined"],
    answer: "B",
    solution: "The blue house is immediately to the left of house 4, so the blue house is house 3.",
    hints: ["'Immediately to the left' means one number smaller.", "If red is house 4, blue is house 4 - 1."],
    difficulty: 1,
    topicSlug: "logical-puzzles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-04",
    question: "What is the next number in the pattern: 2, 4, 8, 16, 32, ...?",
    format: "MULTIPLE_CHOICE",
    choices: ["48", "56", "60", "128", "64"],
    answer: "E",
    solution: "Each number is double the previous one: 2, 4, 8, 16, 32, 64. So the next number is 32 × 2 = 64.",
    hints: ["Look at how each number relates to the one before it.", "Every term is twice the previous term."],
    difficulty: 1,
    topicSlug: "number-patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-05",
    question: "A rectangle has a length of 9 cm and a width of 4 cm. What is its perimeter, in cm?",
    format: "MULTIPLE_CHOICE",
    choices: ["13", "26", "18", "36", "22"],
    answer: "B",
    solution: "Perimeter = 2 × (length + width) = 2 × (9 + 4) = 2 × 13 = 26.",
    hints: ["The perimeter of a rectangle is twice the sum of its length and width.", "Add length and width first, then double."],
    difficulty: 1,
    topicSlug: "quadrilaterals",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-06",
    question: "Three friends, Ana, Ben, and Cody, are standing in a line. Ana is not first. Cody is not last. Ben is first. Who is last?",
    format: "MULTIPLE_CHOICE",
    choices: ["Ana", "Ben", "Cody", "Either Ana or Cody", "It cannot be determined"],
    answer: "A",
    solution: "Ben is first. Cody is not last, so Cody must be second, leaving Ana for last (which is consistent since Ana is not first).",
    hints: ["Since Ben is first, only Ana and Cody remain for second and third place.", "Cody cannot be last, so Cody is second and Ana is last."],
    difficulty: 2,
    topicSlug: "deduction",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-07",
    question: "A pizza is cut into 8 equal slices. Tom eats 3 slices and Lily eats 2 slices. What fraction of the pizza is left?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/8", "2/8", "6/8", "5/8", "3/8"],
    answer: "E",
    solution: "Together Tom and Lily eat 3 + 2 = 5 slices out of 8, so 8 - 5 = 3 slices remain, which is 3/8 of the pizza.",
    hints: ["Add up the slices eaten first.", "Subtract the eaten slices from the total 8 slices."],
    difficulty: 1,
    topicSlug: "fractions",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-08",
    question: "A box of pencils costs $6, and a box has 12 pencils. If Nora buys pencils in boxes to give exactly 1 pencil to each of her 30 classmates with none left over, how many dollars does she spend?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "15", "24", "20", "18"],
    answer: "E",
    solution: "Nora needs 30 pencils, and each box has 12. She needs 3 boxes (36 pencils) to have enough, since 2 boxes (24) is not enough. 3 boxes cost 3 × $6 = $18.",
    hints: ["Figure out how many boxes are needed to reach at least 30 pencils.", "2 boxes give 24 pencils (not enough); 3 boxes give 36 pencils."],
    difficulty: 2,
    topicSlug: "divisibility",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-09",
    question: "In a class of 20 students, every student plays soccer, basketball, or both. 14 students play soccer and 11 play basketball. How many students play both sports?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "7", "6", "5"],
    answer: "E",
    solution: "By inclusion-exclusion, students playing both = soccer + basketball - total = 14 + 11 - 20 = 5.",
    hints: ["Adding the two group sizes double-counts students who play both.", "Soccer + Basketball - Total = Both."],
    difficulty: 2,
    topicSlug: "counting-principles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-10",
    question: "A clock shows 2:00. What angle, in degrees, does the minute hand travel to reach 2:15?",
    format: "MULTIPLE_CHOICE",
    choices: ["15", "30", "60", "90", "180"],
    answer: "D",
    solution: "The minute hand travels a full 360 degrees in 60 minutes, which is 6 degrees per minute. In 15 minutes it travels 15 × 6 = 90 degrees.",
    hints: ["The minute hand moves 360 degrees in a full 60-minute hour.", "Find degrees per minute, then multiply by 15."],
    difficulty: 2,
    topicSlug: "angles",
    competitionSlug: "math-kangaroo",
  },

  // ============================= 4-POINT TIER (difficulty 2-3) =============================
  {
    slug: "kangaroo-11",
    question: "A farmer has chickens and goats. Together they have 18 heads and 50 legs. How many goats are there?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "6", "9", "8", "7"],
    answer: "E",
    solution: "If all 18 animals were chickens, there would be 36 legs, which is 50 - 36 = 14 short. Each goat has 2 more legs than a chicken, so there are 14 / 2 = 7 goats.",
    hints: ["Chickens have 2 legs, goats have 4 legs. Try assuming all animals are chickens first.", "Each goat adds 2 extra legs compared to a chicken."],
    difficulty: 3,
    topicSlug: "linear-equations",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-12",
    question: "Four children — Wren, Xena, Yara, and Zed — ran a race with no ties. Wren finished before Xena. Zed finished before Yara. Xena finished before Zed. In what place did Wren finish?",
    format: "MULTIPLE_CHOICE",
    choices: ["1st", "2nd", "3rd", "4th", "It cannot be determined"],
    answer: "A",
    solution: "Chaining the clues: Wren before Xena, Xena before Zed, Zed before Yara gives the order Wren, Xena, Zed, Yara. Wren finished 1st.",
    hints: ["Combine all three clues into a single chain of order.", "Wren < Xena < Zed < Yara, using 'before' as less than."],
    difficulty: 2,
    topicSlug: "deduction",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-13",
    question: "A 3-by-3 grid of unit squares is drawn (9 small squares total). How many squares of any size (1x1, 2x2, or 3x3) can be found in the grid?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "12", "13", "14", "16"],
    answer: "D",
    solution: "There are 9 squares of size 1x1, 4 squares of size 2x2 (top-left corners can be in any of a 2x2 arrangement of starting positions), and 1 square of size 3x3. Total = 9 + 4 + 1 = 14.",
    hints: ["Count squares of each size separately: 1x1, 2x2, and 3x3.", "For an n-by-n grid, the number of k-by-k squares is (n-k+1)^2."],
    difficulty: 3,
    topicSlug: "counting-principles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-14",
    question: "The sum of two numbers is 24 and their product is 143. What is the positive difference between the two numbers?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "3", "4", "5", "6"],
    answer: "A",
    solution: "We need two numbers summing to 24 with product 143. Testing factor pairs of 143 (= 11 × 13): 11 + 13 = 24, which matches. The difference is 13 - 11 = 2.",
    hints: ["Try to find two factors of 143 that add to 24.", "143 = 11 × 13, and 11 + 13 = 24."],
    difficulty: 3,
    topicSlug: "number-properties",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-15",
    question: "A spinner is divided into 5 equal sectors labeled 1, 2, 3, 4, 5. What is the probability that two spins in a row both land on odd numbers?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/5", "2/5", "3/5", "9/25", "4/25"],
    answer: "D",
    solution: "The odd numbers are 1, 3, 5, which is 3 out of 5 sectors, so the probability of odd on one spin is 3/5. For two independent spins both odd: (3/5) × (3/5) = 9/25.",
    hints: ["Find the probability of landing on an odd number in one spin first.", "Multiply the probability by itself for two independent spins."],
    difficulty: 3,
    topicSlug: "basic-probability",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-16",
    question: "A number is chosen from 1 to 30. How many of these numbers are divisible by 2 or 3 (or both)?",
    format: "MULTIPLE_CHOICE",
    choices: ["15", "18", "25", "22", "20"],
    answer: "E",
    solution: "Multiples of 2: 15. Multiples of 3: 10. Multiples of 6 (both): 5. By inclusion-exclusion: 15 + 10 - 5 = 20.",
    hints: ["Count multiples of 2, multiples of 3, and subtract the overlap (multiples of 6).", "15 + 10 - 5 = 20."],
    difficulty: 3,
    topicSlug: "divisibility",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-17",
    question: "Six points are marked on a circle, evenly spaced. How many straight line segments can be drawn connecting two of these points?",
    format: "MULTIPLE_CHOICE",
    choices: ["15", "12", "6", "18", "30"],
    answer: "A",
    solution: "The number of segments connecting 6 points, choosing 2 at a time, is C(6,2) = (6 × 5) / 2 = 15.",
    hints: ["Each segment connects a unique pair of points; order doesn't matter.", "Use the combination formula for choosing 2 points out of 6."],
    difficulty: 2,
    topicSlug: "combinations",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-18",
    question: "In a magic square using the numbers 1 through 9 once each, every row, column, and diagonal has the same sum. The center number is 5. What is that common sum?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "15", "18", "20", "24"],
    answer: "B",
    solution: "The sum of 1 through 9 is 45, and there are 3 rows, so each row sums to 45 / 3 = 15.",
    hints: ["Add up all the numbers 1 through 9 first.", "Since the numbers split evenly into 3 rows with equal sums, divide the total by 3."],
    difficulty: 2,
    topicSlug: "patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-19",
    question: "A garden path is made of square tiles, each 1 meter wide, laid in a repeating pattern of 2 gray tiles then 3 white tiles, repeating forever. What color is the 47th tile?",
    format: "MULTIPLE_CHOICE",
    choices: ["Gray", "White", "Cannot be determined from the pattern given", "Half gray, half white", "The pattern does not reach tile 47"],
    answer: "A",
    solution: "The pattern repeats every 5 tiles: positions 1 and 2 are gray, positions 3, 4, and 5 are white. Since 47 = 9 × 5 + 2, tile 47 falls in the same position as tile 2 within its block, which is gray.",
    hints: ["Find the remainder when 47 is divided by the pattern length of 5.", "Match that remainder to the corresponding position in one repeating block: gray, gray, white, white, white."],
    difficulty: 3,
    topicSlug: "number-patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-20",
    question: "Three consecutive integers have a sum of 72. What is the largest of the three?",
    format: "MULTIPLE_CHOICE",
    choices: ["22", "23", "24", "25", "26"],
    answer: "D",
    solution: "Let the integers be n-1, n, n+1. Their sum is 3n = 72, so n = 24. The largest is n + 1 = 25.",
    hints: ["Represent the three consecutive integers using a middle variable n.", "The sum of three consecutive integers is always 3 times the middle one."],
    difficulty: 2,
    topicSlug: "number-properties",
    competitionSlug: "math-kangaroo",
  },

  // ============================= 5-POINT TIER (difficulty 3-5) =============================
  {
    slug: "kangaroo-21",
    question: "A square piece of paper is folded in half twice (first left-to-right, then top-to-bottom), forming a smaller square one-quarter the original area. A single corner is then cut off the folded square, removing a small triangle from each layer. When unfolded, how many holes are in the paper?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "2", "3", "4", "8"],
    answer: "D",
    solution: "Folding twice creates 4 layers of paper stacked together. Cutting one corner off the folded stack removes a triangle from each of the 4 layers, so when unfolded there are 4 separate holes, one near each corner region of the original square.",
    hints: ["Count how many layers of paper are stacked after two folds.", "Each layer gets its own cut, creating its own hole when unfolded."],
    difficulty: 3,
    topicSlug: "transformations",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-22",
    question: "Five friends sit around a circular table. Each person shakes hands exactly once with every other person who is NOT sitting directly next to them. How many handshakes happen in total?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "5", "10", "15"],
    answer: "C",
    solution: "Total possible handshakes among 5 people is C(5,2) = 10. Around a circle, each person has 2 neighbors, giving 5 neighbor pairs (adjacent pairs) that do NOT shake hands. So handshakes that do happen = 10 - 5 = 5.",
    hints: ["First count all possible handshakes among 5 people, then subtract the ones between neighbors.", "In a circle of 5, there are exactly 5 pairs of adjacent neighbors."],
    difficulty: 4,
    topicSlug: "combinations",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-23",
    question: "A frog starts at 0 on a number line and wants to reach 5. Each jump, it can move forward 1 or forward 2. How many different sequences of jumps can the frog use to reach exactly 5?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "6", "7", "8", "10"],
    answer: "D",
    solution: "Let f(n) be the number of ways to reach n. f(0)=1, f(1)=1, f(2)=2, f(3)=f(2)+f(1)=3, f(4)=f(3)+f(2)=5, f(5)=f(4)+f(3)=5+3=8.",
    hints: ["This is like counting ways to climb stairs with steps of 1 or 2 — build up from smaller distances.", "The count for reaching n equals the count for reaching n-1 plus the count for reaching n-2."],
    difficulty: 4,
    topicSlug: "counting-principles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-24",
    question: "In a small tournament, each of 5 teams plays every other team exactly once. A win gives 3 points, a loss gives 0 points, and there are no ties. If every game has a winner and a loser, what is the total number of points awarded to all teams combined after the tournament finishes?",
    format: "MULTIPLE_CHOICE",
    choices: ["20", "24", "30", "36", "45"],
    answer: "C",
    solution: "The number of games played is C(5,2) = 10. Each game awards exactly 3 points total (to the winner). So total points = 10 × 3 = 30.",
    hints: ["First find the total number of games played among 5 teams.", "Each individual game contributes exactly 3 points to the grand total."],
    difficulty: 3,
    topicSlug: "combinations",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-25",
    question: "A 4-by-4 grid of dots (16 dots total, arranged in 4 rows and 4 columns, evenly spaced 1 unit apart) has a square drawn with corners at (1,1), (2,3), (4,2), and (3,0), using tilted sides rather than grid lines. What is the area of this square?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "5", "6", "9"],
    answer: "C",
    solution: "The side from (1,1) to (2,3) has horizontal change 1 and vertical change 2, so its length squared is 1^2 + 2^2 = 5. Since all four sides of this tilted square are congruent by symmetry (each side is a (1,2)-step rotated 90 degrees from the last), the area equals the side length squared, which is 5.",
    hints: ["Find the squared length of one side using the horizontal and vertical distance between two adjacent corners.", "For a tilted square, the area equals the square of its side length — you don't need the actual side length, just its square."],
    difficulty: 4,
    topicSlug: "area-volume",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-26",
    question: "Look at the sequence of letters: A, B, B, C, C, C, D, D, D, D, E, E, E, E, E, ... where each letter appears one more time than the letter before it (A once, B twice, C three times, and so on). What is the 25th letter in this sequence?",
    format: "MULTIPLE_CHOICE",
    choices: ["E", "F", "G", "H", "I"],
    answer: "C",
    solution: "The letter A ends at position 1, B ends at position 1+2=3, C ends at 3+3=6, D ends at 6+4=10, E ends at 10+5=15, F ends at 15+6=21, G ends at 21+7=28. Since 25 falls between 22 and 28, the 25th letter is G.",
    hints: ["Find the cumulative position where each letter's block ends: 1, 3, 6, 10, 15, 21, 28, ...", "Determine which block position 25 falls into."],
    difficulty: 4,
    topicSlug: "number-patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-27",
    question: "Two players, Alex and Bo, take turns removing either 1 or 2 coins from a pile of 7 coins, with Alex going first. The player who removes the last coin wins. If both play perfectly, who wins?",
    format: "MULTIPLE_CHOICE",
    choices: ["Alex, by taking 1 coin first", "Alex, by taking 2 coins first", "Bo, no matter what Alex does", "Whoever goes second always loses", "It depends on random chance"],
    answer: "A",
    solution: "A pile size is 'losing' for the player about to move if it's a multiple of 3 (since the opponent can always respond to bring the total removed per round to 3). 7 is not a multiple of 3; 7 mod 3 = 1, so Alex should remove 1 coin, leaving 6 (a multiple of 3) for Bo. Then Alex mirrors Bo's moves to always leave a multiple of 3, eventually winning.",
    hints: ["Think about which pile sizes are 'safe' to leave for your opponent — multiples of 3 are bad for whoever must move next.", "Alex should reduce the pile to a multiple of 3 on the first move."],
    difficulty: 5,
    topicSlug: "games-and-strategies",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-28",
    question: "A cube is painted red on the outside, then cut into 27 identical smaller cubes (a 3x3x3 arrangement). How many of the small cubes have paint on exactly 2 faces?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "8", "12", "20", "24"],
    answer: "C",
    solution: "In a 3x3x3 cube, the small cubes with exactly 2 painted faces are the edge cubes (not corners, not face-centers, not the center). Each of the 12 edges of the large cube contributes exactly 1 such small cube (the middle one along that edge), giving 12 total.",
    hints: ["Classify small cubes by position: corner (3 faces painted), edge (2 faces), face-center (1 face), interior (0 faces).", "A cube has 12 edges, and each edge contributes exactly one small cube with 2 painted faces."],
    difficulty: 4,
    topicSlug: "area-volume",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-29",
    question: "A palindrome is a number that reads the same forwards and backwards (like 121 or 3773). How many 3-digit palindromes are there in total?",
    format: "MULTIPLE_CHOICE",
    choices: ["45", "81", "90", "99", "100"],
    answer: "C",
    solution: "A 3-digit palindrome has the form aba, where a is the first and last digit (1-9, since it can't start with 0) and b is the middle digit (0-9). There are 9 choices for a and 10 choices for b, giving 9 × 10 = 90 palindromes.",
    hints: ["A 3-digit palindrome looks like 'aba' — the first and last digits must match.", "Count the choices for the first digit (cannot be 0) and the middle digit separately, then multiply."],
    difficulty: 3,
    topicSlug: "counting-principles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-30",
    question: "In a room, every person is either a truth-teller (always tells the truth) or a liar (always lies). There are 3 people: Pat, Quinn, and Ray. Pat says, 'Exactly zero of us are truth-tellers.' Quinn says, 'Exactly one of us is a truth-teller.' Ray says, 'Exactly two of us are truth-tellers.' How many truth-tellers are actually in the room?",
    format: "MULTIPLE_CHOICE",
    choices: ["0", "1", "2", "3", "It cannot be determined"],
    answer: "B",
    solution: "Each person's statement claims a specific total T, and that person is a truth-teller exactly when T equals their claim. Since Pat, Quinn, and Ray claim different totals (0, 1, 2), at most one of them can be a truth-teller for any given actual T. Testing T=1: Quinn's claim (1) matches, so Quinn is the truth-teller, while Pat and Ray are liars — this gives exactly 1 truth-teller, matching T=1, so it is self-consistent. Testing T=0: Pat's claim (0) would match, making Pat a truth-teller, but that means there is 1 truth-teller, not 0 — contradiction. T=2 and T=3 fail similarly. So T=1 is the only consistent answer.",
    hints: ["Each statement claims a different total, so figure out which single total, if true, doesn't contradict itself.", "Try assuming the actual number of truth-tellers equals Quinn's claim of 1, and check that it holds up."],
    difficulty: 5,
    topicSlug: "logical-puzzles",
    competitionSlug: "math-kangaroo",
  },

// ============================= DIFFICULTY 1 =============================
  {
    slug: "kangaroo-31",
    question: "A baker makes 18 muffins in the morning and 15 more in the afternoon. She sells 24 muffins by the end of the day. How many muffins does she have left?",
    format: "MULTIPLE_CHOICE",
    choices: ["33", "9", "7", "8", "12"],
    answer: "B",
    solution: "The baker made 18 + 15 = 33 muffins in total. After selling 24, she has 33 - 24 = 9 muffins left.",
    hints: ["First add up all the muffins made during the day.", "Then subtract the number sold from that total."],
    difficulty: 1,
    topicSlug: "arithmetic",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-32",
    question: "What is the next number in the pattern: 3, 6, 9, 12, 15, ...?",
    format: "MULTIPLE_CHOICE",
    choices: ["21", "20", "16", "17", "18"],
    answer: "E",
    solution: "Each number is 3 more than the one before it. Since 15 + 3 = 18, the next number is 18.",
    hints: ["Look at how much each number increases by.", "Every term is 3 more than the previous term."],
    difficulty: 1,
    topicSlug: "number-patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-33",
    question: "A ribbon is cut into 10 equal pieces. Jill uses 4 pieces to wrap a gift. What fraction of the ribbon is left?",
    format: "MULTIPLE_CHOICE",
    choices: ["4/10", "5/10", "6/10", "7/10", "3/10"],
    answer: "C",
    solution: "Jill used 4 of the 10 pieces, so 10 - 4 = 6 pieces remain, which is 6/10 of the ribbon.",
    hints: ["Subtract the pieces used from the total number of pieces.", "Write the remaining pieces as a fraction out of 10."],
    difficulty: 1,
    topicSlug: "fractions",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-34",
    question: "A square garden has a side length of 7 meters. What is its perimeter, in meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["28", "14", "21", "49", "35"],
    answer: "A",
    solution: "A square has 4 equal sides, so its perimeter is 4 × 7 = 28 meters.",
    hints: ["A square's perimeter is 4 times its side length.", "Multiply 7 by 4."],
    difficulty: 1,
    topicSlug: "quadrilaterals",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-35",
    question: "Three kids stand in a line. Uma is first. Tia is right behind Uma. Sam is right behind Tia. Who is last?",
    format: "MULTIPLE_CHOICE",
    choices: ["Uma", "Cannot be determined", "Either Tia or Sam", "Tia", "Sam"],
    answer: "E",
    solution: "The order from first to last is Uma, then Tia, then Sam, so Sam is last.",
    hints: ["Build the line in order starting from Uma.", "'Right behind' means directly following that person."],
    difficulty: 1,
    topicSlug: "logical-puzzles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-36",
    question: "A shop sells shirts in 3 colors (red, blue, green) and 2 sizes (small, large). How many different shirt options are there?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "6", "8", "12", "9"],
    answer: "B",
    solution: "Each of the 3 colors can be paired with either of the 2 sizes, giving 3 × 2 = 6 options.",
    hints: ["Multiply the number of color choices by the number of size choices.", "3 colors times 2 sizes."],
    difficulty: 1,
    topicSlug: "counting-principles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-37",
    question: "Which of these numbers is divisible by both 3 and 4?",
    format: "MULTIPLE_CHOICE",
    choices: ["20", "16", "15", "18", "24"],
    answer: "E",
    solution: "24 divided by 3 is 8 with no remainder, and 24 divided by 4 is 6 with no remainder, so 24 is divisible by both.",
    hints: ["Check each choice for divisibility by 3 first.", "Then check which of those is also divisible by 4."],
    difficulty: 1,
    topicSlug: "divisibility",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-38",
    question: "Ben scored 7, 9, and 8 points in three games. What is his average score?",
    format: "MULTIPLE_CHOICE",
    choices: ["8", "9", "8.5", "7", "24"],
    answer: "A",
    solution: "The total score is 7 + 9 + 8 = 24. The average is 24 divided by 3 games, which is 8.",
    hints: ["Add up all three scores first.", "Divide the total by the number of games."],
    difficulty: 1,
    topicSlug: "averages",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-39",
    question: "A clock shows 3:00. What is the angle between the hour hand and the minute hand, in degrees?",
    format: "MULTIPLE_CHOICE",
    choices: ["90", "30", "60", "180", "120"],
    answer: "A",
    solution: "At 3:00, the minute hand points at 12 and the hour hand points at 3, which is a quarter of the way around the clock. A quarter of 360 degrees is 90 degrees.",
    hints: ["Think of the clock face as a full 360-degree circle.", "At 3:00 the hands form exactly one quarter of the circle."],
    difficulty: 1,
    topicSlug: "angles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-40",
    question: "A triangle has two sides of length 5 cm and 5 cm, and its third side is also 5 cm. What type of triangle is this?",
    format: "MULTIPLE_CHOICE",
    choices: ["Isosceles only (not equilateral)", "Obtuse", "Right", "Equilateral", "Scalene"],
    answer: "D",
    solution: "Since all three sides are equal (5 cm each), the triangle is equilateral.",
    hints: ["Compare all three side lengths.", "A triangle with all three sides equal has a special name."],
    difficulty: 1,
    topicSlug: "triangles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-41",
    question: "A rectangle has an area of 36 square cm and a width of 4 cm. What is its length, in cm?",
    format: "MULTIPLE_CHOICE",
    choices: ["8", "6", "12", "32", "9"],
    answer: "E",
    solution: "Area equals length times width, so length = 36 ÷ 4 = 9 cm.",
    hints: ["Area = length × width.", "Divide the area by the width to find the length."],
    difficulty: 1,
    topicSlug: "quadrilaterals",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-42",
    question: "Which of these numbers is a prime number?",
    format: "MULTIPLE_CHOICE",
    choices: ["21", "35", "27", "33", "29"],
    answer: "E",
    solution: "21 = 3 × 7, 27 = 3 × 9, 33 = 3 × 11, and 35 = 5 × 7, but 29 has no divisors other than 1 and itself, so 29 is prime.",
    hints: ["Try dividing each number by small primes like 3, 5, and 7.", "A prime number has exactly two factors: 1 and itself."],
    difficulty: 1,
    topicSlug: "number-properties",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-43",
    question: "A pattern of shapes repeats every 4 shapes in this order: square, circle, circle, triangle. What is the 10th shape in the pattern?",
    format: "MULTIPLE_CHOICE",
    choices: ["It alternates every time", "Cannot be determined", "Square", "Circle", "Triangle"],
    answer: "D",
    solution: "The pattern repeats every 4 shapes. Since 10 = 2 × 4 + 2, the 10th shape is in the same position as the 2nd shape, which is a circle.",
    hints: ["Find the remainder when 10 is divided by the pattern length of 4.", "Match that remainder to the position in one block: square, circle, circle, triangle."],
    difficulty: 1,
    topicSlug: "patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-44",
    question: "Mia has $45. She spends $18 on a book and $12 on a puzzle. How much money does she have left?",
    format: "MULTIPLE_CHOICE",
    choices: ["17", "20", "25", "15", "13"],
    answer: "D",
    solution: "Mia spends 18 + 12 = 30 dollars in total. She has 45 - 30 = 15 dollars left.",
    hints: ["Add up the total amount spent first.", "Subtract that total from her starting amount."],
    difficulty: 1,
    topicSlug: "arithmetic",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-45",
    question: "In a bag, the ratio of red marbles to blue marbles is 2:3. If there are 10 red marbles, how many blue marbles are there?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "6", "10", "20", "15"],
    answer: "E",
    solution: "Since 10 red marbles correspond to 2 parts, each part is 10 ÷ 2 = 5 marbles. Blue marbles are 3 parts, so 3 × 5 = 15.",
    hints: ["Figure out how many marbles make up one 'part' of the ratio.", "Multiply the value of one part by 3 to get the blue marbles."],
    difficulty: 1,
    topicSlug: "ratios-proportions",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-46",
    question: "A class has 20 students. 50% of them are boys. How many boys are in the class?",
    format: "MULTIPLE_CHOICE",
    choices: ["15", "10", "8", "12", "5"],
    answer: "B",
    solution: "50% means half. Half of 20 students is 10 boys.",
    hints: ["50% is the same as one half.", "Find half of 20."],
    difficulty: 1,
    topicSlug: "percentages",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-47",
    question: "A bag has 4 red balls and 6 blue balls. If one ball is drawn at random, what is the probability that it is red?",
    format: "MULTIPLE_CHOICE",
    choices: ["2/3", "3/10", "1/2", "3/5", "2/5"],
    answer: "E",
    solution: "There are 4 red balls out of 10 total balls, so the probability of drawing red is 4/10, which simplifies to 2/5.",
    hints: ["The probability is the number of red balls divided by the total number of balls.", "Simplify the fraction 4/10."],
    difficulty: 1,
    topicSlug: "basic-probability",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-48",
    question: "Every rose in Lily's garden is red, and every red flower in her garden attracts bees. Lily's garden has only roses and daisies. If a flower in her garden is NOT attracting bees, what must it be?",
    format: "MULTIPLE_CHOICE",
    choices: ["A daisy", "Either a rose or a daisy", "A rose", "A red flower", "Cannot be determined"],
    answer: "A",
    solution: "Every rose is red, and every red flower attracts bees, so every rose attracts bees. A flower that is not attracting bees cannot be a rose, so since the garden has only roses and daisies, it must be a daisy.",
    hints: ["Work out what must be true about every rose in the garden.", "If it can't be a rose, and there are only two kinds of flowers, what's left?"],
    difficulty: 1,
    topicSlug: "deduction",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-49",
    question: "A circular pond has a diameter of 14 meters. What is its radius, in meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["49", "28", "7", "3.5", "14"],
    answer: "C",
    solution: "The radius is always half the diameter, so the radius is 14 ÷ 2 = 7 meters.",
    hints: ["The radius is half of the diameter.", "Divide 14 by 2."],
    difficulty: 1,
    topicSlug: "circles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-50",
    question: "Nina has 3 different hats and 2 different scarves. How many different hat-and-scarf outfits can she make, choosing one hat and one scarf?",
    format: "MULTIPLE_CHOICE",
    choices: ["7", "6", "5", "9", "10"],
    answer: "B",
    solution: "Each of the 3 hats can be paired with either of the 2 scarves, giving 3 × 2 = 6 different outfits.",
    hints: ["Multiply the number of hat choices by the number of scarf choices.", "3 hats times 2 scarves."],
    difficulty: 1,
    topicSlug: "combinatorics",
    competitionSlug: "math-kangaroo",
  },

  // ============================= DIFFICULTY 2 =============================
  {
    slug: "kangaroo-51",
    question: "A train has 6 cars, each holding 48 passengers. If the train is currently carrying 250 passengers, how many more passengers can it hold before it is full?",
    format: "MULTIPLE_CHOICE",
    choices: ["30", "28", "48", "58", "38"],
    answer: "E",
    solution: "The train's full capacity is 6 × 48 = 288 passengers. Since it currently carries 250, it can hold 288 - 250 = 38 more.",
    hints: ["First find the train's total capacity.", "Subtract the current number of passengers from that capacity."],
    difficulty: 2,
    topicSlug: "arithmetic",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-52",
    question: "What is the missing number in the pattern: 1, 4, 9, 16, __, 36?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "20", "22", "25", "30"],
    answer: "D",
    solution: "These are the perfect squares: 1², 2², 3², 4², 5², 6², which are 1, 4, 9, 16, 25, 36. The missing number is 25.",
    hints: ["Each number is a whole number multiplied by itself.", "Find the pattern: 1×1, 2×2, 3×3, 4×4, then continue."],
    difficulty: 2,
    topicSlug: "number-patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-53",
    question: "A recipe calls for 3/4 cup of sugar. If Ravi wants to make half of the recipe, how much sugar does he need, in cups?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/4", "3/4", "3/8", "1/8", "1/2"],
    answer: "C",
    solution: "Half of 3/4 is found by multiplying: (3/4) × (1/2) = 3/8 cup.",
    hints: ["To find half of an amount, multiply it by 1/2.", "Multiply the numerators together and the denominators together."],
    difficulty: 2,
    topicSlug: "fractions",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-54",
    question: "A rectangular room is 8 meters long and 5 meters wide. What is its area, in square meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["13", "26", "35", "40", "45"],
    answer: "D",
    solution: "Area of a rectangle equals length times width, so the area is 8 × 5 = 40 square meters.",
    hints: ["Area = length × width for a rectangle.", "Multiply 8 by 5."],
    difficulty: 2,
    topicSlug: "area-volume",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-55",
    question: "In a row of 5 houses numbered 1 through 5, the green house is house number 3. The red house is immediately to the left of the green house. What number is the red house?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "5", "1", "2", "3"],
    answer: "D",
    solution: "Immediately to the left of house 3 is house 2, so the red house is house number 2.",
    hints: ["'Immediately to the left' means one number smaller.", "The green house is 3, so subtract 1."],
    difficulty: 2,
    topicSlug: "logical-puzzles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-56",
    question: "A restaurant offers 4 appetizers and 3 main courses. How many different appetizer-and-main combinations can a customer order?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "10", "7", "9", "14"],
    answer: "A",
    solution: "Each of the 4 appetizers can be paired with any of the 3 main courses, giving 4 × 3 = 12 combinations.",
    hints: ["Multiply the number of appetizer choices by the number of main course choices.", "4 appetizers times 3 mains."],
    difficulty: 2,
    topicSlug: "counting-principles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-57",
    question: "What is the smallest number greater than 100 that is divisible by 7?",
    format: "MULTIPLE_CHOICE",
    choices: ["104", "101", "105", "107", "102"],
    answer: "C",
    solution: "Dividing 100 by 7 gives about 14.3, so the next whole multiple of 7 is 15 × 7 = 105.",
    hints: ["Divide 100 by 7 to see how close the nearest multiples are.", "Round up to the next whole multiple of 7."],
    difficulty: 2,
    topicSlug: "divisibility",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-58",
    question: "The average of four numbers is 15. If three of the numbers are 10, 12, and 18, what is the fourth number?",
    format: "MULTIPLE_CHOICE",
    choices: ["15", "22", "20", "18", "24"],
    answer: "C",
    solution: "Since the average of 4 numbers is 15, their total sum is 4 × 15 = 60. The three known numbers sum to 10 + 12 + 18 = 40, so the fourth number is 60 - 40 = 20.",
    hints: ["Multiply the average by the count of numbers to get the total sum.", "Subtract the sum of the known numbers from that total."],
    difficulty: 2,
    topicSlug: "averages",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-59",
    question: "Two angles are supplementary, meaning they add up to 180°. One of the angles is 65°. What is the other angle?",
    format: "MULTIPLE_CHOICE",
    choices: ["105", "125", "95", "135", "115"],
    answer: "E",
    solution: "Since the two angles add up to 180°, the other angle is 180 - 65 = 115°.",
    hints: ["Supplementary angles add up to 180 degrees.", "Subtract 65 from 180."],
    difficulty: 2,
    topicSlug: "angles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-60",
    question: "A triangle has angles measuring 50° and 60°. What is the measure of the third angle?",
    format: "MULTIPLE_CHOICE",
    choices: ["75", "70", "65", "60", "80"],
    answer: "B",
    solution: "The angles of a triangle always add up to 180°. So the third angle is 180 - 50 - 60 = 70°.",
    hints: ["All three angles of a triangle add up to 180 degrees.", "Subtract the two known angles from 180."],
    difficulty: 2,
    topicSlug: "triangles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-61",
    question: "A square has a perimeter of 32 cm. What is its area, in square cm?",
    format: "MULTIPLE_CHOICE",
    choices: ["56", "72", "32", "48", "64"],
    answer: "E",
    solution: "Each side of the square is 32 ÷ 4 = 8 cm. The area is 8 × 8 = 64 square cm.",
    hints: ["Find the side length by dividing the perimeter by 4.", "Then square the side length to get the area."],
    difficulty: 2,
    topicSlug: "area-volume",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-62",
    question: "What is the sum of all the factors of 12, including 1 and 12 itself?",
    format: "MULTIPLE_CHOICE",
    choices: ["28", "24", "30", "16", "20"],
    answer: "A",
    solution: "The factors of 12 are 1, 2, 3, 4, 6, and 12. Adding them: 1 + 2 + 3 + 4 + 6 + 12 = 28.",
    hints: ["List all the numbers that divide 12 evenly.", "Add up all of those factors."],
    difficulty: 2,
    topicSlug: "number-properties",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-63",
    question: "A sequence starts at 100 and decreases by 7 each time: 100, 93, 86, .... What is the first term in the sequence that is less than 50?",
    format: "MULTIPLE_CHOICE",
    choices: ["49", "46", "37", "44", "51"],
    answer: "D",
    solution: "The terms are 100 - 7k for k = 0, 1, 2, .... At k = 7, the term is 100 - 49 = 51 (not yet less than 50). At k = 8, the term is 100 - 56 = 44, which is the first term less than 50.",
    hints: ["Write the general term as 100 minus 7 times a counting number.", "Find the first value of that counting number that makes the term drop below 50."],
    difficulty: 2,
    topicSlug: "patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-64",
    question: "A recipe uses flour and sugar in the ratio 5:2. If a baker uses 20 cups of flour, how many cups of sugar are needed?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "7", "8", "10", "9"],
    answer: "C",
    solution: "Since 20 cups of flour corresponds to 5 parts, each part is 20 ÷ 5 = 4 cups. Sugar is 2 parts, so 2 × 4 = 8 cups.",
    hints: ["Find the size of one 'part' using the flour amount.", "Multiply the value of one part by 2 for the sugar."],
    difficulty: 2,
    topicSlug: "ratios-proportions",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-65",
    question: "A shirt originally costs $40. It is on sale for 25% off. What is the sale price?",
    format: "MULTIPLE_CHOICE",
    choices: ["25", "35", "30", "28", "32"],
    answer: "C",
    solution: "25% of $40 is 0.25 × 40 = $10. The sale price is 40 - 10 = $30.",
    hints: ["Find 25% of the original price first.", "Subtract that discount from the original price."],
    difficulty: 2,
    topicSlug: "percentages",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-66",
    question: "A die is rolled once. What is the probability of rolling a number greater than 4?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/6", "1/4", "1/2", "2/3", "1/3"],
    answer: "E",
    solution: "The numbers greater than 4 on a die are 5 and 6, which is 2 out of 6 possible outcomes. This simplifies to 1/3.",
    hints: ["List the numbers on a die that are greater than 4.", "Write that count over the total of 6 possible outcomes, then simplify."],
    difficulty: 2,
    topicSlug: "basic-probability",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-67",
    question: "Ana, Bo, and Cam each have a different number of marbles: 4, 7, and 11, in some order. Ana has fewer marbles than Bo. Cam has more marbles than Bo. How many marbles does Bo have?",
    format: "MULTIPLE_CHOICE",
    choices: ["Cannot be determined", "9", "7", "11", "4"],
    answer: "C",
    solution: "Since Ana has fewer than Bo, and Cam has more than Bo, the order from least to most is Ana, Bo, Cam. Matching this to 4, 7, 11 in order, Bo has 7 marbles.",
    hints: ["Order the three friends from fewest to most marbles.", "Match that order to the numbers 4, 7, and 11."],
    difficulty: 2,
    topicSlug: "deduction",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-68",
    question: "A circle has a radius of 10 cm. What is its diameter, in cm?",
    format: "MULTIPLE_CHOICE",
    choices: ["20", "15", "5", "40", "10"],
    answer: "A",
    solution: "The diameter is always twice the radius, so the diameter is 2 × 10 = 20 cm.",
    hints: ["The diameter is double the radius.", "Multiply 10 by 2."],
    difficulty: 2,
    topicSlug: "circles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-69",
    question: "How many different 2-letter codes can be made using the letters A, B, C, D if letters can be repeated?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "24", "20", "16", "8"],
    answer: "D",
    solution: "There are 4 choices for the first letter and 4 choices for the second letter (since repeats are allowed), giving 4 × 4 = 16 codes.",
    hints: ["Since repeats are allowed, both letter positions have the same number of options.", "Multiply the number of choices for each position: 4 × 4."],
    difficulty: 2,
    topicSlug: "combinatorics",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-70",
    question: "In how many different orders can 3 friends, Amy, Bo, and Cleo, line up for a photo?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "6", "5", "12", "9"],
    answer: "B",
    solution: "There are 3 choices for who stands first, then 2 remaining choices for second, then 1 choice for last: 3 × 2 × 1 = 6 orders.",
    hints: ["Count the choices for each position one at a time: first, then second, then last.", "Multiply 3 × 2 × 1."],
    difficulty: 2,
    topicSlug: "permutations",
    competitionSlug: "math-kangaroo",
  },

  // ============================= DIFFICULTY 3 =============================
  {
    slug: "kangaroo-71",
    question: "A shop had 240 toys. It sold 3/8 of them in the morning and 1/4 of the original amount in the afternoon. How many toys are left?",
    format: "MULTIPLE_CHOICE",
    choices: ["100", "85", "80", "90", "95"],
    answer: "D",
    solution: "In the morning, 3/8 × 240 = 90 toys were sold. In the afternoon, 1/4 × 240 = 60 toys were sold. Total sold = 90 + 60 = 150, so toys left = 240 - 150 = 90.",
    hints: ["Find the number of toys sold in the morning and afternoon separately.", "Subtract the total sold from the original 240."],
    difficulty: 3,
    topicSlug: "fractions",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-72",
    question: "In the sequence 2, 5, 11, 23, 47, ..., each term after the first is found by doubling the previous term and adding 1. What is the next term?",
    format: "MULTIPLE_CHOICE",
    choices: ["96", "95", "94", "92", "98"],
    answer: "B",
    solution: "Following the rule, the next term is 47 × 2 + 1 = 95.",
    hints: ["Apply the stated rule to the last given term, 47.", "Double 47 first, then add 1."],
    difficulty: 3,
    topicSlug: "number-patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-73",
    question: "Two-thirds of a number is 18. What is the number?",
    format: "MULTIPLE_CHOICE",
    choices: ["30", "36", "27", "12", "24"],
    answer: "C",
    solution: "If two-thirds of a number is 18, then one-third of it is 18 ÷ 2 = 9. The whole number is 9 × 3 = 27.",
    hints: ["Find one-third of the number first by halving 18.", "Multiply that one-third value by 3 to get the whole number."],
    difficulty: 3,
    topicSlug: "fractions",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-74",
    question: "A rectangular box has a length of 6 cm, a width of 4 cm, and a height of 3 cm. What is its volume, in cubic cm?",
    format: "MULTIPLE_CHOICE",
    choices: ["13", "52", "60", "84", "72"],
    answer: "E",
    solution: "The volume of a rectangular box is length × width × height = 6 × 4 × 3 = 72 cubic cm.",
    hints: ["Volume = length × width × height.", "Multiply all three dimensions together."],
    difficulty: 3,
    topicSlug: "area-volume",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-75",
    question: "Four friends, Ana, Bo, Cy, and Dee, each own a different pet: cat, dog, fish, or bird. Bo owns the dog. Dee owns the cat. Cy does not own the fish. What pet does Ana own?",
    format: "MULTIPLE_CHOICE",
    choices: ["Dog", "Fish", "Cannot be determined", "Bird", "Cat"],
    answer: "B",
    solution: "With Bo owning the dog and Dee owning the cat, only fish and bird remain for Ana and Cy. Since Cy does not own the fish, Cy must own the bird, leaving the fish for Ana.",
    hints: ["Cross off the pets already assigned to Bo and Dee.", "Use the clue about Cy to decide who gets the fish and who gets the bird."],
    difficulty: 3,
    topicSlug: "logical-puzzles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-76",
    question: "A password is made of 2 letters followed by 1 digit. There are 5 possible letters (A, B, C, D, E) with repetition allowed, and 10 possible digits (0-9). How many different passwords are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["300", "250", "150", "100", "200"],
    answer: "B",
    solution: "There are 5 choices for the first letter, 5 for the second letter, and 10 for the digit: 5 × 5 × 10 = 250.",
    hints: ["Count the choices for each of the 3 positions separately.", "Multiply 5 × 5 × 10."],
    difficulty: 3,
    topicSlug: "counting-principles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-77",
    question: "What is the largest number less than 200 that is divisible by both 6 and 8?",
    format: "MULTIPLE_CHOICE",
    choices: ["180", "168", "184", "192", "196"],
    answer: "D",
    solution: "A number divisible by both 6 and 8 must be a multiple of their least common multiple, 24. The largest multiple of 24 under 200 is 24 × 8 = 192.",
    hints: ["Find the least common multiple of 6 and 8.", "Find the largest multiple of that LCM that is still under 200."],
    difficulty: 3,
    topicSlug: "divisibility",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-78",
    question: "A student's average score on 4 tests is 82. What total score is needed on a 5th test to raise the average to 85?",
    format: "MULTIPLE_CHOICE",
    choices: ["100", "88", "91", "94", "97"],
    answer: "E",
    solution: "The total needed for an average of 85 over 5 tests is 5 × 85 = 425. The current total from 4 tests is 4 × 82 = 328. The 5th test score must be 425 - 328 = 97.",
    hints: ["Find the total score needed across all 5 tests for the new average.", "Subtract the current total (from 4 tests) from that needed total."],
    difficulty: 3,
    topicSlug: "averages",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-79",
    question: "In a triangle, one angle is twice as large as a second angle, and the third angle is 20° more than the second angle. What is the measure of the smallest angle?",
    format: "MULTIPLE_CHOICE",
    choices: ["35", "45", "50", "40", "30"],
    answer: "D",
    solution: "Let the second angle be x. Then the first angle is 2x and the third is x + 20. Since the angles sum to 180: 2x + x + (x + 20) = 180, so 4x = 160, giving x = 40. The three angles are 80, 40, and 60, so the smallest is 40.",
    hints: ["Represent the angles in terms of the second angle, x.", "Set up the equation so all three angles sum to 180 and solve for x."],
    difficulty: 3,
    topicSlug: "angles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-80",
    question: "A right triangle has legs of length 6 cm and 8 cm. What is the length of its hypotenuse, in cm?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "10", "9", "14", "11"],
    answer: "B",
    solution: "By the Pythagorean theorem, the hypotenuse squared equals 6² + 8² = 36 + 64 = 100, so the hypotenuse is the square root of 100, which is 10.",
    hints: ["Use the Pythagorean theorem: the sum of the squares of the legs equals the square of the hypotenuse.", "Add 6² and 8², then take the square root of the result."],
    difficulty: 3,
    topicSlug: "triangles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-81",
    question: "A trapezoid has parallel sides of length 10 cm and 14 cm, and a height of 5 cm. What is its area, in square cm?",
    format: "MULTIPLE_CHOICE",
    choices: ["48", "70", "66", "60", "54"],
    answer: "D",
    solution: "The area of a trapezoid is the average of the parallel sides times the height: (10 + 14) / 2 × 5 = 12 × 5 = 60.",
    hints: ["Average the two parallel side lengths first.", "Multiply that average by the height."],
    difficulty: 3,
    topicSlug: "area-volume",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-82",
    question: "A regular hexagon has a perimeter of 42 cm. What is the length of each side, in cm?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "7", "9", "5", "8"],
    answer: "B",
    solution: "A regular hexagon has 6 equal sides, so each side is 42 ÷ 6 = 7 cm.",
    hints: ["A regular hexagon has 6 equal sides.", "Divide the perimeter by 6."],
    difficulty: 3,
    topicSlug: "polygons",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-83",
    question: "What is the smallest positive integer that has exactly 4 factors, including 1 and itself?",
    format: "MULTIPLE_CHOICE",
    choices: ["8", "9", "6", "10", "4"],
    answer: "C",
    solution: "Checking small numbers: 4 has factors 1, 2, 4 (3 factors); 5 has 1, 5 (2 factors); 6 has factors 1, 2, 3, 6 (exactly 4 factors). So the smallest such number is 6.",
    hints: ["List out the factors of small numbers one at a time, starting from 1.", "Look for the first number whose factor list has exactly 4 entries."],
    difficulty: 3,
    topicSlug: "number-properties",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-84",
    question: "A tiling pattern repeats every 6 tiles in the order: red, red, blue, yellow, yellow, yellow. What color is the 50th tile?",
    format: "MULTIPLE_CHOICE",
    choices: ["Yellow", "Blue", "Red", "Green", "Cannot be determined"],
    answer: "C",
    solution: "The pattern repeats every 6 tiles. Since 50 = 8 × 6 + 2, the 50th tile matches the 2nd position in the pattern, which is red.",
    hints: ["Find the remainder when 50 is divided by 6.", "Match that remainder to a position in one block of the pattern."],
    difficulty: 3,
    topicSlug: "patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-85",
    question: "The ratio of boys to girls in a class is 3:4. If there are 35 students total, how many girls are there?",
    format: "MULTIPLE_CHOICE",
    choices: ["20", "15", "21", "18", "25"],
    answer: "A",
    solution: "The ratio 3:4 has 3 + 4 = 7 total parts. Each part is 35 ÷ 7 = 5 students. Girls make up 4 parts, so 4 × 5 = 20 girls.",
    hints: ["Add the two parts of the ratio to find the total number of parts.", "Find the value of one part, then multiply by the girls' share of the ratio."],
    difficulty: 3,
    topicSlug: "ratios-proportions",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-86",
    question: "A number increased by 20% becomes 96. What was the original number?",
    format: "MULTIPLE_CHOICE",
    choices: ["78", "80", "76", "72", "84"],
    answer: "B",
    solution: "If the original number is x, then x × 1.2 = 96, so x = 96 ÷ 1.2 = 80.",
    hints: ["Increasing by 20% means multiplying the original number by 1.2.", "Divide 96 by 1.2 to undo that multiplication."],
    difficulty: 3,
    topicSlug: "percentages",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-87",
    question: "A bag contains 3 red, 4 blue, and 5 green marbles. If one marble is drawn at random, what is the probability that it is NOT green?",
    format: "MULTIPLE_CHOICE",
    choices: ["7/12", "5/6", "7/10", "5/12", "1/2"],
    answer: "A",
    solution: "There are 12 marbles total. The non-green marbles are 3 red + 4 blue = 7, so the probability of drawing a non-green marble is 7/12.",
    hints: ["Find the total number of marbles in the bag.", "Count the marbles that are not green, then write that as a fraction of the total."],
    difficulty: 3,
    topicSlug: "basic-probability",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-88",
    question: "Two players take turns saying numbers, starting from a total of 0, each time adding 1 or 2 to the running total. The first player to bring the total to exactly 10 wins. Player A goes first. Which first move guarantees Player A a win with perfect play afterward?",
    format: "MULTIPLE_CHOICE",
    choices: ["It depends on what Player B does", "Player A cannot guarantee a win", "Either works equally well", "Add 2", "Add 1"],
    answer: "E",
    solution: "The winning totals to control are 1, 4, 7, 10 (each 3 more than the last). If Player A adds 1 first (reaching 1), then no matter whether Player B adds 1 or 2, Player A can always respond to reach the next target (4, then 7, then 10), guaranteeing the win.",
    hints: ["Work backward from the target total of 10 in steps of 3.", "Player A wants to be the one to reach 1, then 4, then 7, then 10."],
    difficulty: 3,
    topicSlug: "games-and-strategies",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-89",
    question: "In how many ways can 4 different books be arranged on a shelf if 2 specific books must be placed next to each other?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "24", "8", "6", "18"],
    answer: "A",
    solution: "Treat the 2 specific books as a single glued unit, giving 3 units to arrange in 3! = 6 ways. Within the glued unit, the 2 books can swap order in 2 ways. Total: 6 × 2 = 12.",
    hints: ["Temporarily treat the two books that must be together as one combined unit.", "Arrange the units, then account for the 2 internal orders of the joined pair."],
    difficulty: 3,
    topicSlug: "combinatorics",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-90",
    question: "How many different 3-digit numbers can be formed using the digits 1, 2, 3, 4 without repeating any digit?",
    format: "MULTIPLE_CHOICE",
    choices: ["64", "16", "12", "20", "24"],
    answer: "E",
    solution: "There are 4 choices for the first digit, 3 remaining choices for the second digit, and 2 remaining choices for the third digit: 4 × 3 × 2 = 24.",
    hints: ["Count the choices for each digit position one at a time, without repeats.", "Multiply 4 × 3 × 2."],
    difficulty: 3,
    topicSlug: "permutations",
    competitionSlug: "math-kangaroo",
  },

  // ============================= DIFFICULTY 4 =============================
  {
    slug: "kangaroo-91",
    question: "The sum of three consecutive even integers is 96. What is the largest of the three?",
    format: "MULTIPLE_CHOICE",
    choices: ["30", "36", "32", "38", "34"],
    answer: "E",
    solution: "Let the integers be n - 2, n, and n + 2. Their sum is 3n = 96, so n = 32. The largest is n + 2 = 34.",
    hints: ["Represent the three consecutive even integers using a middle value n.", "Their sum is always 3 times the middle value."],
    difficulty: 4,
    topicSlug: "number-properties",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-92",
    question: "In the sequence 1, 1, 2, 3, 5, 8, 13, ..., each term after the first two is the sum of the two terms before it. What is the 10th term?",
    format: "MULTIPLE_CHOICE",
    choices: ["34", "44", "89", "60", "55"],
    answer: "E",
    solution: "Continuing the sequence: 1, 1, 2, 3, 5, 8, 13, 21, 34, 55. The 10th term is 55.",
    hints: ["Each new term equals the sum of the previous two terms.", "Extend the sequence carefully term by term until you reach the 10th."],
    difficulty: 4,
    topicSlug: "number-patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-93",
    question: "A tank is 1/2 full of water. After adding 45 liters, it becomes 3/4 full. What is the tank's total capacity, in liters?",
    format: "MULTIPLE_CHOICE",
    choices: ["200", "160", "90", "135", "180"],
    answer: "E",
    solution: "The 45 liters added fills the difference between 3/4 and 1/2 of the tank, which is 1/4 of the capacity. So 1/4 of the capacity is 45 liters, and the full capacity is 45 × 4 = 180 liters.",
    hints: ["Find what fraction of the tank the 45 liters represents.", "Multiply 45 by the reciprocal of that fraction to get the full capacity."],
    difficulty: 4,
    topicSlug: "fractions",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-94",
    question: "A rectangular prism has a square base with side length 5 cm and a height of 12 cm. What is its volume, in cubic cm?",
    format: "MULTIPLE_CHOICE",
    choices: ["360", "150", "300", "60", "240"],
    answer: "C",
    solution: "The volume is the area of the square base times the height: (5 × 5) × 12 = 25 × 12 = 300 cubic cm.",
    hints: ["Find the area of the square base first.", "Multiply that base area by the height."],
    difficulty: 4,
    topicSlug: "area-volume",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-95",
    question: "Five runners, P, Q, R, S, and T, finish a race with no ties. R finishes first. S finishes right after R. T finishes third. Q finishes right after P. What place does Q finish?",
    format: "MULTIPLE_CHOICE",
    choices: ["3rd", "Cannot be determined", "4th", "5th", "2nd"],
    answer: "D",
    solution: "R is 1st, and S finishes right after R, so S is 2nd. T is given as 3rd. That leaves 4th and 5th for P and Q. Since Q finishes right after P, P must be 4th and Q must be 5th.",
    hints: ["Place R, S, and T first using the direct clues.", "The only two places left must be filled in the order given by the P-then-Q clue."],
    difficulty: 4,
    topicSlug: "logical-puzzles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-96",
    question: "A vending machine sells drinks in 4 flavors and snacks in 5 types. A customer buys exactly one item: either one drink or one snack, not both. How many different single-item purchases are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["20", "9", "5", "15", "4"],
    answer: "B",
    solution: "Since the customer chooses one drink OR one snack (not a combination), the total choices are added rather than multiplied: 4 + 5 = 9.",
    hints: ["Since it's 'either/or' rather than 'both', think about whether to add or multiply the choices.", "Add the number of drink options and snack options."],
    difficulty: 4,
    topicSlug: "counting-principles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-97",
    question: "How many positive integers less than 100 are divisible by 4 but not by 8?",
    format: "MULTIPLE_CHOICE",
    choices: ["16", "10", "8", "14", "12"],
    answer: "E",
    solution: "There are 24 multiples of 4 below 100 (4, 8, ..., 96) and 12 multiples of 8 below 100 (8, 16, ..., 96). Every multiple of 8 is also a multiple of 4, so the numbers divisible by 4 but not 8 total 24 - 12 = 12.",
    hints: ["Count the multiples of 4 below 100, then the multiples of 8 below 100.", "Every multiple of 8 is already counted among the multiples of 4 — subtract them out."],
    difficulty: 4,
    topicSlug: "integer-properties",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-98",
    question: "The average of 5 numbers is 20. If one of the numbers, 30, is removed, what is the average of the remaining 4 numbers?",
    format: "MULTIPLE_CHOICE",
    choices: ["20", "16", "17.5", "18", "15"],
    answer: "C",
    solution: "The sum of all 5 numbers is 5 × 20 = 100. Removing 30 leaves a sum of 100 - 30 = 70 for the remaining 4 numbers, so their average is 70 ÷ 4 = 17.5.",
    hints: ["Find the total sum of all 5 numbers first.", "Subtract 30 from that sum, then divide by the 4 remaining numbers."],
    difficulty: 4,
    topicSlug: "averages",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-99",
    question: "In a triangle, the three angles are in the ratio 2:3:4. What is the measure of the largest angle?",
    format: "MULTIPLE_CHOICE",
    choices: ["90", "100", "80", "60", "70"],
    answer: "C",
    solution: "The ratio parts add to 2 + 3 + 4 = 9, and the angles sum to 180°, so each part is 180 ÷ 9 = 20°. The largest angle is 4 parts, or 4 × 20 = 80°.",
    hints: ["Add up the parts of the ratio, then divide 180 by that total.", "Multiply the value of one part by the largest ratio number."],
    difficulty: 4,
    topicSlug: "angles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-100",
    question: "An isosceles triangle has a base angle of 50°. What is the measure of the vertex angle, the angle between the two equal sides?",
    format: "MULTIPLE_CHOICE",
    choices: ["80", "65", "100", "90", "50"],
    answer: "A",
    solution: "In an isosceles triangle, the two base angles are equal, so both are 50°, summing to 100°. The vertex angle is 180 - 100 = 80°.",
    hints: ["The two base angles of an isosceles triangle are equal to each other.", "Subtract the sum of both base angles from 180."],
    difficulty: 4,
    topicSlug: "triangles",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-101",
    question: "A pentagon has interior angles measuring 100°, 110°, 120°, x°, and x°, where the last two angles are equal. What is x?",
    format: "MULTIPLE_CHOICE",
    choices: ["95", "105", "110", "100", "115"],
    answer: "B",
    solution: "The interior angles of a pentagon sum to 540°. The three known angles sum to 100 + 110 + 120 = 330, leaving 540 - 330 = 210 for the two equal angles. So 2x = 210, giving x = 105.",
    hints: ["Recall that a pentagon's interior angles always sum to 540 degrees.", "Subtract the three known angles from 540, then split the remainder evenly between the two equal angles."],
    difficulty: 4,
    topicSlug: "polygons",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-102",
    question: "What is the units digit of 7^23 (7 raised to the 23rd power)?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "1", "7", "5", "3"],
    answer: "E",
    solution: "The units digits of powers of 7 cycle every 4 steps: 7, 9, 3, 1, then repeat. Since 23 divided by 4 leaves a remainder of 3, the units digit matches the 3rd position in the cycle, which is 3.",
    hints: ["Write out the units digits of the first several powers of 7 and look for a repeating cycle.", "Find the remainder when 23 is divided by the cycle length, then match it to that position."],
    difficulty: 4,
    topicSlug: "integer-properties",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-103",
    question: "A sequence starts with 3, and each next term is found by doubling the previous term and then subtracting 1: 3, 5, 9, 17, .... What is the 6th term?",
    format: "MULTIPLE_CHOICE",
    choices: ["57", "73", "61", "49", "65"],
    answer: "E",
    solution: "Continuing the rule: term 5 = 2 × 17 - 1 = 33, and term 6 = 2 × 33 - 1 = 65.",
    hints: ["The sequence given only goes up to the 4th term (17) — extend it using the doubling-then-subtract-1 rule.", "Compute term 5 first, then use it to find term 6."],
    difficulty: 4,
    topicSlug: "patterns",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-104",
    question: "Two numbers are in the ratio 5:7. If their sum is 96, what is the larger number?",
    format: "MULTIPLE_CHOICE",
    choices: ["60", "40", "54", "56", "48"],
    answer: "D",
    solution: "The ratio parts add to 5 + 7 = 12, so each part is 96 ÷ 12 = 8. The larger number is 7 parts, or 7 × 8 = 56.",
    hints: ["Add the two ratio numbers to find the total number of parts.", "Divide the sum by the total parts, then multiply by the larger ratio number."],
    difficulty: 4,
    topicSlug: "ratios-proportions",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-105",
    question: "A store marks up an item's cost by 40% to set its selling price. If the selling price is $84, what was the original cost?",
    format: "MULTIPLE_CHOICE",
    choices: ["50", "54", "60", "64", "58"],
    answer: "C",
    solution: "If the cost is x, then x × 1.4 = 84, so x = 84 ÷ 1.4 = 60.",
    hints: ["A 40% markup means the selling price is 1.4 times the cost.", "Divide the selling price by 1.4 to find the cost."],
    difficulty: 4,
    topicSlug: "percentages",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-106",
    question: "A jar contains 6 red, 4 blue, and 2 yellow marbles. Two marbles are drawn one after another without putting the first one back. What is the probability that both marbles drawn are red?",
    format: "MULTIPLE_CHOICE",
    choices: ["3/11", "5/22", "5/12", "1/2", "1/4"],
    answer: "B",
    solution: "There are 12 marbles total. The probability the first is red is 6/12. After removing one red marble, 5 red marbles remain out of 11 total, so the probability the second is also red is 5/11. Multiplying: (6/12) × (5/11) = 30/132 = 5/22.",
    hints: ["Find the probability the first marble drawn is red, out of all 12 marbles.", "Since the first marble isn't replaced, recompute the red marble probability out of the remaining 11 for the second draw, then multiply."],
    difficulty: 4,
    topicSlug: "probability",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-107",
    question: "In a game, two players alternately remove 1, 2, or 3 stones from a pile of 17 stones. The player who removes the last stone wins. Player A goes first. If both play perfectly, how many stones should Player A remove on the first turn to guarantee a win?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "4", "1", "3", "It cannot be determined"],
    answer: "C",
    solution: "Since each player can remove 1 to 3 stones, pile sizes that are multiples of 4 are losing positions for whoever must move next. Since 17 = 4 × 4 + 1, Player A should remove 1 stone to leave 16 stones (a multiple of 4) for Player B, and can then always respond to keep leaving multiples of 4.",
    hints: ["Think about which pile sizes are 'safe' to hand to your opponent — multiples of 4 are bad for whoever must move next, since the maximum removal is 3.", "Find how many stones need to be removed from 17 to reach the nearest multiple of 4 below it."],
    difficulty: 4,
    topicSlug: "games-and-strategies",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-108",
    question: "A committee of 3 people is chosen from a group of 7 people. How many different committees are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["21", "28", "35", "49", "42"],
    answer: "C",
    solution: "The number of ways to choose 3 people from 7, where order doesn't matter, is C(7,3) = (7 × 6 × 5) / (3 × 2 × 1) = 210 / 6 = 35.",
    hints: ["Since committee order doesn't matter, this is a combination, not a permutation.", "Use the combination formula for choosing 3 out of 7."],
    difficulty: 4,
    topicSlug: "combinatorics",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-109",
    question: "In how many ways can the letters of the word 'KANGA' be arranged, treating its two A's as identical?",
    format: "MULTIPLE_CHOICE",
    choices: ["60", "120", "90", "30", "20"],
    answer: "A",
    solution: "The word KANGA has 5 letters, with the letter A repeated twice. The number of distinct arrangements is 5! divided by 2! (to account for the repeated A's): 120 / 2 = 60.",
    hints: ["Start with 5! for arranging 5 distinct letters, then adjust for the repeated letter.", "Divide by 2! since the two A's are identical and swapping them doesn't create a new arrangement."],
    difficulty: 4,
    topicSlug: "permutations",
    competitionSlug: "math-kangaroo",
  },
  {
    slug: "kangaroo-110",
    question: "In a group of 30 students, everyone plays chess, checkers, or both. 22 students play chess and 15 play checkers. How many students play both games?",
    format: "MULTIPLE_CHOICE",
    choices: ["7", "5", "9", "6", "8"],
    answer: "A",
    solution: "By inclusion-exclusion, the number playing both is chess + checkers - total = 22 + 15 - 30 = 7.",
    hints: ["Adding the two group sizes double-counts students who play both games.", "Chess + Checkers - Total = Both."],
    difficulty: 4,
    topicSlug: "counting-principles",
    competitionSlug: "math-kangaroo",
  },
];
