import type { ProblemSeed } from "./problems";

/**
 * Hand-written problems styled after the two real MOEMS divisions.
 *
 * MOEMS contests are five short-answer problems, no calculator, no
 * multiple choice — so every problem here is phrased as a self-contained
 * word problem or scenario with a clean integer (occasionally simple
 * fraction) answer, the way an actual MOEMS contest reads. None of these
 * are transcribed from real MOEMS contests; they are original NumberSmith
 * problems written to match that format, phrasing, and difficulty band.
 *
 * Division E (moems-e) targets grades 2-6 and avoids algebraic notation —
 * everything is solvable by direct reasoning or arithmetic. Division M
 * (moems-m) targets grades 5-8 and allows the light pre-algebra, ratio, and
 * probability reasoning the real Division M expects.
 *
 * Seeded as practice (isPlacement: false), same as OLYMPIAD_PROBLEMS.
 */
export const MOEMS_PROBLEMS: ProblemSeed[] = [
  // ------------------------------ Division E ------------------------------
  {
    slug: "moems-e-01",
    question:
      "Ana is 3 years older than her brother Leo. The sum of their ages is 25. How old is Leo?",
    format: "INTEGER",
    answer: "11",
    solution: "Leo's age plus (Leo's age + 3) is 25, so twice Leo's age is 22, and Leo is 11.",
    hints: ["Write Ana's age in terms of Leo's age.", "Their ages add to 25 — subtract 3 first, then split what's left evenly."],
    difficulty: 1,
    topicSlug: "number-properties",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-02",
    question: "A pattern begins 4, 7, 10, 13, … and each number is 3 more than the one before it. What is the 10th number in the pattern?",
    format: "INTEGER",
    answer: "31",
    solution: "Starting at 4, reaching the 10th term takes 9 steps of +3, so the value is 4 + 9 × 3 = 31.",
    hints: ["You need 9 steps of +3 to get from the 1st term to the 10th term.", "4 + 9 × 3"],
    difficulty: 1,
    topicSlug: "patterns",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-03",
    question: "Maria has only nickels and dimes — 12 coins in all, worth exactly $1.00. How many dimes does she have?",
    format: "INTEGER",
    answer: "8",
    solution: "If all 12 were nickels that would be 60 cents, 40 cents short. Each nickel swapped for a dime adds 5 cents, so 40 ÷ 5 = 8 dimes.",
    hints: ["Start by imagining all 12 coins are nickels — how much would that be?", "Every time you trade a nickel for a dime, the total goes up by 5 cents."],
    difficulty: 2,
    topicSlug: "number-properties",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-04",
    question: "A rectangle has a perimeter of 36 cm, and its length is twice its width. What is the area of the rectangle, in square centimeters?",
    format: "INTEGER",
    answer: "72",
    solution: "Length + width is half the perimeter, 18. Since length is twice the width, 3 widths make 18, so width is 6 and length is 12. Area is 6 × 12 = 72.",
    hints: ["Half the perimeter is length + width.", "If length is twice the width, that half-perimeter is 3 widths."],
    difficulty: 2,
    topicSlug: "area-volume",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-05",
    question: "What is the smallest whole number greater than 100 that is divisible by both 6 and 8?",
    format: "INTEGER",
    answer: "120",
    solution: "A number divisible by both 6 and 8 must be divisible by their LCM, 24. The smallest multiple of 24 above 100 is 120.",
    hints: ["Find the smallest number divisible by both 6 and 8 — that's their LCM.", "List multiples of that LCM until you pass 100."],
    difficulty: 2,
    topicSlug: "divisibility",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-06",
    question: "How many two-digit numbers have digits that add up to 9?",
    format: "INTEGER",
    answer: "9",
    solution: "The tens digit can be 1 through 9, and the units digit is then fixed as 9 minus the tens digit (always 0-8), giving 9 numbers: 18, 27, 36, 45, 54, 63, 72, 81, 90.",
    hints: ["The tens digit can't be 0 — try each value 1 through 9 for it.", "Once the tens digit is chosen, the units digit is forced."],
    difficulty: 2,
    topicSlug: "number-properties",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-07",
    question: "Sam buys 3 notebooks and 2 pens for $13 total. Each pen costs $2. How much does one notebook cost, in dollars?",
    format: "INTEGER",
    answer: "3",
    solution: "Two pens cost $4, leaving $9 for 3 notebooks, so each notebook costs $9 ÷ 3 = $3.",
    hints: ["Find the total cost of the pens first.", "Subtract that from $13, then split the rest evenly among the notebooks."],
    difficulty: 1,
    topicSlug: "number-properties",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-08",
    question:
      "One square made of toothpicks uses 4 toothpicks. Two squares in a row share one side and use 7 toothpicks. Three squares in a row use 10 toothpicks. Following this pattern, how many toothpicks are needed for 8 squares in a row?",
    format: "INTEGER",
    answer: "25",
    solution: "Each new square after the first adds 3 toothpicks (one shared side saves one). So 8 squares use 4 + 7 × 3 = 25 toothpicks.",
    hints: ["The first square costs 4 toothpicks; every square after that only adds 3 more.", "4 + 3 × (8 − 1)"],
    difficulty: 2,
    topicSlug: "patterns",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-09",
    question:
      "Four friends — Al, Ben, Cam, and Dan — lined up for lunch. Cam is first in line. Al is right behind Ben. Dan is somewhere behind Al. Who is last in line?",
    format: "SHORT_ANSWER",
    answer: "Dan",
    solution: "Cam must be 1st. \"Al right behind Ben\" forces Ben then Al as consecutive spots, and Dan is behind Al — with only 4 people, the order is Cam, Ben, Al, Dan.",
    hints: ["Place Cam first, since that's given directly.", "\"Right behind\" means directly next in line, with no one in between."],
    difficulty: 1,
    topicSlug: "logical-puzzles",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-10",
    question: "What is the greatest 3-digit number that is a multiple of 7?",
    format: "INTEGER",
    answer: "994",
    solution: "999 ÷ 7 is about 142.7, and 142 × 7 = 994, which is the largest multiple of 7 that is still a 3-digit number.",
    hints: ["Divide 999 by 7 and ignore the remainder.", "Multiply that whole number back by 7."],
    difficulty: 1,
    topicSlug: "divisibility",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-11",
    question: "A pizza is cut into 8 equal slices. Ben eats 3 slices and Lucy eats 2 slices. What fraction of the pizza is left, in lowest terms?",
    format: "SHORT_ANSWER",
    answer: "3/8",
    solution: "Together they ate 5 of the 8 slices, leaving 3 slices out of 8, which is already in lowest terms.",
    hints: ["Add up how many slices were eaten in total.", "Subtract that from the 8 total slices."],
    difficulty: 1,
    topicSlug: "fractions",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-12",
    question: "The average of four numbers is 15. Three of the numbers are 10, 12, and 16. What is the fourth number?",
    format: "INTEGER",
    answer: "22",
    solution: "Four numbers averaging 15 sum to 60. The three known numbers sum to 38, so the fourth is 60 − 38 = 22.",
    hints: ["An average of 15 over 4 numbers means their total is 15 × 4.", "Subtract the three known numbers from that total."],
    difficulty: 2,
    topicSlug: "averages",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-13",
    question: "Using only the letters A, B, and C, and allowing letters to repeat, how many different 2-letter codes can be made?",
    format: "INTEGER",
    answer: "9",
    solution: "There are 3 choices for the first letter and 3 choices for the second letter, so 3 × 3 = 9 codes.",
    hints: ["How many choices are there for each of the 2 letters?", "Multiply the number of choices together."],
    difficulty: 1,
    topicSlug: "counting-principles",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-14",
    question: "A large equilateral triangle with side length 4 is divided into small equilateral triangles with side length 1. How many small triangles are there in total?",
    format: "INTEGER",
    answer: "16",
    solution: "Dividing a side-n equilateral triangle this way always produces n² small triangles; here n = 4, so there are 16.",
    hints: ["Try drawing (or imagining) the same split for a smaller triangle of side 2 or 3 first — count the small triangles there.", "The count follows a square-number pattern based on the side length."],
    difficulty: 2,
    topicSlug: "area-volume",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-15",
    question: "Ivy thought of a number, doubled it, then added 6, and got 30. What number did she start with?",
    format: "INTEGER",
    answer: "12",
    solution: "Undo the steps in reverse: 30 − 6 = 24, and 24 ÷ 2 = 12.",
    hints: ["Work backward from 30, undoing the last step first.", "Subtract 6, then undo the doubling by dividing by 2."],
    difficulty: 1,
    topicSlug: "number-properties",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-16",
    question: "What is the sum of the first 10 odd numbers: 1 + 3 + 5 + … + 19?",
    format: "INTEGER",
    answer: "100",
    solution: "The sum of the first n odd numbers is always n². With n = 10, the sum is 10² = 100.",
    hints: ["Try adding the first few odd numbers and see what pattern the totals make (1, then 1+3, then 1+3+5, ...).", "Those totals are all perfect squares."],
    difficulty: 2,
    topicSlug: "number-patterns",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-17",
    question:
      "A drawer has 6 red socks and 6 blue socks, all mixed together and unmatched. Without looking, what is the fewest socks you must pull out to be sure you have a matching pair?",
    format: "INTEGER",
    answer: "3",
    solution: "In the worst case the first two socks are one of each color. The third sock must match one of them, since there are only two colors.",
    hints: ["Think about the worst possible luck — what's the longest you could go without a matching pair?", "There are only 2 colors to worry about."],
    difficulty: 2,
    topicSlug: "pigeonhole",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-18",
    question: "Eggs are sold in cartons of 12 for $3 per carton. How many dollars would it cost to buy exactly 60 eggs?",
    format: "INTEGER",
    answer: "15",
    solution: "60 eggs is 60 ÷ 12 = 5 cartons, and 5 cartons cost 5 × $3 = $15.",
    hints: ["Figure out how many cartons make 60 eggs.", "Multiply the number of cartons by the price per carton."],
    difficulty: 1,
    topicSlug: "rates",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-19",
    question: "A 2-digit number has digits that add up to 11. Its tens digit is 3 more than its units digit. What is the number?",
    format: "INTEGER",
    answer: "74",
    solution: "If the units digit is u, the tens digit is u + 3, and their sum is 2u + 3 = 11, so u = 4 and the tens digit is 7 — the number is 74.",
    hints: ["Let the units digit be some number, and write the tens digit in terms of it.", "Their sum is 11 — solve for the units digit first."],
    difficulty: 2,
    topicSlug: "number-properties",
    competitionSlug: "moems-e",
  },
  {
    slug: "moems-e-20",
    question:
      "A rectangular garden is 9 meters long and 5 meters wide. A 1-meter-wide path runs around the inside edge of the garden, leaving a smaller rectangular flower bed in the middle. What is the area of the flower bed, in square meters?",
    format: "INTEGER",
    answer: "21",
    solution: "The path eats 1 meter off each side, so the flower bed is (9 − 2) by (5 − 2), which is 7 by 3, an area of 21.",
    hints: ["The path takes 1 meter off of every edge — that's 2 meters total off each dimension.", "7 × 3"],
    difficulty: 2,
    topicSlug: "area-volume",
    competitionSlug: "moems-e",
  },

  // ------------------------------ Division M ------------------------------
  {
    slug: "moems-m-01",
    question: "At a shelter, the ratio of cats to dogs is 3:5. If there are 40 animals total, how many more dogs than cats are there?",
    format: "INTEGER",
    answer: "10",
    solution: "3 + 5 = 8 parts make up the 40 animals, so each part is 5. Cats are 15 and dogs are 25, a difference of 10.",
    hints: ["Add the ratio parts to find how many animals one part represents.", "Cats are 3 parts, dogs are 5 parts."],
    difficulty: 2,
    topicSlug: "ratios-proportions",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-02",
    question: "A shirt originally costs $40 and is on sale for 25% off. What is the sale price, in dollars?",
    format: "INTEGER",
    answer: "30",
    solution: "25% off means paying 75% of the price: 40 × 0.75 = 30.",
    hints: ["25% off means you pay the remaining 75%.", "40 × 0.75"],
    difficulty: 2,
    topicSlug: "percentages",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-03",
    question: "Three times a number, decreased by 7, equals 20. What is the number?",
    format: "INTEGER",
    answer: "9",
    solution: "3x − 7 = 20, so 3x = 27, and x = 9.",
    hints: ["Add 7 to both sides first.", "Then divide by 3."],
    difficulty: 2,
    topicSlug: "linear-equations",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-04",
    question: "A circle has a circumference of 62.8 cm. Using π ≈ 3.14, what is its radius, in centimeters?",
    format: "INTEGER",
    answer: "10",
    solution: "Circumference is 2πr, so r = 62.8 ÷ (2 × 3.14) = 62.8 ÷ 6.28 = 10.",
    hints: ["Circumference equals 2πr.", "Divide the circumference by 2π."],
    difficulty: 3,
    topicSlug: "circles",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-05",
    question: "How many different 3-letter arrangements (order matters, no repeats) can be made from the letters in the word MATH?",
    format: "INTEGER",
    answer: "24",
    solution: "There are 4 choices for the first letter, 3 for the second, and 2 for the third: 4 × 3 × 2 = 24.",
    hints: ["MATH has 4 distinct letters — how many ways to pick and order 3 of them?", "4 × 3 × 2"],
    difficulty: 3,
    topicSlug: "permutations",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-06",
    question: "What is the sum of all positive divisors of 36?",
    format: "INTEGER",
    answer: "91",
    solution: "The divisors of 36 are 1, 2, 3, 4, 6, 9, 12, 18, and 36, which sum to 91.",
    hints: ["List every number that divides 36 evenly.", "Add them all up."],
    difficulty: 3,
    topicSlug: "divisibility",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-07",
    question:
      "A bag holds 4 red marbles, 3 blue marbles, and 5 green marbles. One marble is drawn at random. What is the probability it is NOT green, as a fraction in lowest terms?",
    format: "SHORT_ANSWER",
    answer: "7/12",
    solution: "There are 12 marbles total and 7 that are not green (4 red + 3 blue), giving a probability of 7/12, already in lowest terms.",
    hints: ["Count the marbles that are red or blue.", "Divide by the total number of marbles."],
    difficulty: 2,
    topicSlug: "basic-probability",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-08",
    question: "Pipe A can fill a tank in 6 hours by itself, and Pipe B can fill it in 3 hours by itself. Working together, how many hours would it take them to fill the tank?",
    format: "INTEGER",
    answer: "2",
    solution: "A fills 1/6 of the tank per hour and B fills 1/3, so together they fill 1/6 + 2/6 = 1/2 per hour, meaning the tank fills in 2 hours.",
    hints: ["Write each pipe's rate as a fraction of the tank per hour.", "Add the rates, then find the time as 1 divided by the combined rate."],
    difficulty: 3,
    topicSlug: "rates",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-09",
    question: "Two similar triangles have corresponding sides in ratio 2:5. If the smaller triangle's perimeter is 18, what is the larger triangle's perimeter?",
    format: "INTEGER",
    answer: "45",
    solution: "Similar triangles scale every length — including the perimeter — by the same ratio: 18 × (5/2) = 45.",
    hints: ["The ratio of similarity applies to the whole perimeter, not just one side.", "Multiply 18 by 5/2."],
    difficulty: 2,
    topicSlug: "similarity-congruence",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-10",
    question: "Two warning lights blink together at time 0. One blinks every 8 seconds and the other every 12 seconds. After how many seconds will they next blink together?",
    format: "INTEGER",
    answer: "24",
    solution: "They blink together again at every common multiple of 8 and 12; the smallest such time is their LCM, 24 seconds.",
    hints: ["You need the smallest number that both 8 and 12 divide into evenly.", "That's the least common multiple."],
    difficulty: 2,
    topicSlug: "divisibility",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-11",
    question: "A pen costs $2 more than a pencil. Together, 2 pens and 3 pencils cost $19. What does one pencil cost, in dollars?",
    format: "INTEGER",
    answer: "3",
    solution: "If a pencil costs p, a pen costs p + 2. Then 2(p + 2) + 3p = 19 gives 5p + 4 = 19, so p = 3.",
    hints: ["Write the pen's price in terms of the pencil's price.", "Substitute into the total-cost equation and solve for the pencil."],
    difficulty: 3,
    topicSlug: "linear-equations",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-12",
    question: "A committee of 3 people is chosen from a group of 7 people, where order doesn't matter. How many different committees are possible?",
    format: "INTEGER",
    answer: "35",
    solution: "This is 7 choose 3, which is 7! / (3! × 4!) = 35.",
    hints: ["Order doesn't matter here, so this is a combination, not a permutation.", "7 choose 3 = (7 × 6 × 5) / (3 × 2 × 1)"],
    difficulty: 3,
    topicSlug: "combinations",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-13",
    question:
      "A square has an area of 64 square inches. A circle is inscribed in the square, touching all four sides. Using π ≈ 3.14, what is the area of the circle, rounded to the nearest whole number?",
    format: "INTEGER",
    answer: "50",
    solution: "The square's side is 8, so the inscribed circle has radius 4. Its area is 3.14 × 4² = 50.24, which rounds to 50.",
    hints: ["Find the side length of the square first.", "The inscribed circle's diameter equals the square's side length."],
    difficulty: 4,
    topicSlug: "circles",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-14",
    question: "In the sequence 2, 6, 18, 54, … each term is 3 times the term before it. What is the 7th term?",
    format: "INTEGER",
    answer: "1458",
    solution: "This is a geometric sequence with first term 2 and ratio 3, so the 7th term is 2 × 3⁶ = 2 × 729 = 1458.",
    hints: ["Each term is the first term times the ratio raised to some power.", "The 7th term uses the ratio raised to the 6th power."],
    difficulty: 3,
    topicSlug: "sequences",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-15",
    question: "There are 40 students in a class, and each was born in one of 12 months. What is the minimum number of students guaranteed to share the same birth month?",
    format: "INTEGER",
    answer: "4",
    solution: "If every month had at most 3 students, that would cover only 36 students. With 40 students, at least one month must have 4 or more.",
    hints: ["Ask: what's the most students you could have with no month repeated 4 times?", "12 months × 3 students = 36, which isn't enough to cover 40."],
    difficulty: 4,
    topicSlug: "pigeonhole",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-16",
    question: "A bacteria population grows by 50% every hour. Starting at 200, what will the population be after 2 hours?",
    format: "INTEGER",
    answer: "450",
    solution: "Growing by 50% each hour multiplies the population by 1.5 each time: 200 × 1.5 × 1.5 = 450.",
    hints: ["Growing by 50% means multiplying by 1.5.", "Apply that multiplication twice, once per hour."],
    difficulty: 3,
    topicSlug: "percentages",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-17",
    question: "What is the largest prime factor of 315?",
    format: "INTEGER",
    answer: "7",
    solution: "315 = 3² × 5 × 7, so its largest prime factor is 7.",
    hints: ["Start dividing 315 by small primes: 3, then 3 again, then keep going.", "Once you can't divide by small primes anymore, what's left?"],
    difficulty: 2,
    topicSlug: "primes",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-18",
    question:
      "In a triangle, one angle is twice a second angle, and the third angle is 20° more than the second angle. What is the measure, in degrees, of the smallest angle?",
    format: "INTEGER",
    answer: "40",
    solution: "Let the second angle be x. Then the angles are x, 2x, and x + 20, summing to 4x + 20 = 180, so x = 40. The three angles are 80°, 40°, and 60° — the smallest is 40°.",
    hints: ["Write all three angles in terms of one unknown.", "The three angles of a triangle always sum to 180°."],
    difficulty: 3,
    topicSlug: "angles",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-19",
    question: "A car travels 180 miles in 3 hours, then 140 miles in 2 hours. What is its average speed, in miles per hour, for the entire trip?",
    format: "INTEGER",
    answer: "64",
    solution: "Total distance is 320 miles over a total time of 5 hours, so average speed is 320 ÷ 5 = 64 mph.",
    hints: ["Average speed uses total distance divided by total time — not the average of the two speeds.", "Add both distances and both times separately first."],
    difficulty: 2,
    topicSlug: "rates",
    competitionSlug: "moems-m",
  },
  {
    slug: "moems-m-20",
    question: "How many positive integers less than 100 are multiples of 3 or multiples of 5?",
    format: "INTEGER",
    answer: "46",
    solution: "There are 33 multiples of 3 and 19 multiples of 5 below 100, and 6 multiples of 15 (counted twice), so 33 + 19 − 6 = 46.",
    hints: ["Count the multiples of 3 and the multiples of 5 separately first.", "Numbers that are multiples of both get double-counted — subtract those once."],
    difficulty: 4,
    topicSlug: "inclusion-exclusion",
    competitionSlug: "moems-m",
  },
];
