import type { ProblemSeed } from "./problems";

/**
 * Hand-written problems styled after the AMC 12 (American Mathematics
 * Competitions, grade ≤12) — the hardest of the AMC family, layering
 * logarithms, trigonometry, complex numbers, and advanced sequences on
 * top of the AMC 10 topic base. Every problem below is an original
 * NumberSmith problem, written to match the phrasing conventions and
 * difficulty ramp of a real AMC 12 exam; none are transcribed, closely
 * paraphrased, or numerically reskinned from any official AMC/AHSME
 * contest. Difficulty rises from about 5 (problem 1) to 10 (problem 32),
 * with genuinely difficult multi-step algebra, trig identities, complex
 * numbers, and advanced counting/number-theory dominating the back half.
 *
 * Seeded as practice (isPlacement: false), same as the other
 * competition-tagged problem sets.
 */
export const AMC12_PROBLEMS: ProblemSeed[] = [
  {
    slug: "amc12-01",
    question:
      "A store marks up the price of a bicycle by 40%, then later applies a 25% discount to the marked-up price during a sale. The sale price turns out to be $6 more than the bicycle's original price. What was the original price of the bicycle, in dollars?",
    format: "MULTIPLE_CHOICE",
    choices: ["120", "100", "110", "130", "150"],
    answer: "A",
    solution:
      "Let the original price be p. Marking up by 40% gives 1.4p, and then discounting that by 25% gives 1.4p × 0.75 = 1.05p. Setting the sale price $6 above the original price: 1.05p - p = 6, so 0.05p = 6, giving p = 120.",
    hints: [
      "Apply the markup and discount as successive multipliers on p.",
      "The combined effect of a 40% increase then a 25% decrease is a single multiplier of 1.05 — set 1.05p - p equal to 6.",
    ],
    difficulty: 5,
    topicSlug: "percentages",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-02",
    question:
      "The ratio of pencils to pens in a drawer is 7:4. After 6 pencils are removed and 6 pens are added, the ratio of pencils to pens becomes 1:1. How many pencils were originally in the drawer?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "28", "21", "32", "35"],
    answer: "B",
    solution:
      "Let the pencils be 7x and the pens be 4x. After the changes, (7x - 6)/(4x + 6) = 1, so 7x - 6 = 4x + 6, giving 3x = 12 and x = 4. There were originally 7(4) = 28 pencils.",
    hints: [
      "Represent the original counts as 7x and 4x for some positive x.",
      "Set up an equation from the new ratio being 1:1 and solve for x.",
    ],
    difficulty: 5,
    topicSlug: "ratios-proportions",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-03",
    question: "Two crates have a combined weight of 58 kilograms, and one is 12 kilograms heavier than the other. What is the product of their two weights?",
    format: "MULTIPLE_CHOICE",
    choices: ["780", "793", "805", "812", "840"],
    answer: "C",
    solution: "The weights sum to 58 and differ by 12, so they are (58+12)/2 = 35 and (58−12)/2 = 23. Their product is 35 × 23 = 805.",
    hints: ["Add and subtract the two facts to isolate each weight.", "Half the sum plus half the difference gives the larger weight."],
    difficulty: 5,
    topicSlug: "linear-equations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-04",
    question:
      "A two-digit number and the number formed by reversing its digits have a sum of 143. The tens digit of the original number is 3 more than its units digit. What is the original number?",
    format: "MULTIPLE_CHOICE",
    choices: ["58", "67", "74", "85", "96"],
    answer: "D",
    solution:
      "Let the number be 10a + b, where a is the tens digit and b the units digit. Its reverse is 10b + a, and the sum is 11(a + b) = 143, so a + b = 13. Since a = b + 3, substituting gives 2b + 3 = 13, so b = 5 and a = 8. The original number is 85.",
    hints: [
      "Write the number as 10a + b and its reverse as 10b + a; their sum simplifies nicely.",
      "Combine a + b = 13 with a = b + 3 to solve for each digit.",
    ],
    difficulty: 5,
    topicSlug: "number-properties",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-05",
    question: "A kite is cut as a triangle in which the first corner measures 20 degrees more than the second corner, and the third corner is twice the second. How many degrees is the third corner?",
    format: "MULTIPLE_CHOICE",
    choices: ["60", "65", "70", "75", "80"],
    answer: "E",
    solution: "Let the second corner be b. The first is b + 20 and the third is 2b. Summing to 180: (b+20) + b + 2b = 180, so 4b = 160 and b = 40. The third corner is 2(40) = 80 degrees.",
    hints: ["Write all three corners in terms of the second one.", "Solve for that corner, then double it."],
    difficulty: 5,
    topicSlug: "triangles",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-06",
    question: "A rectangular tarp has a perimeter of 18 meters, and its length exceeds its width by 3 meters. What is its area, in square meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["16", "18", "20", "14", "22"],
    answer: "B",
    solution: "The length and width sum to 9 and differ by 3, so they are 6 and 3. The area is 6 × 3 = 18 square meters.",
    hints: ["Halve the perimeter to get the sum of the dimensions.", "Use the sum and difference to recover both dimensions."],
    difficulty: 6,
    topicSlug: "quadratics",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-07",
    question: "A shop's weekly sales over 15 weeks increase by the same amount each week. The first 5 weeks total 50 items and the last 5 weeks total 200 items. How many items does the shop sell over all 15 weeks?",
    format: "MULTIPLE_CHOICE",
    choices: ["350", "360", "390", "375", "400"],
    answer: "D",
    solution: "In an evenly increasing run of 15 weeks, the three blocks of 5 weeks themselves increase by a constant amount. Since the first block is 50 and the last is 200, the middle block is their average, 125. The total is 50 + 125 + 200 = 375 items.",
    hints: ["Group the 15 weeks into three blocks of 5.", "Those three block totals also increase by a constant amount, so the middle one is the average of the outer two."],
    difficulty: 6,
    topicSlug: "sequences",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-08",
    question: "A culture triples in size every hour. After a hours it is exactly 7 times its starting size, and after b hours it is exactly 63 times its starting size. What is the value of b − a?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "1", "3", "4", "0"],
    answer: "A",
    solution: "The conditions say 3^a = 7 and 3^b = 63. Dividing, 3^(b−a) = 63/7 = 9 = 3², so b − a = 2.",
    hints: ["Divide the two growth equations to eliminate the unknown exponents individually.", "The quotient is a power of 3."],
    difficulty: 6,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-09",
    question: "A circular rug is laid in a square room with 12-foot sides so that it just touches all four walls. How many square feet of floor remain uncovered?",
    format: "MULTIPLE_CHOICE",
    choices: ["108 - 36π", "72 - 36π", "144 - 36π", "36π - 144", "144 - 18π"],
    answer: "C",
    solution: "The square's area is 12² = 144. The rug's diameter is 12, so its radius is 6 and its area is 36π. The uncovered floor measures 144 − 36π square feet.",
    hints: ["Touching all four walls means the rug's diameter equals the room's side.", "Subtract the rug's area from the room's area."],
    difficulty: 6,
    topicSlug: "circles",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-10",
    question:
      "A password consists of 4 characters: the first two are distinct letters chosen from {A, B, C, D, E}, and the last two are distinct digits chosen from {1, 2, 3, 4, 5, 6}. How many such passwords are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["450", "500", "550", "580", "600"],
    answer: "E",
    solution:
      "There are 5 × 4 = 20 ways to choose the two distinct letters in order, and 6 × 5 = 30 ways to choose the two distinct digits in order. By the multiplication principle, the total number of passwords is 20 × 30 = 600.",
    hints: [
      "Count the ordered choices for the letter positions and digit positions separately.",
      "Multiply the two counts together.",
    ],
    difficulty: 6,
    topicSlug: "counting-principles",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-11",
    question: "A taxi's fare rises at a steady rate with distance. At 3 kilometers the fare is $11, and at 7 kilometers it is $23. What would the fare be at 0 kilometers, that is, the amount charged before any distance is driven?",
    format: "MULTIPLE_CHOICE",
    choices: ["0", "2", "1", "3", "4"],
    answer: "B",
    solution: "The rate is (23 − 11)/(7 − 3) = 3 dollars per kilometer. From the point (3, 11), the fare is y − 11 = 3(x − 3), so y = 3x + 2. At x = 0 the fare is $2.",
    hints: ["Find the per-kilometer rate from the two given fares.", "Extend the line back to zero distance."],
    difficulty: 6,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-12",
    question: "A currency kiosk converts any amount x by tripling it and then deducting a $4 fee. A traveler passes an amount through the kiosk twice in a row and ends with $11. What amount did the traveler start with?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "2", "3", "4", "5"],
    answer: "C",
    solution: "One pass gives 3a − 4, and a second gives 3(3a − 4) − 4 = 9a − 16. Setting 9a − 16 = 11 gives 9a = 27, so a = 3.",
    hints: ["Apply the rule once, then feed the result back into the same rule.", "Simplify to a single linear equation in the starting amount."],
    difficulty: 6,
    topicSlug: "functions",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-13",
    question: "A rectangular box has a volume, in cubic units, of x³ − 6x² + 11x − 6, and its three dimensions are x minus a real number in each case. Squares are built on each of those three subtracted numbers. What is the total area of the three squares?",
    format: "MULTIPLE_CHOICE",
    choices: ["14", "10", "12", "16", "18"],
    answer: "A",
    solution: "The polynomial factors as (x−1)(x−2)(x−3), so the three numbers are 1, 2, and 3. The squares have areas 1, 4, and 9, totaling 14.",
    hints: ["Factor the cubic to find the three numbers.", "Square each and add."],
    difficulty: 7,
    topicSlug: "polynomials",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-14",
    question: "Two fair six-sided dice are rolled. What is the probability that the sum of the two dice is a prime number?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/3", "7/18", "4/9", "5/12", "11/36"],
    answer: "D",
    solution:
      "The possible prime sums are 2, 3, 5, 7, and 11. Counting outcomes: sum 2 has 1 way, sum 3 has 2 ways, sum 5 has 4 ways, sum 7 has 6 ways, and sum 11 has 2 ways, for a total of 1 + 2 + 4 + 6 + 2 = 15 favorable outcomes out of 36. The probability is 15/36 = 5/12.",
    hints: [
      "List the prime numbers that are achievable as a sum of two dice (between 2 and 12).",
      "Count the outcomes for each prime sum separately, then add them and divide by 36.",
    ],
    difficulty: 7,
    topicSlug: "basic-probability",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-15",
    question: "A shop's window sign is spelled out using the seven letter tiles A, L, G, E, B, R, A placed in a row. How many distinguishable signs put the two A tiles side by side?",
    format: "MULTIPLE_CHOICE",
    choices: ["600", "720", "360", "840", "5040"],
    answer: "B",
    solution: "Treat the pair of A tiles as a single block. That leaves 6 units to arrange — the block plus L, G, E, B, R — giving 6! = 720 orders. The two A tiles are identical, so swapping them within the block produces nothing new.",
    hints: ["Glue the two A tiles together into one unit.", "Count arrangements of the resulting units, remembering the A tiles are indistinguishable."],
    difficulty: 7,
    topicSlug: "permutations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-16",
    question: "A culture starts with 1 organism and triples every hour. After 2023 hours the organisms are packed into containers of 13, as many full containers as possible. How many organisms are left over?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "9", "10", "12", "3"],
    answer: "E",
    solution: "We need the remainder of 3²⁰²³ upon division by 13. Since 3³ = 27 leaves remainder 1, the remainders repeat every 3 hours. As 2023 leaves remainder 1 upon division by 3, the leftover matches that of 3¹, which is 3.",
    hints: ["Find the cycle length of the remainders of powers of 3 upon division by 13.", "Reduce 2023 by that cycle length."],
    difficulty: 7,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-17",
    question: "A triangular sail has a seam parallel to its 25-foot bottom edge. The seam divides the left edge into an upper piece of 6 feet and a lower piece of 9 feet. How long is the seam, in feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["8", "9", "10", "12", "15"],
    answer: "C",
    solution: "The triangle above the seam is similar to the whole sail, with ratio 6/(6+9) = 6/15 = 2/5. The seam is therefore 25 × (2/5) = 10 feet long.",
    hints: ["The parallel seam creates a triangle similar to the whole sail.", "Compare the full left edge to its upper piece to get the ratio."],
    difficulty: 7,
    topicSlug: "similarity-congruence",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-18",
    question: "A hiking trail's elevation relative to a lodge, in meters, at marker n is given by n² − 7n − 30, where markers before the lodge carry negative numbers. For how many integer markers is the trail below the lodge's elevation?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "10", "11", "13", "14"],
    answer: "A",
    solution: "Factoring gives (n − 10)(n + 3), which is negative exactly when −3 < n < 10. The integers from −2 through 9 number 9 − (−2) + 1 = 12.",
    hints: ["Factor the quadratic to find where it changes sign.", "Count integers strictly between the two roots."],
    difficulty: 7,
    topicSlug: "inequalities",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-19",
    question: "A party hat is a cone whose slanted side measures 10 inches from rim to tip and whose tip stands 8 inches above the center of the rim. What is the volume of the hat, in cubic inches?",
    format: "MULTIPLE_CHOICE",
    choices: ["72π", "84π", "108π", "96π", "120π"],
    answer: "D",
    solution: "The rim radius satisfies r² + 8² = 10², so r = 6. The volume is (1/3)π(6²)(8) = (1/3)π(36)(8) = 96π cubic inches.",
    hints: ["The slant, the height, and the radius form a right triangle.", "Find the radius first, then use the cone volume formula."],
    difficulty: 7,
    topicSlug: "area-volume",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-20",
    question: "A garden plot is shaped like an isosceles trapezoid whose two parallel sides measure 15 and 25 meters, with the two slanted sides each 13 meters. What is the area of the plot, in square meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["200", "240", "220", "260", "280"],
    answer: "B",
    solution: "Each slanted side overhangs by (25 − 15)/2 = 5 meters, so the height satisfies 5² + h² = 13², giving h = 12. The area is ((15 + 25)/2)(12) = 20 × 12 = 240 square meters.",
    hints: ["Drop perpendiculars from the shorter parallel side to split off two right triangles.", "Find the height, then use the trapezoid area formula."],
    difficulty: 7,
    topicSlug: "quadrilaterals",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-21",
    question: "A ramp meets the ground at an acute angle θ. For this angle, the sine and the cosine add to 7/5. What is the product of the sine and the cosine?",
    format: "MULTIPLE_CHOICE",
    choices: ["7/25", "24/25", "1/2", "13/25", "12/25"],
    answer: "E",
    solution: "Squaring, (sin θ + cos θ)² = sin²θ + cos²θ + 2 sin θ cos θ = 1 + 2 sin θ cos θ = 49/25. So 2 sin θ cos θ = 24/25 and sin θ cos θ = 12/25.",
    hints: ["Square the given sum.", "Use the identity that the squares of sine and cosine add to 1."],
    difficulty: 8,
    topicSlug: "functions",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-22",
    question: "In an alternating-current circuit, one component's impedance is z = 3 + 4i ohms. A designer computes the combination z² − 2z + 5. What is the magnitude of the result, in ohms?",
    format: "MULTIPLE_CHOICE",
    choices: ["8√5", "4√5", "16", "8√3", "10√3"],
    answer: "A",
    solution: "First z² = (3+4i)² = 9 + 24i − 16 = −7 + 24i. Then z² − 2z + 5 = (−7 + 24i) − (6 + 8i) + 5 = −8 + 16i. Its magnitude is √(64 + 256) = √320 = 8√5.",
    hints: ["Compute z² first, then subtract 2z and add 5.", "The magnitude is the square root of the sum of the squares of the two parts."],
    difficulty: 8,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-23",
    question:
      "A committee of 5 people is chosen from 6 married couples (12 people total), with the restriction that no two people from the same couple can both be on the committee. How many such committees are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["132", "160", "192", "216", "252"],
    answer: "C",
    solution:
      "Since the committee has 5 people and no couple may be fully represented, it must draw exactly one person from each of 5 different couples out of the 6. There are C(6,5) = 6 ways to choose which couples contribute, and 2 choices for which member of each chosen couple joins, giving 2⁵ = 32 ways. The total is 6 × 32 = 192.",
    hints: [
      "With only 5 people and no couple doubled up, the committee must use exactly 5 of the 6 couples.",
      "Choose which couples are represented, then choose one person from each of those couples.",
    ],
    difficulty: 8,
    topicSlug: "combinations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-24",
    question:
      "A box contains 4 red balls and 6 blue balls. Two balls are drawn without replacement. Given that at least one of the two balls drawn is red, what is the probability that both balls are red?",
    format: "MULTIPLE_CHOICE",
    choices: ["2/9", "3/10", "1/3", "1/5", "2/5"],
    answer: "D",
    solution:
      "P(both red) = C(4,2)/C(10,2) = 6/45 = 2/15. P(no red) = C(6,2)/C(10,2) = 15/45 = 1/3, so P(at least one red) = 1 - 1/3 = 2/3. By the definition of conditional probability, P(both red | at least one red) = (2/15)/(2/3) = 1/5.",
    hints: [
      "Compute P(both red) and P(at least one red) separately using combinations.",
      "Divide the probability of both red by the probability of at least one red.",
    ],
    difficulty: 8,
    topicSlug: "conditional-probability",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-25",
    question: "Two square garden beds have side lengths that are positive whole numbers, and their areas differ by 105 square feet. How many different ordered pairs of side lengths are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "2", "5", "6"],
    answer: "B",
    solution: "With sides x and y, x² − y² = (x−y)(x+y) = 105. Since 105 is odd, every factor pair has both factors odd, and all four pairs (1,105), (3,35), (5,21), (7,15) give positive integer solutions. So there are 4 ordered pairs.",
    hints: ["Factor the difference of squares into a product of two factors.", "Each factor pair of 105 yields one solution, provided both sides come out positive integers."],
    difficulty: 8,
    topicSlug: "diophantine-equations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-26",
    question: "A meter reads 2 on the first day and 5 on the second day. From the third day onward, each reading equals 3 times the previous day's reading minus twice the reading from the day before that. What is the reading on the sixth day?",
    format: "MULTIPLE_CHOICE",
    choices: ["83", "89", "101", "107", "95"],
    answer: "E",
    solution: "Day 3: 3(5) − 2(2) = 11. Day 4: 3(11) − 2(5) = 23. Day 5: 3(23) − 2(11) = 47. Day 6: 3(47) − 2(23) = 95.",
    hints: ["Work forward one day at a time.", "Each step needs the two most recent readings."],
    difficulty: 8,
    topicSlug: "sequences",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-27",
    question: "A scoring rule assigns a value f(x) to every real input x, and it always satisfies f(x) + 2f(1 − x) = 3x². What value does the rule assign to the input 2?",
    format: "MULTIPLE_CHOICE",
    choices: ["-2", "0", "2", "4", "6"],
    answer: "A",
    solution: "Putting x = 2 gives f(2) + 2f(−1) = 12. Putting x = −1 gives f(−1) + 2f(2) = 3. Doubling the second equation gives 2f(−1) + 4f(2) = 6, and subtracting the first leaves 3f(2) = −6, so f(2) = −2.",
    hints: ["Substitute x = 2, then substitute the value of 1 − x that appeared.", "Solve the resulting pair of linear equations."],
    difficulty: 9,
    topicSlug: "functional-equations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-28",
    question: "Two beacons flash at regular whole-number intervals of seconds. They flash together every 360 seconds, and the largest interval dividing both of their intervals is 6 seconds. How many ordered pairs of intervals are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "6", "8", "10", "12"],
    answer: "C",
    solution: "Write the intervals as 6m and 6n with gcd(m,n) = 1 and lcm = 360, so mn = 60 with m and n coprime. Since 60 = 2²·3·5 has three distinct primes, each prime power goes entirely to one factor, giving 2³ = 8 ordered pairs.",
    hints: ["Factor out the common divisor 6 and reduce to a coprime pair.", "Each distinct prime power must belong wholly to one member of the pair."],
    difficulty: 9,
    topicSlug: "advanced-number-theory",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-29",
    question: "A shop offers 8 different toppings. A customer places two orders, a small and a large, each using any set of toppings including possibly none, with the rule that every topping on the small order must also appear on the large one. How many ordered pairs of orders are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["2187", "4096", "8192", "6561", "19683"],
    answer: "D",
    solution: "Decide each topping independently: it can be on neither order, on the large only, or on both. That is 3 choices per topping, for 3⁸ = 6561 pairs.",
    hints: ["Handle each topping independently rather than choosing whole sets.", "Each topping has three possible statuses."],
    difficulty: 9,
    topicSlug: "advanced-combinatorics",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-30",
    question: "A triangular plot has sides AB = 13, BC = 14, and CA = 15 meters. A circular pond is placed inside so that it touches all three sides, meeting side BC at point D. How many meters is D from corner B?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "7", "8", "9", "6"],
    answer: "E",
    solution: "The semiperimeter is s = (13 + 14 + 15)/2 = 21. The touch point on BC lies at distance s − AC = 21 − 15 = 6 meters from B.",
    hints: ["Tangent segments from a corner to the inscribed circle have equal length.", "That distance equals the semiperimeter minus the side opposite the corner."],
    difficulty: 9,
    topicSlug: "advanced-geometry",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-31",
    question: "Three positive quantities a, b, and c total 6, and the three pairwise products ab, bc, and ca total 9. What is the largest possible value of a?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "3.5", "4", "4.5", "5"],
    answer: "C",
    solution: "With b + c = 6 − a and bc = 9 − a(b+c) = 9 − a(6−a) = a² − 6a + 9, the quantities b and c are real when (b+c)² ≥ 4bc: (6−a)² ≥ 4(a² − 6a + 9), so 36 − 12a + a² ≥ 4a² − 24a + 36, giving 3a² ≤ 12a and a ≤ 4.",
    hints: ["Express the sum and product of b and c in terms of a.", "For b and c to be real, the discriminant condition must hold."],
    difficulty: 9,
    topicSlug: "inequalities-olympiad",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-32",
    question: "A rectangular box has a volume, in cubic units, of x³ − 6x² + 3x + 10, and its three dimensions are x minus a, x minus b, and x minus c. Cubes are built on each of a, b, and c. What is the total volume of the three cubes?",
    format: "MULTIPLE_CHOICE",
    choices: ["96", "132", "114", "150", "168"],
    answer: "B",
    solution: "From the coefficients, a+b+c = 6, ab+bc+ca = 3, and abc = −10. Then a³+b³+c³ = (a+b+c)³ − 3(a+b+c)(ab+bc+ca) + 3abc = 216 − 3(6)(3) + 3(−10) = 216 − 54 − 30 = 132.",
    hints: ["Read the three symmetric sums off the polynomial's coefficients.", "Use the identity expressing the sum of cubes in terms of those three sums."],
    difficulty: 10,
    topicSlug: "polynomials",
    competitionSlug: "amc12",
  },

// ============================= DIFFICULTY 5 =============================
  {
    slug: "amc12-33",
    question:
      "Machine A can complete a printing job in 10 hours working alone, and Machine B can complete the same job in 15 hours working alone. If both machines work together the entire time, how many hours will it take them to complete the job?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "7", "4", "6", "8"],
    answer: "D",
    solution:
      "Machine A's rate is 1/10 of the job per hour and Machine B's rate is 1/15 of the job per hour. Together their rate is 1/10 + 1/15 = 3/30 + 2/30 = 5/30 = 1/6 of the job per hour, so the job takes 6 hours.",
    hints: [
      "Convert each machine's time into a rate: jobs completed per hour.",
      "Add the two rates together, then take the reciprocal of the combined rate.",
    ],
    difficulty: 5,
    topicSlug: "rates",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-34",
    question:
      "A price is increased by 20% and then the new price is decreased by 20%. The final price is what percent of the original price?",
    format: "MULTIPLE_CHOICE",
    choices: ["94%", "90%", "100%", "98%", "96%"],
    answer: "E",
    solution:
      "Increasing by 20% multiplies the price by 1.2, and decreasing the result by 20% multiplies by 0.8. The combined effect is 1.2 × 0.8 = 0.96, so the final price is 96% of the original.",
    hints: [
      "Represent each percent change as a multiplier rather than computing amounts separately.",
      "Multiply the two multipliers together to get the overall factor.",
    ],
    difficulty: 5,
    topicSlug: "percentages",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-35",
    question: "A triangular bracket has two equal corner angles at D and E, and its third corner F measures 24 degrees more than the angle at D. How many degrees is the corner at F?",
    format: "MULTIPLE_CHOICE",
    choices: ["64°", "76°", "70°", "82°", "88°"],
    answer: "B",
    solution: "If D = E = d, then F = d + 24 and d + d + (d + 24) = 180, so 3d = 156 and d = 52. Thus F = 52 + 24 = 76 degrees.",
    hints: ["The two equal corners let you use one variable for both.", "Set the three angles' sum to 180."],
    difficulty: 5,
    topicSlug: "triangles",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-36",
    question: "A rectangular banner has a perimeter of 26 feet, and both side lengths are whole numbers with the longer exceeding the shorter by 5 feet. What is its area, in square feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["36", "30", "32", "40", "42"],
    answer: "A",
    solution: "The sides sum to 13 and differ by 5, so they are 9 and 4. The area is 9 × 4 = 36 square feet.",
    hints: ["Halve the perimeter to get the sum of the sides.", "Combine that sum with the difference of 5."],
    difficulty: 5,
    topicSlug: "quadratics",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-37",
    question: "A theater's first row has 7 seats, and each row behind it has 5 more seats than the row in front. How many seats are in the 20th row?",
    format: "MULTIPLE_CHOICE",
    choices: ["97", "107", "112", "100", "102"],
    answer: "E",
    solution: "Row 20 has had 19 increases of 5: 7 + 5(19) = 7 + 95 = 102 seats.",
    hints: ["Count how many increases separate row 1 from row 20.", "There are 19 increases, not 20."],
    difficulty: 5,
    topicSlug: "sequences",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-38",
    question: "Two fair six-sided dice are rolled. What is the probability that the sum of the two dice is 8?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/6", "5/36", "7/36", "5/18", "1/9"],
    answer: "B",
    solution:
      "There are 36 equally likely outcomes. The pairs summing to 8 are (2,6), (3,5), (4,4), (5,3), (6,2), which is 5 outcomes. The probability is 5/36.",
    hints: [
      "List the ordered pairs of dice rolls that sum to 8.",
      "Divide the number of favorable outcomes by the total of 36 outcomes.",
    ],
    difficulty: 5,
    topicSlug: "basic-probability",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-39",
    question: "A straight footbridge crosses a circular pond of radius 13 meters, passing 5 meters from the pond's center at its closest approach. How many meters of the bridge lie over the water?",
    format: "MULTIPLE_CHOICE",
    choices: ["22", "28", "26", "20", "24"],
    answer: "E",
    solution: "Half the span satisfies 5² + h² = 13², so h = 12. The full span over water is 2(12) = 24 meters.",
    hints: ["The perpendicular from the center bisects the span over water.", "Use the Pythagorean theorem with the radius as hypotenuse."],
    difficulty: 5,
    topicSlug: "circles",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-40",
    question: "A street's houses are numbered with two-digit numbers. How many of those house numbers have digits adding to 12?",
    format: "MULTIPLE_CHOICE",
    choices: ["7", "8", "5", "6", "9"],
    answer: "A",
    solution: "Listing the two-digit numbers whose digits sum to 12: 39, 48, 57, 66, 75, 84, 93 — seven of them.",
    hints: ["Let the tens digit run from 1 to 9 and see which give a valid units digit.", "The units digit must stay between 0 and 9."],
    difficulty: 5,
    topicSlug: "number-properties",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-41",
    question:
      "A solution is 30% acid by volume. How many liters of pure acid must be added to 10 liters of this solution to make a solution that is 50% acid?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "2", "3", "6", "5"],
    answer: "A",
    solution:
      "The original solution has 0.3(10) = 3 liters of acid. Adding x liters of pure acid gives (3 + x) liters of acid in (10 + x) liters total. Setting (3 + x)/(10 + x) = 0.5 gives 3 + x = 5 + 0.5x, so 0.5x = 2 and x = 4.",
    hints: [
      "Track the amount of pure acid separately from the total volume.",
      "Set up the equation (acid amount)/(total volume) = 0.5 and solve for x.",
    ],
    difficulty: 5,
    topicSlug: "ratios-proportions",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-42",
    question: "One investment triples in value every year and is valued after 2x − 1 years. A second investment grows 27-fold every year and is valued after x − 2 years. Both have grown by the same factor. What is x?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "7", "6", "5", "3"],
    answer: "D",
    solution: "The factors are 3^(2x−1) and 27^(x−2) = 3^(3x−6). Equating exponents gives 2x − 1 = 3x − 6, so x = 5.",
    hints: ["Rewrite 27 as a power of 3 so both sides share a base.", "Then set the exponents equal."],
    difficulty: 5,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-43",
    question: "A ladder leans against a wall making an acute angle θ with the ground, and the sine of that angle is 3/5. What is the cosine of twice that angle?",
    format: "MULTIPLE_CHOICE",
    choices: ["-7/25", "9/25", "24/25", "7/25", "1/5"],
    answer: "D",
    solution: "Using cos 2θ = 1 − 2 sin²θ = 1 − 2(9/25) = 1 − 18/25 = 7/25.",
    hints: ["Use a double-angle identity written entirely in terms of the sine.", "No need to find the angle itself."],
    difficulty: 5,
    topicSlug: "functions",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-44",
    question: "On a map measured in kilometers, a supply run goes from (1, 2) to (7, 10), and a relay point M is placed exactly halfway along that straight route. How many kilometers is M from a depot at (5, 5)?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "2√2", "√2", "√3", "2"],
    answer: "C",
    solution: "The midpoint is ((1+7)/2, (2+10)/2) = (4, 6). Its distance from (5,5) is √((5−4)² + (5−6)²) = √2 kilometers.",
    hints: ["Average the coordinates of the two endpoints to place M.", "Then apply the distance formula."],
    difficulty: 5,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-45",
    question: "A committee of 3 people is chosen from a group of 8 people. How many different committees are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["70", "64", "42", "48", "56"],
    answer: "E",
    solution:
      "The order of selection does not matter, so this is a combination: C(8,3) = 8!/(3!5!) = (8 × 7 × 6)/(3 × 2 × 1) = 336/6 = 56.",
    hints: [
      "Since the committee has no distinct roles, order doesn't matter — use combinations.",
      "Compute C(8,3) = (8 × 7 × 6)/3!.",
    ],
    difficulty: 5,
    topicSlug: "combinations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-46",
    question: "Two storage bins together hold 15 crates, and the fuller bin holds 3 more crates than the other. What is the product of the two bins' crate counts?",
    format: "MULTIPLE_CHOICE",
    choices: ["50", "60", "45", "48", "54"],
    answer: "E",
    solution: "The counts sum to 15 and differ by 3, so they are 9 and 6. The product is 9 × 6 = 54.",
    hints: ["Half the sum plus half the difference gives the larger count.", "Then multiply the two counts."],
    difficulty: 5,
    topicSlug: "systems-of-equations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-47",
    question: "A rectangular rug has a perimeter of 36 feet and an area of 80 square feet. What is the positive difference between its length and its width, in feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "8", "2", "6", "4"],
    answer: "C",
    solution: "The length and width sum to 18 and multiply to 80, so they are 10 and 8. Their difference is 2 feet.",
    hints: ["Halve the perimeter to get the sum of the dimensions.", "Find two numbers with that sum and the given product."],
    difficulty: 5,
    topicSlug: "area-volume",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-48",
    question: "A deck holds one card for each whole number strictly between 40 and 60. What is the sum of the numbers on the cards showing primes?",
    format: "MULTIPLE_CHOICE",
    choices: ["247", "243", "241", "245", "239"],
    answer: "B",
    solution: "The primes strictly between 40 and 60 are 41, 43, 47, 53, and 59. Their sum is 41 + 43 + 47 + 53 + 59 = 243.",
    hints: ["Test each number in the range for divisibility by 2, 3, 5, and 7.", "Add all the primes you find."],
    difficulty: 5,
    topicSlug: "primes",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-49",
    question:
      "A car travels 60 miles at a constant speed of v miles per hour, then returns along the same route at a speed of v + 10 miles per hour. If the total travel time is 3.5 hours, what is v?",
    format: "MULTIPLE_CHOICE",
    choices: ["35", "40", "25", "20", "30"],
    answer: "E",
    solution:
      "The total time is 60/v + 60/(v+10) = 3.5. Multiplying through by 2v(v+10): 120(v+10) + 120v = 7v(v+10), which simplifies to 7v² - 170v - 1200 = 0. The discriminant is 170² + 4(7)(1200) = 28900 + 33600 = 62500 = 250², so v = (170 + 250)/14 = 30.",
    hints: [
      "Write the total time as the sum of two separate time-equals-distance-over-speed expressions.",
      "Clear denominators to get a quadratic in v, then solve — only the positive root makes sense.",
    ],
    difficulty: 5,
    topicSlug: "rates",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-50",
    question: "A floor tile is shaped like a parallelogram. Two of its neighboring corner angles measure (3x − 10) degrees and (2x + 30) degrees. How many degrees is the first of those angles?",
    format: "MULTIPLE_CHOICE",
    choices: ["84°", "86°", "82°", "88°", "90°"],
    answer: "B",
    solution: "Neighboring angles of a parallelogram sum to 180, so (3x − 10) + (2x + 30) = 180, giving 5x + 20 = 180 and x = 32. The first angle is 3(32) − 10 = 86 degrees.",
    hints: ["Consecutive angles in a parallelogram are supplementary.", "Solve for x, then substitute into the first expression."],
    difficulty: 5,
    topicSlug: "quadrilaterals",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-51",
    question: "A rectangular box has a volume, in cubic units, of x³ − 5x² + kx − 6, and one of its three dimensions is x − 3. What is the value of k?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "9", "7", "6", "8"],
    answer: "E",
    solution: "If x − 3 is a dimension, the volume is zero at x = 3: 27 − 45 + 3k − 6 = 0, so 3k = 24 and k = 8.",
    hints: ["A factor of x − 3 means substituting x = 3 gives zero.", "Solve the resulting linear equation for k."],
    difficulty: 5,
    topicSlug: "polynomials",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-52",
    question: "A town's rainfall over 5 months averaged 20 centimeters per month. With the wettest month set aside, the remaining 4 months averaged 18 centimeters. How many centimeters of rain fell in the month that was set aside?",
    format: "MULTIPLE_CHOICE",
    choices: ["28", "26", "24", "30", "32"],
    answer: "A",
    solution: "The five months total 5 × 20 = 100 centimeters and the remaining four total 4 × 18 = 72, so the set-aside month had 100 − 72 = 28 centimeters.",
    hints: ["Convert each average into a total.", "The removed month is the difference between the two totals."],
    difficulty: 5,
    topicSlug: "averages",
    competitionSlug: "amc12",
  },

  // ============================= DIFFICULTY 6 =============================
  {
    slug: "amc12-53",
    question: "Two tanks hold x liters and x − 6 liters of water. Adding the base-2 logarithm of each volume gives exactly 4. How many liters are in the larger tank?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "6", "10", "12", "8"],
    answer: "E",
    solution: "The condition is log₂(x) + log₂(x−6) = log₂(x(x−6)) = 4, so x(x−6) = 16. Then x² − 6x − 16 = 0 factors as (x−8)(x+2) = 0, and only x = 8 keeps both volumes positive.",
    hints: ["Combine the two logarithms into the logarithm of a product.", "Discard any solution that makes a volume non-positive."],
    difficulty: 6,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-54",
    question: "A surveyor stands at point A and sights two landmarks, one 5 kilometers away and the other 8 kilometers away, with a 60-degree angle between the two lines of sight. How many kilometers apart are the two landmarks?",
    format: "MULTIPLE_CHOICE",
    choices: ["8", "6", "7", "9", "10"],
    answer: "C",
    solution: "By the law of cosines, the distance squared is 5² + 8² − 2(5)(8)cos 60° = 25 + 64 − 80(1/2) = 89 − 40 = 49, so the distance is 7 kilometers.",
    hints: ["Use the law of cosines with the known angle between the two sides.", "The cosine of 60 degrees is 1/2."],
    difficulty: 6,
    topicSlug: "triangles",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-55",
    question: "A measuring scale reports the base-3 logarithm of whatever quantity is placed on it. A sample reads 2.5. What does the scale read when the square of that quantity is placed on it?",
    format: "MULTIPLE_CHOICE",
    choices: ["2.5", "6.25", "4", "10", "5"],
    answer: "E",
    solution: "Since log₃(x²) = 2 log₃(x) = 2(2.5) = 5, the scale reads 5.",
    hints: ["A logarithm of a square is twice the logarithm.", "No need to find x itself."],
    difficulty: 6,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-56",
    question: "A fundraiser collects $3 on its first day, and each following day it collects twice what it collected the day before. How many dollars does it collect over the first 6 days in total?",
    format: "MULTIPLE_CHOICE",
    choices: ["183", "186", "189", "192", "195"],
    answer: "C",
    solution: "The daily amounts are 3, 6, 12, 24, 48, 96, totaling 189. Equivalently, 3(2⁶ − 1)/(2 − 1) = 3(63) = 189.",
    hints: ["Write out the six daily amounts.", "Add directly, or use the geometric series sum."],
    difficulty: 6,
    topicSlug: "sequences",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-57",
    question:
      "In how many ways can 5 distinct books be arranged on a shelf so that two particular books are never adjacent?",
    format: "MULTIPLE_CHOICE",
    choices: ["84", "96", "48", "60", "72"],
    answer: "E",
    solution:
      "There are 5! = 120 total arrangements. Treating the two particular books as a single glued block gives 4! × 2 = 48 arrangements where they are adjacent. The number of arrangements where they are not adjacent is 120 - 48 = 72.",
    hints: [
      "First count all arrangements, then count the ones where the two books ARE adjacent (treat them as a block).",
      "Subtract the adjacent count from the total using complementary counting.",
    ],
    difficulty: 6,
    topicSlug: "permutations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-58",
    question:
      "Two cards are drawn without replacement from a standard 52-card deck. What is the probability that both cards are aces?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/221", "1/169", "1/13", "1/26", "4/221"],
    answer: "A",
    solution:
      "The probability the first card is an ace is 4/52. Given that, the probability the second is also an ace is 3/51. The combined probability is (4/52)(3/51) = 12/2652 = 1/221.",
    hints: [
      "Multiply the probability of the first ace by the conditional probability of the second ace.",
      "Remember the deck has one fewer card (and one fewer ace) for the second draw.",
    ],
    difficulty: 6,
    topicSlug: "conditional-probability",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-59",
    question: "A circular pond covers 49π square meters. Two points on its edge are positioned so that the lines from the center to them meet at 120 degrees, and a straight plank is laid between those two points. How long is the plank, in meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["7√3", "7", "14", "7√5", "7√2"],
    answer: "A",
    solution: "From πr² = 49π, the radius is 7. The plank is a chord subtending 120 degrees, with length 2r sin(60°) = 2(7)(√3/2) = 7√3 meters.",
    hints: ["Use the area to find the radius first.", "Split the isosceles triangle formed by the two radii down the middle."],
    difficulty: 6,
    topicSlug: "circles",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-60",
    question: "A culture starts with 1 organism and multiplies sevenfold every hour. After 100 hours the organisms are packed into trays of 13, filling as many complete trays as possible. How many organisms are left over?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "9", "4", "3", "10"],
    answer: "B",
    solution: "We want the remainder of 7¹⁰⁰ upon division by 13. Since 7¹² leaves remainder 1, and 100 leaves remainder 4 upon division by 12, the answer matches 7⁴. Now 7² = 49 leaves 10, and 10² = 100 leaves 9. So 9 organisms remain.",
    hints: ["Find the cycle length of the remainders of powers of 7 upon division by 13.", "Reduce the exponent 100 by that cycle length, then compute."],
    difficulty: 6,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-61",
    question: "In an alternating-current circuit, two components have impedances of 2 + 3i ohms and 4 − i ohms, and an engineer needs their product. What is it?",
    format: "MULTIPLE_CHOICE",
    choices: ["8 + 10i", "11 - 10i", "8 - 2i", "11 + 10i", "5 + 10i"],
    answer: "D",
    solution: "Expanding, (2 + 3i)(4 − i) = 8 − 2i + 12i − 3i². Since i² = −1, this is 8 + 10i + 3 = 11 + 10i.",
    hints: ["Multiply out all four terms.", "Replace i² with −1 and combine like parts."],
    difficulty: 6,
    topicSlug: "algebra",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-62",
    question: "A club charges each of n members $3 and then pays a $7 fixed cost, while a rival club charges each of its n members $2 and pays $8 in fixed costs. For how many positive whole numbers n does the first club end up with less money than the second?",
    format: "MULTIPLE_CHOICE",
    choices: ["15", "14", "13", "12", "16"],
    answer: "B",
    solution: "The condition is 3n − 7 < 2n + 8, which simplifies to n < 15. The positive whole numbers 1 through 14 satisfy it, so there are 14 values.",
    hints: ["Write the inequality and collect the n terms on one side.", "Count only the positive whole numbers below the bound."],
    difficulty: 6,
    topicSlug: "inequalities",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-63",
    question: "A floor tile is a regular hexagon with 4-inch sides. What is its area, in square inches?",
    format: "MULTIPLE_CHOICE",
    choices: ["18√3", "32√3", "12√3", "16√3", "24√3"],
    answer: "E",
    solution: "A regular hexagon splits into 6 equilateral triangles of side 4, each with area (√3/4)(16) = 4√3. The total is 6(4√3) = 24√3 square inches.",
    hints: ["Split the hexagon into six equilateral triangles from its center.", "Use the equilateral-triangle area formula on one of them."],
    difficulty: 6,
    topicSlug: "polygons",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-64",
    question: "A processing line has two stations. The first squares the number it receives and adds 1. The second doubles the number it receives and subtracts 5. A value of 3 enters the first station and its output goes into the second. What number comes out?",
    format: "MULTIPLE_CHOICE",
    choices: ["17", "15", "19", "10", "13"],
    answer: "B",
    solution: "The first station outputs 3² + 1 = 10. The second then gives 2(10) − 5 = 15.",
    hints: ["Work through the stations in order.", "The first station's output becomes the second station's input."],
    difficulty: 6,
    topicSlug: "functions",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-65",
    question: "An auditorium's 360 chairs are to be placed in a rectangular array with every row holding the same number of chairs. How many different numbers of chairs per row are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["20", "28", "24", "18", "16"],
    answer: "C",
    solution: "Each valid row length is a divisor of 360. Since 360 = 2³·3²·5, the number of divisors is (3+1)(2+1)(1+1) = 24.",
    hints: ["Valid row lengths correspond exactly to divisors of 360.", "Factor 360 and use the divisor-count formula."],
    difficulty: 6,
    topicSlug: "divisibility",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-66",
    question: "A triangular park has corners at (0,0), (6,0), and (3,8) on a map measured in hundreds of meters. What is its area, in the corresponding square units?",
    format: "MULTIPLE_CHOICE",
    choices: ["18", "20", "24", "30", "28"],
    answer: "C",
    solution: "The base along the x-axis runs from (0,0) to (6,0), a length of 6, and the third corner sits 8 units above that line. The area is (1/2)(6)(8) = 24 square units.",
    hints: ["Use the side lying along the x-axis as the base.", "The height is the third corner's distance above that line."],
    difficulty: 6,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-67",
    question:
      "A game costs $5 to play. A player wins $20 with probability 1/5, and wins nothing otherwise. What is the expected net gain (or loss) from playing the game once?",
    format: "MULTIPLE_CHOICE",
    choices: ["-$2", "$4", "$0", "-$1", "$1"],
    answer: "D",
    solution:
      "The expected winnings are 20(1/5) + 0(4/5) = 4. Subtracting the $5 cost to play gives an expected net gain of 4 - 5 = -1, i.e., an expected loss of $1.",
    hints: [
      "First compute the expected winnings alone, ignoring the cost.",
      "Subtract the fixed cost to play from the expected winnings.",
    ],
    difficulty: 6,
    topicSlug: "expected-value",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-68",
    question: "A garden bed is shaped like a trapezoid whose two parallel sides measure 6 and 14 meters, with a perpendicular distance of 8 meters between them. What is its area, in square meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["70", "75", "85", "90", "80"],
    answer: "E",
    solution: "The area is ((6 + 14)/2)(8) = 10 × 8 = 80 square meters.",
    hints: ["Average the two parallel sides.", "Multiply that average by the perpendicular distance."],
    difficulty: 6,
    topicSlug: "quadrilaterals",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-69",
    question: "A rewards counter displays only the final digit of a member's point total. The total starts at 1 point and is multiplied by 7 each week. What digit is displayed after 2023 weeks?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "5", "3", "7", "1"],
    answer: "C",
    solution: "The final digits of powers of 7 cycle 7, 9, 3, 1 with period 4. Since 2023 leaves remainder 3 upon division by 4, the digit matches that of 7³ = 343, namely 3.",
    hints: ["List the last digits of the first few powers of 7 to find the cycle.", "Divide 2023 by the cycle length and use the remainder."],
    difficulty: 6,
    topicSlug: "number-patterns",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-70",
    question: "A gym assigns locker codes that are three-digit numbers from 100 to 999. A code is issued only if all three digits are different and the code is an even number. How many codes can be issued?",
    format: "MULTIPLE_CHOICE",
    choices: ["328", "324", "312", "336", "320"],
    answer: "A",
    solution: "If the last digit is 0 (1 way), the first digit has 9 options and the middle has 8, giving 9·8 = 72. If the last digit is 2, 4, 6, or 8 (4 ways), the first digit has 8 options (not 0, not the last digit) and the middle has 8, giving 4·8·8 = 256. The total is 72 + 256 = 328.",
    hints: ["Split into the case where the final digit is 0 and the case where it is not.", "The leading digit cannot be 0, which makes the two cases differ."],
    difficulty: 6,
    topicSlug: "casework",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-71",
    question: "A caterer buys small platters at $3 each and large platters at $5 each, spending exactly $50 and buying at least one of each. In how many different ways can this be done?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "6", "5", "4", "2"],
    answer: "A",
    solution: "With x small and y large, 3x + 5y = 50. For x to be a positive whole number, 50 − 5y must be a positive multiple of 3, so y leaves remainder 1 upon division by 3. The options y = 1, 4, 7 give x = 15, 10, 5, while y = 10 would leave x = 0. So there are 3 ways.",
    hints: ["Write the spending equation and check divisibility by 3.", "Keep only the options where both counts stay positive."],
    difficulty: 6,
    topicSlug: "diophantine-equations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-72",
    question:
      "In a group of 30 people, what is the minimum number of people who are guaranteed to share the same birth month?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "4", "3", "6", "5"],
    answer: "C",
    solution:
      "There are 12 months. By the Pigeonhole Principle, distributing 30 people among 12 months as evenly as possible gives some month at least ⌈30/12⌉ = 3 people.",
    hints: [
      "This is a Pigeonhole Principle problem with 12 'holes' (months).",
      "Compute ⌈30/12⌉ to find the guaranteed minimum in the fullest month.",
    ],
    difficulty: 6,
    topicSlug: "pigeonhole",
    competitionSlug: "amc12",
  },

  // ============================= DIFFICULTY 7 =============================
  {
    slug: "amc12-73",
    question: "An audio engineer measures one sample's level on a base-2 scale and the same sample's level on a base-4 scale. The two readings add to 6. What quantity was being measured?",
    format: "MULTIPLE_CHOICE",
    choices: ["32", "12", "8", "16", "24"],
    answer: "D",
    solution: "The condition is log₂(x) + log₄(x) = 6. Since log₄(x) = log₂(x)/2, the left side is (3/2)log₂(x) = 6, so log₂(x) = 4 and x = 16.",
    hints: ["Convert the base-4 logarithm into a base-2 logarithm.", "Combine the two terms and solve for the base-2 logarithm first."],
    difficulty: 7,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-74",
    question: "A robotic arm points in a direction whose tangent is 2, with the arm directed into the third quadrant, so that both its horizontal and vertical components are negative. What is the sum of the sine and the cosine of that direction angle?",
    format: "MULTIPLE_CHOICE",
    choices: ["-3/5", "√5/5", "-√5/5", "3√5/5", "-3√5/5"],
    answer: "E",
    solution: "With tangent 2, the reference triangle has legs 1 and 2 and hypotenuse √5. In the third quadrant both sine and cosine are negative: sin θ = −2/√5 and cos θ = −1/√5. Their sum is −3/√5 = −3√5/5.",
    hints: ["Build a right triangle with legs matching the tangent, then find the hypotenuse.", "Apply the correct signs for the third quadrant before adding."],
    difficulty: 7,
    topicSlug: "functions",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-75",
    question: "A signal processor repeatedly multiplies a value by 1 + i, where i is the imaginary unit. Starting from 1, what value remains after 8 such multiplications?",
    format: "MULTIPLE_CHOICE",
    choices: ["16i", "-16i", "16", "-16", "8"],
    answer: "C",
    solution: "Note (1 + i)² = 1 + 2i − 1 = 2i. So (1 + i)⁸ = ((1+i)²)⁴ = (2i)⁴ = 16 i⁴ = 16.",
    hints: ["Square 1 + i first to get a much simpler value.", "Then raise that result to the fourth power."],
    difficulty: 7,
    topicSlug: "algebra",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-76",
    question: "Two circular storage tanks of radii 5 and 3 meters stand with their centers 10 meters apart. A straight fence is built tangent to both tanks on the same side, touching each tank once. How long is the fence between its two points of contact, in meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["4√5", "4√6", "4√7", "6√3", "2√21"],
    answer: "B",
    solution: "A common external tangent has length √(d² − (r₁ − r₂)²) = √(10² − 2²) = √96 = 4√6 meters.",
    hints: ["Form a right triangle whose hypotenuse joins the two centers.", "One leg is the tangent length and the other is the difference of the radii."],
    difficulty: 7,
    topicSlug: "circles",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-77",
    question: "A warehouse's cumulative shipment count after n days is 3n² + 2n crates. How many crates were shipped on the 10th day alone?",
    format: "MULTIPLE_CHOICE",
    choices: ["56", "59", "62", "60", "53"],
    answer: "B",
    solution: "The 10th day's count is the total after 10 days minus the total after 9: (300 + 20) − (243 + 18) = 320 − 261 = 59 crates.",
    hints: ["A single day's amount is the difference of two consecutive cumulative totals.", "Evaluate the formula at n = 10 and n = 9."],
    difficulty: 7,
    topicSlug: "sequences",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-78",
    question: "A parking garage numbers its spaces 1 through 200. A space is reserved if its number is divisible by 3 or by 5, but not if the number is divisible by 15. How many spaces are reserved?",
    format: "MULTIPLE_CHOICE",
    choices: ["93", "80", "66", "53", "73"],
    answer: "B",
    solution: "There are ⌊200/3⌋ = 66 multiples of 3, ⌊200/5⌋ = 40 multiples of 5, and ⌊200/15⌋ = 13 multiples of 15. Removing the multiples of 15 from each group gives (66 − 13) + (40 − 13) = 53 + 27 = 80.",
    hints: ["Count multiples of 3 and of 5 separately.", "The multiples of 15 must be removed from both groups entirely."],
    difficulty: 7,
    topicSlug: "inclusion-exclusion",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-79",
    question: "A game awards a score equal to the product of all the whole numbers from 1 up to n. What is the smallest n whose score is divisible by 1000?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "10", "15", "20", "25"],
    answer: "C",
    solution: "Since 1000 = 2³·5³, we need three factors of 5, which are the scarcer prime. The multiples of 5 contribute one each, so 5, 10, and 15 supply the third factor at n = 15. Factors of 2 are plentiful well before that, so n = 15.",
    hints: ["Factor 1000 into primes and decide which prime is harder to accumulate.", "Count how many multiples of 5 are needed."],
    difficulty: 7,
    topicSlug: "number-theory",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-80",
    question: "A fair coin is flipped 6 times. What is the probability of getting exactly 4 heads?",
    format: "MULTIPLE_CHOICE",
    choices: ["21/64", "3/16", "5/16", "15/64", "15/32"],
    answer: "D",
    solution:
      "The probability is C(6,4)(1/2)⁴(1/2)² = C(6,4)/2⁶ = 15/64.",
    hints: [
      "Use the binomial probability formula with n = 6, k = 4, p = 1/2.",
      "Compute C(6,4) = 15 and divide by 2⁶ = 64.",
    ],
    difficulty: 7,
    topicSlug: "counting-probability",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-81",
    question: "A cube-shaped crate holds 216 cubic feet. How many square feet of material cover all six of its faces?",
    format: "MULTIPLE_CHOICE",
    choices: ["196", "216", "240", "200", "180"],
    answer: "B",
    solution: "The edge is ∛216 = 6 feet. The surface area is 6(6²) = 6(36) = 216 square feet.",
    hints: ["Take the cube root of the volume to get the edge length.", "Then multiply the area of one face by 6."],
    difficulty: 7,
    topicSlug: "three-d-geometry",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-82",
    question: "A shipping crate's volume, in cubic units, is x³ − 6x² + 11x − 6, and each of its three dimensions is x minus one of three real numbers. What is the sum of the squares of those three numbers?",
    format: "MULTIPLE_CHOICE",
    choices: ["16", "12", "10", "18", "14"],
    answer: "E",
    solution: "The polynomial factors as (x−1)(x−2)(x−3), so the numbers are 1, 2, and 3. Their squares sum to 1 + 4 + 9 = 14.",
    hints: ["Factor the cubic completely.", "Square each of the three numbers and add."],
    difficulty: 7,
    topicSlug: "polynomials",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-83",
    question: "A tournament doubles its prize pool every round, starting from 1 unit, and runs for 50 rounds. The final pool is then split into shares of 7 units each, as many whole shares as possible. How many units are left over?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "6", "4", "3", "2"],
    answer: "C",
    solution: "We want the remainder of 2⁵⁰ upon division by 7. Since 2³ = 8 leaves remainder 1, the remainders repeat every 3 rounds. As 50 leaves remainder 2 upon division by 3, the leftover matches 2² = 4.",
    hints: ["Find how often the remainders of powers of 2 repeat upon division by 7.", "Reduce the exponent 50 by that period."],
    difficulty: 7,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-84",
    question: "Two triangular garden beds have exactly the same shape, with corresponding lengths in a 3 to 5 ratio. The smaller bed covers 27 square meters. How many square meters does the larger bed cover?",
    format: "MULTIPLE_CHOICE",
    choices: ["60", "75", "90", "45", "81"],
    answer: "B",
    solution: "For similar figures the area ratio is the square of the length ratio, so the areas are in ratio 9 to 25. The larger area is 27 × 25/9 = 75 square meters.",
    hints: ["Square the length ratio to get the area ratio.", "Then scale the known area by that factor."],
    difficulty: 7,
    topicSlug: "similarity-congruence",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-85",
    question: "How many distinct arrangements are there of the letters in the word BANANA?",
    format: "MULTIPLE_CHOICE",
    choices: ["72", "90", "60", "120", "30"],
    answer: "C",
    solution:
      "BANANA has 6 letters with A repeated 3 times and N repeated 2 times. The number of distinct arrangements is 6!/(3!2!) = 720/12 = 60.",
    hints: [
      "Count the total letters and identify which letters repeat, and how often.",
      "Divide the total permutations 6! by the factorial of each repeated letter's count.",
    ],
    difficulty: 7,
    topicSlug: "permutations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-86",
    question: "A reservoir's level relative to a marker, in centimeters, on day n is n² − 5n − 14, where negative days refer to the period before monitoring began. On how many integer days is the level at or below the marker?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "9", "8", "12", "11"],
    answer: "A",
    solution: "Factoring gives (n − 7)(n + 2), which is at most 0 exactly when −2 ≤ n ≤ 7. The integers from −2 through 7 number 7 − (−2) + 1 = 10.",
    hints: ["Factor the quadratic to find where it equals zero.", "The expression is negative or zero between the two roots, endpoints included."],
    difficulty: 7,
    topicSlug: "inequalities",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-87",
    question: "A colony doubles every hour. It takes x hours to reach exactly 5 times its starting size and y hours to reach exactly 3 times its starting size. By what factor has it grown after x − y hours?",
    format: "MULTIPLE_CHOICE",
    choices: ["5/3", "2/3", "8/3", "3/5", "15"],
    answer: "A",
    solution: "The conditions say 2^x = 5 and 2^y = 3. Dividing, 2^(x−y) = 5/3.",
    hints: ["Write each growth condition as a power of 2.", "Divide the two equations to get the difference of exponents."],
    difficulty: 7,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-88",
    question: "A delivery fee rises steadily with distance. At 2 kilometers it is $3, and at 6 kilometers it is $11. What would the formula give as the fee at 0 kilometers?",
    format: "MULTIPLE_CHOICE",
    choices: ["-1", "0", "-2", "-3", "1"],
    answer: "A",
    solution: "The rate is (11 − 3)/(6 − 2) = 2 dollars per kilometer. From (2, 3): y − 3 = 2(x − 2), so y = 2x − 1. At x = 0 the value is −1.",
    hints: ["Find the per-kilometer rate from the two given fees.", "Extend the line back to zero distance."],
    difficulty: 7,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-89",
    question: "Three fair six-sided dice are rolled. What is the probability that the sum of the three dice is 10?",
    format: "MULTIPLE_CHOICE",
    choices: ["5/36", "1/8", "1/6", "1/9", "7/72"],
    answer: "B",
    solution:
      "There are 6³ = 216 equally likely outcomes. Careful enumeration (or the standard coefficient count) shows exactly 27 ordered triples from {1,...,6} sum to 10. The probability is 27/216 = 1/8.",
    hints: [
      "Total outcomes are 6³ = 216 since each die is independent.",
      "Count ordered triples (a,b,c) with each value 1-6 summing to 10 — there are 27 of them.",
    ],
    difficulty: 7,
    topicSlug: "counting-probability",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-90",
    question: "Two pumps, working alone, would each take a whole number of hours to fill a tank. Working together they fill it in exactly 6 hours. How many ordered pairs of individual times are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "10", "9", "8", "6"],
    answer: "C",
    solution: "The rates give 1/x + 1/y = 1/6, which rearranges to (x − 6)(y − 6) = 36. Each of the 9 divisors of 36 gives one ordered pair, so there are 9.",
    hints: ["Add the two rates and set the sum equal to one sixth of a tank per hour.", "Rearrange into a product of two shifted factors and count divisors."],
    difficulty: 7,
    topicSlug: "diophantine-equations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-91",
    question: "A paving stone is a regular polygon whose interior corner angle measures 150 degrees. How many sides does it have?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "18", "10", "9", "15"],
    answer: "A",
    solution: "Each exterior angle is 180 − 150 = 30 degrees, and the exterior angles total 360, so the stone has 360/30 = 12 sides.",
    hints: ["Find the exterior angle first as 180 minus the interior angle.", "Exterior angles of any polygon sum to 360 degrees."],
    difficulty: 7,
    topicSlug: "polygons",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-92",
    question:
      "A bag contains 4 red balls and 6 blue balls. Two balls are drawn without replacement. What is the expected number of red balls drawn?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "3/5", "1/2", "2/5", "4/5"],
    answer: "E",
    solution:
      "By linearity of expectation, each individual draw has probability 4/10 of being red, regardless of order or dependence between draws. With 2 draws, the expected number of red balls is 2 × 4/10 = 4/5.",
    hints: [
      "Linearity of expectation applies even without replacement — no need for complicated casework.",
      "Each single draw has the same marginal probability 4/10 of being red.",
    ],
    difficulty: 7,
    topicSlug: "expected-value",
    competitionSlug: "amc12",
  },

  // ============================= DIFFICULTY 8 =============================
  {
    slug: "amc12-93",
    question: "Seven identical forces are directed from the center of a circular platform toward seven equally spaced anchor points on its rim, and together they cancel exactly. Writing these directions as 1, ω, ω², …, ω⁶ where ω is a primitive 7th root of unity, what is the value of ω + ω² + ω³ + ω⁴ + ω⁵ + ω⁶?",
    format: "MULTIPLE_CHOICE",
    choices: ["-7", "1", "-1", "7", "0"],
    answer: "C",
    solution: "All seven directions sum to zero, since 1 + ω + ω² + ··· + ω⁶ = 0 for a primitive 7th root of unity. Removing the term 1 leaves ω + ω² + ··· + ω⁶ = −1.",
    hints: ["All seven equally spaced directions add to zero.", "Subtract the one direction that equals 1."],
    difficulty: 8,
    topicSlug: "algebra",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-94",
    question: "A support cable meets the ground at an angle x for which the sine and the cosine add to exactly 7/5. What is the product of that angle's sine and cosine?",
    format: "MULTIPLE_CHOICE",
    choices: ["7/25", "1/2", "49/50", "24/25", "12/25"],
    answer: "E",
    solution: "Squaring the sum: sin²x + cos²x + 2 sin x cos x = 49/25. Since the first two terms total 1, we get 2 sin x cos x = 24/25, so sin x cos x = 12/25.",
    hints: ["Square the given sum.", "Use the fact that the squares of sine and cosine add to 1."],
    difficulty: 8,
    topicSlug: "functions",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-95",
    question: "A triangular plot of land has sides measuring 13, 14, and 15 meters. What is its area, in square meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["90", "84", "76", "80", "88"],
    answer: "B",
    solution: "The semiperimeter is s = 21. By Heron's formula the area is √(21·8·7·6) = √7056 = 84 square meters.",
    hints: ["Use Heron's formula with the semiperimeter.", "Alternatively, drop an altitude to the side of length 14 and split it into 5 and 9."],
    difficulty: 8,
    topicSlug: "triangles",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-96",
    question: "A laboratory logs one sample on a base-4 scale and the same sample on a base-2 scale. The two readings add to 9. What quantity was measured?",
    format: "MULTIPLE_CHOICE",
    choices: ["256", "32", "128", "16", "64"],
    answer: "E",
    solution: "The condition is log₄(x) + log₂(x) = 9. Since log₄(x) = log₂(x)/2, we get (3/2)log₂(x) = 9, so log₂(x) = 6 and x = 64.",
    hints: ["Rewrite the base-4 logarithm in terms of base 2.", "Solve for the base-2 logarithm before recovering x."],
    difficulty: 8,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-97",
    question:
      "In how many ways can 8 people be seated around a circular table if two particular people must NOT sit next to each other? (Rotations are considered identical, reflections are not.)",
    format: "MULTIPLE_CHOICE",
    choices: ["3600", "4320", "3960", "4200", "2880"],
    answer: "A",
    solution:
      "The total number of circular arrangements of 8 people is (8-1)! = 5040. Treating the two particular people as a glued block gives (7-1)! × 2 = 720 × 2 = 1440 arrangements where they are adjacent. The count where they are not adjacent is 5040 - 1440 = 3600.",
    hints: [
      "Recall that circular arrangements of n people number (n-1)!.",
      "Use complementary counting: subtract the adjacent arrangements (treating the pair as one unit) from the total.",
    ],
    difficulty: 8,
    topicSlug: "permutations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-98",
    question: "A theater numbers its seats 1 through 999. A seat is left empty if its number is divisible by 2 or by 3. How many seats are occupied?",
    format: "MULTIPLE_CHOICE",
    choices: ["336", "333", "332", "334", "330"],
    answer: "B",
    solution: "Among 1 to 999 there are 499 multiples of 2, 333 multiples of 3, and 166 multiples of 6. By inclusion-exclusion, 499 + 333 − 166 = 666 are divisible by 2 or 3, leaving 999 − 666 = 333 occupied.",
    hints: ["Count multiples of 2 and of 3, then correct for double counting.", "Numbers counted twice are the multiples of 6."],
    difficulty: 8,
    topicSlug: "inclusion-exclusion",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-99",
    question: "A pendulum swings 8 centimeters to one side, then 4 centimeters back to the other side, then 2 centimeters, and so on, each swing being half the previous one and in the opposite direction. Taking one direction as positive, what is the total signed displacement of all the swings combined?",
    format: "MULTIPLE_CHOICE",
    choices: ["32/3", "4", "8/3", "16/3", "6"],
    answer: "D",
    solution: "This is the geometric series 8 − 4 + 2 − 1 + ··· with first term 8 and ratio −1/2. Its sum is 8/(1 − (−1/2)) = 8/(3/2) = 16/3 centimeters.",
    hints: ["The alternating signs make the common ratio negative.", "Use the infinite geometric sum formula with that ratio."],
    difficulty: 8,
    topicSlug: "sequences",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-100",
    question:
      "A box contains 3 red, 4 green, and 5 blue marbles. Two marbles are drawn without replacement. Given that the first marble drawn is red, what is the probability that the second marble is also red?",
    format: "MULTIPLE_CHOICE",
    choices: ["3/11", "2/11", "1/4", "2/9", "1/6"],
    answer: "B",
    solution:
      "After removing one red marble, 2 red marbles remain out of 11 total marbles. The conditional probability is 2/11.",
    hints: [
      "Update both the count of red marbles and the total count after the first draw.",
      "The conditional probability is simply (remaining red)/(remaining total).",
    ],
    difficulty: 8,
    topicSlug: "conditional-probability",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-101",
    question: "A circular running track on a map is described by x² + y² = 36, with units in hundreds of meters. How long is the portion of the track lying in the first quadrant, in those same units?",
    format: "MULTIPLE_CHOICE",
    choices: ["6π", "12π", "4π", "2π", "3π"],
    answer: "E",
    solution: "The radius is 6, so the full circumference is 12π. The first quadrant holds one quarter of it, or 3π.",
    hints: ["Read the radius from the equation.", "A quadrant is one quarter of the full circumference."],
    difficulty: 8,
    topicSlug: "circles",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-102",
    question: "A projectile's vertical offset from a target, in meters, at horizontal position x is x⁴ − 5x² + 4. At how many distinct positions does the projectile pass exactly through the target's level?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "1", "4", "3", "0"],
    answer: "C",
    solution: "Substituting u = x² gives u² − 5u + 4 = 0, so u = 1 or u = 4. Then x = ±1 and x = ±2, giving 4 distinct positions.",
    hints: ["Substitute u = x² to reduce this to a quadratic.", "Each positive value of u yields two values of x."],
    difficulty: 8,
    topicSlug: "polynomials",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-103",
    question: "A counter displays only the last two digits of a running total. The total starts at 1 and is tripled every hour. What two-digit value does the counter display after 100 hours?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "49", "61", "21", "81"],
    answer: "A",
    solution: "We want 3¹⁰⁰ modulo 100. The powers of 3 repeat modulo 100 with period 20, and 100 is a multiple of 20, so 3¹⁰⁰ leaves the same remainder as 3⁰, namely 1. The counter shows 01.",
    hints: ["Find how often the last two digits of powers of 3 repeat.", "Check whether 100 is a multiple of that period."],
    difficulty: 8,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-104",
    question: "Six guests check their coats at a theater, and the attendant hands the coats back at random, one per guest. In how many ways can the coats be returned so that no guest receives their own coat?",
    format: "MULTIPLE_CHOICE",
    choices: ["266", "120", "265", "720", "264"],
    answer: "C",
    solution: "This counts derangements of 6 items. Using D(n) = n·D(n−1) + (−1)ⁿ from D(1) = 0: D(2) = 1, D(3) = 2, D(4) = 9, D(5) = 44, D(6) = 265.",
    hints: ["Count the arrangements in which nothing lands in its own place — these are derangements.", "Build them up with a recurrence, or use inclusion-exclusion on the guests who do get their own coat."],
    difficulty: 8,
    topicSlug: "permutations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-105",
    question: "A decorative paperweight is a regular tetrahedron with all six edges 6 centimeters long. What is its volume, in cubic centimeters?",
    format: "MULTIPLE_CHOICE",
    choices: ["12√2", "36√2", "18√2", "9√2", "24√2"],
    answer: "C",
    solution: "A regular tetrahedron with edge a has volume a³/(6√2). Here that is 216/(6√2) = 36/√2 = 18√2 cubic centimeters.",
    hints: ["Use the volume formula for a regular tetrahedron in terms of its edge.", "Rationalize the denominator at the end."],
    difficulty: 8,
    topicSlug: "three-d-geometry",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-106",
    question: "Two pipes fill a tank at positive rates that add to 10 tanks per hour. Working alone, the first would take 1/a hours per tank and the second 1/b hours per tank, where a and b are their rates. What is the smallest possible total of those two alone-times?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "1/5", "1/2", "4/5", "2/5"],
    answer: "E",
    solution: "We minimize 1/a + 1/b = (a+b)/(ab) = 10/(ab) subject to a + b = 10. The product ab is largest when a = b = 5, giving ab = 25, so the minimum total is 10/25 = 2/5.",
    hints: ["Combine the two reciprocals over a common denominator.", "With a fixed sum, the product is largest when the two values are equal."],
    difficulty: 8,
    topicSlug: "inequalities-olympiad",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-107",
    question: "A prize of 360 identical tokens is split evenly among some number of winners, where any number of winners that divides 360 exactly is allowed. What is the sum of all possible per-winner amounts?",
    format: "MULTIPLE_CHOICE",
    choices: ["1080", "1140", "1200", "1260", "1170"],
    answer: "E",
    solution: "The possible amounts are exactly the divisors of 360 = 2³·3²·5. Their sum is (1+2+4+8)(1+3+9)(1+5) = 15 × 13 × 6 = 1170.",
    hints: ["Each valid split corresponds to a divisor of 360.", "Factor 360 and use the product formula for the sum of its divisors."],
    difficulty: 8,
    topicSlug: "number-theory",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-108",
    question:
      "Five people, including Alice and Bob, are seated randomly in a row of 5 chairs. What is the probability that Alice and Bob end up in the two end seats (in either order)?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/5", "1/10", "2/5", "1/4", "1/20"],
    answer: "B",
    solution:
      "There are 5! = 120 total seatings. For Alice and Bob to occupy the two end seats, there are 2 ways to arrange them in those seats, times 3! ways to seat the remaining 3 people in the middle seats, giving 2 × 6 = 12 favorable seatings. The probability is 12/120 = 1/10.",
    hints: [
      "Count the favorable arrangements: place Alice and Bob in the two ends, then arrange everyone else.",
      "Divide by the total number of seatings, 5!.",
    ],
    difficulty: 8,
    topicSlug: "counting-probability",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-109",
    question: "A circular walkway on a map passes through a fountain at (0,0), a gate at (4,0), and a statue at (0,6), with units in hundreds of meters. What is the walkway's radius, in those units?",
    format: "MULTIPLE_CHOICE",
    choices: ["7", "√13", "5", "√12", "13"],
    answer: "B",
    solution: "The angle at the fountain, between the two axes, is a right angle, so the segment from the gate to the statue is a diameter. Its length is √(4² + 6²) = √52 = 2√13, making the radius √13.",
    hints: ["The two given points lie on perpendicular axes through the third point.", "An inscribed right angle means the opposite chord is a diameter."],
    difficulty: 8,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-110",
    question: "A machine starts with a stock of 3 units. Each cycle it triples its stock and then consumes 4 units. How many units does it hold after 4 cycles?",
    format: "MULTIPLE_CHOICE",
    choices: ["75", "79", "83", "91", "87"],
    answer: "C",
    solution: "Cycle by cycle: 3, then 3(3) − 4 = 5, then 3(5) − 4 = 11, then 3(11) − 4 = 29, then 3(29) − 4 = 83.",
    hints: ["Apply the tripling and subtraction one cycle at a time.", "Four cycles means four applications starting from 3."],
    difficulty: 8,
    topicSlug: "sequences",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-111",
    question: "A triangular brace has sides of 8, 15, and 17 centimeters. What is the measure, in degrees, of the corner opposite the 17-centimeter side?",
    format: "MULTIPLE_CHOICE",
    choices: ["80°", "90°", "85°", "75°", "95°"],
    answer: "B",
    solution: "Since 8² + 15² = 64 + 225 = 289 = 17², the triangle is right-angled, and the right angle lies opposite the longest side. That corner measures 90 degrees.",
    hints: ["Test whether the squares of the two shorter sides add to the square of the longest.", "The right angle sits opposite the longest side."],
    difficulty: 8,
    topicSlug: "triangles",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-112",
    question: "A fair six-sided die is rolled 4 times. What is the probability that the sequence of rolls is strictly increasing?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/54", "1/216", "5/216", "5/432", "5/108"],
    answer: "D",
    solution:
      "For a strictly increasing sequence, the 4 rolled values must all be distinct, and there is exactly one increasing order for any chosen set of 4 distinct values from {1,...,6}. The number of favorable outcomes is C(6,4) = 15. The total number of outcomes is 6⁴ = 1296. The probability is 15/1296 = 5/432.",
    hints: [
      "A strictly increasing sequence corresponds to choosing a set of 4 distinct values — order is then forced.",
      "Divide C(6,4) by the total number of possible roll sequences, 6⁴.",
    ],
    difficulty: 8,
    topicSlug: "counting-probability",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-113",
    question: "Two oscillating signals are measured over one full cycle, with the setting x running through 0 ≤ x < 2π. The first reads sin 3x and the second reads cos 2x. What is the sum of all settings x at which the two readings agree?",
    format: "MULTIPLE_CHOICE",
    choices: ["5π", "9π/2", "4π", "7π/2", "13π/2"],
    answer: "B",
    solution: "Write cos 2x = sin(π/2 − 2x). Then 3x = π/2 − 2x + 2πk gives x = π/10 + 2πk/5, contributing x = π/10, π/2, 9π/10, 13π/10, 17π/10. Also 3x = π − (π/2 − 2x) + 2πk gives x = π/2 + 2πk, contributing x = π/2 again. Summing the distinct solutions π/10, π/2, 9π/10, 13π/10, 17π/10 gives 45π/10 = 9π/2.",
    hints: ["Convert the cosine into a sine so both sides use the same function.", "Two families of solutions arise; collect the distinct ones before adding."],
    difficulty: 8,
    topicSlug: "functions",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-114",
    question: "A landscaper wants to lay out a perfectly square array of n tiles, where n is at most 1000, and also wants the count n to be built from exactly two distinct prime factors. How many values of n qualify?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "12", "14", "15", "31"],
    answer: "B",
    solution: "A perfect square array requires n to be a perfect square, which is also exactly the condition for n to have an odd number of divisors. The perfect squares up to 1000 are m² for m = 1 to 31, and n = m² has exactly two distinct primes precisely when m does. The values of m ≤ 31 with exactly two distinct prime factors are 6, 10, 12, 14, 15, 18, 20, 21, 22, 24, 26, 28 — twelve of them.",
    hints: ["An odd number of divisors happens exactly for perfect squares.", "A square m² has the same distinct primes as m, so count suitable m up to 31."],
    difficulty: 8,
    topicSlug: "number-theory",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-115",
    question: "Four towns A, B, C, and D lie in that order on a circular road. The straight distances between neighbors are AB = 2, BC = 6, CD = 4, and DA = 4 kilometers. How many kilometers is the straight distance from A to C?",
    format: "MULTIPLE_CHOICE",
    choices: ["16/7", "8√7/7", "16√7/7", "2√7", "4√7/7"],
    answer: "C",
    solution: "Because ABCD is cyclic, angles B and D are supplementary, so their cosines are negatives. Applying the law of cosines to both triangles on diagonal AC: 4 + 36 − 24cos B = 16 + 16 + 32cos B, so 40 − 24cos B = 32 + 32cos B, giving cos B = 1/7. Then AC² = 40 − 24/7 = 256/7, so AC = 16/√7 = 16√7/7.",
    hints: ["Opposite angles of a cyclic quadrilateral are supplementary, so their cosines are negatives.", "Apply the law of cosines to the diagonal from both triangles and equate."],
    difficulty: 8,
    topicSlug: "quadrilaterals",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-116",
    question: "Each of 5 employees is assigned a mentor from among the same 5 employees, and an employee may be assigned to themselves. The assignment must satisfy one rule: every employee who serves as someone's mentor must be their own mentor. In how many ways can the assignment be made?",
    format: "MULTIPLE_CHOICE",
    choices: ["26", "120", "195", "196", "3125"],
    answer: "D",
    solution: "The rule says the assignment f satisfies f(f(x)) = f(x). Choose the set of self-mentors of size k, then assign each of the remaining 5 − k employees to one of them: Σ C(5,k)·k^(5−k) for k = 1 to 5, which is 5·1 + 10·8 + 10·9 + 5·4 + 1 = 5 + 80 + 90 + 20 + 1 = 196.",
    hints: ["The rule forces the image of the assignment to consist of fixed points.", "Sum over the possible number of self-mentors, choosing them and then assigning everyone else."],
    difficulty: 9,
    topicSlug: "counting-principles",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-117",
    question: "A shop is open on some of the 12 days of a festival, choosing any subset of days, but it will never open on three consecutive days. In how many ways can it pick its open days?",
    format: "MULTIPLE_CHOICE",
    choices: ["1364", "1597", "1705", "1920", "2048"],
    answer: "C",
    solution: "Let f(n) count valid subsets of n days. Considering the run of chosen days at the end gives f(n) = f(n−1) + f(n−2) + f(n−3), with f(0) = 1, f(1) = 2, f(2) = 4. Continuing: 7, 13, 24, 44, 81, 149, 274, 504, 927, 1705. So f(12) = 1705.",
    hints: ["Set up a recurrence by looking at how many days at the end are chosen.", "The count depends on the previous three values."],
    difficulty: 9,
    topicSlug: "advanced-combinatorics",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-118",
    question: "A pricing rule assigns a value f(x) to every real x other than 0 and 1, and it always satisfies f(x) + f(1 − 1/x) = x. What value does the rule assign to 3?",
    format: "MULTIPLE_CHOICE",
    choices: ["3/2", "11/12", "19/12", "25/12", "17/12"],
    answer: "B",
    solution: "The map x → 1 − 1/x cycles 3 → 2/3 → −1/2 → 3. The three equations are f(3) + f(2/3) = 3, f(2/3) + f(−1/2) = 2/3, and f(−1/2) + f(3) = −1/2. Adding all three gives 2[f(3)+f(2/3)+f(−1/2)] = 3 + 2/3 − 1/2 = 19/6, so the triple sum is 19/12. Subtracting the middle equation leaves f(3) = 19/12 − 2/3 = 11/12.",
    hints: ["Apply the substitution repeatedly until it returns to the starting value.", "Add all three equations, then subtract the one not containing f(3)."],
    difficulty: 9,
    topicSlug: "functional-equations",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-119",
    question: "The lengths x and y of two sides of a rectangle both exceed 1, the rectangle's area is 144, and log_x y + log_y x = 10/3. What is the average of x and y?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "13√3", "26√3", "13", "14√3"],
    answer: "B",
    solution: "Let t = log_x y, so t + 1/t = 10/3 and t = 3 or t = 1/3. Taking t = 3 gives y = x³, and xy = x⁴ = 144, so x = √12 = 2√3 and y = x³ = 24√3. Then x + y = 26√3 and the average is 13√3.",
    hints: ["Set t equal to one of the logarithms; the other is its reciprocal.", "Solve for t, express y as a power of x, and use the area."],
    difficulty: 9,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-120",
    question: "A monument is a pyramid with a square base of side 6 meters and four equal slanted edges of length 3√3 meters. A cubical block rests on the base, centered, with its edges parallel to the base edges, and all four of its top corners just touch the pyramid's slanted faces. What is the block's edge length, in meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["5/2", "12/5", "2", "18/7", "3"],
    answer: "C",
    solution: "The base half-diagonal is 3√2, so the apex height satisfies h² = (3√3)² − (3√2)² = 27 − 18 = 9, giving h = 3. At height z the pyramid's cross-section is a square of side 6(1 − z/3). The block of edge s has its top at z = s, so s = 6(1 − s/3) = 6 − 2s, giving 3s = 6 and s = 2.",
    hints: ["Find the pyramid's height from a slanted edge and the base half-diagonal.", "The cross-section shrinks linearly with height; match it to the block's edge at the block's top."],
    difficulty: 9,
    topicSlug: "three-d-geometry",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-121",
    question: "A quality-control model is a monic degree-4 polynomial P. Testing gives P(1) = 3, P(2) = 6, P(3) = 11, and P(4) = 18. What does the model predict at 6?",
    format: "MULTIPLE_CHOICE",
    choices: ["38", "128", "146", "158", "278"],
    answer: "D",
    solution: "Notice the given values match x² + 2 at x = 1, 2, 3, 4. So P(x) − (x² + 2) is monic of degree 4 with roots 1, 2, 3, 4, meaning P(x) = (x−1)(x−2)(x−3)(x−4) + x² + 2. Then P(6) = 5·4·3·2 + 36 + 2 = 120 + 38 = 158.",
    hints: ["Look for a simple pattern the four given values already follow.", "Subtract it off; the difference is monic of degree 4 with the four known roots."],
    difficulty: 9,
    topicSlug: "polynomials",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-122",
    question: "Two machines are set to integer levels a and b, each between 1 and 150 inclusive. A safety check passes when a² + b² is divisible by 21. How many ordered pairs of settings pass the check?",
    format: "MULTIPLE_CHOICE",
    choices: ["49", "100", "196", "900", "441"],
    answer: "A",
    solution: "Divisibility by 21 means by both 3 and 7. Modulo 3, squares are 0 or 1, so a² + b² ≡ 0 forces both a and b divisible by 3. Modulo 7, squares are 0, 1, 2, 4, and no two nonzero ones sum to 0, so both must be divisible by 7. Hence both are multiples of 21, and there are 7 such values in 1 to 150 (21 through 147), giving 7 × 7 = 49 pairs.",
    hints: ["Handle divisibility by 3 and by 7 separately.", "In each case check which pairs of quadratic residues can sum to zero."],
    difficulty: 9,
    topicSlug: "integer-properties",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-123",
    question: "A sensor sits inside a triangular plot whose three sides are equal, at distances of 3, 4, and 5 meters from the plot's three corners. How long is each side of the plot, in meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["√41", "√(25 − 12√3)", "√(25 + 12√3)", "√(50 + 12√3)", "7"],
    answer: "C",
    solution: "Rotating the configuration 60 degrees about one corner maps the 3 and 4 distances into a triangle with sides 3, 4, and 5, which is right-angled, so the angle between the 3 and 4 segments at the sensor is 90° + 60° = 150°. Applying the law of cosines to that pair, the side satisfies s² = 9 + 16 − 2(3)(4)cos 150° = 25 + 12√3, so s = √(25 + 12√3).",
    hints: ["Rotate the figure 60 degrees about one corner of the triangle.", "The 3-4-5 triangle that appears pins down the angle at the interior point."],
    difficulty: 9,
    topicSlug: "advanced-geometry",
    competitionSlug: "amc12",
  },
  {
    slug: "amc12-124",
    question:
      "A bug starts at one vertex of a regular octahedron. Each move, it walks along an edge to one of the adjacent vertices, chosen uniformly at random and independently of previous moves. What is the probability that after 4 moves the bug is back at its starting vertex?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/4", "5/32", "1/16", "3/16", "21/128"],
    answer: "D",
    solution:
      "A regular octahedron has 6 vertices in 3 opposite pairs, and each vertex is adjacent to the 4 vertices other than itself and its opposite. Group the vertices relative to the start S: the start itself, its opposite O, and the four 'equatorial' vertices. Let sₙ, oₙ, eₙ be the probabilities of being at S, at O, and at any one specific equatorial vertex after n moves. From S or from O the bug must go to an equatorial vertex; from an equatorial vertex it goes to S, to O, or to one of the two equatorial vertices adjacent to it, each with probability 1/4. Start with s₀ = 1, o₀ = 0, e₀ = 0. After 1 move: s₁ = 0, o₁ = 0, e₁ = 1/4 each. After 2: s₂ = 4 · (1/4)(1/4) = 1/4, o₂ = 1/4, and each equatorial vertex has e₂ = 2 · (1/4)(1/4) = 1/8. After 3: s₃ = 4 · (1/8)(1/4) = 1/8, o₃ = 1/8, and e₃ = (s₂ + o₂)(1/4) + 2·e₂·(1/4) = (1/2)(1/4) + 2(1/8)(1/4) = 1/8 + 1/16 = 3/16. After 4: s₄ = 4 · e₃ · (1/4) = 3/16. So the probability is 3/16. A direct transition-matrix computation over the 6 vertices confirms s₄ = 3/16 (and o₄ = 3/16, with each equatorial vertex at 5/32).",
    hints: [
      "Six vertices is too many to track individually — use the symmetry to collapse them into just three classes relative to the starting vertex.",
      "The key structural fact is that each vertex is adjacent to every vertex except its own opposite, so the bug can never move to the antipode in one step.",
      "Set up a recursion on the three class probabilities and iterate it four times; note that after an even number of moves the start and its opposite are equally likely.",
    ],
    difficulty: 9,
    topicSlug: "probability",
    competitionSlug: "amc12",
  },
];
