import type { ProblemSeed } from "./problems";

/**
 * Hand-written problems styled after the two real Math League contest
 * tiers. Math League contests are short, clean, curriculum-based problems —
 * steady and approachable, testing solid mastery under modest time
 * pressure rather than olympiad-style tricks. None of these are
 * transcribed from real Math League contests; they are original
 * NumberSmith problems written to match that format, phrasing, and
 * difficulty band.
 *
 * Math League (Elementary & Middle School) (math-league-elementary-middle)
 * targets grades 4-8: fractions, ratios, basic geometry, and simple word
 * problems, all short-answer with clean numeric or fraction results.
 *
 * Math League (High School) (math-league-high-school) targets core
 * high-school curriculum — algebra II, geometry, precalc-lite, basic
 * trig — with light competition technique, all multiple choice with five
 * answer options.
 */

export const MATH_LEAGUE_EM_PROBLEMS: ProblemSeed[] = [
  {
    slug: "math-league-em-01",
    question: "What is 2/3 + 1/5?",
    format: "SHORT_ANSWER",
    answer: "13/15",
    solution: "Common denominator is 15: 2/3 = 10/15 and 1/5 = 3/15. Adding gives 13/15.",
    hints: ["Rewrite both fractions with denominator 15.", "10/15 + 3/15"],
    difficulty: 2,
    topicSlug: "fractions",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-02",
    question: "The ratio of red marbles to blue marbles in a bag is 4:7. If there are 21 blue marbles, how many red marbles are there?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "21 blue marbles is 3 groups of 7 (since 21 ÷ 7 = 3). Each group has 4 red marbles, so red = 3 × 4 = 12.",
    hints: ["Find how many groups of 7 make 21.", "Multiply that number of groups by 4."],
    difficulty: 2,
    topicSlug: "ratios-proportions",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-03",
    question: "A triangle has angles measuring 38° and 71°. What is the measure of the third angle, in degrees?",
    format: "SHORT_ANSWER",
    answer: "71",
    solution: "The three angles of a triangle sum to 180°. 180 - 38 - 71 = 71.",
    hints: ["The angles of a triangle always add to 180°.", "Subtract the two given angles from 180."],
    difficulty: 2,
    topicSlug: "triangles",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-04",
    question: "Twelve is 30% of what number?",
    format: "SHORT_ANSWER",
    answer: "40",
    solution: "12 = 0.30 × n, so n = 12 / 0.30 = 40.",
    hints: ["Write 30% as the decimal 0.30.", "Divide 12 by 0.30."],
    difficulty: 2,
    topicSlug: "percentages",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-05",
    question: "A rectangular garden is 9 meters long and 6 meters wide. A gardener wants to put a fence post every 3 meters along the perimeter, including at each corner. How many posts are needed?",
    format: "SHORT_ANSWER",
    answer: "10",
    solution: "The perimeter is 2(9 + 6) = 30 meters. Posts every 3 meters around a closed loop gives 30 / 3 = 10 posts.",
    hints: ["Find the perimeter of the rectangle first.", "For a closed loop, the number of evenly spaced posts equals perimeter divided by spacing."],
    difficulty: 3,
    topicSlug: "area-volume",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-06",
    question: "Find the average of 14, 19, 23, and 32.",
    format: "SHORT_ANSWER",
    answer: "22",
    solution: "Sum = 14 + 19 + 23 + 32 = 88. Average = 88 / 4 = 22.",
    hints: ["Add all four numbers together.", "Divide the sum by 4."],
    difficulty: 2,
    topicSlug: "averages",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-07",
    question: "A car travels 180 miles in 3 hours at a constant speed. At that same speed, how many miles will it travel in 5 hours?",
    format: "SHORT_ANSWER",
    answer: "300",
    solution: "Speed = 180 / 3 = 60 miles per hour. In 5 hours it travels 60 × 5 = 300 miles.",
    hints: ["First find the speed in miles per hour.", "Multiply the speed by 5 hours."],
    difficulty: 2,
    topicSlug: "rates",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-08",
    question: "What is the greatest common factor of 48 and 60?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "48 = 2^4 × 3 and 60 = 2^2 × 3 × 5. The shared factors are 2^2 × 3 = 12.",
    hints: ["Write the prime factorization of each number.", "Multiply together the lowest power of each shared prime."],
    difficulty: 3,
    topicSlug: "number-properties",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-09",
    question: "Solve for x: 5x - 7 = 3x + 15.",
    format: "SHORT_ANSWER",
    answer: "11",
    solution: "Subtract 3x from both sides: 2x - 7 = 15. Add 7: 2x = 22. Divide by 2: x = 11.",
    hints: ["Get all the x terms on one side of the equation.", "Then isolate x by undoing addition/subtraction, then multiplication/division."],
    difficulty: 3,
    topicSlug: "linear-equations",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-10",
    question: "A regular hexagon has a perimeter of 42 cm. What is the length of one side, in centimeters?",
    format: "SHORT_ANSWER",
    answer: "7",
    solution: "A regular hexagon has 6 equal sides, so each side is 42 / 6 = 7 cm.",
    hints: ["A regular hexagon has 6 equal sides.", "Divide the perimeter by 6."],
    difficulty: 2,
    topicSlug: "polygons",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-11",
    question: "Sam has $45. He spends 2/5 of it on a book and then 1/3 of what remains on a snack. How much money does he have left, in dollars?",
    format: "SHORT_ANSWER",
    answer: "18",
    solution: "The book costs 2/5 × 45 = 18 dollars, leaving 45 - 18 = 27 dollars. The snack costs 1/3 × 27 = 9 dollars, leaving 27 - 9 = 18 dollars.",
    hints: ["Find the cost of the book first, then subtract it from $45.", "Take 1/3 of what remains for the snack, then subtract that too."],
    difficulty: 4,
    topicSlug: "fractions",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-12",
    question: "The sum of three consecutive even integers is 84. What is the largest of the three integers?",
    format: "SHORT_ANSWER",
    answer: "30",
    solution: "Let the integers be n, n+2, n+4. Their sum is 3n + 6 = 84, so n = 26. The largest is n + 4 = 30.",
    hints: ["Represent the three consecutive even integers as n, n+2, and n+4.", "Set 3n + 6 equal to 84 and solve for n."],
    difficulty: 4,
    topicSlug: "number-patterns",
    competitionSlug: "math-league-elementary-middle",
  },

{
    slug: "math-league-em-13",
    question: "What is 3/8 + 1/4?",
    format: "SHORT_ANSWER",
    answer: "5/8",
    solution: "Rewrite 1/4 as 2/8. Then 3/8 + 2/8 = 5/8.",
    hints: ["Find a common denominator of 8.", "1/4 = 2/8."],
    difficulty: 2,
    topicSlug: "fractions",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-14",
    question: "A number increased by 17 equals 52. What is the number?",
    format: "SHORT_ANSWER",
    answer: "35",
    solution: "Let the number be n. n + 17 = 52, so n = 52 - 17 = 35.",
    hints: ["Write an equation with n as the unknown number.", "Subtract 17 from both sides."],
    difficulty: 2,
    topicSlug: "arithmetic",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-15",
    question: "What is 15% of 80?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "15% of 80 is 0.15 × 80 = 12.",
    hints: ["Convert 15% to the decimal 0.15.", "Multiply 0.15 by 80."],
    difficulty: 2,
    topicSlug: "percentages",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-16",
    question: "A square has a perimeter of 36 inches. What is its area, in square inches?",
    format: "SHORT_ANSWER",
    answer: "81",
    solution: "Each side is 36 / 4 = 9 inches. Area = 9^2 = 81 square inches.",
    hints: ["Divide the perimeter by 4 to find one side.", "Square the side length to get the area."],
    difficulty: 2,
    topicSlug: "area-volume",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-17",
    question: "What is the least common multiple of 8 and 12?",
    format: "SHORT_ANSWER",
    answer: "24",
    solution: "8 = 2^3 and 12 = 2^2 × 3. The LCM takes the highest power of each prime: 2^3 × 3 = 24.",
    hints: ["List multiples of 12 until you find one divisible by 8.", "24 is divisible by both 8 and 12."],
    difficulty: 3,
    topicSlug: "number-properties",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-18",
    question: "Ben reads 24 pages of a book every day. If the book has 216 pages, how many full days does it take him to finish it?",
    format: "SHORT_ANSWER",
    answer: "9",
    solution: "216 / 24 = 9 days.",
    hints: ["Divide the total pages by the pages read per day.", "216 ÷ 24"],
    difficulty: 2,
    topicSlug: "arithmetic",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-19",
    question: "In a class of 30 students, the ratio of boys to girls is 2:3. How many boys are in the class?",
    format: "SHORT_ANSWER",
    answer: "12",
    solution: "The ratio parts total 2 + 3 = 5, and each part represents 30 / 5 = 6 students. Boys = 2 × 6 = 12.",
    hints: ["Add the ratio parts to find how many students each part represents.", "Multiply the boys' ratio part by that amount."],
    difficulty: 3,
    topicSlug: "ratios-proportions",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-20",
    question: "What is the value of 4^3 - 3^4?",
    format: "SHORT_ANSWER",
    answer: "-17",
    solution: "4^3 = 64 and 3^4 = 81. So 64 - 81 = -17.",
    hints: ["Compute each power separately.", "Subtract the second value from the first."],
    difficulty: 3,
    topicSlug: "arithmetic",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-21",
    question: "A rectangle has length 14 cm and width 5 cm. What is its perimeter, in centimeters?",
    format: "SHORT_ANSWER",
    answer: "38",
    solution: "Perimeter = 2(14 + 5) = 2(19) = 38 cm.",
    hints: ["Add the length and width first.", "Multiply that sum by 2."],
    difficulty: 2,
    topicSlug: "area-volume",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-22",
    question: "Solve for x: 4x + 9 = 2x + 21.",
    format: "SHORT_ANSWER",
    answer: "6",
    solution: "Subtract 2x from both sides: 2x + 9 = 21. Subtract 9: 2x = 12. Divide by 2: x = 6.",
    hints: ["Move the x terms to one side.", "Then isolate x."],
    difficulty: 3,
    topicSlug: "linear-equations",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-23",
    question: "How many positive divisors does 36 have?",
    format: "SHORT_ANSWER",
    answer: "9",
    solution: "36 = 2^2 × 3^2. The number of divisors is (2+1)(2+1) = 9.",
    hints: ["Find the prime factorization of 36.", "Add 1 to each exponent and multiply the results."],
    difficulty: 3,
    topicSlug: "number-properties",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-24",
    question: "A jar contains only nickels and dimes worth $3.15 in total. If there are 45 coins in all, how many dimes are there?",
    format: "SHORT_ANSWER",
    answer: "18",
    solution: "Let d = dimes and n = nickels. n + d = 45 and 5n + 10d = 315 (in cents). From the first equation, n = 45 - d. Substituting: 5(45-d) + 10d = 315, so 225 - 5d + 10d = 315, 5d = 90, d = 18.",
    hints: ["Set up two equations: one for coin count, one for total value in cents.", "Substitute n = 45 - d into the value equation."],
    difficulty: 4,
    topicSlug: "linear-equations",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-25",
    question: "What is the sum of the first 15 positive integers?",
    format: "SHORT_ANSWER",
    answer: "120",
    solution: "Sum = n(n+1)/2 = 15(16)/2 = 120.",
    hints: ["Use the formula for the sum of the first n positive integers.", "n(n+1)/2 with n = 15."],
    difficulty: 3,
    topicSlug: "number-patterns",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-26",
    question: "A circle has a radius of 7 cm. Using π ≈ 22/7, what is its circumference, in centimeters?",
    format: "SHORT_ANSWER",
    answer: "44",
    solution: "Circumference = 2πr = 2 × (22/7) × 7 = 44 cm.",
    hints: ["Use the formula C = 2πr.", "The 7s cancel nicely with π ≈ 22/7."],
    difficulty: 3,
    topicSlug: "circles",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-27",
    question: "Maria has test scores of 88, 92, and 79. What score does she need on a fourth test to have an average of exactly 85?",
    format: "SHORT_ANSWER",
    answer: "81",
    solution: "Four scores averaging 85 sum to 4 × 85 = 340. The first three sum to 88 + 92 + 79 = 259. The fourth score is 340 - 259 = 81.",
    hints: ["Find the total sum needed for an average of 85 over 4 tests.", "Subtract the sum of the known three scores."],
    difficulty: 3,
    topicSlug: "averages",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-28",
    question: "What is 2 5/6 expressed as an improper fraction?",
    format: "SHORT_ANSWER",
    answer: "17/6",
    solution: "2 5/6 = (2 × 6 + 5)/6 = 17/6.",
    hints: ["Multiply the whole number by the denominator.", "Add the numerator, then keep the same denominator."],
    difficulty: 2,
    topicSlug: "fractions",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-29",
    question: "A store marks up an item that costs $40 by 25% to set the selling price. What is the selling price, in dollars?",
    format: "SHORT_ANSWER",
    answer: "50",
    solution: "25% of 40 is 10, so the selling price is 40 + 10 = 50 dollars.",
    hints: ["Find 25% of the original cost.", "Add that markup to the original cost."],
    difficulty: 3,
    topicSlug: "percentages",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-30",
    question: "The product of two consecutive positive integers is 132. What is the smaller integer?",
    format: "SHORT_ANSWER",
    answer: "11",
    solution: "Let the integers be n and n+1. n(n+1) = 132. Testing n = 11: 11 × 12 = 132, which works.",
    hints: ["Try to estimate: √132 is a bit more than 11.", "Test n = 11 and n = 12 as consecutive integers."],
    difficulty: 4,
    topicSlug: "number-patterns",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-31",
    question: "How many prime numbers are there between 20 and 40?",
    format: "SHORT_ANSWER",
    answer: "4",
    solution: "The primes between 20 and 40 are 23, 29, 31, and 37 — that is 4 primes.",
    hints: ["List each number from 21 to 39 and check divisibility.", "Remember to exclude numbers divisible by 2, 3, 5, or 7 appropriately."],
    difficulty: 3,
    topicSlug: "primes",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-32",
    question: "A rectangular prism has length 6, width 4, and height 3. What is its volume?",
    format: "SHORT_ANSWER",
    answer: "72",
    solution: "Volume = length × width × height = 6 × 4 × 3 = 72.",
    hints: ["Volume of a rectangular prism is length times width times height.", "Multiply all three dimensions."],
    difficulty: 2,
    topicSlug: "area-volume",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-33",
    question: "If 3 workers can paint a fence in 8 hours, how many hours would it take 4 workers to paint the same fence, working at the same rate?",
    format: "SHORT_ANSWER",
    answer: "6",
    solution: "Total work = 3 workers × 8 hours = 24 worker-hours. With 4 workers: 24 / 4 = 6 hours.",
    hints: ["Find the total amount of work in worker-hours.", "Divide the total work by the new number of workers."],
    difficulty: 4,
    topicSlug: "rates",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-34",
    question: "What is the remainder when 587 is divided by 9?",
    format: "SHORT_ANSWER",
    answer: "2",
    solution: "9 × 65 = 585, and 587 - 585 = 2. (Check with the digit-sum trick: 5+8+7 = 20, and 20 mod 9 = 2, confirming the remainder is 2.)",
    hints: ["Use the digit-sum trick for divisibility by 9.", "587 = 9 × 65 + remainder."],
    difficulty: 3,
    topicSlug: "divisibility",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-35",
    question: "A number is tripled, then 8 is subtracted, giving a result of 25. What was the original number?",
    format: "SHORT_ANSWER",
    answer: "11",
    solution: "Let the number be n. 3n - 8 = 25, so 3n = 33, and n = 11.",
    hints: ["Translate the words into the equation 3n - 8 = 25.", "Add 8 to both sides, then divide by 3."],
    difficulty: 3,
    topicSlug: "linear-equations",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-36",
    question: "A pentagon has interior angles measuring 100°, 110°, 95°, and 130°. What is the measure of the fifth angle, in degrees?",
    format: "SHORT_ANSWER",
    answer: "105",
    solution: "The interior angles of a pentagon sum to (5-2) × 180 = 540°. The fifth angle is 540 - (100+110+95+130) = 540 - 435 = 105°.",
    hints: ["The sum of interior angles of a pentagon is (n-2) × 180 with n = 5.", "Subtract the four given angles from that total."],
    difficulty: 4,
    topicSlug: "polygons",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-37",
    question: "Simplify: (2/3) ÷ (4/9).",
    format: "SHORT_ANSWER",
    answer: "3/2",
    solution: "Dividing by a fraction means multiplying by its reciprocal: (2/3) × (9/4) = 18/12 = 3/2.",
    hints: ["Multiply by the reciprocal of the second fraction.", "Simplify the resulting fraction."],
    difficulty: 3,
    topicSlug: "fractions",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-38",
    question: "The population of a town grows from 2,000 to 2,500 in one year. What is the percent increase?",
    format: "SHORT_ANSWER",
    answer: "25",
    solution: "The increase is 500. Percent increase = 500 / 2000 × 100 = 25%.",
    hints: ["Find the amount of increase first.", "Divide the increase by the original amount and convert to a percent."],
    difficulty: 3,
    topicSlug: "percentages",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-39",
    question: "A number pattern begins 2, 6, 18, 54, ... where each term is 3 times the previous term. What is the 6th term?",
    format: "SHORT_ANSWER",
    answer: "486",
    solution: "The terms are 2, 6, 18, 54, 162, 486. The 6th term is 2 × 3^5 = 2 × 243 = 486.",
    hints: ["Each term is found by multiplying the previous term by 3.", "Continue the pattern from the 4th term to the 6th."],
    difficulty: 4,
    topicSlug: "number-patterns",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-40",
    question: "In a bag of 60 candies, 3/5 are chocolate and the rest are fruit-flavored. If 8 chocolate candies are eaten, how many chocolate candies remain?",
    format: "SHORT_ANSWER",
    answer: "28",
    solution: "Chocolate candies = 3/5 × 60 = 36. After eating 8, 36 - 8 = 28 remain.",
    hints: ["Find the number of chocolate candies to start.", "Subtract the 8 that were eaten."],
    difficulty: 3,
    topicSlug: "fractions",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-41",
    question: "Two angles are supplementary. One angle is 4 times the other. What is the measure of the smaller angle, in degrees?",
    format: "SHORT_ANSWER",
    answer: "36",
    solution: "Let the smaller angle be x, so the larger is 4x. Supplementary means x + 4x = 180, so 5x = 180, x = 36.",
    hints: ["Supplementary angles sum to 180°.", "Set up the equation x + 4x = 180."],
    difficulty: 4,
    topicSlug: "angles",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-42",
    question: "What is the units digit of 7^23?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution: "The units digits of powers of 7 cycle every 4: 7, 9, 3, 1, 7, 9, 3, 1, ... Since 23 mod 4 = 3, the units digit matches the 3rd term in the cycle, which is 3.",
    hints: ["Find the repeating cycle of units digits for powers of 7.", "Determine where 23 falls in that cycle using remainders."],
    difficulty: 5,
    topicSlug: "number-properties",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-43",
    question: "A trapezoid has parallel sides of length 8 and 14, and a height of 6. What is its area?",
    format: "SHORT_ANSWER",
    answer: "66",
    solution: "Area = (1/2)(b1 + b2)(h) = (1/2)(8 + 14)(6) = (1/2)(22)(6) = 66.",
    hints: ["Use the trapezoid area formula: (1/2)(sum of parallel sides)(height).", "Add the two parallel sides before multiplying."],
    difficulty: 4,
    topicSlug: "quadrilaterals",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-44",
    question: "Two dice are rolled. What is the probability that the sum is 8? Express your answer as a fraction.",
    format: "SHORT_ANSWER",
    answer: "5/36",
    solution: "The pairs summing to 8 are (2,6), (3,5), (4,4), (5,3), (6,2) — 5 outcomes out of 36 total equally likely outcomes. Probability = 5/36.",
    hints: ["List all ordered pairs of dice rolls that sum to 8.", "Divide the count of favorable outcomes by 36."],
    difficulty: 5,
    topicSlug: "basic-probability",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-45",
    question: "A recipe calls for 2 1/4 cups of flour to make 18 cookies. How many cups of flour are needed to make 24 cookies, keeping the same ratio?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution: "Flour per cookie = (2 1/4)/18 = (9/4)/18 = 9/72 = 1/8 cup. For 24 cookies: 24 × 1/8 = 3 cups.",
    hints: ["Find the amount of flour needed per single cookie.", "Multiply that unit rate by 24."],
    difficulty: 4,
    topicSlug: "ratios-proportions",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-46",
    question: "The sum of two numbers is 50 and their difference is 12. What is the larger number?",
    format: "SHORT_ANSWER",
    answer: "31",
    solution: "Let the numbers be x and y with x + y = 50 and x - y = 12. Adding the equations: 2x = 62, so x = 31.",
    hints: ["Add the two equations together to eliminate y.", "Solve for x, the larger number."],
    difficulty: 4,
    topicSlug: "linear-equations",
    competitionSlug: "math-league-elementary-middle",
  },
  {
    slug: "math-league-em-47",
    question: "A cube has a volume of 125 cubic centimeters. What is the total surface area of the cube, in square centimeters?",
    format: "SHORT_ANSWER",
    answer: "150",
    solution: "Since volume = s^3 = 125, the side length s = 5 cm. Surface area = 6s^2 = 6 × 25 = 150 square centimeters.",
    hints: ["Find the side length by taking the cube root of the volume.", "Surface area of a cube is 6 times the square of the side length."],
    difficulty: 5,
    topicSlug: "area-volume",
    competitionSlug: "math-league-elementary-middle",
  },
];

export const MATH_LEAGUE_HS_PROBLEMS: ProblemSeed[] = [
  {
    slug: "math-league-hs-01",
    question: "Solve for x: 2x^2 - 5x - 3 = 0. Which of the following is a solution?",
    format: "MULTIPLE_CHOICE",
    choices: ["x = -1/2", "x = 3", "x = -3", "x = 1", "x = 5/2"],
    answer: "B",
    solution: "Factoring: 2x^2 - 5x - 3 = (2x + 1)(x - 3) = 0, so x = -1/2 or x = 3. Only x = 3 appears among the choices.",
    hints: ["Try factoring the quadratic as (2x + 1)(x - 3).", "Set each factor equal to zero and solve."],
    difficulty: 4,
    topicSlug: "quadratics",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-02",
    question: "What is the sum of the first 20 terms of the arithmetic sequence 3, 7, 11, 15, ...?",
    format: "MULTIPLE_CHOICE",
    choices: ["800", "820", "780", "760", "840"],
    answer: "B",
    solution: "The 20th term is 3 + 19(4) = 79. Sum = 20(3 + 79)/2 = 20(82)/2 = 820.",
    hints: ["Find the 20th term using a_n = a_1 + (n-1)d.", "Use the sum formula S_n = n(a_1 + a_n)/2."],
    difficulty: 5,
    topicSlug: "sequences",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-03",
    question: "In right triangle ABC, angle C = 90°, side a = 9, and side b = 12. What is the length of the hypotenuse c?",
    format: "MULTIPLE_CHOICE",
    choices: ["21", "√63", "15", "13", "18"],
    answer: "C",
    solution: "By the Pythagorean theorem, c = √(9^2 + 12^2) = √(81 + 144) = √225 = 15.",
    hints: ["Apply the Pythagorean theorem c^2 = a^2 + b^2.", "9^2 + 12^2 = 225, and 225 is a perfect square."],
    difficulty: 4,
    topicSlug: "triangles",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-04",
    question: "Simplify: (3x^2y^3)^2 / (9x^3y^4).",
    format: "MULTIPLE_CHOICE",
    choices: ["x^2 y^2", "3x y^2", "x y^2 / 3", "x y^2", "x^2 y^2 / 3"],
    answer: "D",
    solution: "(3x^2y^3)^2 = 9x^4y^6. Dividing by 9x^3y^4 gives (9/9)x^(4-3)y^(6-4) = x y^2.",
    hints: ["First square the numerator: (3x^2y^3)^2 = 9x^4y^6.", "Then divide, subtracting exponents of like bases."],
    difficulty: 4,
    topicSlug: "exponents-radicals",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-05",
    question: "Two circles have radii 5 and 8, and their centers are 13 units apart. What is true about these two circles?",
    format: "MULTIPLE_CHOICE",
    choices: [
      "They are externally tangent",
      "They are internally tangent",
      "They do not intersect",
      "They intersect at two points",
      "One circle is entirely inside the other",
    ],
    answer: "A",
    solution: "Two circles are externally tangent when the distance between centers equals the sum of the radii. Here 5 + 8 = 13, which matches the given distance, so they are externally tangent.",
    hints: ["Compare the distance between centers to the sum and difference of the radii.", "Sum of radii = 5 + 8 = 13."],
    difficulty: 5,
    topicSlug: "circles",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-06",
    question: "If f(x) = 2x - 3 and g(x) = x^2 + 1, what is f(g(2))?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "5", "9", "11", "7"],
    answer: "E",
    solution: "g(2) = 2^2 + 1 = 5. Then f(5) = 2(5) - 3 = 7.",
    hints: ["Evaluate the inner function g(2) first.", "Plug that result into f(x) = 2x - 3."],
    difficulty: 4,
    topicSlug: "functions",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-07",
    question: "Solve the system: 3x + 2y = 16 and x - y = 2. What is the value of x?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "5", "2", "6"],
    answer: "B",
    solution: "From x - y = 2, x = y + 2. Substituting: 3(y+2) + 2y = 16, so 3y + 6 + 2y = 16, 5y = 10, y = 2, and x = y + 2 = 4.",
    hints: ["Solve the second equation for x in terms of y.", "Substitute into the first equation and solve for y, then back-substitute."],
    difficulty: 5,
    topicSlug: "systems-of-equations",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-08",
    question: "In a right triangle, one acute angle measures 30°. If the side opposite that angle has length 7, what is the length of the hypotenuse?",
    format: "MULTIPLE_CHOICE",
    choices: ["7√2", "7√3", "14", "10.5", "21"],
    answer: "C",
    solution: "sin(30°) = opposite/hypotenuse = 1/2, so hypotenuse = opposite / sin(30°) = 7 / (1/2) = 14.",
    hints: ["Use sin(30°) = 1/2 and the relation sin(angle) = opposite/hypotenuse.", "Solve for the hypotenuse by dividing."],
    difficulty: 5,
    topicSlug: "triangles",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-09",
    question: "Factor completely: x^3 - 9x.",
    format: "MULTIPLE_CHOICE",
    choices: ["x(x-9)(x+1)", "(x-3)^2(x+3)", "x^2(x-9)", "x(x-3)(x+3)", "x(x^2-9x)"],
    answer: "D",
    solution: "x^3 - 9x = x(x^2 - 9) = x(x-3)(x+3), using the difference of squares on x^2 - 9.",
    hints: ["Factor out the common factor of x first.", "Then recognize x^2 - 9 as a difference of squares."],
    difficulty: 4,
    topicSlug: "factoring",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-10",
    question: "Solve the inequality: -3x + 7 < 1. Which describes the solution set?",
    format: "MULTIPLE_CHOICE",
    choices: ["x > 2", "x < 2", "x > -2", "x < -2", "x > 8/3"],
    answer: "A",
    solution: "-3x + 7 < 1 gives -3x < -6. Dividing by -3 flips the inequality: x > 2.",
    hints: ["Subtract 7 from both sides first.", "Remember to flip the inequality sign when dividing by a negative number."],
    difficulty: 4,
    topicSlug: "inequalities",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-11",
    question: "A circle has equation x^2 + y^2 - 6x + 4y - 3 = 0. What is the radius of the circle?",
    format: "MULTIPLE_CHOICE",
    choices: ["√13", "16", "13", "5", "4"],
    answer: "E",
    solution: "Completing the square: (x^2 - 6x + 9) + (y^2 + 4y + 4) = 3 + 9 + 4, giving (x-3)^2 + (y+2)^2 = 16. So the radius is √16 = 4.",
    hints: ["Complete the square separately for the x-terms and y-terms.", "The right-hand side after completing the square equals the radius squared."],
    difficulty: 6,
    topicSlug: "coordinate-geometry",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-12",
    question: "How many distinct real solutions does the equation x^4 - 5x^2 + 4 = 0 have?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "0", "4", "3", "1"],
    answer: "C",
    solution: "Let u = x^2. Then u^2 - 5u + 4 = 0 factors as (u-1)(u-4) = 0, so u = 1 or u = 4, meaning x^2 = 1 or x^2 = 4. This gives x = ±1, ±2 — four distinct real solutions.",
    hints: ["Substitute u = x^2 to turn this into a quadratic in u.", "Solve for u, then remember each positive u value gives two real x values."],
    difficulty: 6,
    topicSlug: "polynomials",
    competitionSlug: "math-league-high-school",
  },

{
    slug: "math-league-hs-13",
    question: "Solve for x: 3x^2 + 5x - 2 = 0. What is the largest solution?",
    format: "SHORT_ANSWER",
    answer: "1/3",
    solution: "Factoring: 3x^2 + 5x - 2 = (3x - 1)(x + 2) = 0, so x = 1/3 or x = -2. The largest is 1/3.",
    hints: ["Try factoring into (3x - 1)(x + 2).", "Set each factor to zero and compare the two roots."],
    difficulty: 4,
    topicSlug: "quadratics",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-14",
    question: "What is the 12th term of the arithmetic sequence with first term 5 and common difference -3?",
    format: "SHORT_ANSWER",
    answer: "-28",
    solution: "a_12 = a_1 + 11d = 5 + 11(-3) = 5 - 33 = -28.",
    hints: ["Use a_n = a_1 + (n-1)d.", "Substitute n = 12, a_1 = 5, and d = -3."],
    difficulty: 4,
    topicSlug: "sequences",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-15",
    question: "In right triangle ABC with the right angle at C, leg a = 20 and hypotenuse c = 29. What is the length of leg b?",
    format: "SHORT_ANSWER",
    answer: "21",
    solution: "b = √(c^2 - a^2) = √(841 - 400) = √441 = 21.",
    hints: ["Rearrange the Pythagorean theorem to solve for b.", "841 - 400 = 441, and 441 is a perfect square."],
    difficulty: 4,
    topicSlug: "triangles",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-16",
    question: "Simplify: (2x^3y)^3 / (4x^4y^2).",
    format: "SHORT_ANSWER",
    answer: "2x^5y",
    solution: "(2x^3y)^3 = 8x^9y^3. Dividing by 4x^4y^2 gives (8/4)x^(9-4)y^(3-2) = 2x^5y.",
    hints: ["Cube the numerator first, applying the exponent to every factor.", "Then subtract exponents of matching bases when dividing."],
    difficulty: 4,
    topicSlug: "exponents-radicals",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-17",
    question: "A circle has center (2, -1) and passes through the point (7, 11). What is the radius of the circle?",
    format: "SHORT_ANSWER",
    answer: "13",
    solution: "r = √((7-2)^2 + (11-(-1))^2) = √(25 + 144) = √169 = 13.",
    hints: ["Use the distance formula between the center and the given point.", "5^2 + 12^2 is a familiar Pythagorean combination."],
    difficulty: 5,
    topicSlug: "circles",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-18",
    question: "If f(x) = x^2 - 4x + 1 and g(x) = 2x + 3, what is f(g(1))?",
    format: "SHORT_ANSWER",
    answer: "6",
    solution: "g(1) = 2(1) + 3 = 5. Then f(5) = 25 - 20 + 1 = 6.",
    hints: ["Evaluate g(1) first.", "Substitute that result into f(x)."],
    difficulty: 4,
    topicSlug: "functions",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-19",
    question: "Solve the system: 2x + 3y = 13 and 4x - y = 5. What is the value of y?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution: "From the second equation, y = 4x - 5. Substituting into the first: 2x + 3(4x - 5) = 13, so 2x + 12x - 15 = 13, 14x = 28, x = 2. Then y = 4(2) - 5 = 3.",
    hints: ["Solve the second equation for y in terms of x.", "Substitute into the first equation and solve for x, then find y."],
    difficulty: 5,
    topicSlug: "systems-of-equations",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-20",
    question: "In a right triangle, one acute angle measures 45°, and the hypotenuse has length 10√2. What is the length of each leg?",
    format: "SHORT_ANSWER",
    answer: "10",
    solution: "In a 45-45-90 triangle, each leg equals hypotenuse / √2 = 10√2 / √2 = 10.",
    hints: ["Recognize this as a 45-45-90 triangle where both legs are equal.", "Divide the hypotenuse by √2."],
    difficulty: 4,
    topicSlug: "triangles",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-21",
    question: "Factor completely: 2x^3 - 8x.",
    format: "SHORT_ANSWER",
    answer: "2x(x-2)(x+2)",
    solution: "2x^3 - 8x = 2x(x^2 - 4) = 2x(x-2)(x+2), using difference of squares on x^2 - 4.",
    hints: ["Factor out the greatest common factor of 2x first.", "Recognize x^2 - 4 as a difference of squares."],
    difficulty: 4,
    topicSlug: "factoring",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-22",
    question: "Solve the inequality: -2x + 5 ≥ -7. What is the solution, in the form x [comparison] [value]?",
    format: "SHORT_ANSWER",
    answer: "x <= 6",
    solution: "-2x + 5 >= -7 gives -2x >= -12. Dividing by -2 flips the inequality: x <= 6.",
    hints: ["Subtract 5 from both sides first.", "Dividing by a negative number flips the inequality sign."],
    difficulty: 4,
    topicSlug: "algebra",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-23",
    question: "A circle has equation x^2 + y^2 + 8x - 2y + 8 = 0. What is the radius of the circle?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution: "Completing the square: (x^2 + 8x + 16) + (y^2 - 2y + 1) = -8 + 16 + 1, giving (x+4)^2 + (y-1)^2 = 9. So radius = √9 = 3.",
    hints: ["Complete the square for the x-terms and y-terms separately.", "The right side after completing the square is the radius squared."],
    difficulty: 6,
    topicSlug: "coordinate-geometry",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-24",
    question: "How many distinct real solutions does the equation x^4 - 13x^2 + 36 = 0 have?",
    format: "SHORT_ANSWER",
    answer: "4",
    solution: "Let u = x^2. Then u^2 - 13u + 36 = 0 factors as (u-4)(u-9) = 0, so u = 4 or u = 9, meaning x = ±2 or x = ±3 — four distinct real solutions.",
    hints: ["Substitute u = x^2 to reduce this to a quadratic.", "Each positive value of u gives two real x values."],
    difficulty: 6,
    topicSlug: "polynomials",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-25",
    question: "What is the sum of the infinite geometric series 12 + 4 + 4/3 + 4/9 + ...?",
    format: "SHORT_ANSWER",
    answer: "18",
    solution: "This is geometric with a = 12 and r = 1/3. Sum = a/(1-r) = 12/(1 - 1/3) = 12/(2/3) = 18.",
    hints: ["Identify the first term and common ratio.", "Use the infinite geometric series formula S = a/(1-r)."],
    difficulty: 5,
    topicSlug: "sequences",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-26",
    question: "If log base 2 of x equals 5, what is x?",
    format: "SHORT_ANSWER",
    answer: "32",
    solution: "log_2(x) = 5 means x = 2^5 = 32.",
    hints: ["Rewrite the logarithmic equation in exponential form.", "2^5 = 32."],
    difficulty: 5,
    topicSlug: "exponents-radicals",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-27",
    question: "A triangle has vertices at A(0,0), B(6,0), and C(6,8). What is the length of side AC?",
    format: "SHORT_ANSWER",
    answer: "10",
    solution: "AC = √((6-0)^2 + (8-0)^2) = √(36+64) = √100 = 10.",
    hints: ["Use the distance formula between A and C.", "6^2 + 8^2 = 100, a perfect square."],
    difficulty: 4,
    topicSlug: "coordinate-geometry",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-28",
    question: "Simplify: √50 + √18. Express your answer as a√2 for some integer a, giving just the value of a.",
    format: "SHORT_ANSWER",
    answer: "8",
    solution: "√50 = 5√2 and √18 = 3√2. Adding gives 5√2 + 3√2 = 8√2, so a = 8.",
    hints: ["Simplify each radical separately by factoring out perfect squares.", "Combine like radical terms."],
    difficulty: 5,
    topicSlug: "exponents-radicals",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-29",
    question: "A ladder 26 feet long leans against a wall, with its base 10 feet from the wall. How many feet up the wall does the ladder reach?",
    format: "SHORT_ANSWER",
    answer: "24",
    solution: "By the Pythagorean theorem, height = √(26^2 - 10^2) = √(676-100) = √576 = 24 feet.",
    hints: ["Model the ladder, wall, and ground as a right triangle.", "676 - 100 = 576, a perfect square."],
    difficulty: 4,
    topicSlug: "triangles",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-30",
    question: "In a geometric sequence, the first term is 3 and the fourth term is 192. What is the common ratio?",
    format: "SHORT_ANSWER",
    answer: "4",
    solution: "a_4 = a_1 * r^3, so 192 = 3r^3, giving r^3 = 64, r = 4.",
    hints: ["Use a_4 = a_1 * r^3 for a geometric sequence.", "Solve for r^3 first, then take the cube root."],
    difficulty: 5,
    topicSlug: "sequences",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-31",
    question: "If sin(θ) = 3/5 and θ is an acute angle, what is cos(θ)?",
    format: "SHORT_ANSWER",
    answer: "4/5",
    solution: "Using a 3-4-5 right triangle where opposite = 3 and hypotenuse = 5, the adjacent side is √(25-9) = 4. So cos(θ) = 4/5.",
    hints: ["Picture a right triangle with opposite side 3 and hypotenuse 5.", "Use the Pythagorean theorem to find the adjacent side."],
    difficulty: 5,
    topicSlug: "triangles",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-32",
    question: "Solve for x: log_3(x+2) = 4.",
    format: "SHORT_ANSWER",
    answer: "79",
    solution: "log_3(x+2) = 4 means x+2 = 3^4 = 81, so x = 79.",
    hints: ["Rewrite the logarithmic equation in exponential form.", "3^4 = 81, then subtract 2."],
    difficulty: 5,
    topicSlug: "exponents-radicals",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-33",
    question: "A rectangle is inscribed in a semicircle of radius 5, with its base on the diameter. If the rectangle's height is 3, what is its width?",
    format: "SHORT_ANSWER",
    answer: "8",
    solution: "Half the width, w/2, and the height 3 satisfy (w/2)^2 + 3^2 = 5^2, so (w/2)^2 = 16, w/2 = 4, w = 8.",
    hints: ["Set up a right triangle from the center of the circle to a top corner of the rectangle.", "Use the Pythagorean theorem with the radius as the hypotenuse."],
    difficulty: 6,
    topicSlug: "circles",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-34",
    question: "How many ways can 5 distinct books be arranged on a shelf?",
    format: "SHORT_ANSWER",
    answer: "120",
    solution: "The number of arrangements of 5 distinct items is 5! = 120.",
    hints: ["This is a permutation of all 5 items.", "Compute 5! = 5×4×3×2×1."],
    difficulty: 4,
    topicSlug: "permutations",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-35",
    question: "What is the coefficient of x^2 in the expansion of (x+3)^4?",
    format: "SHORT_ANSWER",
    answer: "54",
    solution: "By the binomial theorem, the x^2 term is C(4,2) x^2 (3)^2 = 6 × 9 × x^2 = 54x^2. The coefficient is 54.",
    hints: ["Use the binomial theorem term C(n,k) x^(n-k) a^k.", "Here you need the term with x^2, so k = 2."],
    difficulty: 6,
    topicSlug: "polynomials",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-36",
    question: "Two fair six-sided dice are rolled. What is the probability that the product of the two numbers is even? Express your answer as a fraction.",
    format: "SHORT_ANSWER",
    answer: "3/4",
    solution: "The product is odd only when both dice show odd numbers: probability (1/2)(1/2) = 1/4. So the product is even with probability 1 - 1/4 = 3/4.",
    hints: ["It's easier to first find the probability the product is odd.", "The product is odd only when both rolls are odd."],
    difficulty: 5,
    topicSlug: "basic-probability",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-37",
    question: "Find the sum of the roots of the equation x^2 - 7x + 10 = 0 without solving for the individual roots.",
    format: "SHORT_ANSWER",
    answer: "7",
    solution: "For a quadratic ax^2+bx+c=0, the sum of roots is -b/a. Here that is -(-7)/1 = 7.",
    hints: ["Recall Vieta's formulas relating coefficients to root sums and products.", "Sum of roots = -b/a."],
    difficulty: 5,
    topicSlug: "quadratics",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-38",
    question: "A regular hexagon has side length 6. What is its area? Express your answer in the form a√3, giving only the value of a.",
    format: "SHORT_ANSWER",
    answer: "54",
    solution: "Area of a regular hexagon with side s is (3√3/2)s^2 = (3√3/2)(36) = 54√3, so a = 54.",
    hints: ["Use the regular hexagon area formula (3√3/2)s^2.", "Substitute s = 6 and simplify."],
    difficulty: 6,
    topicSlug: "polygons",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-39",
    question: "If f(x) = x^2 - 6x + 11, what is the minimum value of f(x)?",
    format: "SHORT_ANSWER",
    answer: "2",
    solution: "Complete the square: f(x) = (x-3)^2 + 2. The minimum value occurs at x=3, giving f(3) = 2.",
    hints: ["Complete the square to write f(x) in vertex form.", "The minimum of (x-3)^2 + k is k."],
    difficulty: 5,
    topicSlug: "quadratics",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-40",
    question: "A committee of 3 people is chosen from a group of 8. How many different committees are possible?",
    format: "SHORT_ANSWER",
    answer: "56",
    solution: "This is a combination: C(8,3) = 8!/(3!5!) = 56.",
    hints: ["Order doesn't matter for a committee, so use combinations.", "Compute C(8,3) = (8×7×6)/(3×2×1)."],
    difficulty: 5,
    topicSlug: "combinations",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-41",
    question: "Solve for x: 4^(x+1) = 32. Express x as a fraction.",
    format: "SHORT_ANSWER",
    answer: "3/2",
    solution: "4^(x+1) = 2^(2x+2) and 32 = 2^5. So 2x + 2 = 5, giving x = 3/2.",
    hints: ["Rewrite both sides with base 2.", "Set the exponents equal and solve for x."],
    difficulty: 6,
    topicSlug: "exponents-radicals",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-42",
    question: "A triangle has sides 7, 24, and 25. What is the area of the triangle?",
    format: "SHORT_ANSWER",
    answer: "84",
    solution: "Since 7^2 + 24^2 = 49 + 576 = 625 = 25^2, this is a right triangle with legs 7 and 24. Area = (1/2)(7)(24) = 84.",
    hints: ["Check whether the triangle is a right triangle using the Pythagorean theorem.", "If it is, the two legs serve as base and height."],
    difficulty: 5,
    topicSlug: "triangles",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-43",
    question: "What is the sum of all integer values of x satisfying |2x - 5| < 9?",
    format: "SHORT_ANSWER",
    answer: "20",
    solution: "|2x-5|<9 means -9 < 2x-5 < 9, so -4 < 2x < 14, giving -2 < x < 7. The integers strictly between -2 and 7 are -1, 0, 1, 2, 3, 4, 5, 6, which sum to 20.",
    hints: ["Solve the absolute value inequality to find the range of x.", "List all integers strictly between the bounds and sum them."],
    difficulty: 6,
    topicSlug: "algebra",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-44",
    question: "Two similar triangles have corresponding side lengths in ratio 3:5. If the area of the smaller triangle is 27, what is the area of the larger triangle?",
    format: "SHORT_ANSWER",
    answer: "75",
    solution: "Areas of similar figures scale with the square of the side ratio: (5/3)^2 = 25/9. Larger area = 27 × 25/9 = 75.",
    hints: ["Area ratio equals the square of the side length ratio.", "Multiply the smaller area by (5/3)^2."],
    difficulty: 6,
    topicSlug: "similarity-congruence",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-45",
    question: "Find all real solutions of x^3 - 6x^2 + 11x - 6 = 0. How many distinct real roots are there?",
    format: "SHORT_ANSWER",
    answer: "3",
    solution: "Testing x=1: 1-6+11-6=0, so (x-1) is a factor. Dividing gives x^2-5x+6=(x-2)(x-3). Roots are 1, 2, 3 — three distinct real roots.",
    hints: ["Try small integer values to find one root by the rational root theorem.", "Factor out that root and solve the remaining quadratic."],
    difficulty: 6,
    topicSlug: "polynomials",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-46",
    question: "A right circular cone has radius 6 and height 8. What is its volume? Express your answer as a multiple of π, giving only the coefficient.",
    format: "SHORT_ANSWER",
    answer: "96",
    solution: "Volume = (1/3)πr^2h = (1/3)π(36)(8) = 96π. The coefficient is 96.",
    hints: ["Use the cone volume formula V = (1/3)πr^2h.", "Substitute r=6 and h=8."],
    difficulty: 5,
    topicSlug: "area-volume",
    competitionSlug: "math-league-high-school",
  },
  {
    slug: "math-league-hs-47",
    question: "Find the value of k, with k > 0, such that the line y = kx + 4 is tangent to the parabola y = x^2 + 4x + 4.",
    format: "SHORT_ANSWER",
    answer: "4",
    solution: "Setting the equations equal: x^2 + 4x + 4 = kx + 4, so x^2 + (4-k)x = 0, which factors as x(x + 4 - k) = 0. This gives roots x = 0 and x = k - 4. Tangency means the quadratic has a repeated (double) root, so these two roots must be equal: k - 4 = 0, giving k = 4. (Check: at x = 0 both curves give y = 4, and the line touches without crossing.)",
    hints: ["Set the line and parabola equal to form a quadratic in x.", "Tangency means the resulting quadratic has a repeated root — its two solutions for x must coincide."],
    difficulty: 7,
    topicSlug: "quadratics",
    competitionSlug: "math-league-high-school",
  },
];
