import type { ProblemSeed } from "./problems";

/**
 * Hand-written problems styled after the AMC 10 (American Mathematics
 * Competitions, 10th-grade level).
 *
 * AMC 10 problems are terse, technique-driven, multiple-choice questions
 * spanning algebra, geometry, number theory, combinatorics, and
 * probability, with a sharp difficulty ramp across the 25-question set —
 * noticeably harder and more technique-heavy than AMC 8, with
 * olympiad-adjacent ideas (casework, pigeonhole, modular arithmetic,
 * clever algebraic identities) appearing in the back third. Every
 * problem below is an original NumberSmith problem, written to match
 * that format, phrasing, and difficulty ramp; none are transcribed,
 * paraphrased, or numerically reskinned from any real AMC contest.
 *
 * Difficulty rises from about 4 (problem 1) to about 9 (problem 32).
 */
export const AMC10_PROBLEMS: ProblemSeed[] = [
  {
    slug: "amc10-01",
    question: "A recipe calls for 2/3 cup of oats and 3/4 cup of flour. A scoop holds 5/6 cup, but 1/12 cup is always left stuck to the bottom and cannot be poured out. How many scoopfuls of usable volume are needed to supply the oats and flour together?",
    format: "MULTIPLE_CHOICE",
    choices: ["17/9", "16/9", "3/2", "2", "19/9"],
    answer: "A",
    solution: "The recipe needs 2/3 + 3/4 = 8/12 + 9/12 = 17/12 cups. Each scoop delivers 5/6 − 1/12 = 10/12 − 1/12 = 9/12 = 3/4 cup. Dividing, (17/12) ÷ (3/4) = 17/12 × 4/3 = 17/9.",
    hints: ["Add the two ingredient amounts, and separately find how much one scoop actually delivers.", "Divide the total needed by the usable amount per scoop."],
    difficulty: 4,
    topicSlug: "fractions",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-02",
    question: "Three houses in a row on one side of a street have consecutive even numbers. The sum of the three house numbers is 42 more than the smallest of them. What is the largest house number?",
    format: "MULTIPLE_CHOICE",
    choices: ["18", "20", "22", "24", "26"],
    answer: "C",
    solution: "Let the numbers be n, n+2, n+4. Their sum is 3n+6, which equals n+42. Solving, 3n+6 = n+42 gives 2n = 36, so n = 18. The largest is n+4 = 22.",
    hints: ["Call the smallest number n and write the other two in terms of n.", "Set the sum equal to n + 42 and solve."],
    difficulty: 4,
    topicSlug: "linear-equations",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-03",
    question:
      "A shirt's price is discounted 20%, and then the sale price is discounted an additional 15%. What single percent discount, applied to the original price, gives the same final price?",
    format: "MULTIPLE_CHOICE",
    choices: ["32%", "35%", "30%", "34%", "28%"],
    answer: "A",
    solution:
      "Applying both discounts multiplies the original price by 0.80 × 0.85 = 0.68, so the final price is 68% of the original — a 32% discount overall.",
    hints: [
      "Successive percent discounts multiply, they don't add.",
      "Multiply the two 'keep' factors (0.80 and 0.85) to find the combined price factor.",
    ],
    difficulty: 4,
    topicSlug: "percentages",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-04",
    question:
      "Train A travels 240 miles at a constant speed and takes 4 hours. Train B travels the same 240-mile route at a speed 20 mph faster than Train A. How many minutes less does Train B take?",
    format: "MULTIPLE_CHOICE",
    choices: ["45", "50", "60", "70", "75"],
    answer: "C",
    solution:
      "Train A's speed is 240/4 = 60 mph, so Train B's speed is 80 mph. Train B's time is 240/80 = 3 hours, which is 1 hour, or 60 minutes, less than Train A's 4 hours.",
    hints: [
      "First find Train A's speed from its distance and time.",
      "Compute Train B's travel time at its (faster) speed, then compare.",
    ],
    difficulty: 4,
    topicSlug: "rates",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-05",
    question: "A basketball player scored an average of 24 points across five games. When her highest-scoring game is set aside, the remaining four games average 21 points. How many points did she score in the game that was set aside?",
    format: "MULTIPLE_CHOICE",
    choices: ["30", "33", "36", "39", "42"],
    answer: "C",
    solution: "The five games total 5 × 24 = 120 points. The remaining four total 4 × 21 = 84. The removed game is 120 − 84 = 36 points.",
    hints: ["Convert each average into a total.", "The removed score is the difference between the two totals."],
    difficulty: 4,
    topicSlug: "averages",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-06",
    question: "A raffle uses tickets numbered 1 through 99. Every ticket whose number is divisible by 2 or by 3 is discarded before the drawing. How many tickets remain?",
    format: "MULTIPLE_CHOICE",
    choices: ["30", "32", "33", "34", "36"],
    answer: "C",
    solution: "Among 1 to 99 there are 49 multiples of 2, 33 multiples of 3, and 16 multiples of 6. By inclusion-exclusion, 49 + 33 − 16 = 66 are divisible by 2 or 3, leaving 99 − 66 = 33.",
    hints: ["Count the multiples of 2 and of 3 separately, then correct for double counting.", "Numbers counted twice are exactly the multiples of 6."],
    difficulty: 4,
    topicSlug: "number-properties",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-07",
    question:
      "A mixture of nuts consists of almonds, cashews, and walnuts in the ratio 3:4:5. After 6 more pounds of cashews are added, the ratio of almonds to cashews becomes 3:5. How many pounds of the mixture were there originally?",
    format: "MULTIPLE_CHOICE",
    choices: ["60", "66", "72", "78", "84"],
    answer: "C",
    solution:
      "Let the original amounts be 3k, 4k, 5k pounds. After adding 6 pounds of cashews, 3k/(4k+6) = 3/5, so 15k = 12k + 18, giving k = 6. The original total is 3k+4k+5k = 12k = 72 pounds.",
    hints: [
      "Write the original amounts as 3k, 4k, 5k pounds.",
      "Set up the new ratio equation 3k/(4k+6) = 3/5 and solve for k.",
    ],
    difficulty: 5,
    topicSlug: "ratios-proportions",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-08",
    question: "A triangular flower bed has one corner measuring 20 degrees more than a second corner, and its third corner measures three times the second corner. How many degrees is the first corner?",
    format: "MULTIPLE_CHOICE",
    choices: ["44", "48", "52", "56", "60"],
    answer: "C",
    solution: "Let the second corner be x. The first is x + 20 and the third is 3x. Since the three sum to 180: (x+20) + x + 3x = 180, so 5x = 160 and x = 32. The first corner is 32 + 20 = 52 degrees.",
    hints: ["Name the second corner x and write the other two in terms of x.", "Set the sum equal to 180, solve for x, then answer the question that was asked."],
    difficulty: 5,
    topicSlug: "angles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-09",
    question: "A triangular frame is welded from three metal rods. Two of the rods measure 11 cm and 17 cm, and the third must be a whole number of centimeters. How many different lengths are possible for the third rod?",
    format: "MULTIPLE_CHOICE",
    choices: ["19", "20", "21", "22", "23"],
    answer: "C",
    solution: "The third rod x must satisfy 17 − 11 < x < 17 + 11, that is 6 < x < 28. The whole numbers from 7 to 27 number 27 − 7 + 1 = 21.",
    hints: ["Each side of a triangle lies strictly between the difference and the sum of the other two.", "Count the whole numbers in that open range, excluding both endpoints."],
    difficulty: 5,
    topicSlug: "triangles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-10",
    question: "A parallelogram-shaped tabletop has sides of length 7 and 9 feet, and a brace runs corner to corner measuring 8 feet. How long is the brace across the other pair of corners, in feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "12", "13", "14", "15"],
    answer: "D",
    solution: "For a parallelogram the squares of the diagonals sum to twice the sum of the squares of the sides: d₁² + d₂² = 2(7² + 9²) = 260. With d₁ = 8, d₂² = 260 − 64 = 196, so d₂ = 14 feet.",
    hints: ["There is an identity relating the two diagonals of a parallelogram to its two side lengths.", "The diagonals' squares add to twice the sum of the sides' squares."],
    difficulty: 5,
    topicSlug: "quadrilaterals",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-11",
    question: "One bacteria colony starts with a single cell and doubles every hour; after x + 3 hours it reaches a certain size. A second colony also starts with a single cell but quadruples every hour, and after x − 1 hours it reaches that same size. What is the value of x?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "5", "6", "7"],
    answer: "C",
    solution: "The sizes are 2^(x+3) and 4^(x−1) = 2^(2x−2). Setting the exponents equal, x + 3 = 2x − 2, so x = 5.",
    hints: ["Rewrite the quadrupling colony's size as a power of 2.", "With the same base, the exponents must match."],
    difficulty: 5,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-12",
    question: "A rectangular banner has side lengths x + p and x + q, where p and q are positive integers with pq = 36. Multiplied out, its area is x² + bx + 36. What is the largest possible value of b?",
    format: "MULTIPLE_CHOICE",
    choices: ["15", "20", "25", "37", "36"],
    answer: "D",
    solution: "Expanding gives b = p + q while pq = 36. The sum is largest when the factors are farthest apart, at p = 1 and q = 36, giving b = 37.",
    hints: ["Multiply out (x+p)(x+q) to see what b equals in terms of p and q.", "Among factor pairs of 36, the most lopsided pair has the biggest sum."],
    difficulty: 5,
    topicSlug: "factoring",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-13",
    question: "A vendor sells pens for $2 each and notebooks for $3 each. One morning she sells x pens and y notebooks for exactly $47, and she sells 6 more pens than notebooks. What is the value of xy?",
    format: "MULTIPLE_CHOICE",
    choices: ["77", "84", "91", "98", "105"],
    answer: "C",
    solution: "The conditions are 2x + 3y = 47 and x − y = 6, so x = y + 6. Substituting, 2(y+6) + 3y = 47 gives 5y + 12 = 47, so y = 7 and x = 13. Then xy = 91.",
    hints: ["Use the second fact to write the pen count in terms of the notebook count.", "Substitute into the money equation and solve."],
    difficulty: 5,
    topicSlug: "systems-of-equations",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-14",
    question:
      "A password consists of 4 characters: the first two are distinct letters chosen from {A, B, C, D, E}, and the last two are distinct digits chosen from {1, 2, 3, 4, 5, 6}. How many such passwords are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["400", "480", "540", "600", "720"],
    answer: "D",
    solution:
      "The two distinct letters can be arranged in 5 × 4 = 20 ways, and the two distinct digits in 6 × 5 = 30 ways. By the multiplication principle, the total is 20 × 30 = 600.",
    hints: [
      "Count the ordered choices for the letter positions and the digit positions separately.",
      "Multiply the two counts together.",
    ],
    difficulty: 5,
    topicSlug: "counting-principles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-15",
    question: "Two circular grain silos of radii 9 and 4 meters stand on level ground with their centers 13 meters apart, so their walls just touch. A straight cable is stretched tangent to both silos on the same side, touching each one once. How long is the cable between its two points of contact, in meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "11", "12", "13", "6√5"],
    answer: "C",
    solution: "A common external tangent between circles with centers d apart and radii r₁, r₂ has length √(d² − (r₁ − r₂)²) = √(13² − 5²) = √144 = 12 meters.",
    hints: ["Drop a perpendicular to build a right triangle whose hypotenuse joins the two centers.", "One leg is the tangent length and the other is the difference of the radii."],
    difficulty: 6,
    topicSlug: "circles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-16",
    question: "A tile shop sells tiles shaped like regular polygons. One style has a corner angle 15 degrees larger than the corner angle of its regular hexagonal tile. How many sides does that style have?",
    format: "MULTIPLE_CHOICE",
    choices: ["7", "8", "9", "10", "12"],
    answer: "B",
    solution: "A regular hexagon's interior angle is 120 degrees, so this tile's is 135 degrees. From (n−2)·180/n = 135, we get 180n − 360 = 135n, so 45n = 360 and n = 8.",
    hints: ["Find the hexagon's interior angle first, then add 15.", "Set the regular-polygon interior angle formula equal to that value and solve for n."],
    difficulty: 6,
    topicSlug: "polygons",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-17",
    question: "A drone climbs at a steady rate as it flies away from a marker. At horizontal position 2 it is 5 meters up, and at horizontal position 8 it is 17 meters up. At what horizontal position was the drone at ground level?",
    format: "MULTIPLE_CHOICE",
    choices: ["−1", "−1/2", "0", "1/2", "1"],
    answer: "B",
    solution: "The rate is (17 − 5)/(8 − 2) = 2 meters per unit. From the point (2, 5), the height is y − 5 = 2(x − 2), so y = 2x + 1. Setting y = 0 gives x = −1/2.",
    hints: ["Find how fast the height rises per unit of horizontal position.", "Write the height as a linear function and set it to zero."],
    difficulty: 6,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-18",
    question: "The seats in an arena are numbered 1 through 499. A seat receives a free program if its number is divisible by both 6 and 8, unless that number is also divisible by 5. How many seats receive a program?",
    format: "MULTIPLE_CHOICE",
    choices: ["14", "15", "16", "17", "18"],
    answer: "C",
    solution: "Divisible by both 6 and 8 means divisible by 24, and ⌊499/24⌋ = 20 such seats exist. Of those, the ones also divisible by 5 are multiples of 120, and ⌊499/120⌋ = 4. So 20 − 4 = 16 seats qualify.",
    hints: ["Divisibility by both 6 and 8 is the same as divisibility by their least common multiple.", "Subtract the ones that are also multiples of 5, which are multiples of 120."],
    difficulty: 6,
    topicSlug: "divisibility",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-19",
    question: "A gardener places a marker at fence post p and also at posts p + 2 and p + 6, but only when all three of those post numbers are prime and p is less than 20. What is the sum of all values of p she uses?",
    format: "MULTIPLE_CHOICE",
    choices: ["28", "33", "36", "39", "41"],
    answer: "B",
    solution: "Testing primes below 20: p = 5 gives 5, 7, 11 (all prime); p = 11 gives 11, 13, 17 (all prime); p = 17 gives 17, 19, 23 (all prime). The others fail, so the sum is 5 + 11 + 17 = 33.",
    hints: ["Test each prime below 20 one at a time.", "Check both p + 2 and p + 6 before accepting a value."],
    difficulty: 6,
    topicSlug: "primes",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-20",
    question: "A culture starts with 1 organism and triples every hour. After 100 hours the organisms are sorted into groups of 13, making as many full groups as possible. How many organisms are left over?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "3", "9", "10", "12"],
    answer: "B",
    solution: "After 100 hours there are 3¹⁰⁰ organisms. Since 3³ = 27 leaves remainder 1 upon division by 13, the remainders cycle with period 3. As 100 = 3(33) + 1, the remainder matches that of 3¹, which is 3.",
    hints: ["Compute the remainders of 3, 9, 27, 81, ... upon division by 13 and find the repeating cycle.", "Divide 100 by the cycle length and use the remainder."],
    difficulty: 6,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-21",
    question: "The seven letter tiles A, L, G, E, B, R, A are laid in a row to spell out a display. How many distinguishable displays have the two A tiles next to each other?",
    format: "MULTIPLE_CHOICE",
    choices: ["360", "480", "600", "720", "840"],
    answer: "D",
    solution: "Glue the two identical A tiles into one block. That leaves 6 distinct units — the block plus L, G, E, B, R — which can be ordered in 6! = 720 ways. Swapping the two A's inside the block changes nothing, since they are identical.",
    hints: ["Treat the pair of A's as a single unit that must stay together.", "Count arrangements of the resulting units, and remember the two A's are indistinguishable."],
    difficulty: 6,
    topicSlug: "permutations",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-22",
    question:
      "A committee of 5 people is chosen from 6 men and 5 women. How many such committees include at least 3 women?",
    format: "MULTIPLE_CHOICE",
    choices: ["171", "176", "181", "186", "191"],
    answer: "C",
    solution:
      "Count by cases on the number of women: exactly 3 women gives C(5,3)C(6,2) = 10×15 = 150; exactly 4 women gives C(5,4)C(6,1) = 5×6 = 30; exactly 5 women gives C(5,5)C(6,0) = 1. The total is 150+30+1 = 181.",
    hints: [
      "Split into cases: exactly 3, exactly 4, and exactly 5 women on the committee.",
      "Use combinations to count each case, then add the cases together.",
    ],
    difficulty: 6,
    topicSlug: "combinations",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-23",
    question:
      "Two fair six-sided dice are rolled. What is the probability that the product of the two numbers rolled is a multiple of 4?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/3", "3/8", "5/12", "4/9", "7/12"],
    answer: "C",
    solution:
      "Classify each face by its power of 2: {1,3,5} contribute 0, {2,6} contribute 1, {4} contributes 2. The product is a multiple of 4 exactly when the total power of 2 from both dice is at least 2. Counting ordered pairs by combined power: total 2 occurs 6+4=10 ways (one die contributes 0 & other 2, or both contribute 1), total 3 occurs 4 ways, total 4 occurs 1 way, giving 10+4+1 = 15 favorable outcomes out of 36. The probability is 15/36 = 5/12.",
    hints: [
      "Track how many factors of 2 each die face contributes: 0 for odd faces, 1 for 2 or 6, 2 for the face 4.",
      "The product is divisible by 4 exactly when the two dice's factor-of-2 counts sum to at least 2 — count those ordered pairs out of 36.",
    ],
    difficulty: 7,
    topicSlug: "basic-probability",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-24",
    question: "A rectangular plot has a perimeter of 16 meters, and the squares built on its length and its width have areas totaling 34 square meters. What is the area of the plot, in square meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "12", "15", "17", "20"],
    answer: "C",
    solution: "The length and width sum to 8, and their squares sum to 34. Since (a+b)² = a² + b² + 2ab, we get 64 = 34 + 2ab, so ab = 15 square meters.",
    hints: ["The perimeter gives you the sum of the two dimensions.", "Expand the square of that sum to bring in the product you want."],
    difficulty: 7,
    topicSlug: "quadratics",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-25",
    question: "A player begins a board game holding 3 tokens. In each round the player's tokens double and then one more token is added. How many tokens does the player hold after 4 rounds?",
    format: "MULTIPLE_CHOICE",
    choices: ["47", "55", "63", "71", "79"],
    answer: "C",
    solution: "Round by round: 3, then 2(3)+1 = 7, then 2(7)+1 = 15, then 2(15)+1 = 31, then 2(31)+1 = 63.",
    hints: ["Apply the doubling and the +1 one round at a time.", "Four rounds means four applications starting from 3."],
    difficulty: 7,
    topicSlug: "sequences",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-26",
    question: "A triangular sail has a horizontal seam running parallel to its bottom edge. The seam cuts the left edge into an upper piece 4 feet long and a lower piece 6 feet long. The small triangle above the seam has an area of 8 square feet. What is the area, in square feet, of the four-sided piece below the seam?",
    format: "MULTIPLE_CHOICE",
    choices: ["32", "36", "40", "42", "45"],
    answer: "D",
    solution: "The small triangle is similar to the whole sail with ratio 4/10 = 2/5, so the whole sail has area 8 ÷ (2/5)² = 8 ÷ (4/25) = 50 square feet. The piece below the seam is 50 − 8 = 42 square feet.",
    hints: ["The seam being parallel to the bottom makes the top triangle similar to the whole sail.", "Compare the left edges to get the ratio, then square it to compare areas."],
    difficulty: 7,
    topicSlug: "similarity-congruence",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-27",
    question:
      "A cylindrical tank with radius 6 and height 10 is filled with water to a height of 4. A solid sphere of radius 3 is then fully submerged in the tank. What is the new height of the water?",
    format: "MULTIPLE_CHOICE",
    choices: ["4.5", "5", "5.5", "6", "6.5"],
    answer: "B",
    solution:
      "The sphere's volume is (4/3)π(3³) = 36π. The tank's cross-sectional area is π(6²) = 36π. The water rises by (volume displaced)/(base area) = 36π/36π = 1, so the new height is 4 + 1 = 5.",
    hints: [
      "Find the volume of water displaced by the submerged sphere.",
      "Divide the displaced volume by the tank's cross-sectional area to find the rise in water level.",
    ],
    difficulty: 7,
    topicSlug: "area-volume",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-28",
    question: "A weather model predicts that the temperature change on day n will be n² − 7n − 30 degrees, where negative values of n refer to days before the model's start date. For how many integer values of n does the model predict a change of at most 0 degrees?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "13", "14", "15", "16"],
    answer: "C",
    solution: "Factor: n² − 7n − 30 = (n − 10)(n + 3), which is at most 0 exactly when −3 ≤ n ≤ 10. The integers from −3 to 10 number 10 − (−3) + 1 = 14.",
    hints: ["Factor the quadratic to find where it crosses zero.", "A product of two factors is negative or zero exactly between the two roots, endpoints included."],
    difficulty: 7,
    topicSlug: "inequalities",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-29",
    question: "Three friends split 12 identical stickers so that each friend gets at least one sticker and no friend gets more than 6. In how many ways can the stickers be distributed, if the friends are distinguishable?",
    format: "MULTIPLE_CHOICE",
    choices: ["19", "22", "25", "28", "31"],
    answer: "C",
    solution: "Ignoring the upper limit, the positive-integer solutions to a+b+c = 12 number C(11,2) = 55. If one friend gets 7 or more, substituting a′ = a − 6 leaves a′+b+c = 6 with C(5,2) = 10 solutions, and the same for each of the three friends. Two friends cannot both exceed 6 at once, so the invalid count is 3 × 10 = 30, leaving 55 − 30 = 25.",
    hints: ["First count the distributions ignoring the cap of 6, using stars and bars.", "Subtract the cases where some friend exceeds 6, and check whether two can exceed it at once."],
    difficulty: 8,
    topicSlug: "casework",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-30",
    question: "A bag holds tiles numbered 1 through 30, one of each. How many tiles must you draw to be certain that two of the drawn numbers differ by exactly 5?",
    format: "MULTIPLE_CHOICE",
    choices: ["11", "13", "15", "16", "18"],
    answer: "D",
    solution: "Sort the numbers into 5 chains by remainder mod 5, each of length 6, such as 1, 6, 11, 16, 21, 26. Within a chain, neighbors differ by 5, so the largest selection avoiding a difference of 5 takes every other entry: 3 per chain, or 15 in all. Drawing a 16th tile forces two numbers differing by 5.",
    hints: ["Group the numbers so that two numbers differing by 5 always land in the same group.", "Find the largest possible draw with no such pair, then add one."],
    difficulty: 8,
    topicSlug: "pigeonhole",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-31",
    question: "A caterer buys small trays costing $5 each and large trays costing $8 each, spending exactly $200 and buying at least one of each size. In how many different ways can this be done?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "5", "6", "7"],
    answer: "B",
    solution: "With x small and y large trays, 5x + 8y = 200. Then x = (200 − 8y)/5 requires 8y to be a multiple of 5, so y is a multiple of 5. With y < 25 to keep x positive, y = 5, 10, 15, 20 give x = 32, 24, 16, 8. That is 4 ways.",
    hints: ["Write the spending equation and solve for one variable.", "Divisibility forces one of the two counts to be a multiple of 5."],
    difficulty: 8,
    topicSlug: "diophantine-equations",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-32",
    question:
      "A fair coin is flipped repeatedly until either two consecutive heads or two consecutive tails have appeared. What is the expected number of flips?",
    format: "MULTIPLE_CHOICE",
    choices: ["5/2", "3", "7/2", "4", "9/2"],
    answer: "B",
    solution:
      "After the first flip, define E as the expected number of additional flips needed. From this state, the next flip matches the previous one with probability 1/2 (stopping immediately) or doesn't match with probability 1/2 (staying in the same type of state, needing E more flips). So E = 1 + (1/2)(0) + (1/2)(E), giving (1/2)E = 1, so E = 2. Including the first flip, the total expected number of flips is 1 + 2 = 3.",
    hints: [
      "Set up a recursive equation for the expected number of additional flips needed once the process has started.",
      "After the first flip, each subsequent flip either ends the process or leaves you in an equivalent waiting state — use this self-similarity to solve for the expectation.",
    ],
    difficulty: 9,
    topicSlug: "expected-value",
    competitionSlug: "amc10",
  },

{
    slug: "amc10-33",
    question: "A pump removes 5/6 of a tank of water per hour, while a leak lets 1/4 of a tank per hour flow back in. The pump runs for 2/3 of an hour and then for another 1/2 hour. What fraction of a tank is removed overall?",
    format: "MULTIPLE_CHOICE",
    choices: ["7/12", "49/72", "1", "7/6", "49/36"],
    answer: "B",
    solution: "The net rate is 5/6 − 1/4 = 10/12 − 3/12 = 7/12 tank per hour, and the total time is 2/3 + 1/2 = 4/6 + 3/6 = 7/6 hours. The amount removed is (7/12)(7/6) = 49/72 of a tank.",
    hints: ["Find the net rate and the total time separately.", "Amount removed is rate times time."],
    difficulty: 4,
    topicSlug: "fractions",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-34",
    question: "Adding 12 books to Nina's shelf gives the same total as tripling the number of books she has and then removing 8. How many books does Nina have?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "11", "12", "14", "20"],
    answer: "A",
    solution: "With x books, x + 12 = 3x − 8, so 20 = 2x and x = 10.",
    hints: ["Write each description as an expression in x and set them equal.", "Collect the x terms on one side."],
    difficulty: 4,
    topicSlug: "linear-equations",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-35",
    question:
      "A jacket originally costs $80. It is marked up 25%, and then the marked-up price is discounted 20% during a sale. What is the final sale price?",
    format: "MULTIPLE_CHOICE",
    choices: ["$80", "$84", "$88", "$92", "$96"],
    answer: "A",
    solution:
      "The markup multiplies the price by 1.25, giving 80 × 1.25 = $100. The discount then multiplies by 0.80, giving 100 × 0.80 = $80. (In general, a 25% increase followed by a 20% decrease multiplies the price by 1.25 × 0.80 = 1, returning to the original price.)",
    hints: [
      "Apply the 25% markup first to find the sale's starting price.",
      "Notice that multiplying by 1.25 and then by 0.80 has a special combined effect.",
    ],
    difficulty: 4,
    topicSlug: "percentages",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-36",
    question:
      "The ratio of boys to girls in a class is 5:7. There are 8 more girls than boys. How many students are in the class in total?",
    format: "MULTIPLE_CHOICE",
    choices: ["36", "40", "44", "48", "52"],
    answer: "D",
    solution:
      "Let the numbers of boys and girls be 5k and 7k. Then 7k − 5k = 8, so 2k = 8 and k = 4. The total number of students is 5k + 7k = 12k = 48.",
    hints: [
      "Write the numbers of boys and girls as 5k and 7k for some k.",
      "The difference 7k − 5k equals 8 — solve for k, then find 12k.",
    ],
    difficulty: 4,
    topicSlug: "ratios-proportions",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-37",
    question:
      "The test scores of 5 students average 82. A sixth student joins the class, and the average of all six scores becomes 84. What score did the sixth student receive?",
    format: "MULTIPLE_CHOICE",
    choices: ["88", "90", "92", "94", "96"],
    answer: "D",
    solution:
      "The five original scores sum to 5 × 82 = 410. The six scores sum to 6 × 84 = 504. The sixth student's score is 504 − 410 = 94.",
    hints: [
      "Convert each average into a total sum by multiplying by the number of students.",
      "The new student's score is the difference between the six-person sum and the five-person sum.",
    ],
    difficulty: 4,
    topicSlug: "averages",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-38",
    question:
      "One printer prints 15 pages per minute, and a second printer prints 10 pages per minute. Working together, how many minutes do the two printers take to print 150 pages?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "6", "7", "8", "9"],
    answer: "B",
    solution:
      "Working together, the printers print 15 + 10 = 25 pages per minute. To print 150 pages takes 150/25 = 6 minutes.",
    hints: [
      "Add the two printing rates to get a combined rate.",
      "Divide the total number of pages by the combined rate.",
    ],
    difficulty: 4,
    topicSlug: "rates",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-39",
    question: "A gym's lockers are numbered 1 through 49. Every locker whose number is a multiple of 3 or a multiple of 4 is assigned to the swim team. How many lockers does the swim team get?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "25", "26", "27", "28"],
    answer: "A",
    solution: "There are ⌊49/3⌋ = 16 multiples of 3 and ⌊49/4⌋ = 12 multiples of 4. Lockers counted twice are multiples of 12, of which there are ⌊49/12⌋ = 4. So the total is 16 + 12 − 4 = 24.",
    hints: ["Count each kind of multiple separately.", "Lockers that are multiples of both get counted twice — subtract them once."],
    difficulty: 4,
    topicSlug: "number-properties",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-40",
    question: "A triangular window has one corner measuring 20 degrees less than a second corner, and its third corner measures 70 degrees. How many degrees is the second corner?",
    format: "MULTIPLE_CHOICE",
    choices: ["55", "60", "65", "70", "75"],
    answer: "C",
    solution: "The first two corners sum to 180 − 70 = 110 degrees. If the second is x, the first is x − 20, so (x − 20) + x = 110, giving 2x = 130 and x = 65 degrees.",
    hints: ["Subtract the known corner from 180 to get the total of the other two.", "Write both unknown corners in terms of one variable."],
    difficulty: 4,
    topicSlug: "triangles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-41",
    question: "A rectangular dog run is enclosed by 64 feet of fencing, and it is 8 feet longer than it is wide. What is the area of the run, in square feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["190", "210", "220", "230", "240"],
    answer: "E",
    solution: "With width w the length is w + 8, and 2(w + w + 8) = 64 gives 2w + 8 = 32, so w = 12 and the length is 20. The area is 12 × 20 = 240 square feet.",
    hints: ["Write the length in terms of the width and use the perimeter.", "Once both dimensions are known, multiply."],
    difficulty: 4,
    topicSlug: "quadrilaterals",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-42",
    question: "A circular pond covers an area of 64π square meters. How many meters long is the path that runs all the way around its edge?",
    format: "MULTIPLE_CHOICE",
    choices: ["4π", "8π", "12π", "14π", "16π"],
    answer: "E",
    solution: "From πr² = 64π we get r = 8. The path is the circumference, 2πr = 16π meters.",
    hints: ["Use the area to find the radius first.", "Then apply the circumference formula."],
    difficulty: 4,
    topicSlug: "circles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-43",
    question: "On a city map the library sits at (1, 2) and the stadium sits at (7, 10), where each unit is one kilometer. How many kilometers apart are they in a straight line?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "11", "12", "13", "14"],
    answer: "A",
    solution: "The horizontal gap is 6 and the vertical gap is 8, so the distance is √(6² + 8²) = √100 = 10 kilometers.",
    hints: ["Find the horizontal and vertical gaps separately.", "Those gaps are the legs of a right triangle whose hypotenuse is the distance."],
    difficulty: 4,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-44",
    question: "A deck contains one card for each whole number from 41 through 59. How many of those cards show a prime number?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "5", "6", "7", "8"],
    answer: "B",
    solution: "Testing each value from 41 to 59, the primes are 41, 43, 47, 53, and 59 — five cards.",
    hints: ["Only check divisibility by 2, 3, 5, and 7, since 8² exceeds 59.", "Work through the range in order so none is missed."],
    difficulty: 4,
    topicSlug: "primes",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-45",
    question: "One machine completes a cycle every 12 seconds and another every 18 seconds. They both start a cycle at the same instant. After how many seconds do they next begin a cycle together?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "28", "30", "33", "36"],
    answer: "E",
    solution: "They coincide at the least common multiple of 12 and 18. Since 12 = 2²·3 and 18 = 2·3², the lcm is 2²·3² = 36 seconds.",
    hints: ["The next shared start is a multiple of both cycle lengths.", "Factor both numbers and take the highest power of each prime."],
    difficulty: 4,
    topicSlug: "divisibility",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-46",
    question:
      "A restaurant offers 4 appetizers, 6 main courses, and 3 desserts. How many different 3-course meals (one of each course) can be ordered?",
    format: "MULTIPLE_CHOICE",
    choices: ["72", "78", "84", "90", "96"],
    answer: "A",
    solution: "By the multiplication principle, the number of meals is 4 × 6 × 3 = 72.",
    hints: [
      "Each course is chosen independently of the others.",
      "Multiply the number of choices for each course together.",
    ],
    difficulty: 4,
    topicSlug: "counting-principles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-47",
    question:
      "A bag contains 4 red marbles and 6 blue marbles. One marble is drawn at random. What is the probability that it is red?",
    format: "MULTIPLE_CHOICE",
    choices: ["3/10", "2/5", "1/2", "3/5", "7/10"],
    answer: "B",
    solution:
      "There are 10 marbles total, 4 of which are red, so the probability of drawing red is 4/10 = 2/5.",
    hints: [
      "Divide the number of red marbles by the total number of marbles.",
      "Simplify the resulting fraction.",
    ],
    difficulty: 4,
    topicSlug: "basic-probability",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-48",
    question: "The first row of a lecture hall has 5 seats, and each row behind it has 6 more seats than the row in front. How many seats are in the 15th row?",
    format: "MULTIPLE_CHOICE",
    choices: ["83", "85", "87", "89", "91"],
    answer: "D",
    solution: "The 15th row has had 14 increases of 6 applied: 5 + 6(14) = 5 + 84 = 89 seats.",
    hints: ["Count how many increases separate row 1 from row 15.", "There are 14 of them, not 15."],
    difficulty: 4,
    topicSlug: "sequences",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-49",
    question: "Two square courtyards have areas of 50 and 18 square meters. A stone border runs along one full side of each courtyard. What is the combined length of the two borders, in meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["8√2", "9√2", "10√2", "11√2", "12√2"],
    answer: "A",
    solution: "The sides are √50 = 5√2 and √18 = 3√2 meters, so the total is 5√2 + 3√2 = 8√2 meters.",
    hints: ["Each side length is the square root of the corresponding area.", "Factor a perfect square out of each radical so the two terms can be combined."],
    difficulty: 4,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-50",
    question: "A startup's balance, in thousands of dollars, t months after launch is modeled by t² − 5t − 24, where negative t refers to months before launch. The balance is exactly zero at two such times. What is the sum of the absolute values of those two times?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "11", "13", "16", "19"],
    answer: "B",
    solution: "Factoring, t² − 5t − 24 = (t − 8)(t + 3), so the zeros are t = 8 and t = −3. The sum of absolute values is 8 + 3 = 11.",
    hints: ["Factor the quadratic to find where it equals zero.", "Take the size of each root, ignoring sign, then add."],
    difficulty: 4,
    topicSlug: "factoring",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-51",
    question: "Adult tickets cost $3 and child tickets cost $2. A group spends exactly $16 and buys 2 more adult tickets than child tickets. How many tickets does the group buy in all?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "5", "6", "7", "8"],
    answer: "C",
    solution: "With x adult and y child tickets, 3x + 2y = 16 and x − y = 2, so x = y + 2. Then 3(y+2) + 2y = 16 gives 5y + 6 = 16, so y = 2 and x = 4. The total is x + y = 6.",
    hints: ["Use the ticket-count relationship to eliminate one variable.", "After solving, add the two counts rather than reporting just one."],
    difficulty: 4,
    topicSlug: "systems-of-equations",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-52",
    question: "Two plots of land meet at a shared corner along a straight boundary wall, so their two corner angles together form a straight line. One angle is 30 degrees more than twice the other. What is the measure, in degrees, of the smaller angle?",
    format: "MULTIPLE_CHOICE",
    choices: ["50", "55", "60", "65", "70"],
    answer: "A",
    solution: "The angles sum to 180 degrees. If the smaller is x, the other is 2x + 30, so x + (2x + 30) = 180, giving 3x = 150 and x = 50 degrees.",
    hints: ["Angles forming a straight line add to 180 degrees.", "Write the larger angle in terms of the smaller one before solving."],
    difficulty: 4,
    topicSlug: "angles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-53",
    question:
      "A recipe requires flour, sugar, and butter in the ratio 5:2:3 by weight. If the baker uses 6 more cups of flour than butter, how many cups of sugar does he use?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "7", "8", "9", "10"],
    answer: "A",
    solution:
      "Let the amounts be 5k, 2k, 3k cups. Since flour exceeds butter by 6 cups, 5k − 3k = 6, so 2k = 6 and k = 3. The sugar amount is 2k = 6 cups.",
    hints: [
      "Write the three amounts as 5k, 2k, and 3k.",
      "Use the given difference between flour and butter to solve for k.",
    ],
    difficulty: 5,
    topicSlug: "ratios-proportions",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-54",
    question: "A triangular sign has corners measuring 2x degrees, (3x + 10) degrees, and (4x − 10) degrees. What is the measure, in degrees, of the largest-labeled corner, the one measuring 4x − 10?",
    format: "MULTIPLE_CHOICE",
    choices: ["50", "55", "60", "65", "70"],
    answer: "E",
    solution: "The angles sum to 180: 2x + (3x+10) + (4x−10) = 180, so 9x = 180 and x = 20. That corner measures 4(20) − 10 = 70 degrees.",
    hints: ["Add the three expressions and set the total to 180.", "Solve for x, then substitute back into the expression asked about."],
    difficulty: 5,
    topicSlug: "triangles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-55",
    question: "A parallelogram-shaped garden has two straight paths running corner to corner, measuring 20 and 10 meters. One side of the garden is 9 meters long. How long is the neighboring side, in meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "11", "12", "13", "14"],
    answer: "D",
    solution: "For a parallelogram the squares of the diagonals sum to twice the sum of the squares of the sides: 20² + 10² = 2(9² + b²). So 500 = 2(81 + b²), giving b² = 169 and b = 13 meters.",
    hints: ["Use the identity linking a parallelogram's two diagonals to its two side lengths.", "Substitute the known diagonal lengths and the known side, then solve for the other side."],
    difficulty: 5,
    topicSlug: "quadrilaterals",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-56",
    question: "A sample of one material triples in mass every hour and is measured after 2x − 1 hours. A sample of a second material grows 27-fold every hour and is measured after x − 2 hours. Both measurements give the same multiple of the starting mass. What is the value of x?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "6", "7", "8", "9"],
    answer: "A",
    solution: "The two multiples are 3^(2x−1) and 27^(x−2) = 3^(3x−6). Setting the exponents equal, 2x − 1 = 3x − 6, so x = 5.",
    hints: ["Rewrite 27 as a power of 3 so both sides share a base.", "Equal powers with the same base force equal exponents."],
    difficulty: 5,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-57",
    question: "A square plot of land with side x meters sits beside a rectangular strip whose area is x square meters. Together they cover 42 square meters. What is the largest possible value of x?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "6", "7", "8", "9"],
    answer: "B",
    solution: "The total area is x² + x = 42, so x² + x − 42 = 0, which factors as (x − 6)(x + 7) = 0. The solutions are 6 and −7, and the largest is 6.",
    hints: ["Write an equation for the combined area.", "Move everything to one side and factor the quadratic."],
    difficulty: 5,
    topicSlug: "quadratics",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-58",
    question: "A rectangular field has a perimeter of 50 meters and an area of 126 square meters. What is the positive difference between its length and its width, in meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["11", "13", "15", "17", "19"],
    answer: "A",
    solution: "The length and width sum to 25 and multiply to 126, so they are the roots of t² − 25t + 126 = 0. The discriminant is 625 − 504 = 121, so the roots are (25 ± 11)/2 = 18 and 7. Their difference is 11 meters.",
    hints: ["The perimeter gives the sum of the dimensions and the area gives their product.", "Build a quadratic with that sum and product, or find the pair by inspection."],
    difficulty: 5,
    topicSlug: "systems-of-equations",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-59",
    question:
      "A code consists of 3 distinct letters chosen from {A, B, C, D, E, F}, followed by 2 distinct digits chosen from {1, 2, 3, 4, 5}. How many such codes are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["1800", "2000", "2200", "2400", "2600"],
    answer: "D",
    solution:
      "The three distinct letters can be arranged in 6 × 5 × 4 = 120 ways, and the two distinct digits in 5 × 4 = 20 ways. By the multiplication principle, the total number of codes is 120 × 20 = 2400.",
    hints: [
      "Count the ordered arrangements of letters and of digits separately.",
      "Multiply the two counts together.",
    ],
    difficulty: 5,
    topicSlug: "counting-principles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-60",
    question:
      "How many ways can 4 different books be arranged on a shelf so that two specific books are not adjacent to each other?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "14", "16", "18", "20"],
    answer: "A",
    solution:
      "There are 4! = 24 total arrangements. Treating the two specific books as a single glued block gives 3! × 2 = 12 arrangements where they are adjacent. So the number of arrangements where they are not adjacent is 24 − 12 = 12.",
    hints: [
      "First count all arrangements, then count the arrangements where the two books are adjacent by gluing them together.",
      "Subtract the adjacent count from the total.",
    ],
    difficulty: 5,
    topicSlug: "permutations",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-61",
    question:
      "A standard six-sided die is rolled twice. What is the probability that the sum of the two rolls is 8?",
    format: "MULTIPLE_CHOICE",
    choices: ["5/36", "1/6", "7/36", "2/9", "1/4"],
    answer: "A",
    solution:
      "The pairs (a,b) with a+b = 8 are (2,6), (3,5), (4,4), (5,3), (6,2) — five outcomes out of 36 total. The probability is 5/36.",
    hints: [
      "List the ordered pairs of die rolls that sum to 8.",
      "Divide the count of favorable outcomes by 36.",
    ],
    difficulty: 5,
    topicSlug: "basic-probability",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-62",
    question: "A charity drive raises $4 on its first day, and on each following day it raises 3 times what it raised the day before. How many dollars does it raise over the first 5 days in total?",
    format: "MULTIPLE_CHOICE",
    choices: ["400", "444", "464", "484", "500"],
    answer: "D",
    solution: "The daily amounts are 4, 12, 36, 108, and 324 dollars, totaling 484. Equivalently, 4(3⁵ − 1)/(3 − 1) = 4(242)/2 = 484.",
    hints: ["Write out the five daily amounts.", "Add them directly, or use the geometric series sum formula."],
    difficulty: 5,
    topicSlug: "sequences",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-63",
    question: "A ramp descends 3 feet for every 4 feet it runs horizontally away from a wall. At a horizontal distance of 4 feet from the wall, the ramp is 1 foot above the ground. How many feet above the ground is the ramp where it meets the wall?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "5", "6", "7", "8"],
    answer: "A",
    solution: "The slope is −3/4, and through the point (4, 1): y − 1 = −(3/4)(x − 4), so y = −(3/4)x + 4. At the wall, x = 0, giving y = 4 feet.",
    hints: ["Descending 3 for every 4 forward means a slope of −3/4.", "Use the given point to find the height at horizontal distance 0."],
    difficulty: 5,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-64",
    question: "A circular rug is placed in a square room with 10-foot sides so that the rug just touches all four walls. What is the area of the rug, in square feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["25π", "30π", "35π", "40π", "50π"],
    answer: "A",
    solution: "The rug's diameter equals the room's side, 10 feet, so its radius is 5. Its area is π(5²) = 25π square feet.",
    hints: ["Touching all four walls means the diameter matches the side length.", "Halve to get the radius before squaring."],
    difficulty: 5,
    topicSlug: "circles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-65",
    question:
      "A price increases by 10%, and then the new price increases by another 10%. If the final price is $968, what was the original price?",
    format: "MULTIPLE_CHOICE",
    choices: ["$800", "$820", "$840", "$860", "$880"],
    answer: "A",
    solution:
      "Two successive 10% increases multiply the original price by 1.1 × 1.1 = 1.21. So the original price is 968/1.21 = $800.",
    hints: [
      "Successive percent increases multiply rather than add.",
      "Divide the final price by the combined growth factor 1.21.",
    ],
    difficulty: 5,
    topicSlug: "percentages",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-66",
    question:
      "Working alone, Alice can paint a room in 6 hours, and Bob can paint the same room in 4 hours. If they work together, how many hours does it take them to paint the room?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "12/5", "5/2", "3", "10/3"],
    answer: "B",
    solution:
      "Alice's rate is 1/6 room per hour and Bob's is 1/4 room per hour. Together their rate is 1/6 + 1/4 = 2/12 + 3/12 = 5/12 room per hour. The time needed is 1 ÷ (5/12) = 12/5 hours.",
    hints: [
      "Add the individual rates (rooms per hour) to find the combined rate.",
      "Take the reciprocal of the combined rate to find the time.",
    ],
    difficulty: 5,
    topicSlug: "rates",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-67",
    question: "A store's sales over six days average 20 items per day. Over the first four of those days the average is 18 items per day. What is the average number of items sold on the last two days?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "25", "26", "27", "28"],
    answer: "A",
    solution: "The six days total 6 × 20 = 120 items and the first four total 4 × 18 = 72, so the last two total 48. Their average is 48/2 = 24 items.",
    hints: ["Turn both averages into totals.", "Subtract to get the total for the last two days, then divide by 2."],
    difficulty: 5,
    topicSlug: "averages",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-68",
    question: "A prize of 60 identical coins is to be split evenly among some number of winners, where any number of winners that divides 60 exactly is allowed. What is the sum of all the possible per-winner amounts?",
    format: "MULTIPLE_CHOICE",
    choices: ["168", "175", "182", "189", "196"],
    answer: "A",
    solution: "The possible per-winner amounts are exactly the divisors of 60. Since 60 = 2²·3·5, their sum is (1+2+4)(1+3)(1+5) = 7 × 4 × 6 = 168.",
    hints: ["Each valid split corresponds to a divisor of 60.", "Factor 60 and use the product formula for the sum of its divisors."],
    difficulty: 5,
    topicSlug: "number-properties",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-69",
    question: "A gear train produces a total reduction ratio of 630, built entirely from gears whose tooth counts are prime numbers. What is the sum of the distinct prime tooth counts used?",
    format: "MULTIPLE_CHOICE",
    choices: ["14", "17", "19", "21", "23"],
    answer: "B",
    solution: "Factoring, 630 = 2 × 3² × 5 × 7. The distinct primes are 2, 3, 5, and 7, which sum to 17.",
    hints: ["Factor 630 completely into primes.", "Add each distinct prime only once, even if it appears twice."],
    difficulty: 5,
    topicSlug: "primes",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-70",
    question: "A carnival prints one ticket for every three-digit number from 100 to 999. A ticket wins a prize if its number is a multiple of 7. How many tickets win a prize?",
    format: "MULTIPLE_CHOICE",
    choices: ["120", "124", "126", "128", "130"],
    answer: "D",
    solution: "The smallest three-digit multiple of 7 is 105 = 7 × 15 and the largest is 994 = 7 × 142, so the count is 142 − 15 + 1 = 128.",
    hints: ["Find the first and last three-digit multiples of 7.", "Divide each by 7 and count the whole numbers between, inclusive."],
    difficulty: 5,
    topicSlug: "divisibility",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-71",
    question: "Two square rugs have areas that differ by 45 square feet, and their side lengths differ by 5 feet. What is the sum of their side lengths, in feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["7", "9", "10", "11", "12"],
    answer: "B",
    solution: "With sides x and y, x² − y² = 45 and x − y = 5. Since x² − y² = (x−y)(x+y), we get 5(x+y) = 45, so x + y = 9 feet.",
    hints: ["The difference of two squares factors into the sum times the difference.", "One of those two factors is already given."],
    difficulty: 5,
    topicSlug: "factoring",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-72",
    question: "A gazebo has a floor shaped like a convex polygon whose interior angles total 1440 degrees. How many sides does the floor have?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "7", "8", "9", "10"],
    answer: "E",
    solution: "For an n-sided polygon, the interior angles sum to (n − 2) × 180 degrees. Setting (n − 2) × 180 = 1440 gives n − 2 = 8, so n = 10.",
    hints: ["Use the interior-angle-sum formula for a polygon.", "Divide 1440 by 180 before solving for n."],
    difficulty: 5,
    topicSlug: "polygons",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-73",
    question: "Two circular ponds of radii 9 and 3 meters have centers 20 meters apart. A straight cable is stretched tangent to both ponds, crossing through the gap between them so that the two ponds lie on opposite sides of the cable. How long is the cable between its two points of contact, in meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "14", "15", "16", "18"],
    answer: "D",
    solution: "A common internal tangent between circles with centers d apart and radii r₁, r₂ has length √(d² − (r₁ + r₂)²) = √(20² − 12²) = √(400 − 144) = √256 = 16 meters.",
    hints: ["For a tangent crossing between the circles, the radii add rather than subtract.", "Build a right triangle with the center-to-center segment as the hypotenuse."],
    difficulty: 6,
    topicSlug: "circles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-74",
    question: "A designer is laying out a regular-polygon paving stone. Each of its interior corner angles measures 20 degrees more than 3 times the turn you make at each corner when walking once around its edge. How many sides does the stone have?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "7", "8", "9", "10"],
    answer: "D",
    solution: "The turn at each corner is the exterior angle e, and the interior angle is 180 − e. So 180 − e = 3e + 20, giving 4e = 160 and e = 40 degrees. Since the exterior angles total 360, the stone has 360/40 = 9 sides.",
    hints: ["The turn at each corner is the exterior angle, and interior plus exterior is 180 degrees.", "Walking all the way around turns through 360 degrees in total."],
    difficulty: 6,
    topicSlug: "polygons",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-75",
    question: "Two cyclists ride along the same straight road. After x hours, the first is at position 2x − 3 kilometers from a marker and the second is at position −x + 9 kilometers from it. They are side by side at exactly one moment. What is the sum of that time, in hours, and that position, in kilometers?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "6", "7", "8", "9"],
    answer: "E",
    solution: "Setting 2x − 3 = −x + 9 gives 3x = 12, so x = 4 hours. The shared position is 2(4) − 3 = 5 kilometers. The sum is 4 + 5 = 9.",
    hints: ["Set the two position expressions equal to find when they meet.", "Substitute back to get the position, then add the two values."],
    difficulty: 6,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-76",
    question: "A stadium's seats are numbered 1 through 299. A seat is repainted if its number is divisible by 9, unless that number is also divisible by 15. How many seats are repainted?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "25", "26", "27", "28"],
    answer: "D",
    solution: "There are ⌊299/9⌋ = 33 multiples of 9. Those also divisible by 15 are the multiples of lcm(9,15) = 45, of which there are ⌊299/45⌋ = 6. So 33 − 6 = 27 seats are repainted.",
    hints: ["Count multiples of 9 first.", "The excluded ones are multiples of the least common multiple of 9 and 15."],
    difficulty: 6,
    topicSlug: "divisibility",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-77",
    question: "A lighting designer switches on the bulbs numbered p, p + 4, and p + 6, but only when all three of those numbers are prime and p is less than 30. What is the sum of all values of p she can use?",
    format: "MULTIPLE_CHOICE",
    choices: ["8", "12", "16", "18", "20"],
    answer: "E",
    solution: "Testing primes below 30: p = 7 gives 7, 11, 13, all prime; p = 13 gives 13, 17, 19, all prime. Every other prime below 30 fails. The sum is 7 + 13 = 20.",
    hints: ["Check each prime below 30 in turn.", "Both p + 4 and p + 6 must be prime, not just one of them."],
    difficulty: 6,
    topicSlug: "primes",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-78",
    question: "A culture starts with a single organism and multiplies sevenfold every hour. After 45 hours the organisms are arranged into rows of 11, as many complete rows as possible. How many organisms are left over?",
    format: "MULTIPLE_CHOICE",
    choices: ["0", "1", "3", "7", "10"],
    answer: "E",
    solution: "The count is 7⁴⁵, and we want its remainder upon division by 11. Since 7¹⁰ leaves remainder 1, the remainders repeat every 10 hours, and 45 leaves remainder 5 upon division by 10. Computing 7⁵ = 16807 = 11(1527) + 10, the leftover is 10.",
    hints: ["Find the repeating cycle of remainders of powers of 7 upon division by 11.", "Reduce the exponent 45 using that cycle length."],
    difficulty: 6,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-79",
    question: "How many distinct arrangements are there of the letters in the word BANANA?",
    format: "MULTIPLE_CHOICE",
    choices: ["30", "60", "90", "120", "150"],
    answer: "B",
    solution:
      "BANANA has 6 letters with A repeated 3 times and N repeated 2 times. The number of distinct arrangements is 6!/(3!·2!) = 720/12 = 60.",
    hints: [
      "Use the formula for permutations of a multiset: divide the factorial of the total count by the factorials of each repeated letter's count.",
      "B appears once, A appears 3 times, N appears 2 times.",
    ],
    difficulty: 6,
    topicSlug: "permutations",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-80",
    question:
      "A committee of 4 people is chosen from 5 juniors and 4 seniors and must include at least 2 seniors. How many such committees are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["69", "72", "75", "78", "81"],
    answer: "E",
    solution:
      "Count by cases on the number of seniors: 2 seniors and 2 juniors gives C(4,2)·C(5,2) = 6×10 = 60; 3 seniors and 1 junior gives C(4,3)·C(5,1) = 4×5 = 20; 4 seniors and 0 juniors gives C(4,4)·C(5,0) = 1. The total is 60 + 20 + 1 = 81.",
    hints: [
      "Split into cases based on exactly how many seniors are on the committee.",
      "Use combinations for each case, then add the cases together.",
    ],
    difficulty: 6,
    topicSlug: "combinations",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-81",
    question: "A fair coin is flipped 5 times. What is the probability of getting exactly 3 heads?",
    format: "MULTIPLE_CHOICE",
    choices: ["5/32", "3/16", "1/4", "5/16", "15/32"],
    answer: "D",
    solution:
      "The number of ways to choose which 3 of the 5 flips are heads is C(5,3) = 10, out of 2⁵ = 32 equally likely outcomes. The probability is 10/32 = 5/16.",
    hints: [
      "Use combinations to count the number of ways to place 3 heads among 5 flips.",
      "Divide by the total number of possible outcomes, 2⁵.",
    ],
    difficulty: 6,
    topicSlug: "basic-probability",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-82",
    question: "A rectangular plot has a perimeter of 12 meters, and its length exceeds its width by 4 meters. What is its area, in square meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["1", "2", "3", "4", "5"],
    answer: "E",
    solution: "The length and width sum to 6 and differ by 4, so they are 5 and 1. The area is 5 × 1 = 5 square meters.",
    hints: ["Halve the perimeter to get the sum of the two dimensions.", "Use the sum and the difference to find both dimensions."],
    difficulty: 6,
    topicSlug: "quadratics",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-83",
    question: "A triangular garden has a 14-meter base along a straight wall, and the garden covers 84 square meters. A post is placed on the wall 6 meters from one end of the base, and a straight path runs from that post to the garden's far corner. What is the area, in square meters, of the piece of garden between the path and the nearer end of the wall?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "18", "24", "30", "36"],
    answer: "E",
    solution: "Both pieces share the same height from the far corner down to the wall. Areas are therefore proportional to their bases, so the smaller piece has area 84 × (6/14) = 36 square meters.",
    hints: ["The two pieces have the same height measured from the far corner.", "Their areas are in the same ratio as the two parts of the base."],
    difficulty: 6,
    topicSlug: "triangles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-84",
    question: "Two sails have exactly the same triangular shape but different sizes, covering 50 and 128 square feet of canvas. The smaller sail is edged with 25 feet of rope around its border. How many feet of rope edge the larger sail?",
    format: "MULTIPLE_CHOICE",
    choices: ["32", "35", "38", "40", "42"],
    answer: "D",
    solution: "The ratio of areas is 128/50 = 64/25, so the ratio of corresponding lengths is √(64/25) = 8/5. The larger border is 25 × 8/5 = 40 feet.",
    hints: ["For similar figures, the area ratio is the square of the length ratio.", "Take the square root of the area ratio before scaling the border."],
    difficulty: 6,
    topicSlug: "similarity-congruence",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-85",
    question: "A rectangular carton measures 4 inches by 6 inches by x inches. Wrapping it takes exactly 208 square inches of paper, covering all six faces with no overlap. What is the value of x?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "5", "6", "7", "8"],
    answer: "E",
    solution: "The surface area is 2(4·6 + 4x + 6x) = 2(24 + 10x) = 48 + 20x. Setting 48 + 20x = 208 gives 20x = 160, so x = 8.",
    hints: ["Write the surface area as twice the sum of the three distinct face areas.", "Set that expression equal to 208 and solve."],
    difficulty: 6,
    topicSlug: "area-volume",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-86",
    question: "A bakery sells 2 pastries on its first day and 5 on its second day. On every later day it sells as many pastries as the two previous days combined, plus one extra. How many pastries does it sell on the fifth day?",
    format: "MULTIPLE_CHOICE",
    choices: ["15", "17", "19", "21", "23"],
    answer: "E",
    solution: "Day 3 is 5 + 2 + 1 = 8, day 4 is 8 + 5 + 1 = 14, and day 5 is 14 + 8 + 1 = 23 pastries.",
    hints: ["Build the days up one at a time.", "Do not forget the extra pastry added each day."],
    difficulty: 6,
    topicSlug: "sequences",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-87",
    question: "A factory line has two machines. The first takes a number, squares it, and adds 1. Its output is fed into the second machine, which doubles a number and subtracts 3. If 3 enters the first machine, what number leaves the second?",
    format: "MULTIPLE_CHOICE",
    choices: ["13", "15", "17", "19", "21"],
    answer: "C",
    solution: "The first machine outputs 3² + 1 = 10. The second then gives 2(10) − 3 = 17.",
    hints: ["Work through the machines in order, first then second.", "The first machine's output is the second machine's input."],
    difficulty: 6,
    topicSlug: "functions",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-88",
    question: "In a recipe the flour-to-sugar ratio is 3 to 5, and the sugar-to-butter ratio is 10 to 7. What is the ratio of flour to butter?",
    format: "MULTIPLE_CHOICE",
    choices: ["3:7", "3:5", "5:7", "6:7", "6:5"],
    answer: "D",
    solution: "Scale the first ratio so sugar matches: flour to sugar is 3:5 = 6:10. With sugar to butter at 10:7, the combined chain is flour : sugar : butter = 6 : 10 : 7, so flour to butter is 6:7.",
    hints: ["Rescale one ratio so the shared quantity has the same number in both.", "Then read off the two outer quantities."],
    difficulty: 6,
    topicSlug: "ratios-proportions",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-89",
    question: "Three shelves hold 21 books in total. The first shelf holds 2 more books than the second, and the third holds 4 more than the second. How many books are on the third shelf?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "7", "8", "9", "10"],
    answer: "D",
    solution: "Let the second shelf hold y books. Then the first holds y + 2 and the third holds y + 4, so (y+2) + y + (y+4) = 21, giving 3y = 15 and y = 5. The third shelf holds 5 + 4 = 9 books.",
    hints: ["Express all three shelves in terms of the second one.", "Solve for that shelf first, then answer about the third."],
    difficulty: 6,
    topicSlug: "systems-of-equations",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-90",
    question:
      "A pizza shop offers 5 toppings, and each topping is either included or not (no topping is used twice). How many different pizzas can be made using at least 1 but at most 3 toppings?",
    format: "MULTIPLE_CHOICE",
    choices: ["20", "22", "25", "28", "31"],
    answer: "C",
    solution:
      "The number of pizzas with exactly k toppings is C(5,k). Summing for k = 1, 2, 3: C(5,1) + C(5,2) + C(5,3) = 5 + 10 + 10 = 25.",
    hints: [
      "Break the count into cases based on the exact number of toppings used.",
      "Add the combinations C(5,1), C(5,2), and C(5,3).",
    ],
    difficulty: 6,
    topicSlug: "counting-principles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-91",
    question:
      "In a class of 40 students, 22 take Spanish, 18 take French, and 8 take both languages. How many students take neither language?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "7", "8", "9", "10"],
    answer: "C",
    solution:
      "By inclusion-exclusion, the number taking at least one language is 22 + 18 − 8 = 32. The number taking neither is 40 − 32 = 8.",
    hints: [
      "Use inclusion-exclusion to find how many students take at least one of the two languages.",
      "Subtract that count from the total class size.",
    ],
    difficulty: 6,
    topicSlug: "inclusion-exclusion",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-92",
    question: "A cube-shaped gift box takes exactly 150 square inches of paper to cover all six of its faces with no overlap. What is the volume of the box, in cubic inches?",
    format: "MULTIPLE_CHOICE",
    choices: ["100", "110", "120", "125", "130"],
    answer: "D",
    solution: "With edge s, the surface area is 6s² = 150, so s² = 25 and s = 5. The volume is 5³ = 125 cubic inches.",
    hints: ["Divide the surface area by 6 to get the area of one face.", "The edge is the square root of that; then cube it."],
    difficulty: 6,
    topicSlug: "three-d-geometry",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-93",
    question:
      "Two fair six-sided dice are rolled. What is the probability that the sum of the two numbers rolled is a multiple of 3?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/4", "7/24", "1/3", "3/8", "5/12"],
    answer: "C",
    solution:
      "The possible sums that are multiples of 3 are 3, 6, 9, and 12. Counting ordered pairs: sum 3 has 2 ways, sum 6 has 5 ways, sum 9 has 4 ways, and sum 12 has 1 way, totaling 12 ways out of 36. The probability is 12/36 = 1/3.",
    hints: [
      "List the sums between 2 and 12 that are multiples of 3.",
      "Count the ordered pairs of dice giving each of those sums, then divide by 36.",
    ],
    difficulty: 7,
    topicSlug: "basic-probability",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-94",
    question: "A rectangular tabletop has a perimeter of 18 feet and an area of 20 square feet. What is the difference between the area of a square built on its longer side and the area of a square built on its shorter side, in square feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "7", "9", "11", "13"],
    answer: "C",
    solution: "The sides sum to 9 and multiply to 20, so they are 5 and 4. The squares have areas 25 and 16, differing by 9 square feet.",
    hints: ["Use the perimeter and area to find the two side lengths.", "Then square each side and subtract."],
    difficulty: 7,
    topicSlug: "quadratics",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-95",
    question: "A mason lays 1 brick on the first row. For each later row, the number of bricks laid increases by 2 more than the increase used for the previous row, starting with an increase of 2 bricks from row 1 to row 2. How many bricks are in the 10th row?",
    format: "MULTIPLE_CHOICE",
    choices: ["81", "85", "89", "91", "95"],
    answer: "D",
    solution: "The increases from row to row are 2, 4, 6, ..., 18, which total 2(1+2+···+9) = 2(45) = 90. Starting from 1, row 10 has 1 + 90 = 91 bricks.",
    hints: ["List the nine increases that separate row 1 from row 10.", "Add them to the starting count of 1."],
    difficulty: 7,
    topicSlug: "sequences",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-96",
    question: "A triangular flag has a straight seam joining a point on one edge to a point on another edge, both edges meeting at the flag's top corner. The point on the first edge is 2/3 of the way down from the top corner, and the point on the second edge is 3/4 of the way down. What fraction of the flag's area lies in the small triangle at the top corner?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/3", "5/12", "1/2", "7/12", "2/3"],
    answer: "C",
    solution: "The small triangle shares the top corner's angle with the whole flag, so its area ratio is the product of the two side ratios: (2/3)(3/4) = 1/2.",
    hints: ["The two triangles share an angle at the top corner.", "For a shared angle, the area ratio is the product of the ratios of the two enclosing sides."],
    difficulty: 7,
    topicSlug: "similarity-congruence",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-97",
    question: "A paper drinking cup is shaped like a cone with a depth of 12 centimeters and a circular rim of radius 5 centimeters. What is its volume, in cubic centimeters, expressed in terms of π?",
    format: "MULTIPLE_CHOICE",
    choices: ["60π", "80π", "100π", "120π", "150π"],
    answer: "C",
    solution: "The volume of a cone is (1/3)πr²h = (1/3)π(25)(12) = 100π cubic centimeters.",
    hints: ["Use the cone volume formula, one third of the base area times the height.", "The base area is π times the radius squared."],
    difficulty: 7,
    topicSlug: "area-volume",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-98",
    question: "An account's balance, in dollars, in week n is given by 2n² − 9n − 18, where negative values of n refer to weeks before the account was opened. For how many integer values of n is the balance negative?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "6", "7", "8", "9"],
    answer: "C",
    solution: "Factoring, 2n² − 9n − 18 = (2n + 3)(n − 6), which is negative exactly when −3/2 < n < 6. The integers in that range run from −1 to 5, a total of 7 values.",
    hints: ["Factor the quadratic to locate where it changes sign.", "A product of two factors is negative strictly between its roots."],
    difficulty: 7,
    topicSlug: "quadratics",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-99",
    question: "A school buys T-shirts at $7 each and caps at $4 each, spending exactly $100 and buying at least one of each item. In how many different ways can this be done?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "3", "4", "5", "6"],
    answer: "B",
    solution: "With x shirts and y caps, 7x + 4y = 100. Then 7x must leave the same remainder as 100 upon division by 4, forcing x to be a multiple of 4. The options x = 4, 8, 12 give y = 18, 11, 4, and x = 16 would exceed $100. So there are 3 ways.",
    hints: ["Write the spending equation and use divisibility by 4.", "Only the options keeping the cap count positive are allowed."],
    difficulty: 7,
    topicSlug: "diophantine-equations",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-100",
    question: "A display shows only the final digit of a running total. A culture starts with 1 organism and multiplies sevenfold each hour. What digit does the display show after 2023 hours?",
    format: "MULTIPLE_CHOICE",
    choices: ["0", "1", "3", "7", "9"],
    answer: "C",
    solution: "The final digits of powers of 7 cycle 7, 9, 3, 1 with period 4. Since 2023 leaves remainder 3 upon division by 4, the digit matches that of 7³ = 343, which is 3.",
    hints: ["List the last digits of 7, 7², 7³, 7⁴ and find the repeating cycle.", "Divide 2023 by the cycle length and use the remainder."],
    difficulty: 7,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-101",
    question: "A locker uses a 4-digit code from 1000 to 9999. A code is valid only if all four digits are different and the code is an even number. How many valid codes are there?",
    format: "MULTIPLE_CHOICE",
    choices: ["2240", "2260", "2280", "2296", "2320"],
    answer: "D",
    solution: "Split by the last digit. If it is 0 (1 choice), the leading digit has 9 options and the middle two have 8 and 7, giving 9·8·7 = 504. If it is 2, 4, 6, or 8 (4 choices), the leading digit has 8 options (not 0, not the last digit) and the middle two have 8 and 7, giving 4·8·8·7 = 1792. The total is 504 + 1792 = 2296.",
    hints: ["Handle the case of a final digit 0 separately from the other even final digits.", "A leading digit cannot be 0, which is why the two cases differ."],
    difficulty: 7,
    topicSlug: "casework",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-102",
    question: "A fair six-sided die is rolled repeatedly until a 6 appears. What is the expected number of rolls needed?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "5", "6", "7", "8"],
    answer: "C",
    solution:
      "The number of rolls follows a geometric distribution with success probability p = 1/6. The expected number of trials until the first success is 1/p = 6.",
    hints: [
      "This is a geometric distribution: rolls repeat until the first success.",
      "The expected number of trials for a geometric distribution is 1 divided by the success probability.",
    ],
    difficulty: 7,
    topicSlug: "expected-value",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-103",
    question: "A machine takes a number x and returns x² − 2x. The machine's output is then fed back into the same machine. For how many different starting numbers does the second output equal 0?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "3", "4", "5", "6"],
    answer: "C",
    solution: "The second output is 0 when the first output is a number the machine sends to 0, namely 0 or 2. From x² − 2x = 0 we get x = 0 and x = 2. From x² − 2x = 2 we get x = 1 ± √3. That is 4 starting numbers in all.",
    hints: ["First find every input the machine sends to 0.", "Then find every input the machine sends to each of those values."],
    difficulty: 7,
    topicSlug: "functions",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-104",
    question: "Two lighthouses flash at regular intervals of a whole number of seconds. The two intervals add to 42 seconds, and the lighthouses flash together again after exactly 72 seconds. What is the greatest common divisor of the two intervals?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "3", "4", "6", "9"],
    answer: "D",
    solution: "The intervals sum to 42 with least common multiple 72. Testing pairs, 18 and 24 work: their lcm is 72 and their sum is 42. Their greatest common divisor is 6.",
    hints: ["Flashing together again after 72 seconds means the least common multiple is 72.", "Search pairs summing to 42 whose least common multiple is 72."],
    difficulty: 7,
    topicSlug: "number-theory",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-105",
    question: "A rectangular box has a volume, in cubic units, of x³ − 6x² + 11x − 6, and its three dimensions can be written as x − a, x − b, and x − c for real numbers a, b, and c. What is the value of a + b + c?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "5", "6", "7"],
    answer: "D",
    solution: "Multiplying out (x−a)(x−b)(x−c) gives x³ − (a+b+c)x² + ···, so a + b + c is the negative of the coefficient of x², which is 6.",
    hints: ["Expand the product of the three dimensions and compare coefficients.", "The x² coefficient carries the sum you want."],
    difficulty: 7,
    topicSlug: "polynomials",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-106",
    question: "On a map with coordinates in meters, the edge of a sprinkler's watered region is described by x² + y² − 6x + 4y − 12 = 0. How many meters does the sprinkler reach from its center?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "5", "6", "7"],
    answer: "C",
    solution: "Completing the square: (x² − 6x + 9) + (y² + 4y + 4) = 12 + 9 + 4, so (x − 3)² + (y + 2)² = 25. The radius is √25 = 5 meters.",
    hints: ["Complete the square in x and in y separately.", "Move the constants to the right side; the radius is the square root of what remains."],
    difficulty: 7,
    topicSlug: "circles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-107",
    question:
      "A box contains 3 red balls and 5 blue balls. Two balls are drawn without replacement. Given that the first ball drawn is red, what is the probability that the second ball drawn is also red?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/4", "2/7", "3/8", "1/3", "3/7"],
    answer: "B",
    solution:
      "After removing one red ball, 2 red and 5 blue balls remain, for 7 balls total. The probability the second ball is red is 2/7.",
    hints: [
      "Update the counts of red and total balls after the first (red) ball is removed.",
      "Divide the remaining red count by the remaining total.",
    ],
    difficulty: 7,
    topicSlug: "conditional-probability",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-108",
    question:
      "How many ways can 8 identical candies be distributed among 3 children so that each child receives at least 1 candy?",
    format: "MULTIPLE_CHOICE",
    choices: ["15", "18", "21", "24", "27"],
    answer: "C",
    solution:
      "By stars and bars, first give each child 1 candy, leaving 5 candies to distribute freely among 3 children: this is C(5+3−1, 3−1) = C(7,2) = 21.",
    hints: [
      "Give each child one candy first to satisfy the 'at least 1' condition.",
      "Distribute the remaining candies freely using stars and bars: C(n+k−1, k−1).",
    ],
    difficulty: 7,
    topicSlug: "combinatorics",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-109",
    question:
      "What is the minimum number of people needed in a room to guarantee that at least 4 people share the same birth month?",
    format: "MULTIPLE_CHOICE",
    choices: ["25", "30", "33", "36", "37"],
    answer: "E",
    solution:
      "In the worst case, each of the 12 months could have exactly 3 people without any month reaching 4, using 12 × 3 = 36 people. One more person, 37 total, forces some month to have at least 4 people.",
    hints: [
      "Consider the worst case where every month has as many people as possible without reaching 4.",
      "Add one more person to that worst-case total to force the fourth match.",
    ],
    difficulty: 7,
    topicSlug: "pigeonhole",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-110",
    question:
      "Of five friends A, B, C, D, and E, exactly one always tells the truth and the other four always lie. A says, 'B is the truth-teller.' B says, 'C is the truth-teller.' C says, 'D is the truth-teller.' D says, 'I am the truth-teller.' E says nothing. Who is the truth-teller?",
    format: "MULTIPLE_CHOICE",
    choices: ["A", "B", "C", "D", "E"],
    answer: "E",
    solution:
      "If A were the truth-teller, A's true statement would make B the truth-teller too — a contradiction, since only one person is truthful. So A lies, meaning B is not the truth-teller (since A's false statement claims B is). Since B is a liar, B's statement 'C is the truth-teller' is false, so C is not the truth-teller. Since C is a liar, C's statement 'D is the truth-teller' is false, so D is not the truth-teller — which is consistent with D's own statement being a lie. With A, B, C, and D all ruled out as liars, E must be the truth-teller.",
    hints: [
      "Test each person as the truth-teller and look for a contradiction in the chain of statements.",
      "Once A, B, C, and D are all shown to be liars, the truth-teller must be E by elimination.",
    ],
    difficulty: 7,
    topicSlug: "deduction",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-111",
    question:
      "A standard 52-card deck is shuffled, and 2 cards are drawn without replacement. What is the probability that both cards are aces?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/221", "1/169", "4/221", "1/52", "1/13"],
    answer: "A",
    solution:
      "The probability the first card is an ace is 4/52, and given that, the probability the second is also an ace is 3/51. Multiplying, (4/52)(3/51) = 12/2652 = 1/221.",
    hints: [
      "Multiply the probability the first card is an ace by the (conditional) probability the second card is also an ace.",
      "Simplify the resulting fraction fully.",
    ],
    difficulty: 7,
    topicSlug: "basic-probability",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-112",
    question: "A triangular park has corners at A(0,0), B(6,0), and C(6,8), with coordinates measured in meters. A path runs from corner A straight to the midpoint of the side joining B and C. How long is the path, in meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["2√10", "2√11", "2√12", "2√13", "2√14"],
    answer: "D",
    solution: "The midpoint of B and C is (6, 4). The distance from (0,0) is √(6² + 4²) = √52 = 2√13 meters.",
    hints: ["Average the coordinates of B and C to locate the midpoint.", "Then apply the distance formula from the origin."],
    difficulty: 7,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-113",
    question:
      "Three fair six-sided dice are rolled. What is the probability that at least one pair among the three dice shows values that differ by exactly 1?",
    format: "MULTIPLE_CHOICE",
    choices: ["5/12", "7/12", "1/2", "2/3", "11/18"],
    answer: "B",
    solution:
      "Complementary counting is cleaner: count the ordered triples in which no two of the three values differ by exactly 1. Work with the underlying multiset of values first. If all three values are equal (6 multisets), no two differ by 1, giving 6 ordered triples. If exactly two are equal, say value a twice and b once with b ≠ a, we need |a − b| ≠ 1; for each a there are 6 − 1 (itself) − (number of neighbors of a) choices of b, which is 4 when a ∈ {1,6} and 3 otherwise, for 2(4) + 4(3) = 20 multisets, each giving 3 ordered triples, so 60. If all three are distinct, we need a 3-element subset of {1,…,6} with no two elements consecutive; the standard gap count gives C(6 − 3 + 1, 3) = C(4,3) = 4 such subsets, each giving 3! = 6 ordered triples, so 24. The total with no pair differing by 1 is 6 + 60 + 24 = 90, so the count with at least one such pair is 216 − 90 = 126, and the probability is 126/216 = 7/12.",
    hints: [
      "Counting the arrangements that avoid the condition entirely is far easier than counting the ones that satisfy it.",
      "Split the 'no two differ by 1' count by how many of the three dice are equal: all three equal, exactly two equal, or all distinct.",
      "For the all-distinct case you are choosing a 3-element subset of {1,…,6} containing no two consecutive integers — there are C(4,3) = 4 of them.",
    ],
    difficulty: 8,
    topicSlug: "counting-probability",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-114",
    question: "Two cylindrical pipes of radii 1 and 4 rest on a flat floor, touching each other and each touching the floor along a line. A third, smaller cylindrical pipe is wedged into the gap between them, resting on the floor and touching both larger pipes. What is the radius of the smallest pipe?",
    format: "MULTIPLE_CHOICE",
    choices: ["2/3", "4/9", "1/2", "4/5", "2/5"],
    answer: "B",
    solution: "For circles tangent to a common line and to one another, the radii satisfy 1/√r = 1/√r₁ + 1/√r₂. Here 1/√r = 1/√1 + 1/√4 = 1 + 1/2 = 3/2, so √r = 2/3 and r = 4/9.",
    hints: ["Place the centers above the floor at heights equal to their radii and use horizontal distances.", "The reciprocals of the square roots of the radii add."],
    difficulty: 8,
    topicSlug: "circles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-115",
    question: "A machine replaces any number x with x² − 4x + 1. For certain starting numbers, running the machine twice returns the original number even though running it once does not. What is the sum of all such starting numbers?",
    format: "MULTIPLE_CHOICE",
    choices: ["8", "5", "3", "−2", "2"],
    answer: "C",
    solution: "A single run fixes x when x² − 4x + 1 = x, that is x² − 5x + 1 = 0. Two runs give the quartic x⁴ − 8x³ + 14x² + 7x − 2 = 0, which factors as (x² − 5x + 1)(x² − 3x − 2) = 0. The numbers wanted are the roots of x² − 3x − 2 = 0, whose sum is 3.",
    hints: ["The starting numbers unchanged by one run satisfy a quadratic; divide it out.", "The remaining quadratic factor holds exactly the numbers you want."],
    difficulty: 8,
    topicSlug: "functions",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-116",
    question: "A game awards a score equal to the product of all the whole numbers from 1 up to n. What is the smallest n whose score is divisible by 2025⁵?",
    format: "MULTIPLE_CHOICE",
    choices: ["40", "45", "30", "50", "25"],
    answer: "B",
    solution: "Since 2025 = 3⁴ · 5², we need 3²⁰ · 5¹⁰ to divide n!. The factors of 5 are scarcer: n = 45 gives ⌊45/5⌋ + ⌊45/25⌋ = 9 + 1 = 10, while n = 44 gives only 9. At n = 45 the factors of 3 number ⌊45/3⌋ + ⌊45/9⌋ + ⌊45/27⌋ = 15 + 5 + 1 = 21, which is enough. So n = 45.",
    hints: ["Factor 2025 into primes and raise it to the fifth power.", "Count the factors of 5 and of 3 in n! and find which prime runs out last."],
    difficulty: 8,
    topicSlug: "divisibility",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-117",
    question: "A courier starts at the point P = (4, 1), walks to some point A on a straight river running along the x-axis, then to some point B on a straight fence running along the line y = x, and finally back to P. What is the shortest possible total distance walked?",
    format: "MULTIPLE_CHOICE",
    choices: ["√17", "√34", "2√17", "√29", "6"],
    answer: "B",
    solution: "Reflect P across the river to get (4, −1) and across the fence to get (1, 4). The shortest closed route has length equal to the straight distance between the two reflections: √((4−1)² + (−1−4)²) = √(9 + 25) = √34.",
    hints: ["Reflect the starting point across each of the two lines it must touch.", "The shortest path equals the straight-line distance between the two reflected points."],
    difficulty: 8,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-118",
    question:
      "A frog starts at 0 on the number line. Each second it jumps forward 1 unit or forward 2 units, each with probability 1/2, independently of all previous jumps. What is the probability that the frog ever lands exactly on 10?",
    format: "MULTIPLE_CHOICE",
    choices: ["2/3", "341/512", "683/1024", "1023/1024", "341/1024"],
    answer: "C",
    solution:
      "Let pₙ be the probability the frog ever lands on n. The frog reaches n only by arriving from n − 1 (then jumping 1) or from n − 2 (then jumping 2), and these two events are disjoint given where the last jump started, so pₙ = (1/2)pₙ₋₁ + (1/2)pₙ₋₂ with p₀ = 1 and p₁ = 1/2. The characteristic equation 2x² − x − 1 = 0 factors as (2x + 1)(x − 1) = 0, with roots 1 and −1/2, so pₙ = A + B(−1/2)ⁿ. From p₀ = 1 and p₁ = 1/2 we get A + B = 1 and A − B/2 = 1/2, so A = 2/3 and B = 1/3, giving pₙ = 2/3 + (1/3)(−1/2)ⁿ. Then p₁₀ = 2/3 + (1/3)(1/1024) = (2048 + 1)/3072 = 2049/3072 = 683/1024. (Choice A is the limiting value as n → ∞, and 341/512 is p₉.)",
    hints: [
      "Condition on the frog's last jump before it would reach 10 — there are only two ways to arrive at any given point.",
      "This gives a two-term recurrence pₙ = (1/2)pₙ₋₁ + (1/2)pₙ₋₂ with p₀ = 1 and p₁ = 1/2.",
      "Solve the recurrence in closed form: the characteristic roots are 1 and −1/2, so pₙ = 2/3 + (1/3)(−1/2)ⁿ.",
    ],
    difficulty: 8,
    topicSlug: "probability",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-119",
    question: "A club records how many new members join each month. Starting from the third month, the number joining equals the sum of the two previous months' numbers, and every month's number is a positive whole number. In the seventh month, 200 new members joined. How many different values are possible for the number who joined in the first month?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "5", "6", "2"],
    answer: "B",
    solution: "Writing everything in terms of the first two months gives a₇ = 5a₁ + 8a₂ = 200. So 5a₁ = 200 − 8a₂, which forces a₂ to be a multiple of 5. With both counts positive, a₂ = 5, 10, 15, 20 give a₁ = 32, 24, 16, 8, so there are 4 possible values.",
    hints: ["Express the seventh month's count in terms of the first two months.", "Divisibility forces the second month to be a multiple of 5, and both counts must stay positive."],
    difficulty: 7,
    topicSlug: "sequences",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-120",
    question: "A triangular plot has sides AB = 10, BC = 12, and CA = 14 meters. From corner A, one straight line splits the corner angle into two equal parts and meets side BC at D, while a second line drops perpendicular to BC and meets it at E. How many meters apart are D and E?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "3", "5", "7/2", "4"],
    answer: "B",
    solution: "The angle-splitting line divides BC in the ratio AB : AC = 10 : 14 = 5 : 7, so BD = 12(5/12) = 5. For the perpendicular, BE = (AB² + BC² − CA²)/(2·BC) = (100 + 144 − 196)/24 = 48/24 = 2. Thus DE = 5 − 2 = 3 meters.",
    hints: ["An angle-splitting line cuts the opposite side in the ratio of the two adjacent sides.", "Locate the foot of the perpendicular using the Pythagorean theorem on the two right triangles."],
    difficulty: 7,
    topicSlug: "triangles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-121",
    question: "Six guests numbered 1 through 6 are seated in six chairs numbered 1 through 6, one guest per chair. No guest may sit in the chair matching their own number, and for each i from 1 to 5, guest i may not sit in chair i + 1 either. In how many ways can the guests be seated?",
    format: "MULTIPLE_CHOICE",
    choices: ["265", "96", "144", "120", "84"],
    answer: "B",
    solution: "This counts permutations avoiding both a_i = i and a_i = i + 1, a total of 11 forbidden positions. Inclusion-exclusion over these forbidden placements, which form two disjoint diagonals, yields 96 valid seatings.",
    hints: ["Model the forbidden placements as marked squares on a 6 by 6 board.", "Use inclusion-exclusion, counting ways to place k non-attacking markers on the forbidden squares."],
    difficulty: 8,
    topicSlug: "inclusion-exclusion",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-122",
    question: "A counter displays only the last two digits of a number. A culture starts with one organism and multiplies sevenfold each hour, running for 7⁷ hours. What two-digit value does the counter display?",
    format: "MULTIPLE_CHOICE",
    choices: ["7", "49", "43", "1", "93"],
    answer: "C",
    solution: "We want 7^(7⁷) modulo 100. The powers of 7 repeat modulo 100 with period 4, since 7⁴ = 2401 leaves remainder 1. Now 7⁷ leaves remainder 3 upon division by 4, so the answer matches 7³ = 343, which leaves 43.",
    hints: ["Find how often the last two digits of powers of 7 repeat.", "Reduce the giant exponent 7⁷ using that period."],
    difficulty: 8,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-123",
    question:
      "A three-digit positive integer is chosen at random, with all 900 of them equally likely. What is the probability that its digits, read from left to right, are either strictly increasing or strictly decreasing?",
    format: "MULTIPLE_CHOICE",
    choices: ["7/75", "17/75", "2/15", "17/150", "4/25"],
    answer: "B",
    solution:
      "Count the two kinds separately. If the digits strictly increase, none of them can be 0 (a 0 could only come first, and the leading digit is nonzero anyway, so 0 cannot appear at all), and any three distinct digits from 1 through 9 can be written in increasing order in exactly one way. That gives C(9, 3) = 84 numbers. If the digits strictly decrease, 0 is allowed — it can only land in the units place, and the leading digit is then automatically nonzero — so any three distinct digits from 0 through 9 arrange in decreasing order in exactly one way, giving C(10, 3) = 120 numbers. The two cases cannot overlap, since a strictly increasing triple of digits is never strictly decreasing. So 84 + 120 = 204 of the 900 three-digit numbers qualify, and the probability is 204/900 = 17/75.",
    hints: [
      "For each kind of number, notice that a set of three distinct digits determines the number completely — the order is forced.",
      "Decide separately whether the digit 0 is available in each case, thinking about where a 0 could possibly sit.",
      "Add the two counts (they cannot overlap) and divide by 900, then reduce the fraction.",
    ],
    difficulty: 7,
    topicSlug: "counting-principles",
    competitionSlug: "amc10",
  },
  {
    slug: "amc10-124",
    question:
      "Each of the nine unit squares of a 3×3 grid is colored red or blue. How many of the 512 colorings contain no 2×2 block of four squares that are all the same color?",
    format: "MULTIPLE_CHOICE",
    choices: ["417", "336", "322", "320", "256"],
    answer: "C",
    solution:
      "There are four 2×2 blocks (upper-left, upper-right, lower-left, lower-right). For each block B, let A_B be the set of colorings in which B is monochromatic; |A_B| = 2 (the block's color) × 2⁵ (the other five cells) = 64. Use inclusion–exclusion. Singles: 4 · 64 = 256. Pairs: two blocks overlap either in two cells (horizontally or vertically adjacent blocks, 4 such pairs) or in one cell (the two diagonal pairs, 2 such pairs). If both blocks are monochromatic and they share at least one cell, they must share the same color, so their union of 6 cells (adjacent pair) or 7 cells (diagonal pair) is one color: adjacent pairs give 2 · 2³ = 16 each, diagonal pairs give 2 · 2² = 8 each. Pair total: 4 · 16 + 2 · 8 = 80. Triples: any three of the four blocks overlap pairwise in a connected way, so all are forced to the same color, and their union always covers 8 of the 9 cells (it misses exactly the corner of the one omitted block). That leaves 2 · 2¹ = 4 colorings each, and there are 4 triples: 16. Quadruple: all nine cells one color, 2 colorings. Inclusion–exclusion gives |A₁ ∪ … ∪ A₄| = 256 − 80 + 16 − 2 = 190, so the answer is 512 − 190 = 322. An exhaustive check of all 512 colorings confirms 322.",
    hints: [
      "Count the colorings that DO contain a monochromatic 2×2 block and subtract from 512.",
      "There are four 2×2 blocks; overlapping blocks that are both monochromatic are forced to share the same color, which collapses many cells at once.",
      "Apply inclusion–exclusion, treating the horizontally/vertically adjacent block pairs (sharing two cells) separately from the diagonal pairs (sharing one cell).",
    ],
    difficulty: 8,
    topicSlug: "casework",
    competitionSlug: "amc10",
  },
];
