import type { ProblemSeed } from "./problems";

/**
 * Hand-written problems styled after the AMC 8 (American Mathematics
 * Competition 8, for students in grades 8 and below).
 *
 * AMC 8 problems are 5-choice multiple choice, phrased as accessible but
 * cleverly-constructed word problems drawn from arithmetic, basic algebra,
 * geometry, number theory, combinatorics, and logic. Every problem below
 * is an original NumberSmith problem, written to match that phrasing,
 * tone, and increasing difficulty ramp; none are transcribed, closely
 * paraphrased, or numerically reskinned from any real AMC 8 contest.
 * Difficulty rises roughly from 2 (problem 1) to 7 (problem 30), mirroring
 * how the real 25-question, 40-minute contest escalates from one-step
 * arithmetic to problems that combine two or three ideas.
 *
 * Seeded as practice (isPlacement: false), same as the other
 * competition-tagged problem sets.
 */
export const AMC8_PROBLEMS: ProblemSeed[] = [
  {
    slug: "amc8-01",
    question:
      "A pizza is cut into 8 equal slices. Sam eats 3 slices and Mia eats 2 slices. What fraction of the pizza is left?",
    format: "MULTIPLE_CHOICE",
    choices: ["3/8", "5/8", "1/2", "2/8", "3/5"],
    answer: "A",
    solution:
      "Together Sam and Mia eat 3 + 2 = 5 slices out of 8, leaving 8 - 5 = 3 slices. That is 3/8 of the pizza.",
    hints: [
      "Find the total number of slices eaten first.",
      "Subtract the eaten slices from 8, then write the result as a fraction of 8.",
    ],
    difficulty: 2,
    topicSlug: "fractions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-02",
    question: "A shirt originally costs $40. It is on sale for 25% off. What is the sale price?",
    format: "MULTIPLE_CHOICE",
    choices: ["$30", "$25", "$35", "$10", "$32"],
    answer: "A",
    solution: "25% of $40 is $10, so the sale price is $40 - $10 = $30.",
    hints: [
      "First find 25% of the original price.",
      "Subtract that discount amount from $40.",
    ],
    difficulty: 2,
    topicSlug: "percentages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-03",
    question:
      "In a fruit basket, the ratio of apples to oranges is 4:3. If there are 12 apples, how many oranges are there?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "8", "16", "12", "7"],
    answer: "A",
    solution: "Since 12 apples correspond to 4 parts, each part is 12/4 = 3. Oranges are 3 parts, so 3 × 3 = 9.",
    hints: [
      "Figure out how many fruits one \"part\" of the ratio represents.",
      "Multiply that part size by the number of parts for oranges.",
    ],
    difficulty: 2,
    topicSlug: "ratios-proportions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-04",
    question:
      "Maria scored 82, 88, and 90 on three tests. What score must she earn on a fourth test so that her average over all four tests is exactly 88?",
    format: "MULTIPLE_CHOICE",
    choices: ["92", "90", "88", "94", "96"],
    answer: "A",
    solution: "Four tests averaging 88 requires a total of 88 × 4 = 352. Her first three tests total 82 + 88 + 90 = 260, so she needs 352 - 260 = 92.",
    hints: [
      "Multiply the target average by 4 to get the required total of all four scores.",
      "Subtract her current total from that required total.",
    ],
    difficulty: 2,
    topicSlug: "averages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-05",
    question: "The front row of a small theater has 2 seats, and each row behind it has 2 more seats than the row just in front of it. The theater has 10 rows. How many seats does it have in all?",
    format: "MULTIPLE_CHOICE",
    choices: ["110", "100", "90", "120", "55"],
    answer: "A",
    solution: "The rows hold 2, 4, 6, ..., 20 seats. Pairing the first row with the last, the second with the second-to-last, and so on gives 5 pairs that each total 22, so the theater has 5 × 22 = 110 seats.",
    hints: ["Write out how many seats each of the 10 rows holds.", "Pair the smallest row with the largest, the next smallest with the next largest, and notice every pair has the same total."],
    difficulty: 2,
    topicSlug: "number-properties",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-06",
    question:
      "A train travels 180 miles in 3 hours at a constant speed. At this same speed, how many miles does it travel in 5 hours?",
    format: "MULTIPLE_CHOICE",
    choices: ["300", "280", "240", "360", "250"],
    answer: "A",
    solution: "The speed is 180 / 3 = 60 miles per hour. In 5 hours it travels 60 × 5 = 300 miles.",
    hints: [
      "Find the train's speed in miles per hour first.",
      "Multiply that speed by the new number of hours.",
    ],
    difficulty: 3,
    topicSlug: "rates",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-07",
    question: "Devon triples the number of trading cards in his binder, then gives 7 of them to a friend. He is left with 20 cards. How many cards were in the binder to begin with?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "9", "13", "4", "11"],
    answer: "B",
    solution: "If he started with n cards, then 3n − 7 = 20, so 3n = 27 and n = 9.",
    hints: ["Let n be the starting number of cards and write an equation for what happens to it.", "Undo the steps in reverse: add back the 7 he gave away, then divide by 3."],
    difficulty: 3,
    topicSlug: "linear-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-08",
    question: "A straight fence rail is hinged at a post so that it bends into two angles that together make up the straight rail. The larger angle measures 30 degrees more than twice the smaller angle. What is the measure, in degrees, of the smaller angle?",
    format: "MULTIPLE_CHOICE",
    choices: ["50", "40", "60", "70", "45"],
    answer: "A",
    solution: "The two angles add to 180 degrees. If the smaller is x, the larger is 2x + 30, so x + (2x + 30) = 180. Then 3x = 150 and x = 50.",
    hints: ["Two angles that make up a straight line add to 180 degrees.", "Call the smaller angle x, write the larger one in terms of x, and set the sum equal to 180."],
    difficulty: 3,
    topicSlug: "angles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-09",
    question:
      "A sandwich shop offers 3 types of bread, 4 types of filling, and 2 types of cheese. How many different sandwiches can be made using exactly one bread, one filling, and one cheese?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "9", "20", "12", "30"],
    answer: "A",
    solution: "By the multiplication principle, the number of sandwiches is 3 × 4 × 2 = 24.",
    hints: [
      "Each choice (bread, filling, cheese) is made independently.",
      "Multiply the number of options for each category together.",
    ],
    difficulty: 3,
    topicSlug: "counting-principles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-10",
    question: "A florist wants to set out 36 identical tulips in a rectangular array with the same number of tulips in every row. How many different arrays are possible? (An array with 4 rows of 9 and one with 9 rows of 4 count as different.)",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "6", "8", "12", "10"],
    answer: "A",
    solution: "Each array corresponds to a way of writing 36 as (rows) × (columns), so the count is the number of positive divisors of 36. Since 36 = 2² · 3², it has (2+1)(2+1) = 9 divisors, giving 9 arrays.",
    hints: ["Each arrangement matches a divisor of 36 used as the number of rows.", "Factor 36 into primes and use the exponents to count its divisors."],
    difficulty: 3,
    topicSlug: "divisibility",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-11",
    question:
      "A rectangular garden measures 12 feet by 8 feet. A path of uniform width 2 feet surrounds the garden on the outside. What is the area of the path, in square feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["96", "88", "80", "100", "112"],
    answer: "A",
    solution:
      "Including the path, the outer rectangle measures (12+4) by (8+4), i.e. 16 by 12, for an area of 192. The garden itself has area 12 × 8 = 96. The path's area is 192 - 96 = 96.",
    hints: [
      "The path adds 2 feet to every side, so it adds 4 feet total to each dimension.",
      "Find the area of the larger outer rectangle and subtract the garden's area.",
    ],
    difficulty: 4,
    topicSlug: "area-volume",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-12",
    question: "On the first day of her reading challenge Nadia reads 5 pages, and on each day after that she reads 4 more pages than she read the day before. How many pages does she read on the 15th day?",
    format: "MULTIPLE_CHOICE",
    choices: ["61", "65", "56", "60", "64"],
    answer: "A",
    solution: "Day 15 is 14 days after day 1, so she reads 5 + 14 × 4 = 5 + 56 = 61 pages.",
    hints: ["Count how many times the daily increase of 4 has been applied by the 15th day.", "It is 14 increases, not 15 — the first day has had none yet."],
    difficulty: 4,
    topicSlug: "sequences",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-13",
    question: "Three straight sticks are joined end to end to make a triangular frame. Two of the sticks are 7 inches and 15 inches long. Which of the following cannot be the length, in inches, of the third stick?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "14", "20", "22", "16"],
    answer: "D",
    solution: "The third side must be longer than 15 − 7 = 8 and shorter than 15 + 7 = 22. A stick of length 22 would lie flat along the other two rather than close a triangle, so 22 is impossible.",
    hints: ["Any side of a triangle must be shorter than the sum of the other two.", "Find the range of allowed lengths, then check which choice falls outside it."],
    difficulty: 4,
    topicSlug: "triangles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-14",
    question: "The lockers along one school hallway are numbered 11 through 29. A custodian repaints every locker whose number is prime. What is the sum of the numbers on the lockers she repaints?",
    format: "MULTIPLE_CHOICE",
    choices: ["112", "100", "120", "108", "116"],
    answer: "A",
    solution: "The primes from 11 to 29 are 11, 13, 17, 19, 23, and 29. Their sum is 11 + 13 + 17 + 19 + 23 + 29 = 112.",
    hints: ["List the numbers from 11 to 29 and cross out the ones with a factor other than 1 and themselves.", "Check each remaining number against 2, 3, and 5 before adding."],
    difficulty: 4,
    topicSlug: "primes",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-15",
    question: "A committee of 3 people is to be chosen from a group of 8 people. How many different committees are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["56", "24", "336", "48", "64"],
    answer: "A",
    solution: "Since order does not matter, the number of committees is C(8,3) = (8×7×6)/(3×2×1) = 56.",
    hints: [
      "Since the committee is unordered, this is a combination, not a permutation.",
      "Compute C(8,3) using the combination formula.",
    ],
    difficulty: 4,
    topicSlug: "combinations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-16",
    question: "A rectangular vegetable garden is enclosed by 46 feet of fencing, and the garden is 5 feet longer than it is wide. What is the area of the garden, in square feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["126", "130", "120", "132", "117"],
    answer: "A",
    solution: "If the width is w, the length is w + 5 and the perimeter is 2w + 2(w + 5) = 46, so 4w = 36 and w = 9. The length is 14, and the area is 9 × 14 = 126 square feet.",
    hints: ["Write the length in terms of the width, then use the perimeter formula.", "Once you know both dimensions, multiply them."],
    difficulty: 5,
    topicSlug: "quadrilaterals",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-17",
    question: "A machine starts with 1 token and doubles its supply every hour. After 20 hours the tokens are packed into bags of 7, filling as many full bags as possible. How many tokens are left over?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "1", "2", "6", "3"],
    answer: "A",
    solution: "After 20 hours there are 2²⁰ tokens. Remainders of powers of 2 when divided by 7 cycle 2, 4, 1, 2, 4, 1, ... with period 3. Since 20 leaves remainder 2 when divided by 3, 2²⁰ leaves the same remainder as 2², which is 4.",
    hints: ["Doubling 20 times from 1 token gives 2²⁰ tokens.", "Compute the remainders of 2, 4, 8, 16, ... upon division by 7 and look for a repeating cycle."],
    difficulty: 5,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-18",
    question: "A circular fountain has a rim that is 18π feet long. What is the area of the fountain, in square feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["81π", "90π", "162π", "36π", "324π"],
    answer: "A",
    solution: "The rim is the circumference, so 2πr = 18π and r = 9. The area is πr² = 81π square feet.",
    hints: ["Use the circumference to find the radius first.", "Then substitute that radius into the area formula."],
    difficulty: 5,
    topicSlug: "circles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-19",
    question:
      "A bag contains 4 red marbles, 5 blue marbles, and 3 green marbles. One marble is drawn at random. What is the probability that it is not blue?",
    format: "MULTIPLE_CHOICE",
    choices: ["7/12", "5/12", "1/3", "3/4", "2/3"],
    answer: "A",
    solution: "There are 12 marbles total, of which 12 - 5 = 7 are not blue. The probability is 7/12.",
    hints: [
      "Find the total number of marbles and the number that are not blue.",
      "Write the probability as (not blue) / (total).",
    ],
    difficulty: 5,
    topicSlug: "basic-probability",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-20",
    question:
      "Alice, Ben, and Cara each play a different sport: soccer, tennis, or swimming. Alice does not play soccer. Ben does not play tennis or swimming. Cara does not play swimming. What sport does Alice play?",
    format: "MULTIPLE_CHOICE",
    choices: ["Swimming", "Soccer", "Tennis", "Cannot be determined", "Soccer and tennis"],
    answer: "A",
    solution:
      "Since Ben plays neither tennis nor swimming, Ben must play soccer. Since Alice does not play soccer and Cara does not play swimming, Cara must play tennis, leaving swimming for Alice.",
    hints: [
      "Start with the person who has the most restrictions — figure out Ben's sport first.",
      "Once Ben's sport is fixed, use Cara's restriction to place the remaining two sports.",
    ],
    difficulty: 5,
    topicSlug: "logical-puzzles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-21",
    question: "A sheet of paper starts as 1 layer. Each time Priya folds it a certain way, the number of layers triples. After x + 2 folds the sheet has 81 layers. What is the value of x?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "4", "3", "6", "1"],
    answer: "A",
    solution: "After x + 2 folds there are 3^(x+2) layers, so 3^(x+2) = 81 = 3⁴. Matching exponents gives x + 2 = 4, so x = 2.",
    hints: ["Write 81 as a power of 3.", "When two powers of 3 are equal, their exponents are equal."],
    difficulty: 5,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-22",
    question: "Two friends have 34 marbles between them, and one of them has 8 more marbles than the other. What is the product of the two numbers of marbles?",
    format: "MULTIPLE_CHOICE",
    choices: ["273", "264", "280", "252", "289"],
    answer: "A",
    solution: "If the counts are a and b with a + b = 34 and a − b = 8, then adding gives 2a = 42 and a = 21, so b = 13. The product is 21 × 13 = 273.",
    hints: ["Add the two equations to eliminate one of the unknowns.", "Once you know both counts, multiply them."],
    difficulty: 6,
    topicSlug: "systems-of-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-23",
    question: "Two triangular sails have exactly the same shape, with the bottom edge of the small sail corresponding to the bottom edge of the large one. The small sail's bottom edge is 6 feet long and the large sail's is 9 feet. The small sail has an area of 24 square feet. What is the area of the large sail, in square feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["54", "36", "48", "60", "45"],
    answer: "A",
    solution: "The sails are similar with ratio 9/6 = 3/2, so their areas are in the ratio (3/2)² = 9/4. The large sail has area 24 × 9/4 = 54 square feet.",
    hints: ["Find the ratio of corresponding edges first.", "Areas of similar figures scale by the square of that ratio."],
    difficulty: 6,
    topicSlug: "similarity-congruence",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-24",
    question:
      "What is the minimum number of people needed in a room to guarantee that at least 3 of them were born in the same month?",
    format: "MULTIPLE_CHOICE",
    choices: ["25", "24", "13", "36", "26"],
    answer: "A",
    solution:
      "By the pigeonhole principle, with 12 months, 2 × 12 = 24 people could have at most 2 per month with none tripled up. One more person, 25 total, forces some month to have 3.",
    hints: [
      "Think about the worst case: how many people can you place with at most 2 per month?",
      "Add one more person to that worst-case total to force a third match.",
    ],
    difficulty: 6,
    topicSlug: "pigeonhole",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-25",
    question: "A hiker's elevation is measured in meters above a trail marker, and she climbs at a steady rate. Two hours into the hike she is at 3 meters, and six hours in she is at 11 meters. What was her elevation, in meters, at the moment she started?",
    format: "MULTIPLE_CHOICE",
    choices: ["-1", "1", "-2", "0", "2"],
    answer: "A",
    solution: "Her rate is (11 − 3)/(6 − 2) = 2 meters per hour. Working back from 3 meters at hour 2 gives 3 − 2 × 2 = −1 meters at hour 0.",
    hints: ["Find how many meters she gains per hour.", "Step backwards from the 2-hour reading to the starting time."],
    difficulty: 6,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-26",
    question: "A stair-climbing robot climbs 2 steps on its first trip and 5 steps on its second trip. On every trip after that, it climbs as many steps as its two previous trips combined. How many steps does it climb on its seventh trip?",
    format: "MULTIPLE_CHOICE",
    choices: ["50", "49", "45", "55", "48"],
    answer: "A",
    solution: "The trips are 2, 5, then 2 + 5 = 7, 5 + 7 = 12, 7 + 12 = 19, 12 + 19 = 31, and 19 + 31 = 50. The seventh trip is 50 steps.",
    hints: ["Write out the trips one at a time rather than looking for a formula.", "Each new entry is the sum of the two before it."],
    difficulty: 6,
    topicSlug: "recursion-in-counting",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-27",
    question:
      "In a class of 30 students, 18 take Spanish, 15 take French, and 8 take both languages. How many students take neither language?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "7", "8", "10", "3"],
    answer: "A",
    solution:
      "By inclusion-exclusion, the number taking at least one language is 18 + 15 - 8 = 25. The number taking neither is 30 - 25 = 5.",
    hints: [
      "Use inclusion-exclusion to find how many students take at least one of the two languages.",
      "Subtract that count from the total class size.",
    ],
    difficulty: 6,
    topicSlug: "inclusion-exclusion",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-28",
    question: "A rectangular pen is built with 18 meters of fencing, and both its length and width are whole numbers of meters. What is the largest possible area of the pen, in square meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["20", "18", "14", "8", "16"],
    answer: "A",
    solution: "The length and width add to 9. The whole-number pairs are 1×8, 2×7, 3×6, and 4×5, with areas 8, 14, 18, and 20. The largest area is 20 square meters.",
    hints: ["The perimeter tells you the sum of the length and the width.", "List every whole-number pair with that sum and compare their products."],
    difficulty: 7,
    topicSlug: "quadratics",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-29",
    question: "Adult tickets to a school play cost $4 and child tickets cost $3. A family spends exactly $60 and buys at least one ticket of each kind. In how many different ways could they have done this?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "5", "3", "6", "15"],
    answer: "A",
    solution: "If they buy x adult and y child tickets, 4x + 3y = 60. Since 60 and 4x are multiples of 3 only when x is, x must be a multiple of 3: x = 3, 6, 9, 12 give y = 16, 12, 8, 4. That is 4 ways.",
    hints: ["Write an equation for the total cost and look for positive whole-number solutions.", "Notice that one of the two counts is forced to be a multiple of 3."],
    difficulty: 7,
    topicSlug: "diophantine-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-30",
    question:
      "Two players, Alex and Blake, take turns removing 1, 2, or 3 stones from a pile of 17 stones, with Alex moving first. The player who removes the last stone wins. If both players play optimally, who wins, and how many stones does the winner remove on their very first move?",
    format: "MULTIPLE_CHOICE",
    choices: [
      "Alex, by removing 1 stone",
      "Alex, by removing 3 stones",
      "Blake, by removing 2 stones",
      "Alex, by removing 2 stones",
      "Blake, no matter what Alex does",
    ],
    answer: "A",
    solution:
      "Since each move removes 1 to 3 stones, a pile size that is a multiple of 4 is always a losing position for the player about to move, because whatever they remove (1, 2, or 3), the opponent can restore the pile to the next lower multiple of 4. Since 17 is 1 more than the multiple of 4 equal to 16, Alex should remove 1 stone, leaving 16 for Blake — a losing position. Alex wins by removing 1 stone first.",
    hints: [
      "Think about which pile sizes are 'safe' to hand to your opponent — sizes where any move they make can be countered back to another safe size.",
      "Multiples of 4 are losing positions for the player about to move, since 1, 2, or 3 removed can always be answered to return to the next lower multiple of 4.",
    ],
    difficulty: 7,
    topicSlug: "games-and-strategies",
    competitionSlug: "amc8",
  },

{
    slug: "amc8-31",
    question:
      "A baker makes 150 cookies and packs them into boxes of 8 cookies each, filling as many full boxes as possible. How many cookies are left over?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "4", "8", "2", "0"],
    answer: "A",
    solution:
      "150 ÷ 8 = 18 remainder 6, since 8 × 18 = 144 and 150 − 144 = 6.",
    hints: [
      "Find the largest multiple of 8 that is at most 150.",
      "Subtract that multiple from 150.",
    ],
    difficulty: 2,
    topicSlug: "arithmetic",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-32",
    question: "A pitcher is 2/3 full of lemonade. Miguel pours in enough lemonade to add another 1/6 of the pitcher's capacity. What fraction of the pitcher is full now?",
    format: "MULTIPLE_CHOICE",
    choices: ["5/9", "1", "5/6", "1/2", "3/9"],
    answer: "C",
    solution: "Rewrite 2/3 as 4/6. Then 4/6 + 1/6 = 5/6 of the pitcher is full.",
    hints: ["Rewrite both fractions with the same denominator.", "Sixths work, since 3 divides 6."],
    difficulty: 2,
    topicSlug: "fractions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-33",
    question: "A store marks up a $50 item by 20% to set its price. What is the new price?",
    format: "MULTIPLE_CHOICE",
    choices: ["$60", "$70", "$55", "$40", "$65"],
    answer: "A",
    solution: "20% of $50 is $10, so the new price is $50 + $10 = $60.",
    hints: [
      "Find 20% of $50 first.",
      "Add that amount to the original price.",
    ],
    difficulty: 2,
    topicSlug: "percentages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-34",
    question:
      "A recipe uses flour and sugar in the ratio 5:2. If a baker uses 20 cups of flour, how many cups of sugar does she use?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "8", "10", "4", "12"],
    answer: "B",
    solution: "Since 20 cups of flour is 4 times 5, sugar is 4 times 2 = 8 cups.",
    hints: [
      "Find how many times larger 20 is than 5.",
      "Multiply that factor by 2 to get the sugar amount.",
    ],
    difficulty: 2,
    topicSlug: "ratios-proportions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-35",
    question: "Ravi has taken four spelling quizzes, and his four scores average 15. Three of his scores are 10, 12, and 18. What is his fourth score?",
    format: "MULTIPLE_CHOICE",
    choices: ["20", "15", "24", "18", "22"],
    answer: "A",
    solution: "Four scores averaging 15 total 4 × 15 = 60. The three known scores total 10 + 12 + 18 = 40, so the fourth is 60 − 40 = 20.",
    hints: ["Turn the average into a total first.", "Subtract the sum of the three known scores from that total."],
    difficulty: 2,
    topicSlug: "averages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-36",
    question: "A warehouse holds 7 crates, each crate holds 8 boxes, and each box holds 9 marbles. What is the units digit of the total number of marbles?",
    format: "MULTIPLE_CHOICE",
    choices: ["4", "2", "6", "8", "0"],
    answer: "A",
    solution: "The total is 7 × 8 × 9. Multiplying units digits, 7 × 8 = 56 ends in 6, and 6 × 9 = 54 ends in 4. The units digit is 4.",
    hints: ["You only need the units digit, not the whole product.", "Multiply step by step, keeping only the last digit each time."],
    difficulty: 2,
    topicSlug: "number-properties",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-37",
    question: "A square rug has trim running all the way around its edge, and the trim is 24 inches long. What is the area of the rug, in square inches?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "64", "30", "36", "48"],
    answer: "D",
    solution: "The trim is the perimeter, so each side is 24/4 = 6 inches. The area is 6 × 6 = 36 square inches.",
    hints: ["A square's perimeter is four equal sides.", "Find one side, then square it."],
    difficulty: 2,
    topicSlug: "geometry",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-38",
    question: "A triangular garden plot has two corners measuring 50 degrees and 65 degrees. What is the measure, in degrees, of the third corner?",
    format: "MULTIPLE_CHOICE",
    choices: ["55", "60", "75", "65", "70"],
    answer: "D",
    solution: "The three angles of a triangle sum to 180 degrees, so the third is 180 − 50 − 65 = 65 degrees.",
    hints: ["The angles of any triangle add to 180 degrees.", "Subtract the two known angles from 180."],
    difficulty: 2,
    topicSlug: "angles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-39",
    question: "A club wants to line up all of its members in equal rows, using more than one row and more than one member per row. For which of the following club sizes is that impossible?",
    format: "MULTIPLE_CHOICE",
    choices: ["87", "51", "57", "97", "91"],
    answer: "D",
    solution: "Such an arrangement is impossible exactly when the club size is prime. Among the choices, 87 = 3 × 29, 51 = 3 × 17, 57 = 3 × 19, and 91 = 7 × 13, but 97 has no factor other than 1 and itself, so 97 is the answer.",
    hints: ["The arrangement works whenever the number can be written as a product of two factors, each bigger than 1.", "Test each choice for small factors like 3 and 7."],
    difficulty: 2,
    topicSlug: "primes",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-40",
    question: "Bus A leaves the station every 6 minutes and Bus B leaves every 8 minutes. Both leave together at 9:00 AM. How many minutes later do they next leave at the same time?",
    format: "MULTIPLE_CHOICE",
    choices: ["48", "36", "16", "12", "24"],
    answer: "E",
    solution: "They leave together again after a number of minutes that is a multiple of both 6 and 8. The least common multiple of 6 and 8 is 24, so it happens 24 minutes later.",
    hints: ["You want the smallest time that is a multiple of both schedules.", "List multiples of 6 and of 8 until you find a shared one."],
    difficulty: 2,
    topicSlug: "divisibility",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-41",
    question: "Admission to a fair costs $8, each ride ticket costs $5, and Leo has a coupon worth $4 off his total. If Leo buys 6 ride tickets, how many dollars does he pay?",
    format: "MULTIPLE_CHOICE",
    choices: ["66", "34", "30", "38", "54"],
    answer: "B",
    solution: "He pays 8 + 6 × 5 − 4 = 8 + 30 − 4 = 34 dollars.",
    hints: ["Work out the cost of the ride tickets before adding anything.", "Multiplication comes before addition and subtraction."],
    difficulty: 2,
    topicSlug: "arithmetic",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-42",
    question: "In each of five classrooms, the fraction of the students who walk to school is listed below. In which classroom is that fraction closest to one half?",
    format: "MULTIPLE_CHOICE",
    choices: ["3/8", "7/15", "5/9", "2/5", "4/7"],
    answer: "B",
    solution: "Compare each to 1/2 = 0.5: 3/8 = 0.375, 7/15 ≈ 0.4667, 5/9 ≈ 0.5556, 2/5 = 0.4, and 4/7 ≈ 0.5714. The distances from 0.5 are 0.125, 0.0333, 0.0556, 0.1, and 0.0714, so 7/15 is closest.",
    hints: ["Convert each fraction to a decimal, or compare each with 1/2 by cross-multiplying.", "Find the size of the gap from 1/2 for each one, then pick the smallest gap."],
    difficulty: 2,
    topicSlug: "fractions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-43",
    question: "A printer prints 45 pages in 3 minutes. At this rate, how many pages does it print in 8 minutes?",
    format: "MULTIPLE_CHOICE",
    choices: ["90", "110", "120", "135", "100"],
    answer: "C",
    solution: "The printer's rate is 45/3 = 15 pages per minute. In 8 minutes it prints 15 × 8 = 120 pages.",
    hints: [
      "Find the printer's rate in pages per minute.",
      "Multiply that rate by 8.",
    ],
    difficulty: 2,
    topicSlug: "rates",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-44",
    question:
      "A license plate consists of 2 letters followed by 3 digits. How many license plates are possible if letters and digits can repeat?",
    format: "MULTIPLE_CHOICE",
    choices: ["260,000", "1,000,000", "676,000", "67,600", "520,000"],
    answer: "C",
    solution:
      "There are 26 choices for each letter and 10 choices for each digit, so the total is 26 × 26 × 10 × 10 × 10 = 676,000.",
    hints: [
      "Multiply the number of choices for each position together.",
      "There are 26 options for each letter slot and 10 for each digit slot.",
    ],
    difficulty: 2,
    topicSlug: "counting-principles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-45",
    question: "A rectangular picture frame is 9 inches long and 4 inches wide. How many inches of molding are needed to go all the way around it?",
    format: "MULTIPLE_CHOICE",
    choices: ["36", "52", "26", "18", "13"],
    answer: "C",
    solution: "The molding follows the perimeter: 2(9 + 4) = 26 inches.",
    hints: ["Going all the way around a rectangle means its perimeter.", "Add the length and width, then double."],
    difficulty: 2,
    topicSlug: "quadrilaterals",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-46",
    question: "A rumor starts with 2 people on Monday, and each day the number of people who hear it is triple the number from the day before. So on the next three days 6, 18, and 54 people hear it. How many people hear it on the day after that?",
    format: "MULTIPLE_CHOICE",
    choices: ["144", "216", "108", "81", "162"],
    answer: "E",
    solution: "Each day's count is 3 times the previous day's, so the next count is 3 × 54 = 162.",
    hints: ["Check what you multiply by to get from each day to the next.", "Apply that same multiplier once more to 54."],
    difficulty: 2,
    topicSlug: "number-patterns",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-47",
    question: "In a class of 25 students, 40% are boys. How many girls are in the class?",
    format: "MULTIPLE_CHOICE",
    choices: ["13", "14", "10", "15", "12"],
    answer: "D",
    solution: "40% of 25 is 10 boys, so the remaining 25 − 10 = 15 students are girls.",
    hints: [
      "Find 40% of 25 to get the number of boys.",
      "Subtract that from the total to find the girls.",
    ],
    difficulty: 2,
    topicSlug: "percentages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-48",
    question: "The cross-section of a tent is an isosceles triangle whose two base angles each measure 70 degrees. What is the measure, in degrees, of the angle at the peak?",
    format: "MULTIPLE_CHOICE",
    choices: ["70", "55", "40", "110", "35"],
    answer: "C",
    solution: "The three angles sum to 180 degrees, so the peak measures 180 − 70 − 70 = 40 degrees.",
    hints: ["The two base angles of this triangle are equal and both given.", "Subtract both from 180."],
    difficulty: 2,
    topicSlug: "triangles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-49",
    question: "The houses along one street are numbered 11 through 40. Only the even-numbered houses receive a recycling bin. How many bins are delivered?",
    format: "MULTIPLE_CHOICE",
    choices: ["13", "20", "14", "15", "16"],
    answer: "D",
    solution: "The even numbers in that range run 12, 14, ..., 40. That is (40 − 12)/2 + 1 = 15 numbers, so 15 bins.",
    hints: ["Identify the first and last even numbers in the range.", "Count them by stepping through by 2, remembering to include both ends."],
    difficulty: 2,
    topicSlug: "integer-properties",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-50",
    question: "A standard six-sided die is rolled once. What is the probability that the result is a multiple of 3?",
    format: "MULTIPLE_CHOICE",
    choices: ["1/6", "1/2", "1/3", "2/3", "1/4"],
    answer: "C",
    solution: "There are two multiples of 3 among 1–6, namely 3 and 6, so the probability is 2/6 = 1/3.",
    hints: [
      "List the outcomes from 1 to 6 that are multiples of 3.",
      "Divide the count of favorable outcomes by 6.",
    ],
    difficulty: 2,
    topicSlug: "basic-probability",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-51",
    question: "A caterer sets out twice as many chairs as tables, plus 5 extra chairs. There are 27 chairs. How many tables are there?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "11", "12", "16", "10"],
    answer: "B",
    solution: "If there are t tables, then 2t + 5 = 27, so 2t = 22 and t = 11.",
    hints: ["Let t be the number of tables and write the chair count in terms of t.", "Subtract the 5 extra chairs before dividing by 2."],
    difficulty: 3,
    topicSlug: "linear-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-52",
    question:
      "In a bag of marbles, red to blue marbles are in ratio 3:5, and there are 48 marbles total. How many blue marbles are there?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "30", "18", "36", "15"],
    answer: "B",
    solution:
      "There are 3 + 5 = 8 parts total, so each part is 48/8 = 6 marbles. Blue marbles are 5 × 6 = 30.",
    hints: [
      "Add the ratio parts to find the total number of parts.",
      "Multiply the size of one part by the blue ratio number.",
    ],
    difficulty: 3,
    topicSlug: "ratios-proportions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-53",
    question: "A shipping carton measures 4 inches by 5 inches by 6 inches. How many 1-inch cubes fit inside it?",
    format: "MULTIPLE_CHOICE",
    choices: ["120", "60", "90", "150", "100"],
    answer: "A",
    solution: "The number of unit cubes equals the volume: 4 × 5 × 6 = 120.",
    hints: ["Each 1-inch cube takes up one cubic inch.", "Multiply the three dimensions together."],
    difficulty: 3,
    topicSlug: "area-volume",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-54",
    question: "A stack of nesting chairs is 4 inches tall when it holds one chair, and each additional chair adds 5 inches to the height. How tall is a stack of 10 chairs, in inches?",
    format: "MULTIPLE_CHOICE",
    choices: ["49", "54", "44", "45", "50"],
    answer: "A",
    solution: "Nine chairs beyond the first each add 5 inches, so the height is 4 + 9 × 5 = 49 inches.",
    hints: ["Count how many chairs beyond the first are in the stack.", "That is 9 chairs, each adding 5 inches to the starting 4."],
    difficulty: 3,
    topicSlug: "sequences",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-55",
    question: "A teacher can split a class of 28 students into equal groups in several ways, where a single group of all 28 and 28 groups of 1 both count as valid. What is the sum of all the possible group sizes?",
    format: "MULTIPLE_CHOICE",
    choices: ["42", "58", "56", "55", "50"],
    answer: "C",
    solution: "The possible group sizes are the divisors of 28: 1, 2, 4, 7, 14, and 28. Their sum is 1 + 2 + 4 + 7 + 14 + 28 = 56.",
    hints: ["A group size works exactly when it divides 28 evenly.", "List all divisors of 28 in pairs that multiply to 28, then add them."],
    difficulty: 3,
    topicSlug: "divisibility",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-56",
    question: "A garden gate is shaped like a parallelogram. One of its corners measures 62 degrees. What is the measure, in degrees, of a corner next to it?",
    format: "MULTIPLE_CHOICE",
    choices: ["128", "90", "118", "62", "112"],
    answer: "C",
    solution: "Adjacent angles of a parallelogram add to 180 degrees, so the neighboring corner is 180 − 62 = 118 degrees.",
    hints: ["In a parallelogram, two angles that share a side are supplementary.", "Subtract 62 from 180."],
    difficulty: 3,
    topicSlug: "angles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-57",
    question: "Five consecutive pages of a book have page numbers that average 21. What is the largest of those page numbers?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "23", "21", "25", "22"],
    answer: "B",
    solution: "For five consecutive numbers the average is the middle one, so the middle page is 21 and the five pages are 19, 20, 21, 22, 23. The largest is 23.",
    hints: ["With an odd count of consecutive numbers, the average sits exactly in the middle.", "Count up two from the middle to reach the largest."],
    difficulty: 3,
    topicSlug: "averages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-58",
    question:
      "A pizza shop offers 6 toppings. How many different 2-topping pizzas can be made, where order doesn't matter and toppings aren't repeated?",
    format: "MULTIPLE_CHOICE",
    choices: ["15", "20", "12", "30", "10"],
    answer: "A",
    solution: "C(6,2) = (6 × 5)/2 = 15.",
    hints: [
      "Since order doesn't matter, use combinations, not permutations.",
      "Compute C(6,2) = (6 × 5)/(2 × 1).",
    ],
    difficulty: 3,
    topicSlug: "combinations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-59",
    question: "The odometer of a delivery van reads 4,987 miles. What is the sum of the digits it shows?",
    format: "MULTIPLE_CHOICE",
    choices: ["26", "29", "28", "30", "27"],
    answer: "C",
    solution: "4 + 9 + 8 + 7 = 28.",
    hints: ["Add the digits one at a time, ignoring their place values.", "Keep a running total: 4, then 13, then 21, then 28."],
    difficulty: 3,
    topicSlug: "number-properties",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-60",
    question: "A circular running track has a radius of 7 meters. How many meters long is one lap around it? Express your answer in terms of π.",
    format: "MULTIPLE_CHOICE",
    choices: ["28π", "7π", "49π", "14π", "21π"],
    answer: "D",
    solution: "One lap is the circumference, 2πr = 2π(7) = 14π meters.",
    hints: ["A lap around a circle is its circumference.", "Use C = 2πr and leave π in the answer."],
    difficulty: 3,
    topicSlug: "circles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-61",
    question:
      "A tank is 3/4 full of water. After removing 15 gallons, it is 1/2 full. What is the tank's total capacity, in gallons?",
    format: "MULTIPLE_CHOICE",
    choices: ["30", "90", "60", "45", "75"],
    answer: "C",
    solution:
      "Let the capacity be T. Then (3/4)T − 15 = (1/2)T, so (1/4)T = 15, giving T = 60.",
    hints: [
      "Set up an equation relating the two fractional amounts and the 15 gallons removed.",
      "The difference between 3/4 and 1/2 of the tank is exactly 15 gallons.",
    ],
    difficulty: 3,
    topicSlug: "fractions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-62",
    question:
      "Two hoses fill a pool. Hose A alone fills it in 6 hours; Hose B alone fills it in 3 hours. How many hours does it take both hoses working together to fill the pool?",
    format: "MULTIPLE_CHOICE",
    choices: ["1.5", "3", "2.5", "2", "4.5"],
    answer: "D",
    solution:
      "Hose A fills 1/6 of the pool per hour and Hose B fills 1/3 = 2/6 per hour. Together they fill 3/6 = 1/2 per hour, so it takes 2 hours to fill the whole pool.",
    hints: [
      "Add the two hoses' rates (pool per hour) together.",
      "The time to finish is 1 divided by the combined rate.",
    ],
    difficulty: 3,
    topicSlug: "rates",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-63",
    question: "A ramp leans against a loading dock. The bottom of the ramp sits 9 feet out from the dock, and the top rests on the dock 12 feet above the ground. How long is the ramp, in feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["16", "13", "21", "14", "15"],
    answer: "E",
    solution: "The ramp is the hypotenuse of a right triangle with legs 9 and 12, so its length is √(9² + 12²) = √(81 + 144) = √225 = 15 feet.",
    hints: ["The ground, the dock wall, and the ramp form a right triangle.", "Square both legs, add, then take the square root."],
    difficulty: 3,
    topicSlug: "triangles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-64",
    question: "A hall has 100 chairs, which are set out in rows of 7 with as many complete rows as possible. How many chairs are left over?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "1", "3", "4", "5"],
    answer: "A",
    solution: "Since 7 × 14 = 98, fourteen complete rows use 98 chairs and 100 − 98 = 2 chairs are left over.",
    hints: ["Find the largest multiple of 7 that does not exceed 100.", "Subtract it from 100."],
    difficulty: 3,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-65",
    question:
      "A population of 400 increases by 15% one year and then decreases by 10% the next year. What is the population after these two changes?",
    format: "MULTIPLE_CHOICE",
    choices: ["414", "400", "420", "410", "405"],
    answer: "A",
    solution:
      "After a 15% increase, the population is 400 × 1.15 = 460. After a 10% decrease, it becomes 460 × 0.9 = 414.",
    hints: [
      "Apply each percent change one at a time, in order.",
      "Multiply by 1.15 for the increase and by 0.9 for the decrease.",
    ],
    difficulty: 3,
    topicSlug: "percentages",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-66",
    question: "A gazebo has a floor shaped like a hexagon. What is the sum, in degrees, of the six interior angles of the floor?",
    format: "MULTIPLE_CHOICE",
    choices: ["720°", "540°", "600°", "1080°", "900°"],
    answer: "A",
    solution: "An n-sided polygon has interior angles summing to (n − 2) × 180 degrees. For n = 6 that is 4 × 180 = 720 degrees.",
    hints: ["A hexagon can be cut into triangles by drawing diagonals from one corner.", "Count the triangles and multiply by 180."],
    difficulty: 3,
    topicSlug: "polygons",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-67",
    question: "A combination lock has three dials, and each dial can be set to any one of the digits 1, 3, 5, 7, or 9. How many different combinations are possible?",
    format: "MULTIPLE_CHOICE",
    choices: ["243", "100", "120", "150", "125"],
    answer: "E",
    solution: "Each of the three dials has 5 independent settings, so there are 5 × 5 × 5 = 125 combinations.",
    hints: ["Count the choices for each dial separately.", "Multiply the counts, since the dials are set independently."],
    difficulty: 3,
    topicSlug: "counting-principles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-68",
    question: "A jeweler has 84 red beads and 126 blue beads and wants to make identical bracelets, using every bead with none left over. What is the greatest number of bracelets she can make?",
    format: "MULTIPLE_CHOICE",
    choices: ["63", "14", "42", "28", "21"],
    answer: "C",
    solution: "The number of bracelets must divide both 84 and 126. Since 84 = 2² · 3 · 7 and 126 = 2 · 3² · 7, their greatest common factor is 2 · 3 · 7 = 42.",
    hints: ["Identical bracelets mean the count must divide both bead totals.", "Factor both numbers and take the shared primes to their smallest powers."],
    difficulty: 3,
    topicSlug: "factorization",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-69",
    question: "On a park map the fountain sits at (1, 2) and the gate sits at (4, 6), where each unit is one block. How many blocks apart are they in a straight line?",
    format: "MULTIPLE_CHOICE",
    choices: ["7", "25", "6", "4", "5"],
    answer: "E",
    solution: "The horizontal gap is 3 and the vertical gap is 4, so the straight-line distance is √(3² + 4²) = √25 = 5 blocks.",
    hints: ["Find the horizontal and vertical gaps separately.", "Those two gaps are the legs of a right triangle whose hypotenuse you want."],
    difficulty: 3,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-70",
    question:
      "Four friends — Dan, Ella, Finn, and Grace — each finished in a different place (1st through 4th) in a race. Dan finished before Ella. Finn finished 2nd. Grace did not finish 1st or 4th. Who finished 1st?",
    format: "MULTIPLE_CHOICE",
    choices: ["Dan", "Finn", "Ella", "Cannot be determined", "Grace"],
    answer: "A",
    solution:
      "Finn is 2nd. Since Grace is neither 1st nor 4th, and 2nd is taken, Grace must be 3rd. That leaves 1st and 4th for Dan and Ella, and since Dan finishes before Ella, Dan is 1st and Ella is 4th.",
    hints: [
      "Place Finn first since his position is given directly.",
      "Use Grace's restriction to find her position, then order Dan and Ella in what's left.",
    ],
    difficulty: 3,
    topicSlug: "logical-puzzles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-71",
    question: "A rectangle has a perimeter of 14 and an area of 12. What is the sum of the squares of its length and its width?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "37", "25", "13", "49"],
    answer: "C",
    solution: "The length and width sum to 7 and multiply to 12. Then (length)² + (width)² = (length + width)² − 2(length)(width) = 49 − 24 = 25.",
    hints: ["The perimeter gives the sum of the two dimensions and the area gives their product.", "Expand (a + b)² to relate a² + b² to a + b and ab."],
    difficulty: 4,
    topicSlug: "quadratics",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-72",
    question: "At a bake sale, twice the number of muffins plus three times the number of scones is 26, and there are 3 more muffins than scones. How many muffins are there?",
    format: "MULTIPLE_CHOICE",
    choices: ["10", "9", "4", "7", "6"],
    answer: "D",
    solution: "With m muffins and s scones, 2m + 3s = 26 and m − s = 3. Substituting s = m − 3 gives 2m + 3(m − 3) = 26, so 5m = 35 and m = 7.",
    hints: ["Use the second fact to write the number of scones in terms of muffins.", "Substitute into the first equation and solve for m."],
    difficulty: 4,
    topicSlug: "systems-of-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-73",
    question: "A cylindrical water tank has a radius of 3 feet and a height of 10 feet. What is its volume, in cubic feet, in terms of π?",
    format: "MULTIPLE_CHOICE",
    choices: ["270π", "94π", "60π", "90π", "30π"],
    answer: "D",
    solution: "The volume is πr²h = π(3²)(10) = 90π cubic feet.",
    hints: ["The volume of a cylinder is the area of its circular base times its height.", "Square the radius before multiplying by the height."],
    difficulty: 4,
    topicSlug: "area-volume",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-74",
    question: "A photograph is enlarged so that every length in the enlargement is 5/2 times the matching length in the original. The original has an area of 12 square inches. What is the area of the enlargement, in square inches?",
    format: "MULTIPLE_CHOICE",
    choices: ["75", "30", "60", "96", "48"],
    answer: "A",
    solution: "Lengths scale by 5/2, so areas scale by (5/2)² = 25/4. The enlargement has area 12 × 25/4 = 75 square inches.",
    hints: ["Area does not scale by the same factor as length.", "Square the length ratio, then multiply the original area by it."],
    difficulty: 4,
    topicSlug: "similarity-congruence",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-75",
    question: "A choir director wants a number of singers that can be arranged in exactly 6 different equal-row formations, where a single row of everyone and a single column of everyone both count as formations. What is the smallest number of singers that works?",
    format: "MULTIPLE_CHOICE",
    choices: ["16", "18", "20", "24", "12"],
    answer: "E",
    solution: "Each formation matches a divisor, so the director needs the smallest number with exactly 6 divisors. Checking upward, 12 = 2² · 3 has (2+1)(1+1) = 6 divisors: 1, 2, 3, 4, 6, 12. Nothing smaller works, so the answer is 12.",
    hints: ["Each formation corresponds to one divisor of the number of singers.", "Count divisors of 1, 2, 3, ... until you first reach exactly 6."],
    difficulty: 4,
    topicSlug: "number-theory",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-76",
    question: "Two square gardens have areas of 50 and 18 square meters. A straight path runs along one full side of each garden. What is the total length of the two paths, in meters, in simplest radical form?",
    format: "MULTIPLE_CHOICE",
    choices: ["5√5", "8√6", "√68", "8√2", "68"],
    answer: "D",
    solution: "The sides are √50 = 5√2 and √18 = 3√2, so the total is 5√2 + 3√2 = 8√2 meters.",
    hints: ["The side of a square is the square root of its area.", "Pull perfect squares out of each radical so both have the same radical part."],
    difficulty: 4,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-77",
    question: "In how many ways can 5 different books be arranged in a row on a shelf?",
    format: "MULTIPLE_CHOICE",
    choices: ["24", "120", "60", "100", "20"],
    answer: "B",
    solution: "There are 5! = 120 ways to arrange 5 distinct books.",
    hints: [
      "This is a permutation of all 5 books.",
      "Compute 5 × 4 × 3 × 2 × 1.",
    ],
    difficulty: 4,
    topicSlug: "permutations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-78",
    question:
      "A circular pizza with diameter 16 inches is cut into 8 equal slices. What is the area of one slice, in terms of π?",
    format: "MULTIPLE_CHOICE",
    choices: ["64π", "8π", "16π", "4π", "32π"],
    answer: "B",
    solution:
      "The radius is 8, so the total area is π(8²) = 64π. One of 8 equal slices has area 64π/8 = 8π.",
    hints: [
      "Find the radius from the diameter, then the total area.",
      "Divide the total area by the number of slices.",
    ],
    difficulty: 4,
    topicSlug: "circles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-79",
    question: "A shop restocks its shelves every 4 days and washes its windows every 6 days, doing both on day 0. On how many of days 1 through 99 does it do both jobs on the same day?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "12", "16", "7", "8"],
    answer: "E",
    solution: "Both jobs fall on days that are multiples of both 4 and 6, that is, multiples of 12. From 1 to 99 these are 12, 24, ..., 96, which is 96/12 = 8 days.",
    hints: ["Both jobs coincide on multiples of the least common multiple of 4 and 6.", "Count the multiples of 12 that are less than 100."],
    difficulty: 4,
    topicSlug: "divisibility",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-80",
    question: "A colony of algae is weighed once a day. On the first day it weighs 3 grams, and on the fourth day it weighs 81 grams. If the colony is multiplied by the same factor each day, what is that factor?",
    format: "MULTIPLE_CHOICE",
    choices: ["27", "9", "3", "6", "4"],
    answer: "C",
    solution: "Three days of growth multiply the weight by r³, so 3r³ = 81 and r³ = 27, giving r = 3.",
    hints: ["Count how many days of growth separate day 1 from day 4.", "That is three steps, so the daily factor is cubed."],
    difficulty: 4,
    topicSlug: "sequences",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-81",
    question:
      "A bag contains 4 white and 6 black socks. Two socks are drawn at random without replacement. What is the probability both are white?",
    format: "MULTIPLE_CHOICE",
    choices: ["2/15", "1/3", "2/9", "4/25", "1/5"],
    answer: "A",
    solution:
      "P(first white) = 4/10. Given that, P(second white) = 3/9. Multiplying, the probability both are white is (4/10)(3/9) = 12/90 = 2/15.",
    hints: [
      "Multiply the probability of the first sock being white by the probability of the second also being white given the first was white.",
      "Remember the total number of socks decreases by one after the first draw.",
    ],
    difficulty: 4,
    topicSlug: "counting-probability",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-82",
    question: "A triangular road sign has one corner twice as large as a second corner, and its third corner is 20 degrees larger than that second corner. How many degrees is the second corner?",
    format: "MULTIPLE_CHOICE",
    choices: ["30", "35", "50", "40", "45"],
    answer: "D",
    solution: "Let the second corner be B. Then the others are 2B and B + 20, and 2B + B + (B + 20) = 180. So 4B = 160 and B = 40 degrees.",
    hints: ["Name the second corner B and write the other two in terms of B.", "Set the total equal to 180 degrees."],
    difficulty: 4,
    topicSlug: "triangles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-83",
    question: "Attendance at a school play rose by 40% from last year to this year. This year 84 people attended. How many attended last year?",
    format: "MULTIPLE_CHOICE",
    choices: ["50", "56", "67.2", "70", "60"],
    answer: "E",
    solution: "This year's attendance is 1.4 times last year's, so last year's was 84/1.4 = 60 people.",
    hints: ["A 40% increase multiplies the original by 1.4.", "Divide rather than subtracting 40% of 84."],
    difficulty: 4,
    topicSlug: "linear-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-84",
    question: "Today is a Tuesday. What day of the week will it be 100 days from today?",
    format: "MULTIPLE_CHOICE",
    choices: ["Friday", "Wednesday", "Thursday", "Saturday", "Monday"],
    answer: "C",
    solution:
      "Since 100 = 14×7 + 2, 100 days from now is the same as 2 days from now. Two days after Tuesday is Thursday.",
    hints: [
      "Find the remainder when 100 is divided by 7.",
      "Count that many days forward from Tuesday.",
    ],
    difficulty: 4,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-85",
    question:
      "Among 50 students, 28 play basketball and 22 play volleyball, and 10 play both. How many play neither sport?",
    format: "MULTIPLE_CHOICE",
    choices: ["8", "10", "18", "12", "6"],
    answer: "B",
    solution:
      "By inclusion-exclusion, students playing at least one sport number 28 + 22 − 10 = 40. Those playing neither are 50 − 40 = 10.",
    hints: [
      "Use inclusion-exclusion to find the number playing at least one sport.",
      "Subtract that from the total number of students.",
    ],
    difficulty: 4,
    topicSlug: "inclusion-exclusion",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-86",
    question: "A gift box is a cube, and it takes exactly 96 square inches of paper to cover its outside with no overlap. What is the volume of the box, in cubic inches?",
    format: "MULTIPLE_CHOICE",
    choices: ["96", "16", "48", "64", "32"],
    answer: "D",
    solution: "A cube has 6 equal faces, so each face has area 96/6 = 16 and each edge is 4 inches. The volume is 4³ = 64 cubic inches.",
    hints: ["Divide the surface area among the cube's six faces.", "Take the square root of one face's area to get the edge length."],
    difficulty: 4,
    topicSlug: "three-d-geometry",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-87",
    question:
      "A tile pattern uses 3 tiles for stage 1, 7 tiles for stage 2, and 11 tiles for stage 3, increasing by the same amount each stage. How many tiles are needed for stage 8?",
    format: "MULTIPLE_CHOICE",
    choices: ["28", "27", "35", "31", "32"],
    answer: "D",
    solution:
      "The pattern increases by 4 tiles each stage, so stage n uses 3 + 4(n−1) tiles. Stage 8 uses 3 + 4(7) = 3 + 28 = 31.",
    hints: [
      "Find the common difference between consecutive stages.",
      "Use stage n = first term + (n−1) × common difference.",
    ],
    difficulty: 4,
    topicSlug: "patterns",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-88",
    question: "A taxi charges $4 per mile for every mile beyond the first 3 miles, which are free. A rideshare charges a $10 base fee plus $2 per mile for the whole trip. For a trip of how many miles do the two cost the same?",
    format: "MULTIPLE_CHOICE",
    choices: ["13", "9", "7", "8", "11"],
    answer: "E",
    solution: "The taxi costs 4(x − 3) and the rideshare costs 2x + 10 = 2(x + 5). Setting them equal, 4x − 12 = 2x + 10, so 2x = 22 and x = 11 miles.",
    hints: ["Write a cost expression for each service in terms of the trip length x.", "Set the two expressions equal and solve."],
    difficulty: 4,
    topicSlug: "algebra",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-89",
    question: "A plot of land is shaped like a trapezoid. Its two parallel sides measure 8 meters and 14 meters, and the distance between those sides is 6 meters. What is the area of the plot, in square meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["44", "72", "132", "66", "60"],
    answer: "D",
    solution: "The area is the average of the parallel sides times the height: ((8 + 14)/2) × 6 = 11 × 6 = 66 square meters.",
    hints: ["Average the two parallel sides first.", "Multiply that average by the distance between them."],
    difficulty: 4,
    topicSlug: "quadrilaterals",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-90",
    question:
      "A drawer contains socks of 5 different colors. What is the minimum number of socks you must pull out (without looking) to guarantee at least 2 socks of the same color?",
    format: "MULTIPLE_CHOICE",
    choices: ["11", "5", "6", "10", "4"],
    answer: "C",
    solution:
      "In the worst case you could pull one sock of each of the 5 colors before getting a repeat, so 5 + 1 = 6 socks guarantees a matching pair.",
    hints: [
      "Think about the worst-case order in which socks could be pulled.",
      "Once all 5 colors have appeared once, the next sock must repeat a color.",
    ],
    difficulty: 4,
    topicSlug: "pigeonhole",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-91",
    question: "A rectangular sandbox is framed with 12 feet of boards, and both its length and width are whole numbers of feet. What is the largest possible area of the sandbox, in square feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["9", "12", "8", "6", "5"],
    answer: "A",
    solution: "The length and width sum to 6. The whole-number pairs are 1×5, 2×4, and 3×3, with areas 5, 8, and 9. The largest is 9 square feet.",
    hints: ["The perimeter fixes the sum of the length and width.", "Try every whole-number pair with that sum and compare areas."],
    difficulty: 5,
    topicSlug: "quadratics",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-92",
    question: "A vending machine sells snacks for $5 each and drinks for $2 each. A class spends exactly $40 and buys at least one snack and at least one drink. In how many different ways could they have done this?",
    format: "MULTIPLE_CHOICE",
    choices: ["3", "4", "8", "5", "2"],
    answer: "A",
    solution: "With x snacks and y drinks, 5x + 2y = 40. For 40 − 5x to be positive and even, x must be even and less than 8: x = 2, 4, 6 give y = 15, 10, 5. That is 3 ways.",
    hints: ["Write the spending equation and look for positive whole-number solutions.", "Notice that the number of snacks is forced to be even."],
    difficulty: 5,
    topicSlug: "diophantine-equations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-93",
    question: "In a triangular park, a straight path connects the midpoints of two of the three sides. The path is 7 meters long. How long is the third side of the park, in meters?",
    format: "MULTIPLE_CHOICE",
    choices: ["28", "7", "14", "21", "10.5"],
    answer: "C",
    solution: "A segment joining the midpoints of two sides is half the length of the third side, so the third side is 2 × 7 = 14 meters.",
    hints: ["A segment connecting two midpoints is parallel to the third side.", "It is exactly half as long, so double it."],
    difficulty: 5,
    topicSlug: "similarity-congruence",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-94",
    question:
      "Two players take turns removing 1 or 2 stones from a pile of 21 stones; Ana moves first. The player who removes the last stone wins. If both play optimally, who wins?",
    format: "MULTIPLE_CHOICE",
    choices: ["It depends on later moves", "Ana, by removing 1 stone", "Ben, only if Ana errs", "Ben, no matter what Ana does", "Ana, by removing 2 stones"],
    answer: "D",
    solution:
      "With moves of 1 or 2 stones, multiples of 3 are losing positions for the player about to move, since any move (1 or 2) lets the opponent return the pile to the next lower multiple of 3. Since 21 is a multiple of 3, Ana (moving first) is already in a losing position, so Ben wins with correct play.",
    hints: [
      "Identify which pile sizes are 'safe' — sizes where any move can be answered to return to another safe size.",
      "Multiples of 3 are losing positions here, since removing 1 or 2 always lets the opponent restore a multiple of 3.",
    ],
    difficulty: 5,
    topicSlug: "games-and-strategies",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-95",
    question: "A committee of 4 is chosen from 6 men and 5 women. How many committees have exactly 2 men and 2 women?",
    format: "MULTIPLE_CHOICE",
    choices: ["100", "55", "120", "210", "150"],
    answer: "E",
    solution:
      "Choose 2 of the 6 men: C(6,2) = 15. Choose 2 of the 5 women: C(5,2) = 10. Multiply: 15 × 10 = 150.",
    hints: [
      "Handle the men and women selections separately, then multiply the counts.",
      "Compute C(6,2) and C(5,2) individually.",
    ],
    difficulty: 5,
    topicSlug: "combinations",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-96",
    question: "A jar holds 3 beetles on day 1, and the number of beetles triples every day. What is the units digit of the number of beetles on day 47?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "9", "3", "1", "7"],
    answer: "E",
    solution: "On day 47 there are 3⁴⁷ beetles. The units digits of powers of 3 cycle 3, 9, 7, 1 with period 4. Since 47 leaves remainder 3 when divided by 4, the units digit matches that of 3³ = 27, which is 7.",
    hints: ["Write out the units digits of 3, 9, 27, 81, 243, ... and find the repeating cycle.", "Divide 47 by the cycle length and use the remainder."],
    difficulty: 5,
    topicSlug: "modular-arithmetic",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-97",
    question: "On a town map a straight road follows the line y = 2x − 5. A second straight road crosses it at a right angle and passes through the point (4, 1). At what y-value does the second road cross the y-axis?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "1", "3", "5", "-1"],
    answer: "C",
    solution: "Perpendicular lines have slopes that multiply to −1, so the second road has slope −1/2. Through (4, 1): 1 = −1/2(4) + b gives b = 3.",
    hints: ["Flip the slope and change its sign to get the perpendicular slope.", "Plug the given point into y = mx + b and solve for b."],
    difficulty: 5,
    topicSlug: "coordinate-geometry",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-98",
    question: "A sports league gives each team a three-digit jersey number. A number is called lucky if all three of its digits are the same, like 222 or 777. How many lucky numbers are there?",
    format: "MULTIPLE_CHOICE",
    choices: ["99", "10", "8", "90", "9"],
    answer: "E",
    solution: "The repeated digit can be any of 1 through 9 (a leading 0 would not give a three-digit number), so there are 9 lucky numbers.",
    hints: ["Once the repeated digit is chosen, the whole number is determined.", "Remember that the leading digit cannot be 0."],
    difficulty: 5,
    topicSlug: "casework",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-99",
    question:
      "A game costs $2 to play. You roll a fair six-sided die and win $5 if it lands on a 6, and win nothing otherwise. What is the expected net profit (winnings minus cost) of playing once, in dollars?",
    format: "MULTIPLE_CHOICE",
    choices: ["-1", "1/6", "5/6", "-7/6", "-1/6"],
    answer: "D",
    solution:
      "Expected winnings are 5 × (1/6) = 5/6 dollars. Subtracting the $2 cost gives an expected net profit of 5/6 − 2 = −7/6 dollars.",
    hints: [
      "Compute the expected winnings first: probability of winning times the prize.",
      "Subtract the cost to play from the expected winnings.",
    ],
    difficulty: 5,
    topicSlug: "expected-value",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-100",
    question: "A rectangular crate measures 3 feet by 4 feet by 12 feet. What is the length, in feet, of the longest straight pole that fits inside it?",
    format: "MULTIPLE_CHOICE",
    choices: ["12.5", "19", "17", "15", "13"],
    answer: "E",
    solution: "The longest pole runs along the space diagonal, which measures √(3² + 4² + 12²) = √(9 + 16 + 144) = √169 = 13 feet.",
    hints: ["The longest segment inside a box is its corner-to-opposite-corner diagonal.", "Square all three dimensions, add, and take the square root."],
    difficulty: 5,
    topicSlug: "three-d-geometry",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-101",
    question: "A machine takes a number, doubles it, and then adds 3. Kira puts 4 into the machine, then feeds the result back into the machine. What number comes out the second time?",
    format: "MULTIPLE_CHOICE",
    choices: ["25", "14", "11", "22", "28"],
    answer: "A",
    solution: "The first pass gives 2(4) + 3 = 11. The second pass gives 2(11) + 3 = 25.",
    hints: ["Run the machine once and write down the intermediate result.", "Then run that result through the same two steps."],
    difficulty: 5,
    topicSlug: "functions",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-102",
    question: "A factory packs its output into boxes of 1000. On day n it produces n! items, meaning 1 × 2 × 3 × ⋯ × n. What is the smallest n for which that day's output packs into full boxes with nothing left over?",
    format: "MULTIPLE_CHOICE",
    choices: ["12", "15", "20", "25", "10"],
    answer: "B",
    solution: "Since 1000 = 2³ · 5³, the product needs three factors of 5. Factors of 5 appear at 5, 10, and 15, so n = 15 is the first value that supplies three of them; factors of 2 are plentiful well before that.",
    hints: ["Factor 1000 into primes and decide which prime is the bottleneck.", "Count how many multiples of 5 appear in 1 × 2 × ⋯ × n."],
    difficulty: 5,
    topicSlug: "number-theory",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-103",
    question: "A company's profit, in thousands of dollars, t months after it opens is given by P(t) = t³ − 4t² + t + 6. What is its profit, in thousands of dollars, 2 months after opening?",
    format: "MULTIPLE_CHOICE",
    choices: ["2", "4", "-2", "0", "6"],
    answer: "D",
    solution: "P(2) = 8 − 4(4) + 2 + 6 = 8 − 16 + 2 + 6 = 0.",
    hints: ["Substitute t = 2 everywhere in the expression.", "Work out each term separately before adding."],
    difficulty: 5,
    topicSlug: "polynomials",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-104",
    question:
      "A box has 3 red and 5 blue balls. Two balls are drawn without replacement. Given that the first ball drawn is red, what is the probability that the second ball is also red?",
    format: "MULTIPLE_CHOICE",
    choices: ["2/8", "2/7", "1/4", "3/7", "3/8"],
    answer: "B",
    solution:
      "After removing one red ball, 2 red and 5 blue balls remain, for 7 total. The probability the second ball is red is 2/7.",
    hints: [
      "Update the counts after the first red ball is removed.",
      "Divide the new number of red balls by the new total.",
    ],
    difficulty: 5,
    topicSlug: "conditional-probability",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-105",
    question: "A square tablecloth is spread over a round table of radius 6 feet so that all four of its corners just touch the edge of the table. What is the area of the tablecloth, in square feet?",
    format: "MULTIPLE_CHOICE",
    choices: ["72", "144", "108", "96", "36"],
    answer: "A",
    solution: "The tablecloth's diagonal is the table's diameter, 12 feet. A square with diagonal d has area d²/2 = 144/2 = 72 square feet.",
    hints: ["The corners touching the rim means the square's diagonal spans the circle.", "For a square, area equals half the square of the diagonal."],
    difficulty: 5,
    topicSlug: "circles",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-106",
    question:
      "Among four friends — Priya, Quinn, Rosa, and Sam — each owns a different pet: cat, dog, fish, or bird. Priya's pet is not the cat or the fish. Quinn's pet is the dog. Rosa's pet is not the bird. Sam owns the fish. What pet does Priya own?",
    format: "MULTIPLE_CHOICE",
    choices: ["Dog", "Cat", "Cannot be determined", "Fish", "Bird"],
    answer: "E",
    solution:
      "Quinn owns the dog and Sam owns the fish, leaving cat and bird for Priya and Rosa. Since Priya's pet is not the cat, Priya must own the bird (and Rosa owns the cat, consistent with Rosa not owning the bird).",
    hints: [
      "Place Quinn's and Sam's pets first since they're given directly.",
      "Use Priya's restriction to choose between the two remaining pets.",
    ],
    difficulty: 5,
    topicSlug: "deduction",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-107",
    question: "Two ribbons have lengths, in inches, that add up to 12. The squares built on the two ribbons have areas that differ by 48 square inches. What is the difference between the two ribbon lengths, in inches?",
    format: "MULTIPLE_CHOICE",
    choices: ["6", "8", "4", "3", "5"],
    answer: "C",
    solution: "With lengths a and b, a + b = 12 and a² − b² = 48. Since a² − b² = (a + b)(a − b), we get 12(a − b) = 48, so a − b = 4 inches.",
    hints: ["Factor the difference of two squares.", "One of the two factors is already given to you."],
    difficulty: 5,
    topicSlug: "algebra",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-108",
    question: "A floor tile is a regular hexagon with a side length of 4 inches. What is its area, in square inches?",
    format: "MULTIPLE_CHOICE",
    choices: ["24√3", "16√3", "36√3", "48√3", "12√3"],
    answer: "A",
    solution: "Cutting from the center gives 6 equilateral triangles of side 4, each with area (√3/4)(4²) = 4√3. The hexagon's area is 6 × 4√3 = 24√3 square inches.",
    hints: ["Split the hexagon into six equilateral triangles meeting at the center.", "Use the area formula for an equilateral triangle, then multiply by 6."],
    difficulty: 5,
    topicSlug: "area-volume",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-109",
    question: "A fair coin is flipped 4 times. What is the probability of getting exactly 3 heads?",
    format: "MULTIPLE_CHOICE",
    choices: ["3/8", "1/8", "1/2", "1/4", "1/16"],
    answer: "D",
    solution:
      "There are C(4,3) = 4 ways to choose which flips are heads, out of 2⁴ = 16 total outcomes. The probability is 4/16 = 1/4.",
    hints: [
      "Count the number of ways to choose which 3 of the 4 flips are heads.",
      "Divide by the total number of possible outcomes, 2⁴ = 16.",
    ],
    difficulty: 5,
    topicSlug: "counting-probability",
    competitionSlug: "amc8",
  },
  {
    slug: "amc8-110",
    question: "One bacteria colony doubles every hour and reaches 32 times its starting size after a hours. A second colony triples every hour and reaches 81 times its starting size after b hours. What is the value of a + b?",
    format: "MULTIPLE_CHOICE",
    choices: ["5", "9", "13", "20", "4"],
    answer: "B",
    solution: "From 2^a = 32 = 2⁵ we get a = 5, and from 3^b = 81 = 3⁴ we get b = 4. So a + b = 9.",
    hints: ["Write 32 as a power of 2 and 81 as a power of 3.", "Read off each exponent, then add."],
    difficulty: 5,
    topicSlug: "exponents-radicals",
    competitionSlug: "amc8",
  },
];
